/**
 * Sheet, column and summary labels for the submissions export.
 *
 * These live next to the route rather than in the admin `strings.ts` bundle
 * because they are only ever read on the server while writing the file —
 * shipping them to the admin client would be dead weight.
 */
import type { AdminLocale } from "@/app/(admin)/admin/_i18n/strings";

const uk = {
  sheet: { detail: "Заявки", summary: "Зведення" },
  status: { new: "Нова", processed: "Оброблено" },
  col: {
    date: "Дата і час",
    day: "День тижня",
    hour: "Година",
    status: "Статус",
    name: "Ім'я",
    phone: "Телефон",
    email: "Email",
    interest: "Цікавиться",
    formLabel: "Форма",
    formType: "Тип форми",
    preferredTime: "Зручний час",
    message: "Повідомлення",
    source: "UTM source",
    medium: "UTM medium",
    campaign: "UTM campaign",
    term: "UTM term",
    content: "UTM content",
    referrer: "Реферер",
    pageHost: "Домен",
    pagePath: "Сторінка",
    pageTitle: "Заголовок сторінки",
    lang: "Мова",
    processedAt: "Оброблено о",
    responseHours: "Реакція, год",
    id: "ID",
  },
  summary: {
    metric: "Показник",
    value: "Значення",
    countHeader: "Кількість",
    generated: "Вивантажено",
    generatedBy: "Ким",
    period: "Період",
    total: "Всього заявок",
    newCount: "Нових",
    processedCount: "Оброблених",
    avgResponse: "Середня реакція, год",
    firstLast: "Перша — остання заявка",
    byDirection: "За напрямком",
    byForm: "За формою",
    bySource: "За джерелом (UTM)",
    byCampaign: "За кампанією",
    byPage: "За сторінкою",
    byLang: "За мовою сайту",
    byDay: "За днями",
    byHour: "За годинами доби",
    notSet: "Не вказано",
    direct: "Прямий / без UTM",
    noData: "Немає даних",
    rangeAll: "Усі заявки",
    rangeSelected: (n: number) => `Вибрані заявки (${n})`,
  },
};

const ru: typeof uk = {
  sheet: { detail: "Заявки", summary: "Сводка" },
  status: { new: "Новая", processed: "Обработана" },
  col: {
    date: "Дата и время",
    day: "День недели",
    hour: "Час",
    status: "Статус",
    name: "Имя",
    phone: "Телефон",
    email: "Email",
    interest: "Интересует",
    formLabel: "Форма",
    formType: "Тип формы",
    preferredTime: "Удобное время",
    message: "Сообщение",
    source: "UTM source",
    medium: "UTM medium",
    campaign: "UTM campaign",
    term: "UTM term",
    content: "UTM content",
    referrer: "Реферер",
    pageHost: "Домен",
    pagePath: "Страница",
    pageTitle: "Заголовок страницы",
    lang: "Язык",
    processedAt: "Обработана в",
    responseHours: "Реакция, ч",
    id: "ID",
  },
  summary: {
    metric: "Показатель",
    value: "Значение",
    countHeader: "Количество",
    generated: "Выгружено",
    generatedBy: "Кем",
    period: "Период",
    total: "Всего заявок",
    newCount: "Новых",
    processedCount: "Обработанных",
    avgResponse: "Средняя реакция, ч",
    firstLast: "Первая — последняя заявка",
    byDirection: "По направлению",
    byForm: "По форме",
    bySource: "По источнику (UTM)",
    byCampaign: "По кампании",
    byPage: "По странице",
    byLang: "По языку сайта",
    byDay: "По дням",
    byHour: "По часам суток",
    notSet: "Не указано",
    direct: "Прямой / без UTM",
    noData: "Нет данных",
    rangeAll: "Все заявки",
    rangeSelected: (n: number) => `Выбранные заявки (${n})`,
  },
};

const en: typeof uk = {
  sheet: { detail: "Submissions", summary: "Summary" },
  status: { new: "New", processed: "Processed" },
  col: {
    date: "Date & time",
    day: "Weekday",
    hour: "Hour",
    status: "Status",
    name: "Name",
    phone: "Phone",
    email: "Email",
    interest: "Interested in",
    formLabel: "Form",
    formType: "Form type",
    preferredTime: "Preferred time",
    message: "Message",
    source: "UTM source",
    medium: "UTM medium",
    campaign: "UTM campaign",
    term: "UTM term",
    content: "UTM content",
    referrer: "Referrer",
    pageHost: "Domain",
    pagePath: "Page",
    pageTitle: "Page title",
    lang: "Language",
    processedAt: "Processed at",
    responseHours: "Response, h",
    id: "ID",
  },
  summary: {
    metric: "Metric",
    value: "Value",
    countHeader: "Count",
    generated: "Exported at",
    generatedBy: "Exported by",
    period: "Period",
    total: "Total submissions",
    newCount: "New",
    processedCount: "Processed",
    avgResponse: "Avg. response, h",
    firstLast: "First — last submission",
    byDirection: "By interest",
    byForm: "By form",
    bySource: "By source (UTM)",
    byCampaign: "By campaign",
    byPage: "By page",
    byLang: "By site language",
    byDay: "By day",
    byHour: "By hour of day",
    notSet: "Not set",
    direct: "Direct / no UTM",
    noData: "No data",
    rangeAll: "All submissions",
    rangeSelected: (n: number) => `Selected submissions (${n})`,
  },
};

export const EXPORT_STRINGS: Record<AdminLocale, typeof uk> = { uk, ru, en };
