import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "service",
    slug: "scar-resurfacing",
    items: [
      { q: { uk: "З якими типами рубців працює лазер?", ru: "С какими типами рубцов работает лазер?", en: "Which types of scars can the laser treat?" },
        a: { uk: "Найкраще відповідають атрофічні та нормотрофічні рубці — післяопераційні, після травм і акне. Гіпертрофічні рубці потребують комбінації з ін'єкційною терапією. При схильності до келоїдів лазерне шліфування застосовують дуже обережно й лише за рішенням лікаря.", ru: "Лучше всего отвечают атрофические и нормотрофические рубцы — послеоперационные, после травм и акне. Гипертрофические рубцы требуют комбинации с инъекционной терапией. При склонности к келоидам лазерная шлифовка применяется очень осторожно и только по решению врача.", en: "Atrophic and normotrophic scars respond best — post-surgical, post-traumatic and acne scars. Hypertrophic scars need combining with injectable therapy. With a keloid tendency, laser resurfacing is used very cautiously and only at the physician's discretion." } },
      { q: { uk: "Скільки процедур потрібно для роботи з рубцем?", ru: "Сколько процедур нужно для работы с рубцом?", en: "How many sessions does scar treatment take?" },
        a: { uk: "Зазвичай 3–5 сеансів з інтервалом 6–8 тижнів. Свіжі рубці до 18 місяців відповідають швидше, старі потребують більшої кількості процедур. Проміжний результат оцінюють після другого сеансу, коли завершиться перебудова тканини.", ru: "Обычно 3–5 сеансов с интервалом 6–8 недель. Свежие рубцы до 18 месяцев отвечают быстрее, старые требуют большего количества процедур. Промежуточный результат оценивают после второго сеанса, когда завершится перестройка ткани.", en: "Usually three to five sessions six to eight weeks apart. Scars under 18 months old respond faster; older ones need more sessions. Progress is reviewed after the second session, once tissue remodelling has taken place." } },
      { q: { uk: "Чи можна працювати з рубцями на тілі?", ru: "Можно ли работать с рубцами на теле?", en: "Can scars on the body be treated?" },
        a: { uk: "Так — після кесаревого розтину, апендектомії, травм і опіків. Шкіра тіла відновлюється повільніше за шкіру обличчя, тому інтервали між сеансами довші, а курс може бути на 1–2 процедури більшим. Зону обов'язково захищають від сонця весь період курсу.", ru: "Да — после кесарева сечения, аппендэктомии, травм и ожогов. Кожа тела восстанавливается медленнее кожи лица, поэтому интервалы между сеансами длиннее, а курс может быть на 1–2 процедуры больше. Зону обязательно защищают от солнца весь период курса.", en: "Yes — after caesarean section, appendectomy, trauma or burns. Body skin heals more slowly than facial skin, so intervals are longer and the course may run one or two sessions more. The area must be protected from the sun throughout." } },
      { q: { uk: "Як доглядати за рубцем після процедури?", ru: "Как ухаживать за рубцом после процедуры?", en: "How should I care for the scar after treatment?" },
        a: { uk: "Перші дні — призначені лікарем засоби для загоєння й ретельне зволоження, потім силіконові гелі або пластирі за рекомендацією. SPF 50+ на зону щонайменше місяць: ультрафіолет робить свіжий рубець темнішим і помітнішим. Скоринки не здирайте.", ru: "Первые дни — назначенные врачом средства для заживления и тщательное увлажнение, затем силиконовые гели или пластыри по рекомендации. SPF 50+ на зону минимум месяц: ультрафиолет делает свежий рубец темнее и заметнее. Корочки не сдирайте.", en: "For the first days, the healing products prescribed plus thorough moisturising; then silicone gels or sheets if recommended. SPF 50+ on the area for at least a month — UV makes a fresh scar darker and more visible. Never pick the crusts." } },
    ],
  },
  {
    type: "service",
    slug: "skin",
    items: [
      { q: { uk: "Як зрозуміти, яка процедура потрібна саме моїй шкірі?", ru: "Как понять, какая процедура нужна именно моей коже?", en: "How do I know which treatment my skin needs?" },
        a: { uk: "Орієнтуйтеся на задачу: очищення та зволоження — HydraFacial, пігментація й судини — M22 Stellar Black, рельєф, рубці та зморшки — AcuPulse CO₂. На консультації лікар оцінює стан шкіри й часто пропонує послідовність із двох методик замість однієї.", ru: "Ориентируйтесь на задачу: очищение и увлажнение — HydraFacial, пигментация и сосуды — M22 Stellar Black, рельеф, рубцы и морщины — AcuPulse CO₂. На консультации врач оценивает состояние кожи и часто предлагает последовательность из двух методик вместо одной.", en: "Start from the goal: cleansing and hydration — HydraFacial; pigmentation and vessels — M22 Stellar Black; texture, scars and wrinkles — AcuPulse CO₂. At the consultation the physician assesses your skin and often proposes a sequence of two methods rather than one." } },
      { q: { uk: "Чи потрібна консультація перед апаратною процедурою?", ru: "Нужна ли консультация перед аппаратной процедурой?", en: "Is a consultation required before a device treatment?" },
        a: { uk: "Так. Лікар перевіряє протипоказання, визначає фототип і підбирає параметри — від цього залежить і результат, і безпека. Для доглядових процедур на кшталт HydraFacial консультацію часто проводять у той самий день, безпосередньо перед сеансом.", ru: "Да. Врач проверяет противопоказания, определяет фототип и подбирает параметры — от этого зависят и результат, и безопасность. Для уходовых процедур вроде HydraFacial консультацию часто проводят в тот же день, непосредственно перед сеансом.", en: "Yes. The physician checks contraindications, determines your phototype and selects the settings — both the result and safety depend on this. For care treatments such as HydraFacial the consultation is often held the same day, right before the session." } },
    ],
  },
  {
    type: "service",
    slug: "splendor-x",
    items: [
      { q: { uk: "Чим Splendor X відрізняється від інших лазерів для епіляції?", ru: "Чем Splendor X отличается от других лазеров для эпиляции?", en: "How does Splendor X differ from other hair removal lasers?" },
        a: { uk: "Splendor X поєднує дві довжини хвилі — александритову 755 нм і Nd:YAG 1064 нм — і дозволяє змішувати їх у потрібній пропорції під конкретний тип шкіри та волосся. Квадратна пляма великого розміру обробляє зону без пропусків і швидше, ніж класичні системи.", ru: "Splendor X сочетает две длины волны — александритовую 755 нм и Nd:YAG 1064 нм — и позволяет смешивать их в нужной пропорции под конкретный тип кожи и волос. Квадратное пятно большого размера обрабатывает зону без пропусков и быстрее, чем классические системы.", en: "Splendor X combines two wavelengths — alexandrite 755 nm and Nd:YAG 1064 nm — and lets them be blended in the right proportion for your skin and hair type. Its large square spot covers the area without gaps and faster than classic systems." } },
      { q: { uk: "Чи використовують Splendor X не лише для епіляції?", ru: "Используют ли Splendor X не только для эпиляции?", en: "Is Splendor X used for anything besides hair removal?" },
        a: { uk: "Так. Nd:YAG-режим застосовують для роботи із судинними елементами та для фотоомолодження — стимуляції колагену без пошкодження поверхні шкіри. Конкретний протокол лікар обирає за вашим запитом і типом шкіри.", ru: "Да. Nd:YAG-режим применяют для работы с сосудистыми элементами и для фотоомоложения — стимуляции коллагена без повреждения поверхности кожи. Конкретный протокол врач выбирает по вашему запросу и типу кожи.", en: "Yes. The Nd:YAG mode is used for vascular lesions and for photorejuvenation — stimulating collagen without damaging the skin surface. The physician selects the protocol according to your goal and skin type." } },
      { q: { uk: "Як довго тримається результат після курсу?", ru: "Как долго держится результат после курса?", en: "How long do results last after a course?" },
        a: { uk: "Після повного курсу ріст волосся зменшується до 80–90%, і цей результат тримається роками. Поодинокі волосини можуть з'являтися через гормональні зміни — для них достатньо 1–2 підтримувальних сеансів на рік.", ru: "После полного курса рост волос уменьшается до 80–90%, и этот результат держится годами. Единичные волосы могут появляться из-за гормональных изменений — для них достаточно 1–2 поддерживающих сеансов в год.", en: "After a full course hair growth is reduced by 80–90% and the result lasts for years. Isolated hairs may appear because of hormonal changes; one or two maintenance sessions a year are enough to manage them." } },
      { q: { uk: "Чи потрібне знеболення під час епіляції на Splendor X?", ru: "Нужно ли обезболивание во время эпиляции на Splendor X?", en: "Is anaesthesia needed for Splendor X hair removal?" },
        a: { uk: "Зазвичай ні. Апарат має вбудовану систему контактного охолодження, яка захищає шкіру й робить сеанс комфортним. Для особливо чутливих зон лікар може нанести аплікаційний анестетик за 30 хвилин до процедури.", ru: "Обычно нет. Аппарат имеет встроенную систему контактного охлаждения, которая защищает кожу и делает сеанс комфортным. Для особо чувствительных зон врач может нанести аппликационный анестетик за 30 минут до процедуры.", en: "Usually not. The device has built-in contact cooling that protects the skin and keeps the session comfortable. For particularly sensitive areas the physician can apply a topical anaesthetic 30 minutes beforehand." } },
    ],
  },
  {
    type: "service",
    slug: "stem-cell-therapy",
    items: [
      { q: { uk: "Які обстеження потрібні перед терапією стовбуровими клітинами?", ru: "Какие обследования нужны перед терапией стволовыми клетками?", en: "Which tests are needed before stem cell therapy?" },
        a: { uk: "Перед процедурою обов'язкові розгорнутий аналіз крові, біохімія, коагулограма, аналізи на інфекції, а за показаннями — онкомаркери та консультації профільних спеціалістів. Це медична процедура, тому обстеження не формальність, а умова безпеки.", ru: "Перед процедурой обязательны развёрнутый анализ крови, биохимия, коагулограмма, анализы на инфекции, а по показаниям — онкомаркеры и консультации профильных специалистов. Это медицинская процедура, поэтому обследование не формальность, а условие безопасности.", en: "A full blood count, biochemistry, coagulation profile and infection screening are mandatory, with tumour markers and specialist consultations if indicated. This is a medical procedure, so the work-up is a safety requirement, not a formality." } },
      { q: { uk: "Кому не підходить терапія стовбуровими клітинами?", ru: "Кому не подходит терапия стволовыми клетками?", en: "Who is not suitable for stem cell therapy?" },
        a: { uk: "Процедуру не проводять при онкологічних захворюваннях та в анамнезі без узгодження з онкологом, автоімунних станах у загостренні, гострих інфекціях, вагітності та лактації, тяжких порушеннях згортання крові. Рішення ухвалюють після повного обстеження.", ru: "Процедуру не проводят при онкологических заболеваниях и в анамнезе без согласования с онкологом, аутоиммунных состояниях в обострении, острых инфекциях, беременности и лактации, тяжёлых нарушениях свёртывания крови. Решение принимают после полного обследования.", en: "It is not performed with oncological disease — current or past, without oncology clearance — autoimmune conditions in flare, acute infection, pregnancy and breastfeeding, or severe clotting disorders. The decision follows a full work-up." } },
    ],
  },
  {
    type: "service",
    slug: "stretch-marks-removal",
    items: [
      { q: { uk: "Які зони найчастіше обробляють при розтяжках?", ru: "Какие зоны чаще всего обрабатывают при растяжках?", en: "Which areas are most often treated for stretch marks?" },
        a: { uk: "Живіт, стегна, сідниці, груди та внутрішня поверхня рук — саме там стрії з'являються найчастіше після вагітності, зміни ваги чи підліткового росту. Площу й кількість зон визначають на консультації, від них залежить тривалість сеансу.", ru: "Живот, бёдра, ягодицы, грудь и внутренняя поверхность рук — именно там стрии появляются чаще всего после беременности, изменения веса или подросткового роста. Площадь и количество зон определяют на консультации, от них зависит длительность сеанса.", en: "The abdomen, thighs, buttocks, breasts and inner arms — where stretch marks most often appear after pregnancy, weight change or adolescent growth. The area and number of zones are agreed at the consultation and determine session length." } },
      { q: { uk: "Чи болісна процедура і як проходить відновлення?", ru: "Болезненна ли процедура и как проходит восстановление?", en: "Is the procedure painful and what is recovery like?" },
        a: { uk: "Перед сеансом наносять аплікаційну анестезію, тому обробка переноситься комфортно — відчувається тепло й поколювання. Почервоніння та набряк тримаються 2–4 дні, легке лущення — до тижня. Місяць після процедури зону захищають кремом SPF 50+.", ru: "Перед сеансом наносят аппликационную анестезию, поэтому обработка переносится комфортно — ощущается тепло и покалывание. Покраснение и отёк держатся 2–4 дня, лёгкое шелушение — до недели. Месяц после процедуры зону защищают кремом SPF 50+.", en: "Topical anaesthetic is applied beforehand, so the treatment is comfortable — you feel warmth and tingling. Redness and swelling last two to four days and light flaking up to a week. The area needs SPF 50+ for a month afterwards." } },
      { q: { uk: "Чи можна запобігти появі нових розтяжок?", ru: "Можно ли предотвратить появление новых растяжек?", en: "Can new stretch marks be prevented?" },
        a: { uk: "Значною мірою так. Головні чинники — плавна зміна ваги, достатнє зволоження шкіри, збалансоване харчування з білком і контроль гормонального фону. Під час вагітності важливі догляд і поступовий набір ваги — це реально зменшує ризик.", ru: "В значительной мере да. Главные факторы — плавное изменение веса, достаточное увлажнение кожи, сбалансированное питание с белком и контроль гормонального фона. Во время беременности важны уход и постепенный набор веса — это реально уменьшает риск.", en: "Largely yes. The key factors are gradual weight change, well-hydrated skin, a balanced protein-adequate diet and hormonal balance. In pregnancy, skincare and steady weight gain genuinely reduce the risk." } },
      { q: { uk: "Чи можна поєднувати лазер з апаратною корекцією тіла?", ru: "Можно ли сочетать лазер с аппаратной коррекцией тела?", en: "Can laser treatment be combined with body contouring?" },
        a: { uk: "Так, і часто це логічно: спершу працюємо з об'ємами й тонусом за допомогою EMSCULPT NEO чи Ultraformer MPT, потім лазером — із текстурою шкіри та стріями. Послідовність та інтервали визначає лікар, зазвичай між методиками витримують 2–4 тижні.", ru: "Да, и часто это логично: сначала работаем с объёмами и тонусом с помощью EMSCULPT NEO или Ultraformer MPT, затем лазером — с текстурой кожи и стриями. Последовательность и интервалы определяет врач, обычно между методиками выдерживают 2–4 недели.", en: "Yes, and it often makes sense: first address volume and tone with EMSCULPT NEO or Ultraformer MPT, then treat skin texture and striae with the laser. The physician sets the order and intervals — usually two to four weeks between methods." } },
    ],
  },
  {
    type: "service",
    slug: "ultraformer-mpt",
    items: [
      { q: { uk: "Кому підходить HIFU-ліфтинг Ultraformer MPT?", ru: "Кому подходит HIFU-лифтинг Ultraformer MPT?", en: "Who is Ultraformer MPT HIFU lifting suitable for?" },
        a: { uk: "Тим, у кого з'явився помірний птоз: розмитий овал, опущені куточки губ, надлишок тканин під підборіддям. Найкраще методика працює у віці 35–60 років. При вираженому надлишку шкіри апаратний ліфтинг результату не дасть — тоді доречна консультація хірурга.", ru: "Тем, у кого появился умеренный птоз: размытый овал, опущенные уголки губ, избыток тканей под подбородком. Лучше всего методика работает в возрасте 35–60 лет. При выраженном избытке кожи аппаратный лифтинг результата не даст — тогда уместна консультация хирурга.", en: "Those with moderate laxity: a blurred jawline, downturned mouth corners, fullness under the chin. It works best between 35 and 60. With significant excess skin, device lifting will not deliver — a surgical consultation is the right step." } },
      { q: { uk: "Коли буде видно результат після Ultraformer MPT?", ru: "Когда будет виден результат после Ultraformer MPT?", en: "When will I see results from Ultraformer MPT?" },
        a: { uk: "Легкий ефект підтяжки помітний одразу, але головні зміни розвиваються поступово: синтез нового колагену триває 2–3 місяці, і саме тоді оцінюють результат. Це методика для тих, хто готовий почекати заради природності.", ru: "Лёгкий эффект подтяжки заметен сразу, но главные изменения развиваются постепенно: синтез нового коллагена длится 2–3 месяца, и именно тогда оценивают результат. Это методика для тех, кто готов подождать ради естественности.", en: "A slight lift is visible immediately, but the main change develops gradually: new collagen synthesis continues for two to three months, when the result is assessed. It is a method for those willing to wait for a natural outcome." } },
      { q: { uk: "Чи є протипоказання до Ultraformer MPT?", ru: "Есть ли противопоказания к Ultraformer MPT?", en: "Are there contraindications to Ultraformer MPT?" },
        a: { uk: "Так: вагітність і лактація, наявність металевих імплантатів або ниток у зоні обробки, кардіостимулятор, активні запалення та інфекції шкіри, онкологічні захворювання в активній фазі, тяжкі форми акне в зоні впливу. Анамнез перевіряють на консультації.", ru: "Да: беременность и лактация, наличие металлических имплантатов или нитей в зоне обработки, кардиостимулятор, активные воспаления и инфекции кожи, онкологические заболевания в активной фазе, тяжёлые формы акне в зоне воздействия. Анамнез проверяют на консультации.", en: "Yes: pregnancy and breastfeeding, metal implants or threads in the treated area, a pacemaker, active skin inflammation or infection, active oncological disease, and severe acne in the treatment zone. Your history is reviewed at the consultation." } },
      { q: { uk: "Чи є обмеження після процедури?", ru: "Есть ли ограничения после процедуры?", en: "Are there restrictions after the treatment?" },
        a: { uk: "Період відновлення відсутній: до звичних справ можна повертатися одразу. Дві доби варто уникати сауни, гарячої ванни та інтенсивних тренувань. Легка чутливість або відчуття «крепатури» в зоні обробки протягом кількох днів — нормальна реакція.", ru: "Период восстановления отсутствует: к привычным делам можно возвращаться сразу. Двое суток стоит избегать сауны, горячей ванны и интенсивных тренировок. Лёгкая чувствительность или ощущение «крепатуры» в зоне обработки в течение нескольких дней — нормальная реакция.", en: "There is no downtime — you can return to normal activities immediately. Avoid saunas, hot baths and intensive exercise for 48 hours. Mild tenderness in the treated area for a few days is a normal reaction." } },
    ],
  },
];

seed(batches);
