import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "service",
    slug: "laser-resurfacing",
    items: [
      { q: { uk: "Як підготуватися до лазерної шліфовки обличчя?", ru: "Как подготовиться к лазерной шлифовке лица?", en: "How should I prepare for laser resurfacing?" },
        a: { uk: "За 2–4 тижні відмовтеся від засмаги й солярію, за 5–7 днів — від кислот, ретиноїдів і скрабів. При схильності до герпесу лікар призначає противірусну профілактику. Заздалегідь придбайте засіб для загоєння та SPF 50+.", ru: "За 2–4 недели откажитесь от загара и солярия, за 5–7 дней — от кислот, ретиноидов и скрабов. При склонности к герпесу врач назначает противовирусную профилактику. Заранее приобретите средство для заживления и SPF 50+.", en: "Avoid tanning and solariums for 2–4 weeks and acids, retinoids and scrubs for 5–7 days. If you are prone to herpes, the physician will prescribe antiviral prophylaxis. Buy a healing product and SPF 50+ in advance." } },
      { q: { uk: "Чи залишаються сліди після лазерної шліфовки?", ru: "Остаются ли следы после лазерной шлифовки?", en: "Does laser resurfacing leave marks?" },
        a: { uk: "За дотримання рекомендацій — ні. Ризики виникають, коли пацієнт здирає лусочки, нехтує SPF або виходить на активне сонце в перші тижні: тоді можлива тимчасова післязапальна пігментація. Вона зворотна, але потребує додаткового лікування.", ru: "При соблюдении рекомендаций — нет. Риски возникают, когда пациент сдирает чешуйки, пренебрегает SPF или выходит на активное солнце в первые недели: тогда возможна временная поствоспалительная пигментация. Она обратима, но требует дополнительного лечения.", en: "Not if the aftercare is followed. Problems arise when flakes are picked off, SPF is skipped or the skin meets strong sun in the first weeks — this can cause temporary post-inflammatory pigmentation. It is reversible but needs extra treatment." } },
      { q: { uk: "У яку пору року краще планувати лазерну шліфовку?", ru: "В какое время года лучше планировать лазерную шлифовку?", en: "What time of year is best for laser resurfacing?" },
        a: { uk: "Оптимально — з жовтня до березня, коли сонячна активність низька. Влітку процедуру теж проводять, але вимоги до фотозахисту суворіші, а від поїздок на море в перший місяць доведеться відмовитися. Плануйте курс з урахуванням відпустки.", ru: "Оптимально — с октября по март, когда солнечная активность низкая. Летом процедуру тоже проводят, но требования к фотозащите строже, а от поездок на море в первый месяц придётся отказаться. Планируйте курс с учётом отпуска.", en: "Ideally October to March, when UV levels are low. It can be done in summer, but photoprotection requirements are stricter and beach holidays must be avoided for the first month. Plan the course around your travel." } },
      { q: { uk: "Чи можна робити шліфовку на шиї та в зоні декольте?", ru: "Можно ли делать шлифовку на шее и в зоне декольте?", en: "Can resurfacing be done on the neck and décolleté?" },
        a: { uk: "Так, але шкіра там тонша й гірше кровопостачається, тому лікар працює м'якшими параметрами та збільшує кількість сеансів. Відновлення в цих зонах триває довше, ніж на обличчі — це нормально й враховується в плані курсу.", ru: "Да, но кожа там тоньше и хуже кровоснабжается, поэтому врач работает более мягкими параметрами и увеличивает количество сеансов. Восстановление в этих зонах длится дольше, чем на лице — это нормально и учитывается в плане курса.", en: "Yes, though the skin there is thinner with poorer blood supply, so gentler settings and more sessions are used. Recovery in these areas takes longer than on the face — this is expected and built into the plan." } },
    ],
  },
  {
    type: "service",
    slug: "laser-resurfacing-post-acne",
    items: [
      { q: { uk: "Скільки сеансів потрібно для корекції рубців постакне?", ru: "Сколько сеансов нужно для коррекции рубцов постакне?", en: "How many sessions are needed for post-acne scarring?" },
        a: { uk: "Зазвичай 3–4 процедури з інтервалом 6–8 тижнів. Кількість залежить від типу та глибини рубців: поверхневі rolling-рубці відповідають швидше, глибокі ice-pick потребують більшої кількості сеансів. Проміжний результат оцінюють після другої процедури.", ru: "Обычно 3–4 процедуры с интервалом 6–8 недель. Количество зависит от типа и глубины рубцов: поверхностные rolling-рубцы отвечают быстрее, глубокие ice-pick требуют большего количества сеансов. Промежуточный результат оценивают после второй процедуры.", en: "Usually three to four sessions six to eight weeks apart. The number depends on scar type and depth: shallow rolling scars respond faster, deep ice-pick scars need more sessions. Progress is reviewed after the second treatment." } },
      { q: { uk: "Чи можна поєднувати шліфовку постакне з PRP-терапією?", ru: "Можно ли сочетать шлифовку постакне с PRP-терапией?", en: "Can post-acne resurfacing be combined with PRP therapy?" },
        a: { uk: "Так, і це часто прискорює відновлення. Плазму або екзосоми наносять одразу після лазерної обробки, коли мікроканали відкриті, — це підсилює регенерацію та скорочує період почервоніння. Доцільність комбінації визначає лікар.", ru: "Да, и это часто ускоряет восстановление. Плазму или экзосомы наносят сразу после лазерной обработки, когда микроканалы открыты, — это усиливает регенерацию и сокращает период покраснения. Целесообразность комбинации определяет врач.", en: "Yes, and it often speeds recovery. Plasma or exosomes are applied immediately after the laser pass, while the microchannels are open, which boosts regeneration and shortens the redness phase. The physician decides whether to combine them." } },
      { q: { uk: "Що робити з пігментними плямами після акне?", ru: "Что делать с пигментными пятнами после акне?", en: "What can be done about pigmented marks after acne?" },
        a: { uk: "Плями — це післязапальна пігментація, а не рубці, і працюють із ними інакше. Часто достатньо IPL на M22 Stellar Black у поєднанні з домашнім доглядом і суворим SPF. Якщо є і плями, і рубці, лікар планує послідовність методик.", ru: "Пятна — это поствоспалительная пигментация, а не рубцы, и работают с ними иначе. Часто достаточно IPL на M22 Stellar Black в сочетании с домашним уходом и строгим SPF. Если есть и пятна, и рубцы, врач планирует последовательность методик.", en: "Marks are post-inflammatory pigmentation, not scars, and are treated differently. IPL on M22 Stellar Black plus home care and strict SPF is often enough. If both marks and scars are present, the physician sequences the treatments." } },
      { q: { uk: "Чи можна робити процедуру при активних висипаннях?", ru: "Можно ли делать процедуру при активных высыпаниях?", en: "Can the treatment be done with active breakouts?" },
        a: { uk: "Ні. Спершу потрібно зняти запалення — інакше лазер може спровокувати загострення й нові сліди. Ми починаємо з лікування акне, а до шліфовки переходимо після щонайменше 3 місяців стабільної ремісії.", ru: "Нет. Сначала нужно снять воспаление — иначе лазер может спровоцировать обострение и новые следы. Мы начинаем с лечения акне, а к шлифовке переходим после минимум 3 месяцев стабильной ремиссии.", en: "No. The inflammation must be controlled first, otherwise the laser can trigger a flare and new marks. We begin with acne treatment and move to resurfacing after at least three months of stable remission." } },
    ],
  },
  {
    type: "service",
    slug: "laser-women",
    items: [
      { q: { uk: "Як гормональні зміни впливають на результат епіляції?", ru: "Как гормональные изменения влияют на результат эпиляции?", en: "How do hormonal changes affect hair removal results?" },
        a: { uk: "Гормональний фон безпосередньо впливає на ріст волосся: при СПКЯ, порушеннях роботи щитоподібної залози або в період вагітності можливе відновлення росту навіть після повного курсу. У таких випадках варто паралельно проконсультуватися з ендокринологом — інакше підтримувальні сеанси будуть потрібні частіше.", ru: "Гормональный фон напрямую влияет на рост волос: при СПКЯ, нарушениях работы щитовидной железы или в период беременности возможно возобновление роста даже после полного курса. В таких случаях стоит параллельно проконсультироваться с эндокринологом — иначе поддерживающие сеансы понадобятся чаще.", en: "Hormones directly affect hair growth: with PCOS, thyroid disorders or during pregnancy, regrowth can occur even after a full course. In such cases an endocrinology review is worthwhile — otherwise maintenance sessions will be needed more often." } },
      { q: { uk: "Чи можна робити лазерну епіляцію під час годування груддю?", ru: "Можно ли делать лазерную эпиляцию во время грудного вскармливания?", en: "Can laser hair removal be done while breastfeeding?" },
        a: { uk: "Процедуру зазвичай відкладають до завершення лактації: гормональний фон нестабільний, тому результат непередбачуваний, а зону грудей не обробляють. Обробку інших зон лікар розглядає індивідуально після консультації.", ru: "Процедуру обычно откладывают до завершения лактации: гормональный фон нестабилен, поэтому результат непредсказуем, а зону груди не обрабатывают. Обработку других зон врач рассматривает индивидуально после консультации.", en: "It is usually postponed until breastfeeding ends: hormones are unstable so results are unpredictable, and the breast area is not treated. Treatment of other areas is considered individually after a consultation." } },
    ],
  },
  {
    type: "service",
    slug: "lip-augmentation",
    items: [
      { q: { uk: "Скільки філера потрібно для губ?", ru: "Сколько филлера нужно для губ?", en: "How much filler do lips need?" },
        a: { uk: "Найчастіше 0,5–1 мл за процедуру. Для делікатного зволоження й контуру достатньо половини шприца, для помітного об'єму — цілого. Якщо потрібна виразніша зміна, краще розділити на два етапи з інтервалом 3–4 тижні: так тканини адаптуються, а результат виглядає природно.", ru: "Чаще всего 0,5–1 мл за процедуру. Для деликатного увлажнения и контура достаточно половины шприца, для заметного объёма — целого. Если нужна более выраженная перемена, лучше разделить на два этапа с интервалом 3–4 недели: так ткани адаптируются, а результат выглядит естественно.", en: "Usually 0.5–1 ml per session. Half a syringe is enough for subtle hydration and definition; a full one gives noticeable volume. For a bigger change it is better to split into two stages three to four weeks apart, so the tissue adapts and the result looks natural." } },
      { q: { uk: "Як довго тримається результат збільшення губ?", ru: "Как долго держится результат увеличения губ?", en: "How long do lip filler results last?" },
        a: { uk: "У середньому 6–12 місяців. Губи — рухома зона з активним кровопостачанням, тому препарат розсмоктується швидше, ніж у вилицях чи підборідді. Тривалість також залежить від метаболізму, куріння та обраного філера.", ru: "В среднем 6–12 месяцев. Губы — подвижная зона с активным кровоснабжением, поэтому препарат рассасывается быстрее, чем в скулах или подбородке. Длительность также зависит от метаболизма, курения и выбранного филлера.", en: "On average 6–12 months. The lips move constantly and have a rich blood supply, so filler breaks down faster than in the cheekbones or chin. Metabolism, smoking and the product chosen also affect longevity." } },
      { q: { uk: "Які обмеження після збільшення губ?", ru: "Какие ограничения после увеличения губ?", en: "What restrictions apply after lip augmentation?" },
        a: { uk: "Дві доби уникайте гарячих напоїв, сауни, спорту й алкоголю, тиждень — стоматологічних процедур і масажу обличчя. Не спіть обличчям у подушку перші ночі. Пийте більше води й не масажуйте губи без вказівки лікаря.", ru: "Двое суток избегайте горячих напитков, сауны, спорта и алкоголя, неделю — стоматологических процедур и массажа лица. Не спите лицом в подушку первые ночи. Пейте больше воды и не массируйте губы без указания врача.", en: "For 48 hours avoid hot drinks, saunas, exercise and alcohol; for a week avoid dental work and facial massage. Do not sleep face-down for the first few nights. Drink plenty of water and do not massage the lips unless instructed." } },
      { q: { uk: "Чи можна виправити асиметрію губ філером?", ru: "Можно ли исправить асимметрию губ филлером?", en: "Can filler correct lip asymmetry?" },
        a: { uk: "Так, це одне з частих завдань. Лікар вводить різний об'єм у різні ділянки, вирівнюючи форму — легка природна асиметрія при цьому зазвичай залишається, бо саме вона робить обличчя живим. Виражена асиметрія може потребувати двох етапів корекції.", ru: "Да, это одна из частых задач. Врач вводит разный объём в разные участки, выравнивая форму — лёгкая естественная асимметрия при этом обычно остаётся, потому что именно она делает лицо живым. Выраженная асимметрия может потребовать двух этапов коррекции.", en: "Yes, it is a common goal. The physician places different volumes in different areas to even out the shape, while keeping the slight natural asymmetry that makes a face look alive. Pronounced asymmetry may need two stages." } },
    ],
  },
  {
    type: "service",
    slug: "lip-biorevitalisation",
    items: [
      { q: { uk: "Чим біоревіталізація губ відрізняється від філерів?", ru: "Чем биоревитализация губ отличается от филлеров?", en: "How does lip biorevitalisation differ from fillers?" },
        a: { uk: "Філер створює об'єм і форму, біоревіталізація працює з якістю тканини: зволоженням, гладкістю, кольором. Це різні задачі й різні препарати. Часто їх поєднують: спершу відновлюють якість губ, потім за бажанням додають об'єм.", ru: "Филлер создаёт объём и форму, биоревитализация работает с качеством ткани: увлажнением, гладкостью, цветом. Это разные задачи и разные препараты. Часто их сочетают: сначала восстанавливают качество губ, затем при желании добавляют объём.", en: "Filler creates volume and shape; biorevitalisation works on tissue quality — hydration, smoothness and colour. They are different goals and different products, and are often combined: quality first, volume afterwards if wanted." } },
      { q: { uk: "Чи є набряк після біоревіталізації губ?", ru: "Есть ли отёк после биоревитализации губ?", en: "Is there swelling after lip biorevitalisation?" },
        a: { uk: "Незначний набряк і дрібні папули в місцях ін'єкцій тримаються 24–48 годин. Іноді з'являються точкові синці, які минають за 3–5 днів. Холод у перші години й відмова від алкоголю помітно скорочують цей період.", ru: "Незначительный отёк и мелкие папулы в местах инъекций держатся 24–48 часов. Иногда появляются точечные синяки, которые проходят за 3–5 дней. Холод в первые часы и отказ от алкоголя заметно сокращают этот период.", en: "Mild swelling and small papules at the injection points last 24–48 hours. Occasional pinpoint bruises fade within three to five days. Cold compresses in the first hours and avoiding alcohol shorten this noticeably." } },
      { q: { uk: "Чи допоможе процедура при сухості та тріщинах на губах?", ru: "Поможет ли процедура при сухости и трещинах на губах?", en: "Does the treatment help with dry, cracked lips?" },
        a: { uk: "Так, це її основне призначення: гіалуронова кислота утримує вологу в тканині зсередини, тому губи перестають пересихати й тріскатися. Якщо сухість супроводжується заїдами чи запаленням, лікар спершу з'ясовує причину — це може бути дефіцит заліза або вітамінів групи B.", ru: "Да, это её основное назначение: гиалуроновая кислота удерживает влагу в ткани изнутри, поэтому губы перестают пересыхать и трескаться. Если сухость сопровождается заедами или воспалением, врач сначала выясняет причину — это может быть дефицит железа или витаминов группы B.", en: "Yes, that is its main purpose: hyaluronic acid holds water within the tissue, so the lips stop drying and cracking. If dryness comes with cracked corners or inflammation, the physician looks for a cause first — often iron or B-vitamin deficiency." } },
      { q: { uk: "Чи можна робити процедуру перед подією?", ru: "Можно ли делать процедуру перед событием?", en: "Can it be done before an event?" },
        a: { uk: "Плануйте сеанс щонайменше за тиждень: папули розсмоктуються за добу-дві, але дрібні синці можуть триматися до п'яти днів. Тоді до події губи виглядатимуть доглянутими й гладкими, без слідів ін'єкцій.", ru: "Планируйте сеанс минимум за неделю: папулы рассасываются за сутки-двое, но мелкие синяки могут держаться до пяти дней. Тогда к событию губы будут выглядеть ухоженными и гладкими, без следов инъекций.", en: "Book at least a week ahead: the papules settle within a day or two, but small bruises can last up to five days. By the event the lips look smooth and cared-for, with no sign of injections." } },
    ],
  },
  {
    type: "service",
    slug: "longevity-program",
    items: [
      { q: { uk: "З чого починається Longevity-програма?", ru: "С чего начинается Longevity-программа?", en: "How does the Longevity programme start?" },
        a: { uk: "З комплексної діагностики: розгорнута лабораторна панель, гормональний статус, маркери запалення, аналіз складу тіла на InBody та за потреби УЗД. Далі — консультація, на якій лікар пояснює цифри й формує персональний протокол на найближчі місяці.", ru: "С комплексной диагностики: развёрнутая лабораторная панель, гормональный статус, маркеры воспаления, анализ состава тела на InBody и при необходимости УЗИ. Далее — консультация, на которой врач объясняет цифры и формирует персональный протокол на ближайшие месяцы.", en: "With comprehensive diagnostics: an extended laboratory panel, hormonal status, inflammatory markers, an InBody composition scan and ultrasound where needed. Then a consultation where the physician explains the numbers and builds your protocol for the months ahead." } },
      { q: { uk: "Що таке біологічний вік і як його визначають?", ru: "Что такое биологический возраст и как его определяют?", en: "What is biological age and how is it measured?" },
        a: { uk: "Біологічний вік відображає фактичний стан організму, який може відрізнятися від паспортного в обидва боки. Його оцінюють за сукупністю показників: метаболічні маркери, рівень запалення, гормональний профіль, склад тіла, стан судин. Це орієнтир для протоколу й спосіб бачити динаміку.", ru: "Биологический возраст отражает фактическое состояние организма, которое может отличаться от паспортного в обе стороны. Его оценивают по совокупности показателей: метаболические маркеры, уровень воспаления, гормональный профиль, состав тела, состояние сосудов. Это ориентир для протокола и способ видеть динамику.", en: "Biological age reflects the actual state of the body, which can differ from your calendar age in either direction. It is estimated from a combination of markers: metabolism, inflammation, hormones, body composition and vascular health. It guides the protocol and lets you track progress." } },
      { q: { uk: "Що входить до Longevity-протоколу, крім аналізів?", ru: "Что входит в Longevity-протокол, кроме анализов?", en: "What does the Longevity protocol include besides tests?" },
        a: { uk: "Залежно від результатів це може бути корекція харчування та сну, персональні нутрицевтики за виявленими дефіцитами, IV-терапія, робота з гормональним балансом, рекомендації щодо фізичної активності. Естетичні процедури за бажанням вбудовуються в той самий план.", ru: "В зависимости от результатов это может быть коррекция питания и сна, персональные нутрицевтики по выявленным дефицитам, IV-терапия, работа с гормональным балансом, рекомендации по физической активности. Эстетические процедуры при желании встраиваются в тот же план.", en: "Depending on the findings: nutrition and sleep correction, personalised nutraceuticals for identified deficiencies, IV therapy, hormonal balance work and activity recommendations. Aesthetic treatments can be built into the same plan if you wish." } },
      { q: { uk: "Скільки триває участь у програмі?", ru: "Сколько длится участие в программе?", en: "How long does the programme last?" },
        a: { uk: "Базовий цикл розрахований на 6–12 місяців — саме стільки потрібно, щоб змінити показники, а не лише самопочуття. Далі більшість пацієнтів переходять у режим щорічного контролю з підтримувальними протоколами.", ru: "Базовый цикл рассчитан на 6–12 месяцев — именно столько нужно, чтобы изменить показатели, а не только самочувствие. Далее большинство пациентов переходят в режим ежегодного контроля с поддерживающими протоколами.", en: "The core cycle runs 6–12 months — the time needed to change measurable markers, not just how you feel. Most patients then move to annual reviews with maintenance protocols." } },
    ],
  },
  {
    type: "service",
    slug: "m22-stellar-black",
    items: [
      { q: { uk: "Чи є реабілітація після процедури M22 Stellar Black?", ru: "Есть ли реабилитация после процедуры M22 Stellar Black?", en: "Is there downtime after M22 Stellar Black?" },
        a: { uk: "Після IPL реабілітації практично немає: почервоніння минає за кілька годин, пігментні плями темніють і сходять протягом 5–10 днів. Після фракційного модуля ResurFX можливе легке лущення 3–5 днів. SPF 50+ обов'язковий у будь-якому режимі.", ru: "После IPL реабилитации практически нет: покраснение проходит за несколько часов, пигментные пятна темнеют и сходят в течение 5–10 дней. После фракционного модуля ResurFX возможно лёгкое шелушение 3–5 дней. SPF 50+ обязателен в любом режиме.", en: "After IPL there is virtually no downtime: redness settles within hours and pigmented spots darken then flake away over 5–10 days. After the fractional ResurFX module there may be light flaking for 3–5 days. SPF 50+ is essential in every mode." } },
      { q: { uk: "Чи можна робити M22 влітку?", ru: "Можно ли делать M22 летом?", en: "Can M22 be done in summer?" },
        a: { uk: "IPL-процедури проводять на незасмаглій шкірі, тому влітку їх планують обережно: потрібні 2 тижні без сонця до сеансу та суворий SPF 50+ після. За наявності свіжої засмаги процедуру переносять — інакше зростає ризик пігментації.", ru: "IPL-процедуры проводят на незагорелой коже, поэтому летом их планируют осторожно: нужны 2 недели без солнца до сеанса и строгий SPF 50+ после. При наличии свежего загара процедуру переносят — иначе возрастает риск пигментации.", en: "IPL is performed on untanned skin, so summer scheduling needs care: two weeks without sun before the session and strict SPF 50+ afterwards. With a fresh tan the treatment is postponed, as the pigmentation risk rises." } },
      { q: { uk: "Чи повертається пігментація після лікування на M22?", ru: "Возвращается ли пигментация после лечения на M22?", en: "Does pigmentation return after M22 treatment?" },
        a: { uk: "Оброблені плями не відновлюються, але схильність до пігментації залишається — під впливом сонця чи гормональних змін можуть з'явитися нові. Щоденний SPF і контроль гормонального фону суттєво зменшують ймовірність рецидиву.", ru: "Обработанные пятна не восстанавливаются, но склонность к пигментации остаётся — под воздействием солнца или гормональных изменений могут появиться новые. Ежедневный SPF и контроль гормонального фона существенно уменьшают вероятность рецидива.", en: "Treated spots do not come back, but the tendency to pigment remains — sun exposure or hormonal shifts can create new ones. Daily SPF and attention to hormonal balance greatly reduce the chance of recurrence." } },
    ],
  },
];

seed(batches);
