import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "static_page",
    slug: "laboratory",
    items: [
      { q: { uk: "Як підготуватися до здачі аналізів крові?", ru: "Как подготовиться к сдаче анализов крови?", en: "How should I prepare for blood tests?" },
        a: { uk: "Більшість аналізів здають натще — останній прийом їжі за 8–12 годин до візиту, воду пити можна. За добу уникайте алкоголю та інтенсивних тренувань. Якщо ви приймаєте препарати чи добавки, повідомте про це — окремі з них тимчасово скасовують.", ru: "Большинство анализов сдают натощак — последний приём пищи за 8–12 часов до визита, воду пить можно. За сутки избегайте алкоголя и интенсивных тренировок. Если вы принимаете препараты или добавки, сообщите об этом — отдельные из них временно отменяют.", en: "Most tests require fasting — your last meal 8–12 hours before, water is allowed. Avoid alcohol and intensive exercise for 24 hours. Tell us about any medication or supplements: some need to be paused." } },
      { q: { uk: "Які дослідження доступні у власній лабораторії GENEVITY?", ru: "Какие исследования доступны в собственной лаборатории GENEVITY?", en: "Which tests are available in GENEVITY's own laboratory?" },
        a: { uk: "Загальний і біохімічний аналізи крові, гормональні панелі, вітаміни та мікроелементи, ліпідограма, маркери запалення, онкомаркери, ПЛР-діагностика, бакпосіви, імунологічні та алергологічні тести. Повний перелік і терміни виконання підкаже адміністратор.", ru: "Общий и биохимический анализы крови, гормональные панели, витамины и микроэлементы, липидограмма, маркеры воспаления, онкомаркеры, ПЦР-диагностика, бакпосевы, иммунологические и аллергологические тесты. Полный перечень и сроки выполнения подскажет администратор.", en: "Full blood count and biochemistry, hormone panels, vitamins and trace elements, lipid profile, inflammatory and tumour markers, PCR testing, cultures, and immunological and allergy tests. The administrator can confirm the full list and turnaround times." } },
      { q: { uk: "Чи допоможе лікар розібратися з результатами аналізів?", ru: "Поможет ли врач разобраться с результатами анализов?", en: "Will a physician help me interpret my results?" },
        a: { uk: "Так. Окремі цифри поза контекстом мало що означають — важлива їх сукупність і ваш анамнез. На консультації лікар пояснює показники у зв'язку між собою та складає план дій. Записатися можна одразу після отримання результатів.", ru: "Да. Отдельные цифры вне контекста мало что значат — важна их совокупность и ваш анамнез. На консультации врач объясняет показатели во взаимосвязи и составляет план действий. Записаться можно сразу после получения результатов.", en: "Yes. Isolated numbers mean little on their own — what matters is the whole picture alongside your history. At the consultation the physician explains the results together and sets out a plan. You can book as soon as results arrive." } },
    ],
  },
  {
    type: "static_page",
    slug: "stationary",
    items: [
      { q: { uk: "Які процедури проводять у денному стаціонарі?", ru: "Какие процедуры проводят в дневном стационаре?", en: "Which procedures take place in the day hospital?" },
        a: { uk: "Насамперед це IV-терапія, крапельниці з екзосомами, інфузійні longevity-протоколи, а також спостереження після процедур, що потребують медичного нагляду. Кожен пацієнт перебуває в окремій палаті під контролем медичного персоналу.", ru: "Прежде всего это IV-терапия, капельницы с экзосомами, инфузионные longevity-протоколы, а также наблюдение после процедур, требующих медицинского контроля. Каждый пациент находится в отдельной палате под контролем медицинского персонала.", en: "Primarily IV therapy, exosome infusions and longevity infusion protocols, plus observation after procedures that require monitoring. Each patient stays in a private room under the care of medical staff." } },
      { q: { uk: "Скільки часу пацієнт проводить у денному стаціонарі?", ru: "Сколько времени пациент проводит в дневном стационаре?", en: "How long does a stay in the day hospital last?" },
        a: { uk: "Залежно від протоколу — від 40 хвилин до кількох годин. Стандартна інфузія триває близько години, після неї передбачено коротке спостереження. Госпіталізація на ніч не проводиться: стаціонар денний.", ru: "В зависимости от протокола — от 40 минут до нескольких часов. Стандартная инфузия длится около часа, после неё предусмотрено короткое наблюдение. Госпитализация на ночь не проводится: стационар дневной.", en: "From 40 minutes to a few hours, depending on the protocol. A standard infusion takes about an hour, followed by a short period of observation. There are no overnight stays — this is a day facility." } },
    ],
  },
  {
    type: "faq_page",
    slug: "faq",
    category: "booking",
    items: [
      { q: { uk: "Чи можна записатися на конкретного лікаря?", ru: "Можно ли записаться к конкретному врачу?", en: "Can I book with a specific physician?" },
        a: { uk: "Так. Повідомте адміністратора ім'я лікаря під час запису — ми підберемо найближчий вільний час у його розкладі. Якщо ви не визначилися, адміністратор підкаже, хто веде ваш профіль запиту.", ru: "Да. Сообщите администратору имя врача при записи — мы подберём ближайшее свободное время в его расписании. Если вы не определились, администратор подскажет, кто ведёт ваш профиль запроса.", en: "Yes. Give the administrator the physician's name when booking and we will find the earliest slot in their schedule. If you are unsure, the administrator will suggest who handles your type of request." } },
      { q: { uk: "Як перенести або скасувати запис?", ru: "Как перенести или отменить запись?", en: "How do I reschedule or cancel an appointment?" },
        a: { uk: "Зателефонуйте нам або напишіть у месенджер — ми перенесемо візит на зручний час. Просимо попереджати заздалегідь: так ми зможемо запропонувати цей час іншому пацієнту, який чекає на прийом.", ru: "Позвоните нам или напишите в мессенджер — мы перенесём визит на удобное время. Просим предупреждать заранее: так мы сможем предложить это время другому пациенту, который ждёт приёма.", en: "Call us or send a message and we will move your visit to a convenient time. Please let us know in advance so the slot can be offered to another patient who is waiting." } },
      { q: { uk: "Чи можна записатися на кілька процедур в один день?", ru: "Можно ли записаться на несколько процедур в один день?", en: "Can I book several treatments on the same day?" },
        a: { uk: "Часто так — це зручно, якщо ви приїжджаєте здалеку. Але не всі методики сумісні в один візит: деякі потребують інтервалу. Повідомте адміністратора про всі бажані процедури, і ми узгодимо з лікарем оптимальну послідовність.", ru: "Часто да — это удобно, если вы приезжаете издалека. Но не все методики совместимы в один визит: некоторые требуют интервала. Сообщите администратору обо всех желаемых процедурах, и мы согласуем с врачом оптимальную последовательность.", en: "Often yes, which helps if you are travelling from afar. Not all methods can be combined in one visit, though — some need spacing. Tell the administrator everything you would like and we will agree the best sequence with the physician." } },
      { q: { uk: "Наскільки заздалегідь варто планувати візит?", ru: "Насколько заранее стоит планировать визит?", en: "How far in advance should I book?" },
        a: { uk: "Для консультації зазвичай достатньо кількох днів. Для процедур у конкретного лікаря або тривалих протоколів краще планувати за 1–2 тижні. Якщо потрібно терміново, зателефонуйте — ми пошукаємо вільне вікно.", ru: "Для консультации обычно достаточно нескольких дней. Для процедур у конкретного врача или длительных протоколов лучше планировать за 1–2 недели. Если нужно срочно, позвоните — мы поищем свободное окно.", en: "A few days is usually enough for a consultation. For treatments with a specific physician or longer protocols, plan one to two weeks ahead. If you need something urgently, call us and we will look for a gap." } },
    ],
  },
  {
    type: "faq_page",
    slug: "faq",
    category: "preparation",
    items: [
      { q: { uk: "Чи можна приходити на процедуру після безсонної ночі або застуди?", ru: "Можно ли приходить на процедуру после бессонной ночи или простуды?", en: "Can I come for a treatment after a sleepless night or a cold?" },
        a: { uk: "При гострих станах — підвищеній температурі, застуді, загостренні герпесу — процедуру краще перенести: організм зайнятий іншим, а ризик небажаних реакцій зростає. Втома сама по собі не є протипоказанням, але повідомте про неї лікаря.", ru: "При острых состояниях — повышенной температуре, простуде, обострении герпеса — процедуру лучше перенести: организм занят другим, а риск нежелательных реакций возрастает. Усталость сама по себе не противопоказание, но сообщите о ней врачу.", en: "With acute illness — fever, a cold, a herpes flare — it is better to reschedule: the body is busy elsewhere and the risk of unwanted reactions rises. Tiredness alone is not a contraindication, but do mention it." } },
      { q: { uk: "Чи потрібно скасовувати ліки перед процедурами?", ru: "Нужно ли отменять лекарства перед процедурами?", en: "Do I need to stop my medication before a treatment?" },
        a: { uk: "Самостійно скасовувати призначені препарати не можна. Перед ін'єкційними процедурами лікар може порекомендувати тимчасово припинити прийом засобів, що розріджують кров, — але лише за погодженням із лікарем, який їх призначив.", ru: "Самостоятельно отменять назначенные препараты нельзя. Перед инъекционными процедурами врач может рекомендовать временно прекратить приём средств, разжижающих кровь, — но только по согласованию с врачом, который их назначил.", en: "Never stop prescribed medication on your own. Before injectable treatments the physician may advise pausing blood-thinning drugs — but only in agreement with the doctor who prescribed them." } },
      { q: { uk: "Чи можна робити процедури під час менструації?", ru: "Можно ли делать процедуры во время менструации?", en: "Can treatments be done during menstruation?" },
        a: { uk: "Більшість естетичних процедур можливі, але чутливість у ці дні вища, тому дискомфорт може посилитися. Гінекологічні огляди та процедури в інтимній зоні планують на інші дні циклу. Якщо сумніваєтеся, зателефонуйте — перенесемо запис.", ru: "Большинство эстетических процедур возможны, но чувствительность в эти дни выше, поэтому дискомфорт может усилиться. Гинекологические осмотры и процедуры в интимной зоне планируют на другие дни цикла. Если сомневаетесь, позвоните — перенесём запись.", en: "Most aesthetic treatments are possible, though sensitivity is higher and discomfort may increase. Gynaecological examinations and intimate treatments are scheduled for other days of the cycle. If in doubt, call and we will move the appointment." } },
      { q: { uk: "Чи можна планувати процедури перед відпусткою на морі?", ru: "Можно ли планировать процедуры перед отпуском на море?", en: "Can I plan treatments before a beach holiday?" },
        a: { uk: "Це залежить від методики. Лазерні процедури та фотоомолодження потребують кількох тижнів без активного сонця — їх планують після поїздки. Догляд, зволоження та більшість ін'єкційних методик сумісні з відпусткою за умови SPF-захисту.", ru: "Это зависит от методики. Лазерные процедуры и фотоомоложение требуют нескольких недель без активного солнца — их планируют после поездки. Уход, увлажнение и большинство инъекционных методик совместимы с отпуском при условии SPF-защиты.", en: "It depends on the method. Laser treatments and photorejuvenation need several weeks away from strong sun, so they are planned after the trip. Skincare, hydration and most injectables are compatible with a holiday if SPF is used." } },
    ],
  },
];

seed(batches);
