import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "category",
    slug: "laser-hair-removal",
    items: [
      { q: { uk: "Як підготуватися до лазерної епіляції?", ru: "Как подготовиться к лазерной эпиляции?", en: "How should I prepare for laser hair removal?" },
        a: { uk: "За 2 тижні відмовтеся від сонця, солярію та автозасмаги, за 3–4 тижні — від воску, шугарингу й пінцета: лазеру потрібен корінь волосини. Напередодні зголіть зону станком. У день сеансу не наносьте креми, олії та дезодоранти.", ru: "За 2 недели откажитесь от солнца, солярия и автозагара, за 3–4 недели — от воска, шугаринга и пинцета: лазеру нужен корень волоса. Накануне побрейте зону станком. В день сеанса не наносите кремы, масла и дезодоранты.", en: "Avoid sun, solariums and self-tanner for two weeks, and waxing, sugaring and tweezing for three to four — the laser needs the root. Shave the area the day before. On the day, use no creams, oils or deodorants." } },
      { q: { uk: "Чи безпечна лазерна епіляція?", ru: "Безопасна ли лазерная эпиляция?", en: "Is laser hair removal safe?" },
        a: { uk: "Так, за умови коректно підібраних параметрів і дотримання протоколу. Splendor X має вбудоване охолодження, яке захищає епідерміс, а лікар підбирає режим під ваш фототип. Ризики виникають при роботі на засмаглій шкірі або порушенні рекомендацій.", ru: "Да, при условии корректно подобранных параметров и соблюдения протокола. Splendor X имеет встроенное охлаждение, которое защищает эпидермис, а врач подбирает режим под ваш фототип. Риски возникают при работе на загорелой коже или нарушении рекомендаций.", en: "Yes, provided the settings are correct and the protocol is followed. Splendor X has built-in cooling that protects the epidermis, and the physician selects the mode for your phototype. Risks arise when treating tanned skin or ignoring aftercare." } },
      { q: { uk: "Які обмеження після сеансу лазерної епіляції?", ru: "Какие ограничения после сеанса лазерной эпиляции?", en: "What restrictions apply after a session?" },
        a: { uk: "Добу уникайте сауни, басейну, гарячої ванни та інтенсивних тренувань, два тижні — прямого сонця й солярію. Не використовуйте скраби 3–4 дні. Між сеансами волосся можна лише голити — виривати не можна.", ru: "Сутки избегайте сауны, бассейна, горячей ванны и интенсивных тренировок, две недели — прямого солнца и солярия. Не используйте скрабы 3–4 дня. Между сеансами волосы можно только брить — выдёргивать нельзя.", en: "Avoid saunas, pools, hot baths and intensive exercise for 24 hours, and direct sun and solariums for two weeks. Skip scrubs for three to four days. Between sessions you may shave only — never pluck." } },
      { q: { uk: "Чи є протипоказання до лазерної епіляції?", ru: "Есть ли противопоказания к лазерной эпиляции?", en: "Are there contraindications to laser hair removal?" },
        a: { uk: "Так: вагітність і лактація, свіжа засмага, активні запалення чи інфекції шкіри в зоні, герпес у стадії загострення, прийом фотосенсибілізуючих препаратів та ізотретиноїну, онкологічні захворювання. Родимки в зоні обробки лікар обходить.", ru: "Да: беременность и лактация, свежий загар, активные воспаления или инфекции кожи в зоне, герпес в стадии обострения, приём фотосенсибилизирующих препаратов и изотретиноина, онкологические заболевания. Родинки в зоне обработки врач обходит.", en: "Yes: pregnancy and breastfeeding, fresh tanning, active skin inflammation or infection in the area, a herpes flare, photosensitising medication and isotretinoin, and oncological disease. Moles in the area are avoided." } },
      { q: { uk: "Чому між сеансами потрібна пауза 4–6 тижнів?", ru: "Почему между сеансами нужна пауза 4–6 недель?", en: "Why is a 4–6 week gap needed between sessions?" },
        a: { uk: "Лазер руйнує лише ті фолікули, що перебувають у фазі активного росту, — це частина всього об'єму волосся. Пауза потрібна, щоб наступна група волосин увійшла в цю фазу. Скорочувати інтервал немає сенсу: сеанс просто не дасть результату.", ru: "Лазер разрушает только те фолликулы, что находятся в фазе активного роста, — это часть всего объёма волос. Пауза нужна, чтобы следующая группа волос вошла в эту фазу. Сокращать интервал нет смысла: сеанс просто не даст результата.", en: "The laser only destroys follicles in the active growth phase, which is a fraction of the total. The gap lets the next group of hairs enter that phase. Shortening it is pointless — the session simply will not work." } },
    ],
  },
  {
    type: "category",
    slug: "longevity",
    items: [
      { q: { uk: "З чого починається longevity-програма?", ru: "С чего начинается longevity-программа?", en: "How does a longevity programme begin?" },
        a: { uk: "З діагностики: розгорнута лабораторна панель, гормональний статус, маркери запалення, аналіз складу тіла на InBody, за потреби УЗД. Далі лікар пояснює показники у зв'язку між собою й складає персональний протокол.", ru: "С диагностики: развёрнутая лабораторная панель, гормональный статус, маркеры воспаления, анализ состава тела на InBody, при необходимости УЗИ. Далее врач объясняет показатели во взаимосвязи и составляет персональный протокол.", en: "With diagnostics: an extended laboratory panel, hormonal status, inflammatory markers, an InBody composition scan and ultrasound if needed. The physician then interprets the markers together and builds a personal protocol." } },
      { q: { uk: "Чим longevity-медицина відрізняється від звичайного чек-апу?", ru: "Чем longevity-медицина отличается от обычного чек-апа?", en: "How does longevity medicine differ from a standard check-up?" },
        a: { uk: "Класичний чек-ап шукає захворювання, longevity-підхід оцінює функціональний стан організму до появи хвороби: рівень запалення, метаболічну гнучкість, гормональний баланс, склад тіла. Мета — не лише виявити проблему, а й змінити траєкторію.", ru: "Классический чек-ап ищет заболевания, longevity-подход оценивает функциональное состояние организма до появления болезни: уровень воспаления, метаболическую гибкость, гормональный баланс, состав тела. Цель — не только выявить проблему, но и изменить траекторию.", en: "A classic check-up looks for disease; the longevity approach assesses how the body is functioning before disease appears: inflammation, metabolic flexibility, hormonal balance and body composition. The aim is not only to find a problem but to change the trajectory." } },
      { q: { uk: "Що входить до longevity-напряму в GENEVITY?", ru: "Что входит в longevity-направление в GENEVITY?", en: "What does the longevity service at GENEVITY include?" },
        a: { uk: "Check-Up 40+, робота з гормональним балансом, персональні нутрицевтики, IV-терапія, аналіз складу тіла на InBody та регенеративні методики. Усі напрями поєднуються в один протокол, а не існують окремо.", ru: "Check-Up 40+, работа с гормональным балансом, персональные нутрицевтики, IV-терапия, анализ состава тела на InBody и регенеративные методики. Все направления объединяются в один протокол, а не существуют по отдельности.", en: "Check-Up 40+, hormonal balance work, personalised nutraceuticals, IV therapy, InBody composition analysis and regenerative methods. These are combined into a single protocol rather than run separately." } },
      { q: { uk: "Коли будуть помітні результати програми?", ru: "Когда будут заметны результаты программы?", en: "When will results become noticeable?" },
        a: { uk: "Самопочуття, сон і рівень енергії зазвичай змінюються протягом 4–8 тижнів. Лабораторні показники — повільніше: контрольні аналізи призначають через 3 місяці, а повну динаміку оцінюють через півроку.", ru: "Самочувствие, сон и уровень энергии обычно меняются в течение 4–8 недель. Лабораторные показатели — медленнее: контрольные анализы назначают через 3 месяца, а полную динамику оценивают через полгода.", en: "Wellbeing, sleep and energy usually shift within four to eight weeks. Laboratory markers move more slowly: control tests are done at three months and the full picture is reviewed at six." } },
      { q: { uk: "Чи потрібно приймати препарати в межах longevity-протоколу?", ru: "Нужно ли принимать препараты в рамках longevity-протокола?", en: "Does the longevity protocol require medication?" },
        a: { uk: "Не обов'язково. У багатьох випадках достатньо корекції харчування, сну, фізичної активності та закриття виявлених дефіцитів. Медикаментозну чи гормональну терапію призначають лише за чіткими показаннями й під лабораторним контролем.", ru: "Не обязательно. Во многих случаях достаточно коррекции питания, сна, физической активности и закрытия выявленных дефицитов. Медикаментозную или гормональную терапию назначают только по чётким показаниям и под лабораторным контролем.", en: "Not necessarily. In many cases correcting nutrition, sleep and activity and addressing identified deficiencies is enough. Drug or hormone therapy is prescribed only on clear indications and with laboratory monitoring." } },
      { q: { uk: "Чи підходить longevity-підхід людям до 35 років?", ru: "Подходит ли longevity-подход людям до 35 лет?", en: "Is the longevity approach relevant before 35?" },
        a: { uk: "Так, і саме в цьому віці він дає найбільше. Раннє виявлення дефіцитів, інсулінорезистентності чи прихованого запалення дозволяє скоригувати стан простими засобами — поки зміни ще повністю зворотні.", ru: "Да, и именно в этом возрасте он даёт больше всего. Раннее выявление дефицитов, инсулинорезистентности или скрытого воспаления позволяет скорректировать состояние простыми средствами — пока изменения ещё полностью обратимы.", en: "Yes — and this is when it delivers most. Detecting deficiencies, insulin resistance or low-grade inflammation early allows simple corrections while the changes are still fully reversible." } },
    ],
  },
  {
    type: "category",
    slug: "plastic-surgery",
    items: [
      { q: { uk: "Які обстеження потрібні перед пластичною операцією?", ru: "Какие обследования нужны перед пластической операцией?", en: "Which investigations are needed before plastic surgery?" },
        a: { uk: "Стандартний передопераційний набір: загальний і біохімічний аналізи крові, коагулограма, група крові та резус, аналізи на інфекції, ЕКГ і висновок терапевта. Більшість досліджень можна пройти у власній лабораторії GENEVITY.", ru: "Стандартный предоперационный набор: общий и биохимический анализы крови, коагулограмма, группа крови и резус, анализы на инфекции, ЭКГ и заключение терапевта. Большинство исследований можно пройти в собственной лаборатории GENEVITY.", en: "The standard pre-operative set: full blood count and biochemistry, coagulation profile, blood group and Rh, infection screening, ECG and physician's clearance. Most can be done in GENEVITY's own laboratory." } },
      { q: { uk: "Скільки часу займає відновлення після операції?", ru: "Сколько времени занимает восстановление после операции?", en: "How long is recovery after surgery?" },
        a: { uk: "Після невеликих втручань до звичного ритму повертаються за 7–14 днів, після великих — за 4–6 тижнів. Остаточний результат формується протягом 3–6 місяців, коли спадає набряк і дозріває рубець. Точні терміни хірург називає до операції.", ru: "После небольших вмешательств к привычному ритму возвращаются за 7–14 дней, после крупных — за 4–6 недель. Окончательный результат формируется в течение 3–6 месяцев, когда спадает отёк и созревает рубец. Точные сроки хирург называет до операции.", en: "After minor procedures most people resume normal life in 7–14 days; after major surgery, four to six weeks. The final result settles over three to six months as swelling resolves and the scar matures. The surgeon gives exact timings beforehand." } },
      { q: { uk: "Як підготуватися до операції?", ru: "Как подготовиться к операции?", en: "How do I prepare for surgery?" },
        a: { uk: "За 2 тижні відмовтеся від куріння та, за погодженням із лікарем, від препаратів, що розріджують кров. Пройдіть призначені обстеження, стабілізуйте вагу й режим сну. Хірург надасть повний перелік рекомендацій із точними термінами.", ru: "За 2 недели откажитесь от курения и, по согласованию с врачом, от препаратов, разжижающих кровь. Пройдите назначенные обследования, стабилизируйте вес и режим сна. Хирург предоставит полный перечень рекомендаций с точными сроками.", en: "Stop smoking two weeks beforehand and, with your physician's agreement, pause blood-thinning medication. Complete the required tests and stabilise your weight and sleep. The surgeon provides a full list of instructions with exact timings." } },
      { q: { uk: "Що робити з рубцями після операції?", ru: "Что делать с рубцами после операции?", en: "What can be done about post-surgical scars?" },
        a: { uk: "Після повного загоєння — силіконові гелі або пластирі, ретельний фотозахист і терпіння: рубець дозріває до року. Якщо через 6–12 місяців він залишається помітним, лікар за погодженням із хірургом може запропонувати лазерне шліфування.", ru: "После полного заживления — силиконовые гели или пластыри, тщательная фотозащита и терпение: рубец созревает до года. Если через 6–12 месяцев он остаётся заметным, врач по согласованию с хирургом может предложить лазерную шлифовку.", en: "Once fully healed: silicone gels or sheets, careful sun protection and patience — a scar matures for up to a year. If it remains visible at 6–12 months, laser resurfacing can be considered in agreement with the surgeon." } },
    ],
  },
  {
    type: "category",
    slug: "podology",
    items: [
      { q: { uk: "Чим подолог відрізняється від майстра педикюру?", ru: "Чем подолог отличается от мастера педикюра?", en: "How does a podologist differ from a pedicurist?" },
        a: { uk: "Подолог працює з медичними станами стоп і нігтів: вростанням, грибковими ураженнями, гіперкератозом, деформаціями. Він може встановити коригувальну систему, призначити лікування та вести пацієнтів із діабетом. Майстер педикюру виконує естетичний догляд.", ru: "Подолог работает с медицинскими состояниями стоп и ногтей: врастанием, грибковыми поражениями, гиперкератозом, деформациями. Он может установить корректирующую систему, назначить лечение и вести пациентов с диабетом. Мастер педикюра выполняет эстетический уход.", en: "A podologist treats medical conditions of the feet and nails: ingrown nails, fungal infection, hyperkeratosis and deformities, and can fit corrective systems, prescribe treatment and manage patients with diabetes. A pedicurist provides cosmetic care." } },
      { q: { uk: "Чи можна вилікувати вростання нігтя без операції?", ru: "Можно ли вылечить врастание ногтя без операции?", en: "Can an ingrown nail be treated without surgery?" },
        a: { uk: "У більшості випадків так. Подолог знімає запалення, звільняє нігтьовий валик і встановлює коригувальну систему — скобу або пластину, яка поступово змінює форму нігтя. Хірургічне втручання розглядають лише при повторних тяжких рецидивах.", ru: "В большинстве случаев да. Подолог снимает воспаление, освобождает ногтевой валик и устанавливает корректирующую систему — скобу или пластину, которая постепенно меняет форму ногтя. Хирургическое вмешательство рассматривают только при повторных тяжёлых рецидивах.", en: "In most cases, yes. The podologist relieves the inflammation, frees the nail fold and fits a corrective device — a brace or plate that gradually reshapes the nail. Surgery is considered only for severe, recurring cases." } },
    ],
  },
  {
    type: "category",
    slug: "skincare",
    items: [
      { q: { uk: "Як підготуватися до доглядової процедури?", ru: "Как подготовиться к уходовой процедуре?", en: "How should I prepare for a facial care treatment?" },
        a: { uk: "Спеціальної підготовки не потрібно — достатньо прийти без макіяжу або зняти його на місці. За 3–5 днів до сеансу не використовуйте агресивні кислоти й скраби. Якщо ви приймаєте ретиноїди, повідомте лікаря — це впливає на вибір протоколу.", ru: "Специальной подготовки не нужно — достаточно прийти без макияжа или снять его на месте. За 3–5 дней до сеанса не используйте агрессивные кислоты и скрабы. Если вы принимаете ретиноиды, сообщите врачу — это влияет на выбор протокола.", en: "No special preparation is needed — simply come without make-up or remove it on arrival. Avoid strong acids and scrubs for three to five days beforehand. Tell the physician if you use retinoids, as it affects the protocol." } },
      { q: { uk: "Чи можна робити доглядові процедури перед подією?", ru: "Можно ли делать уходовые процедуры перед событием?", en: "Can care treatments be done before an event?" },
        a: { uk: "Так, більшість із них не залишають слідів — шкіра одразу виглядає свіжішою. Оптимально запланувати сеанс за 1–3 дні до події. Пілінги та чистки краще робити щонайменше за тиждень: шкірі потрібен час на відновлення.", ru: "Да, большинство из них не оставляют следов — кожа сразу выглядит свежее. Оптимально запланировать сеанс за 1–3 дня до события. Пилинги и чистки лучше делать минимум за неделю: коже нужно время на восстановление.", en: "Yes — most leave no visible traces and the skin looks fresher immediately. Ideally book one to three days before. Peels and extractions are better done at least a week ahead, as the skin needs time to settle." } },
    ],
  },
];

seed(batches);
