import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "service",
    slug: "botulinum-therapy",
    items: [
      { q: { uk: "Скільки тримається ефект від ботулінотерапії?", ru: "Сколько держится эффект от ботулинотерапии?", en: "How long does the effect of botulinum therapy last?" },
        a: { uk: "У середньому 4–6 місяців. Тривалість залежить від зони, дози, активності міміки та швидкості метаболізму. При регулярних повторах м'язи поступово «розучуються» працювати надмірно, тому інтервали між процедурами часто збільшуються.", ru: "В среднем 4–6 месяцев. Длительность зависит от зоны, дозы, активности мимики и скорости метаболизма. При регулярных повторах мышцы постепенно «отвыкают» работать чрезмерно, поэтому интервалы между процедурами часто увеличиваются.", en: "On average 4–6 months. Duration depends on the area, the dose, how active your facial muscles are and your metabolism. With regular repeat treatments the muscles gradually lose the habit of overworking, so intervals often lengthen." } },
      { q: { uk: "Чи залишиться обличчя живим і природним?", ru: "Останется ли лицо живым и естественным?", en: "Will my face still look natural and expressive?" },
        a: { uk: "Так — за умови виваженого дозування. Ми працюємо мінімально достатніми дозами: мета не «заморозити» обличчя, а прибрати надмірне напруження м'язів. Міміка залишається, зникає лише різкість заломів шкіри.", ru: "Да — при взвешенной дозировке. Мы работаем минимально достаточными дозами: цель не «заморозить» лицо, а убрать избыточное напряжение мышц. Мимика сохраняется, исчезает лишь резкость заломов кожи.", en: "Yes, with careful dosing. We work with the minimum effective dose: the aim is not to freeze the face but to release excessive muscle tension. Expression remains — only the sharpness of the creases goes." } },
      { q: { uk: "Які зони найчастіше коригують ботулотоксином?", ru: "Какие зоны чаще всего корректируют ботулотоксином?", en: "Which areas are most often treated with botulinum toxin?" },
        a: { uk: "Класичні зони — міжбрів'я, чоло та зовнішні куточки очей. Також коригують «кисетні» зморшки, опущені куточки губ, напружене підборіддя, платизму на шиї. Окремий напрям — ботулінотерапія при гіпергідрозі пахв.", ru: "Классические зоны — межбровье, лоб и внешние уголки глаз. Также корректируют «кисетные» морщины, опущенные уголки губ, напряжённый подбородок, платизму на шее. Отдельное направление — ботулинотерапия при гипергидрозе подмышек.", en: "The classic areas are the glabella, forehead and crow's feet. We also treat perioral lines, downturned mouth corners, a tense chin and the platysmal bands of the neck. A separate indication is botulinum therapy for underarm hyperhidrosis." } },
      { q: { uk: "Що робити, якщо результат здається несиметричним?", ru: "Что делать, если результат кажется несимметричным?", en: "What if the result looks asymmetric?" },
        a: { uk: "Дочекайтеся 14-го дня — саме тоді ефект розкривається повністю, і те, що здавалося асиметрією на 5-й день, часто вирівнюється. На контрольному огляді лікар оцінює результат і за потреби робить безкоштовну корекцію мікродозою.", ru: "Дождитесь 14-го дня — именно тогда эффект раскрывается полностью, и то, что казалось асимметрией на 5-й день, часто выравнивается. На контрольном осмотре врач оценивает результат и при необходимости делает бесплатную коррекцию микродозой.", en: "Wait until day 14, when the effect is fully developed — what looked asymmetric on day five often evens out. At the follow-up the physician assesses the result and, if needed, makes a complimentary micro-dose adjustment." } },
    ],
  },
  {
    type: "service",
    slug: "check-up-40",
    items: [
      { q: { uk: "Що входить до програми Check-Up 40+?", ru: "Что входит в программу Check-Up 40+?", en: "What does the Check-Up 40+ programme include?" },
        a: { uk: "Базова панель охоплює розгорнутий аналіз крові, ліпідний профіль і показники вуглеводного обміну, гормональний статус, маркери запалення, вітаміни й мікроелементи, УЗД-скринінг та аналіз складу тіла на InBody. Обсяг лікар може розширити за вашим анамнезом.", ru: "Базовая панель охватывает развёрнутый анализ крови, липидный профиль и показатели углеводного обмена, гормональный статус, маркеры воспаления, витамины и микроэлементы, УЗИ-скрининг и анализ состава тела на InBody. Объём врач может расширить с учётом вашего анамнеза.", en: "The core panel covers a full blood count, lipid profile and carbohydrate metabolism, hormonal status, inflammatory markers, vitamins and trace elements, an ultrasound screen and an InBody composition scan. The physician can extend it based on your history." } },
      { q: { uk: "Як підготуватися до Check-Up 40+?", ru: "Как подготовиться к Check-Up 40+?", en: "How should I prepare for Check-Up 40+?" },
        a: { uk: "Кров здають натще — останній прийом їжі за 8–12 годин до візиту, вода дозволена. За добу варто уникати алкоголю та інтенсивних тренувань. Якщо ви приймаєте препарати або добавки, повідомте адміністратора заздалегідь — окремі з них тимчасово скасовують.", ru: "Кровь сдают натощак — последний приём пищи за 8–12 часов до визита, вода разрешена. За сутки стоит избегать алкоголя и интенсивных тренировок. Если вы принимаете препараты или добавки, сообщите администратору заранее — отдельные из них временно отменяют.", en: "Blood is taken fasting — your last meal 8–12 hours before the visit, water is allowed. Avoid alcohol and intensive exercise for 24 hours beforehand. Tell the administrator in advance about any medication or supplements: some need to be paused." } },
      { q: { uk: "Кому варто пройти Check-Up 40+?", ru: "Кому стоит пройти Check-Up 40+?", en: "Who should consider Check-Up 40+?" },
        a: { uk: "Програма створена для чоловіків і жінок після 40 років, коли метаболізм і гормональний фон змінюються поступово й непомітно. Вона також доречна раніше — за спадкових ризиків, хронічної втоми, змін ваги чи сну. Це саме той випадок, коли цифри з'являються раніше за симптоми.", ru: "Программа создана для мужчин и женщин после 40 лет, когда метаболизм и гормональный фон меняются постепенно и незаметно. Она уместна и раньше — при наследственных рисках, хронической усталости, изменениях веса или сна. Это тот случай, когда цифры появляются раньше симптомов.", en: "The programme is designed for men and women over 40, when metabolism and hormones shift gradually and quietly. It is also relevant earlier — with a family history, chronic fatigue, or changes in weight or sleep. Numbers usually appear before symptoms do." } },
      { q: { uk: "Що я отримаю за результатами обстеження?", ru: "Что я получу по результатам обследования?", en: "What do I receive at the end of the check-up?" },
        a: { uk: "Ви отримуєте всі протоколи досліджень і консультацію лікаря, на якій показники розбирають у зв'язку між собою, а не окремими рядками. На виході — письмовий план дій: харчування, добавки за дефіцитами, потрібні процедури й дата наступного контролю.", ru: "Вы получаете все протоколы исследований и консультацию врача, на которой показатели разбирают во взаимосвязи, а не отдельными строками. На выходе — письменный план действий: питание, добавки по дефицитам, необходимые процедуры и дата следующего контроля.", en: "You receive all test reports plus a consultation where the results are interpreted together rather than line by line. The outcome is a written action plan: nutrition, supplements for identified deficiencies, any procedures needed and a date for the next review." } },
    ],
  },
  {
    type: "service",
    slug: "contour-plasty",
    items: [
      { q: { uk: "Скільки тримається результат контурної пластики?", ru: "Сколько держится результат контурной пластики?", en: "How long do the results of dermal fillers last?" },
        a: { uk: "У середньому 6–18 місяців залежно від зони та щільності препарату. Найшвидше розсмоктуються філери в губах через активну міміку, найдовше тримаються щільні гелі у вилицях і підборідді. Метаболізм і спосіб життя також впливають на тривалість.", ru: "В среднем 6–18 месяцев в зависимости от зоны и плотности препарата. Быстрее всего рассасываются филлеры в губах из-за активной мимики, дольше держатся плотные гели в скулах и подбородке. Метаболизм и образ жизни также влияют на длительность.", en: "On average 6–18 months, depending on the area and the density of the product. Lip fillers break down fastest because of constant movement; firmer gels in the cheekbones and chin last longest. Metabolism and lifestyle also play a role." } },
      { q: { uk: "Чи можна прибрати філер, якщо результат не сподобався?", ru: "Можно ли убрать филлер, если результат не понравился?", en: "Can filler be dissolved if I do not like the result?" },
        a: { uk: "Так. Філери на основі гіалуронової кислоти розчиняються ферментом гіалуронідазою — це керована процедура, яку виконує лікар. Саме зворотність робить гіалуронові препарати одними з найбезпечніших в естетичній медицині.", ru: "Да. Филлеры на основе гиалуроновой кислоты растворяются ферментом гиалуронидазой — это управляемая процедура, которую выполняет врач. Именно обратимость делает гиалуроновые препараты одними из самых безопасных в эстетической медицине.", en: "Yes. Hyaluronic acid fillers can be dissolved with hyaluronidase — a controlled procedure performed by the physician. This reversibility is what makes HA products among the safest options in aesthetic medicine." } },
      { q: { uk: "Скільки тримаються набряки та синці після філерів?", ru: "Сколько держатся отёки и синяки после филлеров?", en: "How long do swelling and bruising last after fillers?" },
        a: { uk: "Набряк найпомітніший перші 24–72 години, особливо в губах, і повністю сходить за 5–7 днів. Синці трапляються не в усіх і зазвичай минають за 7–10 днів. Холод у перші години та відмова від алкоголю й спорту помітно скорочують цей період.", ru: "Отёк наиболее заметен первые 24–72 часа, особенно в губах, и полностью сходит за 5–7 дней. Синяки бывают не у всех и обычно проходят за 7–10 дней. Холод в первые часы и отказ от алкоголя и спорта заметно сокращают этот период.", en: "Swelling peaks in the first 24–72 hours, especially in the lips, and settles within 5–7 days. Bruising does not affect everyone and usually fades in 7–10 days. Cold compresses in the first hours and avoiding alcohol and exercise shorten this noticeably." } },
      { q: { uk: "Чи розтягує філер шкіру з часом?", ru: "Растягивает ли филлер кожу со временем?", en: "Do fillers stretch the skin over time?" },
        a: { uk: "За коректних об'ємів — ні. Проблеми виникають, коли препарат вводять надлишково або занадто часто, не даючи тканинам відновитися. Ми працюємо поетапно: краще додати трохи на контрольному огляді, ніж перевантажити зону за один візит.", ru: "При корректных объёмах — нет. Проблемы возникают, когда препарат вводят избыточно или слишком часто, не давая тканям восстановиться. Мы работаем поэтапно: лучше добавить немного на контрольном осмотре, чем перегрузить зону за один визит.", en: "With correct volumes, no. Problems arise when product is over-injected or repeated too often without letting tissue recover. We work in stages: it is better to add a little at the follow-up than to overload an area in one visit." } },
    ],
  },
  {
    type: "service",
    slug: "cosmetologist",
    items: [
      { q: { uk: "Як проходить консультація косметолога в GENEVITY?", ru: "Как проходит консультация косметолога в GENEVITY?", en: "What happens during a cosmetologist consultation at GENEVITY?" },
        a: { uk: "Лікар збирає анамнез, оцінює тип і стан шкіри, аналізує ваш домашній догляд і попередні процедури. Далі обговорюємо ваш запит і реалістичні очікування. Результат візиту — покроковий план: що робимо зараз, що згодом, чого краще не робити взагалі.", ru: "Врач собирает анамнез, оценивает тип и состояние кожи, анализирует ваш домашний уход и предыдущие процедуры. Затем обсуждаем ваш запрос и реалистичные ожидания. Результат визита — пошаговый план: что делаем сейчас, что позже, чего лучше не делать вовсе.", en: "The physician takes your history, assesses skin type and condition, and reviews your home routine and previous treatments. We then discuss your goals and what is realistically achievable. You leave with a step-by-step plan: what to do now, what later, and what to avoid." } },
      { q: { uk: "Чи можна зробити процедуру в день консультації?", ru: "Можно ли сделать процедуру в день консультации?", en: "Can a treatment be done on the day of the consultation?" },
        a: { uk: "Часто так — якщо немає протипоказань і потрібен час у розкладі лікаря. Для ін'єкційних і лазерних методик краще попередити адміністратора під час запису, щоб зарезервувати достатньо часу. Окремі протоколи потребують попередньої підготовки шкіри.", ru: "Часто да — если нет противопоказаний и есть время в расписании врача. Для инъекционных и лазерных методик лучше предупредить администратора при записи, чтобы зарезервировать достаточно времени. Отдельные протоколы требуют предварительной подготовки кожи.", en: "Often yes, if there are no contraindications and the physician has time available. For injectable and laser treatments, tell the administrator when booking so enough time is reserved. Some protocols require the skin to be prepared in advance." } },
      { q: { uk: "Чим лікар-косметолог відрізняється від естетиста?", ru: "Чем врач-косметолог отличается от эстетиста?", en: "How does a medical cosmetologist differ from an aesthetician?" },
        a: { uk: "Лікар-косметолог має вищу медичну освіту та право працювати з ін'єкціями, лазерами й медикаментозною терапією, ставити діагноз і призначати обстеження. Естетист виконує доглядові процедури. У GENEVITY усі медичні маніпуляції виконують саме лікарі.", ru: "Врач-косметолог имеет высшее медицинское образование и право работать с инъекциями, лазерами и медикаментозной терапией, ставить диагноз и назначать обследования. Эстетист выполняет уходовые процедуры. В GENEVITY все медицинские манипуляции выполняют именно врачи.", en: "A medical cosmetologist holds a medical degree and may perform injections, laser treatments and drug therapy, make diagnoses and order tests. An aesthetician performs care procedures. At GENEVITY all medical procedures are carried out by physicians." } },
      { q: { uk: "Що взяти із собою на консультацію?", ru: "Что взять с собой на консультацию?", en: "What should I bring to the consultation?" },
        a: { uk: "Візьміть перелік засобів домашнього догляду, інформацію про попередні процедури та препарати, які приймаєте, а також результати нещодавніх аналізів, якщо вони є. Приходьте без макіяжу або з мінімальним — так лікар точніше оцінить стан шкіри.", ru: "Возьмите перечень средств домашнего ухода, информацию о предыдущих процедурах и препаратах, которые принимаете, а также результаты недавних анализов, если они есть. Приходите без макияжа или с минимальным — так врач точнее оценит состояние кожи.", en: "Bring a list of your home skincare products, details of previous treatments and any medication you take, plus recent test results if you have them. Come without make-up, or with as little as possible, so the physician can assess your skin accurately." } },
      { q: { uk: "Чи консультує косметолог онлайн?", ru: "Консультирует ли косметолог онлайн?", en: "Does the cosmetologist offer online consultations?" },
        a: { uk: "Попередні питання можна обговорити з адміністратором у телефонному режимі або в Instagram @genevity.center. Але повноцінна діагностика шкіри потребує очного огляду: тактильна оцінка тургору, стану пор і судин по фото недоступна.", ru: "Предварительные вопросы можно обсудить с администратором по телефону или в Instagram @genevity.center. Но полноценная диагностика кожи требует очного осмотра: тактильная оценка тургора, состояния пор и сосудов по фото недоступна.", en: "Preliminary questions can be discussed with an administrator by phone or via Instagram @genevity.center. Full skin assessment, however, requires an in-person visit: turgor, pores and vessels cannot be evaluated from a photograph." } },
    ],
  },
  {
    type: "service",
    slug: "couperose-treatment",
    items: [
      { q: { uk: "Як підготуватися до лікування куперозу?", ru: "Как подготовиться к лечению купероза?", en: "How should I prepare for couperose treatment?" },
        a: { uk: "За 2 тижні до сеансу відмовтеся від засмаги й солярію, за 5–7 днів — від кислот і ретиноїдів. У день процедури приходьте без макіяжу. Якщо приймаєте фотосенсибілізуючі препарати, обов'язково повідомте лікаря.", ru: "За 2 недели до сеанса откажитесь от загара и солярия, за 5–7 дней — от кислот и ретиноидов. В день процедуры приходите без макияжа. Если принимаете фотосенсибилизирующие препараты, обязательно сообщите врачу.", en: "Avoid sun exposure and solariums for two weeks before the session, and acids and retinoids for 5–7 days. Come without make-up on the day. If you take photosensitising medication, tell the physician." } },
      { q: { uk: "Як виглядає шкіра одразу після процедури?", ru: "Как выглядит кожа сразу после процедуры?", en: "How does the skin look right after the treatment?" },
        a: { uk: "Одразу після сеансу помітні легке почервоніння й набряк по ходу судин — це очікувана реакція, яка минає за кілька годин або до доби. Судини можуть потемніти й стати помітнішими на 3–7 днів, а потім поступово зникнути.", ru: "Сразу после сеанса заметны лёгкое покраснение и отёк по ходу сосудов — это ожидаемая реакция, которая проходит за несколько часов или до суток. Сосуды могут потемнеть и стать заметнее на 3–7 дней, а затем постепенно исчезнуть.", en: "Immediately afterwards there is mild redness and swelling along the vessels — an expected reaction that settles within hours or up to a day. Vessels may darken and look more visible for 3–7 days before fading." } },
      { q: { uk: "Чи можна лікувати купероз при розацеа?", ru: "Можно ли лечить купероз при розацеа?", en: "Can couperose be treated if I have rosacea?" },
        a: { uk: "Так, судинний компонент розацеа добре відповідає на IPL-терапію. Але спершу потрібно вивести захворювання зі стадії загострення — на активному запаленні процедуру не проводять. Лікар складає протокол, що поєднує медикаментозну терапію та апаратні сеанси.", ru: "Да, сосудистый компонент розацеа хорошо отвечает на IPL-терапию. Но сначала нужно вывести заболевание из стадии обострения — при активном воспалении процедуру не проводят. Врач составляет протокол, сочетающий медикаментозную терапию и аппаратные сеансы.", en: "Yes — the vascular component of rosacea responds well to IPL. The condition must first be brought out of a flare, as the treatment is not performed on actively inflamed skin. The physician builds a protocol combining medication with device sessions." } },
      { q: { uk: "Чи можна прибрати судини на носі та крилах носа?", ru: "Можно ли убрать сосуды на носу и крыльях носа?", en: "Can vessels on the nose be removed?" },
        a: { uk: "Так, це одна з найчастіших зон обробки. Шкіра там тонша й чутливіша, тому лікар працює м'якшими параметрами й іноді потребує на один сеанс більше. Результат у цій зоні зазвичай дуже наочний.", ru: "Да, это одна из самых частых зон обработки. Кожа там тоньше и чувствительнее, поэтому врач работает более мягкими параметрами и иногда требуется на один сеанс больше. Результат в этой зоне обычно очень наглядный.", en: "Yes, it is one of the most commonly treated areas. The skin there is thinner and more sensitive, so the physician uses gentler settings and sometimes one extra session is needed. Results in this area are usually very visible." } },
    ],
  },
  {
    type: "service",
    slug: "emface",
    items: [
      { q: { uk: "Кому підходить процедура EMFACE?", ru: "Кому подходит процедура EMFACE?", en: "Who is EMFACE suitable for?" },
        a: { uk: "EMFACE обирають, коли хочеться підтягнути овал і повернути тонус без ін'єкцій та відновлення. Найкраще методика працює у віці 35–60 років при легкому та помірному птозі. Її також обирають ті, хто не готовий до голок або має алергію на компоненти філерів.", ru: "EMFACE выбирают, когда хочется подтянуть овал и вернуть тонус без инъекций и восстановления. Лучше всего методика работает в возрасте 35–60 лет при лёгком и умеренном птозе. Её также выбирают те, кто не готов к иглам или имеет аллергию на компоненты филлеров.", en: "EMFACE suits those who want to lift the contour and restore tone without injections or downtime. It works best between 35 and 60 with mild to moderate laxity, and is often chosen by patients who prefer to avoid needles or react to filler components." } },
      { q: { uk: "Чи є протипоказання до EMFACE?", ru: "Есть ли противопоказания к EMFACE?", en: "Are there contraindications to EMFACE?" },
        a: { uk: "Так. Процедуру не проводять за наявності металевих імплантатів у зоні обробки, кардіостимулятора, під час вагітності, при епілепсії, онкологічних захворюваннях в активній фазі та гарячкових станах. Повний перелік лікар перевіряє на консультації.", ru: "Да. Процедуру не проводят при наличии металлических имплантатов в зоне обработки, кардиостимулятора, во время беременности, при эпилепсии, онкологических заболеваниях в активной фазе и лихорадочных состояниях. Полный перечень врач проверяет на консультации.", en: "Yes. It is not performed with metal implants in the treated area, a pacemaker, during pregnancy, or with epilepsy, active oncological disease or fever. The physician reviews the full list at the consultation." } },
    ],
  },
  {
    type: "service",
    slug: "emsculpt-neo",
    items: [
      { q: { uk: "Чи є протипоказання до EMSCULPT NEO?", ru: "Есть ли противопоказания к EMSCULPT NEO?", en: "Are there contraindications to EMSCULPT NEO?" },
        a: { uk: "Процедуру не проводять при вагітності, наявності кардіостимулятора чи інших електронних імплантатів, металевих конструкцій у зоні обробки, епілепсії, онкології в активній фазі та порушеннях згортання крові. Наявність внутрішньоматкової спіралі обговорюється з лікарем окремо.", ru: "Процедуру не проводят при беременности, наличии кардиостимулятора или других электронных имплантатов, металлических конструкций в зоне обработки, эпилепсии, онкологии в активной фазе и нарушениях свёртывания крови. Наличие внутриматочной спирали обсуждается с врачом отдельно.", en: "It is not performed during pregnancy, or with a pacemaker or other electronic implants, metal hardware in the treated area, epilepsy, active oncological disease or clotting disorders. An intrauterine device is discussed with the physician separately." } },
      { q: { uk: "Чи повертається жир після курсу EMSCULPT NEO?", ru: "Возвращается ли жир после курса EMSCULPT NEO?", en: "Does the fat come back after a course of EMSCULPT NEO?" },
        a: { uk: "Зруйновані жирові клітини виводяться організмом і не відновлюються. Але клітини, що залишилися, здатні збільшуватися в об'ємі при переїданні та наборі ваги. Стабільна вага і базова фізична активність зберігають результат роками.", ru: "Разрушенные жировые клетки выводятся организмом и не восстанавливаются. Но оставшиеся клетки способны увеличиваться в объёме при переедании и наборе веса. Стабильный вес и базовая физическая активность сохраняют результат годами.", en: "The destroyed fat cells are cleared by the body and do not return. The remaining cells, however, can enlarge if you overeat and gain weight. A stable weight and basic physical activity keep the result for years." } },
    ],
  },
];

seed(batches);
