import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "service",
    slug: "endocrinologist",
    items: [
      { q: { uk: "Як довго триває прийом ендокринолога?", ru: "Сколько длится приём эндокринолога?", en: "How long does an endocrinologist appointment take?" },
        a: { uk: "Первинна консультація триває 40–60 хвилин: збір анамнезу, огляд, пальпація щитоподібної залози, аналіз наявних досліджень і складання плану обстеження. Повторний прийом із результатами аналізів — близько 30 хвилин.", ru: "Первичная консультация длится 40–60 минут: сбор анамнеза, осмотр, пальпация щитовидной железы, анализ имеющихся исследований и составление плана обследования. Повторный приём с результатами анализов — около 30 минут.", en: "A first consultation lasts 40–60 minutes: history taking, examination, palpation of the thyroid, review of existing tests and a plan for further investigation. A follow-up with results takes about 30 minutes." } },
      { q: { uk: "Чи можна здати аналізи та зробити УЗД в один день із консультацією?", ru: "Можно ли сдать анализы и сделать УЗИ в один день с консультацией?", en: "Can I have tests and an ultrasound on the same day as the consultation?" },
        a: { uk: "Так. У GENEVITY є власна лабораторія та кабінет УЗД, тож більшість досліджень можна пройти одразу після прийому. Кров на гормони здають натще, тому зручніше планувати візит на ранок — попередьте про це адміністратора під час запису.", ru: "Да. В GENEVITY есть собственная лаборатория и кабинет УЗИ, поэтому большинство исследований можно пройти сразу после приёма. Кровь на гормоны сдают натощак, поэтому визит удобнее планировать на утро — предупредите об этом администратора при записи.", en: "Yes. GENEVITY has its own laboratory and ultrasound room, so most investigations can be done straight after the appointment. Hormone tests require fasting, so a morning visit is easier — mention this when booking." } },
      { q: { uk: "Чи веде ендокринолог пацієнтів із цукровим діабетом?", ru: "Ведёт ли эндокринолог пациентов с сахарным диабетом?", en: "Does the endocrinologist manage patients with diabetes?" },
        a: { uk: "Так. Лікар оцінює глікемічний контроль, стан вуглеводного обміну та ризик ускладнень, коригує схему терапії й режим харчування. Ми також працюємо з переддіабетом та інсулінорезистентністю — на цьому етапі зміни ще повністю зворотні.", ru: "Да. Врач оценивает гликемический контроль, состояние углеводного обмена и риск осложнений, корректирует схему терапии и режим питания. Мы также работаем с предиабетом и инсулинорезистентностью — на этом этапе изменения ещё полностью обратимы.", en: "Yes. The physician assesses glycaemic control, carbohydrate metabolism and complication risk, and adjusts therapy and diet. We also manage prediabetes and insulin resistance, where the changes are still fully reversible." } },
      { q: { uk: "Як часто потрібні повторні візити до ендокринолога?", ru: "Как часто нужны повторные визиты к эндокринологу?", en: "How often are follow-up visits needed?" },
        a: { uk: "На етапі підбору терапії контроль зазвичай призначають через 4–8 тижнів. Коли схема стабільна, достатньо 1–2 візитів на рік із контрольними аналізами. Точний графік лікар визначає за вашим діагнозом і динамікою показників.", ru: "На этапе подбора терапии контроль обычно назначают через 4–8 недель. Когда схема стабильна, достаточно 1–2 визитов в год с контрольными анализами. Точный график врач определяет по вашему диагнозу и динамике показателей.", en: "While treatment is being adjusted, a review is usually scheduled after 4–8 weeks. Once the regimen is stable, one or two visits a year with control tests are enough. The physician sets the schedule based on your diagnosis and progress." } },
    ],
  },
  {
    type: "service",
    slug: "exion-body",
    items: [
      { q: { uk: "Чи болісна процедура EXION Body?", ru: "Болезненна ли процедура EXION Body?", en: "Is EXION Body painful?" },
        a: { uk: "Ні. Відчуття описують як приємне глибоке тепло й легке ковзання насадки — багато пацієнтів порівнюють сеанс із теплим масажем. AI-контроль утримує температуру в комфортному діапазоні, тож перегріву не відбувається.", ru: "Нет. Ощущения описывают как приятное глубокое тепло и лёгкое скольжение насадки — многие пациенты сравнивают сеанс с тёплым массажем. AI-контроль удерживает температуру в комфортном диапазоне, поэтому перегрева не происходит.", en: "No. Patients describe a pleasant deep warmth as the applicator glides over the skin — many compare it to a warm massage. AI control keeps the temperature within a comfortable range, so overheating does not occur." } },
      { q: { uk: "Чи допомагає EXION Body при целюліті?", ru: "Помогает ли EXION Body при целлюлите?", en: "Does EXION Body help with cellulite?" },
        a: { uk: "Так, це один з основних запитів. RF-нагрів покращує мікроциркуляцію, ущільнює дерму й вирівнює рельєф шкіри, через що прояви целюліту стають менш вираженими. Найкращий результат дає курс у поєднанні з питним режимом і фізичною активністю.", ru: "Да, это один из основных запросов. RF-нагрев улучшает микроциркуляцию, уплотняет дерму и выравнивает рельеф кожи, из-за чего проявления целлюлита становятся менее выраженными. Лучший результат даёт курс в сочетании с питьевым режимом и физической активностью.", en: "Yes, it is one of the main reasons patients come. RF heating improves microcirculation, densifies the dermis and evens out the skin surface, making cellulite less pronounced. Results are best with a full course plus good hydration and activity." } },
    ],
  },
  {
    type: "service",
    slug: "exion-face",
    items: [
      { q: { uk: "Чи є реабілітація після EXION Face?", ru: "Есть ли реабилитация после EXION Face?", en: "Is there any downtime after EXION Face?" },
        a: { uk: "Реабілітації немає. Одразу після сеансу можливе легке рожеве забарвлення шкіри, яке минає за 1–2 години. Того ж дня можна нанести макіяж і повернутися до звичних справ — процедуру часто роблять у робочу перерву.", ru: "Реабилитации нет. Сразу после сеанса возможно лёгкое розовое окрашивание кожи, которое проходит за 1–2 часа. В тот же день можно нанести макияж и вернуться к привычным делам — процедуру часто делают в рабочий перерыв.", en: "There is no downtime. A light pink flush may remain for an hour or two after the session. You can apply make-up and return to your day immediately — many patients book it during a work break." } },
      { q: { uk: "З якого віку доречний EXION Face?", ru: "С какого возраста уместен EXION Face?", en: "From what age is EXION Face appropriate?" },
        a: { uk: "Методику застосовують із 25–30 років для профілактики: вона підтримує зволоженість і щільність шкіри, коли власний синтез гіалуронової кислоти починає сповільнюватися. Після 40 років EXION Face зазвичай поєднують із ліфтинговими технологіями.", ru: "Методику применяют с 25–30 лет для профилактики: она поддерживает увлажнённость и плотность кожи, когда собственный синтез гиалуроновой кислоты начинает замедляться. После 40 лет EXION Face обычно сочетают с лифтинговыми технологиями.", en: "It is used from around 25–30 as a preventive measure, supporting hydration and skin density as natural hyaluronic acid synthesis begins to slow. After 40, EXION Face is usually combined with lifting technologies." } },
      { q: { uk: "Чим EXION Face відрізняється від біоревіталізації?", ru: "Чем EXION Face отличается от биоревитализации?", en: "How does EXION Face differ from biorevitalisation?" },
        a: { uk: "Біоревіталізація вводить гіалуронову кислоту ззовні голкою, EXION Face стимулює шкіру виробляти власну — без ін'єкцій і слідів. Ефект розвивається повільніше, зате підходить тим, хто не готовий до голок. Методики добре доповнюють одна одну в межах курсу.", ru: "Биоревитализация вводит гиалуроновую кислоту извне иглой, EXION Face стимулирует кожу вырабатывать собственную — без инъекций и следов. Эффект развивается медленнее, зато подходит тем, кто не готов к иглам. Методики хорошо дополняют друг друга в рамках курса.", en: "Biorevitalisation introduces hyaluronic acid with a needle; EXION Face prompts the skin to produce its own, with no injections and no marks. The effect builds more gradually but suits those who prefer to avoid needles. The two complement each other well within one course." } },
    ],
  },
  {
    type: "service",
    slug: "exosome-iv-drip",
    items: [
      { q: { uk: "Скільки триває крапельниця з екзосомами?", ru: "Сколько длится капельница с экзосомами?", en: "How long does an exosome IV drip take?" },
        a: { uk: "Сама інфузія триває приблизно 40–60 хвилин. Разом з оглядом лікаря, встановленням катетера та коротким спостереженням після процедури закладайте на візит близько 1,5 години. Час ви проводите в окремій палаті денного стаціонару.", ru: "Сама инфузия занимает примерно 40–60 минут. Вместе с осмотром врача, установкой катетера и коротким наблюдением после процедуры закладывайте на визит около 1,5 часов. Время вы проводите в отдельной палате дневного стационара.", en: "The infusion itself takes about 40–60 minutes. Allow roughly an hour and a half for the visit overall, including the medical review, cannulation and a short period of observation. You spend the time in a private day-hospital room." } },
      { q: { uk: "Які відчуття під час і після процедури?", ru: "Какие ощущения во время и после процедуры?", en: "How does the procedure feel during and afterwards?" },
        a: { uk: "Під час інфузії відчутний лише момент встановлення катетера — далі можна читати, працювати чи відпочивати. Після процедури більшість пацієнтів відзначають легкість і приплив енергії; іноді буває короткочасна сонливість. Обмежень на день процедури зазвичай немає.", ru: "Во время инфузии ощутим только момент установки катетера — дальше можно читать, работать или отдыхать. После процедуры большинство пациентов отмечают лёгкость и прилив энергии; иногда бывает кратковременная сонливость. Ограничений на день процедуры обычно нет.", en: "The only sensation is the cannula insertion — after that you can read, work or rest. Most patients report lightness and a lift in energy afterwards; occasionally there is brief drowsiness. There are usually no restrictions for the rest of the day." } },
      { q: { uk: "Чи потрібні аналізи перед крапельницею з екзосомами?", ru: "Нужны ли анализы перед капельницей с экзосомами?", en: "Are any tests required before an exosome drip?" },
        a: { uk: "Так, зазвичай лікар призначає базову лабораторну панель — щоб виключити протипоказання й переконатися, що процедура доречна саме зараз. Аналізи можна здати у власній лабораторії центру, часто в день консультації.", ru: "Да, обычно врач назначает базовую лабораторную панель — чтобы исключить противопоказания и убедиться, что процедура уместна именно сейчас. Анализы можно сдать в собственной лаборатории центра, часто в день консультации.", en: "Usually yes: the physician orders a basic laboratory panel to rule out contraindications and confirm the treatment is appropriate at this point. Tests can be done in the centre's own laboratory, often on the day of the consultation." } },
      { q: { uk: "Кому не підходить внутрішньовенна терапія екзосомами?", ru: "Кому не подходит внутривенная терапия экзосомами?", en: "Who is not suitable for intravenous exosome therapy?" },
        a: { uk: "Процедуру не проводять при вагітності та лактації, гострих інфекційних станах, онкологічних захворюваннях в активній фазі, тяжкій нирковій чи печінковій недостатності та автоімунних станах у загостренні. Остаточне рішення лікар ухвалює після огляду й аналізів.", ru: "Процедуру не проводят при беременности и лактации, острых инфекционных состояниях, онкологических заболеваниях в активной фазе, тяжёлой почечной или печёночной недостаточности и аутоиммунных состояниях в обострении. Окончательное решение врач принимает после осмотра и анализов.", en: "It is not performed during pregnancy or breastfeeding, in acute infection, active oncological disease, severe kidney or liver failure, or autoimmune conditions in flare. The physician decides after examination and test results." } },
    ],
  },
  {
    type: "service",
    slug: "exosomes",
    items: [
      { q: { uk: "Що таке екзосоми простими словами?", ru: "Что такое экзосомы простыми словами?", en: "What are exosomes, in simple terms?" },
        a: { uk: "Екзосоми — це найдрібніші позаклітинні везикули, своєрідні «посилки» з сигнальними молекулами, якими клітини обмінюються між собою. Потрапляючи у шкіру, вони передають фібробластам сигнал до відновлення: активніший синтез колагену, зменшення запалення, вирівнювання тону.", ru: "Экзосомы — это мельчайшие внеклеточные везикулы, своего рода «посылки» с сигнальными молекулами, которыми клетки обмениваются между собой. Попадая в кожу, они передают фибробластам сигнал к восстановлению: более активный синтез коллагена, уменьшение воспаления, выравнивание тона.", en: "Exosomes are tiny extracellular vesicles — small 'parcels' of signalling molecules that cells use to communicate. Delivered into the skin, they instruct fibroblasts to repair: more collagen synthesis, less inflammation and a more even tone." } },
      { q: { uk: "Чи допомагають екзосоми при випадінні волосся?", ru: "Помогают ли экзосомы при выпадении волос?", en: "Do exosomes help with hair loss?" },
        a: { uk: "Так, це один із перспективних напрямів. Ін'єкції в шкіру голови покращують мікроциркуляцію та живлення фолікулів, зменшуючи випадіння й підтримуючи фазу росту. Перед курсом лікар з'ясовує причину випадіння — за потреби з гормональною панеллю та аналізом на дефіцити.", ru: "Да, это одно из перспективных направлений. Инъекции в кожу головы улучшают микроциркуляцию и питание фолликулов, уменьшая выпадение и поддерживая фазу роста. Перед курсом врач выясняет причину выпадения — при необходимости с гормональной панелью и анализом на дефициты.", en: "Yes, this is a promising application. Injections into the scalp improve microcirculation and follicle nutrition, reducing shedding and supporting the growth phase. Before starting, the physician identifies the cause of the hair loss, with hormone and deficiency testing if needed." } },
    ],
  },
  {
    type: "service",
    slug: "face",
    items: [
      { q: { uk: "Що обрати: апаратне омолодження чи ін'єкції?", ru: "Что выбрать: аппаратное омоложение или инъекции?", en: "Should I choose device treatments or injections?" },
        a: { uk: "Це різні задачі. Апаратні методики працюють із тонусом тканин, щільністю шкіри та овалом, ін'єкції — з об'ємами, зморшками та зволоженням. Найчастіше протокол комбінований: лікар визначає, з чого почати, за станом шкіри та вашими пріоритетами.", ru: "Это разные задачи. Аппаратные методики работают с тонусом тканей, плотностью кожи и овалом, инъекции — с объёмами, морщинами и увлажнением. Чаще всего протокол комбинированный: врач определяет, с чего начать, по состоянию кожи и вашим приоритетам.", en: "They solve different problems. Device treatments address tissue tone, skin density and facial contour; injections address volume, wrinkles and hydration. Most protocols combine both — the physician decides where to start based on your skin and priorities." } },
      { q: { uk: "Як часто можна робити апаратні процедури для обличчя?", ru: "Как часто можно делать аппаратные процедуры для лица?", en: "How often can facial device treatments be repeated?" },
        a: { uk: "Усередині курсу інтервал зазвичай становить 1–2 тижні, залежно від методики. Повторний курс планують раз на 12–18 місяців, а між ними роблять підтримувальні сеанси 1–2 рази на рік. Частіше не варто: тканинам потрібен час на синтез нового колагену.", ru: "Внутри курса интервал обычно составляет 1–2 недели, в зависимости от методики. Повторный курс планируют раз в 12–18 месяцев, а между ними делают поддерживающие сеансы 1–2 раза в год. Чаще не стоит: тканям нужно время на синтез нового коллагена.", en: "Within a course, sessions are usually 1–2 weeks apart depending on the technology. A repeat course is planned every 12–18 months, with one or two maintenance sessions in between. More frequent treatment is pointless — tissue needs time to build new collagen." } },
    ],
  },
  {
    type: "service",
    slug: "gynaecology",
    items: [
      { q: { uk: "Що входить у консультацію гінеколога в GENEVITY?", ru: "Что входит в консультацию гинеколога в GENEVITY?", en: "What does a gynaecology consultation at GENEVITY include?" },
        a: { uk: "Прийом включає збір анамнезу, огляд на кріслі, за потреби — забір мазків і призначення лабораторних досліджень чи УЗД органів малого таза. За результатами лікар пояснює ситуацію та складає план спостереження або лікування.", ru: "Приём включает сбор анамнеза, осмотр на кресле, при необходимости — забор мазков и назначение лабораторных исследований или УЗИ органов малого таза. По результатам врач объясняет ситуацию и составляет план наблюдения или лечения.", en: "The appointment includes history taking, an examination, and where needed smears plus laboratory tests or a pelvic ultrasound. The physician then explains the findings and sets out a plan for monitoring or treatment." } },
      { q: { uk: "Як часто потрібно відвідувати гінеколога для профілактики?", ru: "Как часто нужно посещать гинеколога для профилактики?", en: "How often should I see a gynaecologist for check-ups?" },
        a: { uk: "Профілактичний огляд рекомендований раз на рік навіть за відсутності скарг. Цитологічне дослідження шийки матки проводять із визначеною лікарем періодичністю, зазвичай раз на 1–3 роки. У період менопаузи або при хронічних станах графік може бути щільнішим.", ru: "Профилактический осмотр рекомендован раз в год даже при отсутствии жалоб. Цитологическое исследование шейки матки проводят с определённой врачом периодичностью, обычно раз в 1–3 года. В период менопаузы или при хронических состояниях график может быть плотнее.", en: "A preventive examination is recommended once a year, even without symptoms. Cervical cytology is repeated at intervals set by the physician, typically every one to three years. During menopause or with chronic conditions the schedule may be tighter." } },
      { q: { uk: "У який день циклу краще записатися на прийом?", ru: "В какой день цикла лучше записаться на приём?", en: "Which day of the cycle is best for an appointment?" },
        a: { uk: "Для планового огляду оптимальні дні — з 5-го по 12-й день циклу, одразу після завершення менструації. УЗД органів малого таза зазвичай призначають на 5–10-й день. За гострих скарг приходьте будь-якого дня — огляд проведуть незалежно від фази циклу.", ru: "Для планового осмотра оптимальны дни с 5-го по 12-й день цикла, сразу после завершения менструации. УЗИ органов малого таза обычно назначают на 5–10-й день. При острых жалобах приходите в любой день — осмотр проведут независимо от фазы цикла.", en: "For a routine examination, days 5–12 of the cycle — just after menstruation ends — are ideal, and pelvic ultrasound is usually scheduled for days 5–10. With acute symptoms, come any day: you will be examined regardless of cycle phase." } },
      { q: { uk: "Чи можна здати аналізи одразу після огляду?", ru: "Можно ли сдать анализы сразу после осмотра?", en: "Can I have tests done straight after the examination?" },
        a: { uk: "Так. Власна клініко-діагностична лабораторія працює на місці, тому мазки, посіви, ПЛР і гормональні панелі здають одразу після прийому. Результати надсилаємо на email або в месенджер, а лікар пояснює їх на повторній консультації.", ru: "Да. Собственная клинико-диагностическая лаборатория работает на месте, поэтому мазки, посевы, ПЦР и гормональные панели сдают сразу после приёма. Результаты отправляем на email или в мессенджер, а врач объясняет их на повторной консультации.", en: "Yes. The in-house clinical laboratory is on site, so smears, cultures, PCR and hormone panels can be taken immediately after the appointment. Results are sent by email or messenger and explained by the physician at a follow-up." } },
      { q: { uk: "Чи веде гінеколог пацієнток у період менопаузи?", ru: "Ведёт ли гинеколог пациенток в период менопаузы?", en: "Does the gynaecologist care for patients going through menopause?" },
        a: { uk: "Так. Ми оцінюємо гормональний статус, стан кісткової тканини й метаболізму, обговорюємо менопаузальну гормональну терапію та її альтернативи. За потреби до ведення долучається ендокринолог центру — це дозволяє працювати з причиною, а не лише зі скаргами.", ru: "Да. Мы оцениваем гормональный статус, состояние костной ткани и метаболизма, обсуждаем менопаузальную гормональную терапию и её альтернативы. При необходимости к ведению подключается эндокринолог центра — это позволяет работать с причиной, а не только с жалобами.", en: "Yes. We assess hormonal status, bone health and metabolism, and discuss menopausal hormone therapy and its alternatives. Where useful, the centre's endocrinologist joins the case so we address the cause, not just the symptoms." } },
      { q: { uk: "Чи можна прийти на консультацію без скарг, просто перевіритися?", ru: "Можно ли прийти на консультацию без жалоб, просто провериться?", en: "Can I come for a check without any symptoms?" },
        a: { uk: "Так, і це найкращий сценарій. Більшість гінекологічних станів на ранніх етапах не дають симптомів, а виявляються на плановому огляді чи УЗД. Профілактичний візит займає близько 30 хвилин.", ru: "Да, и это лучший сценарий. Большинство гинекологических состояний на ранних этапах не дают симптомов, а выявляются на плановом осмотре или УЗИ. Профилактический визит занимает около 30 минут.", en: "Yes, and it is the best scenario. Most gynaecological conditions cause no symptoms early on and are found at a routine examination or ultrasound. A preventive visit takes about 30 minutes." } },
      { q: { uk: "Чи пов'язана гінекологія з естетичними процедурами інтимної зони?", ru: "Связана ли гинекология с эстетическими процедурами интимной зоны?", en: "How does gynaecology relate to intimate aesthetic treatments?" },
        a: { uk: "Так, і саме гінеколог визначає, чи доречні такі процедури. Перед лазерним інтимним омолодженням або біоревіталізацією інтимної зони обов'язковий огляд і виключення запальних процесів. Такий порядок робить естетичний результат прогнозованим і безпечним.", ru: "Да, и именно гинеколог определяет, уместны ли такие процедуры. Перед лазерным интимным омоложением или биоревитализацией интимной зоны обязателен осмотр и исключение воспалительных процессов. Такой порядок делает эстетический результат прогнозируемым и безопасным.", en: "Closely — the gynaecologist decides whether such treatments are appropriate. Before intimate laser rejuvenation or biorevitalisation, an examination is required to exclude inflammation. This sequence is what makes the aesthetic result predictable and safe." } },
    ],
  },
];

seed(batches);
