import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "category",
    slug: "apparatus-cosmetology",
    items: [
      { q: { uk: "Чим апаратна косметологія відрізняється від доглядових процедур?", ru: "Чем аппаратная косметология отличается от уходовых процедур?", en: "How does device cosmetology differ from care treatments?" },
        a: { uk: "Доглядові процедури працюють переважно з поверхневими шарами шкіри: очищення, зволоження, живлення. Апаратні методики впливають глибше — на дерму, м'язи та SMAS-шар, запускаючи синтез колагену. Тому результат тримається місяцями, а не тижнями.", ru: "Уходовые процедуры работают преимущественно с поверхностными слоями кожи: очищение, увлажнение, питание. Аппаратные методики воздействуют глубже — на дерму, мышцы и SMAS-слой, запуская синтез коллагена. Поэтому результат держится месяцами, а не неделями.", en: "Care treatments work mainly on the surface layers: cleansing, hydration, nourishment. Device methods reach deeper — the dermis, muscles and SMAS layer — triggering collagen synthesis. The result therefore lasts months rather than weeks." } },
      { q: { uk: "Чи є протипоказання до апаратних процедур?", ru: "Есть ли противопоказания к аппаратным процедурам?", en: "Are there contraindications to device treatments?" },
        a: { uk: "Так, і вони спільні для більшості методик: вагітність і лактація, кардіостимулятор та електронні імплантати, металеві конструкції в зоні обробки, епілепсія, онкологічні захворювання в активній фазі, гострі запалення шкіри. Лікар перевіряє анамнез перед кожним курсом.", ru: "Да, и они общие для большинства методик: беременность и лактация, кардиостимулятор и электронные имплантаты, металлические конструкции в зоне обработки, эпилепсия, онкологические заболевания в активной фазе, острые воспаления кожи. Врач проверяет анамнез перед каждым курсом.", en: "Yes, and most methods share them: pregnancy and breastfeeding, pacemakers and electronic implants, metal hardware in the treated area, epilepsy, active oncological disease and acute skin inflammation. Your history is reviewed before every course." } },
      { q: { uk: "З якого віку варто починати апаратні процедури?", ru: "С какого возраста стоит начинать аппаратные процедуры?", en: "At what age should device treatments begin?" },
        a: { uk: "Орієнтир — стан тканин, а не паспортний вік. До 35 років зазвичай доречні м'якші RF-методики для якості шкіри, після 35–40 додають технології ліфтингу. Виражений птоз потребує інших рішень, тому підхід завжди підбирає лікар після огляду.", ru: "Ориентир — состояние тканей, а не паспортный возраст. До 35 лет обычно уместны более мягкие RF-методики для качества кожи, после 35–40 добавляют технологии лифтинга. Выраженный птоз требует других решений, поэтому подход всегда подбирает врач после осмотра.", en: "Tissue condition matters more than age. Before 35, gentler RF methods for skin quality are usually appropriate; from 35–40, lifting technologies are added. Pronounced laxity needs different solutions, so the physician always decides after examination." } },
      { q: { uk: "Як довго тримається результат апаратних процедур?", ru: "Как долго держится результат аппаратных процедур?", en: "How long do the results of device treatments last?" },
        a: { uk: "Залежно від методики — від 6 до 18 місяців. Ліфтингові технології дають найдовший ефект, оскільки працюють через синтез власного колагену. Результат подовжують підтримувальні сеанси 1–2 рази на рік і базовий домашній догляд із SPF.", ru: "В зависимости от методики — от 6 до 18 месяцев. Лифтинговые технологии дают самый долгий эффект, поскольку работают через синтез собственного коллагена. Результат продлевают поддерживающие сеансы 1–2 раза в год и базовый домашний уход с SPF.", en: "From six to eighteen months, depending on the method. Lifting technologies last longest because they work through your own collagen synthesis. Maintenance sessions once or twice a year plus basic home care with SPF extend the result." } },
    ],
  },
  {
    type: "category",
    slug: "diagnostics",
    items: [
      { q: { uk: "Як швидко готові результати досліджень?", ru: "Как быстро готовы результаты исследований?", en: "How quickly are results ready?" },
        a: { uk: "Загальний аналіз крові — за кілька годин, біохімія — до доби, гормони — 1–2 дні, ПЛР — 1–3 доби. Висновок УЗД ви отримуєте одразу після дослідження. Точний термін адміністратор називає під час здачі аналізів.", ru: "Общий анализ крови — за несколько часов, биохимия — до суток, гормоны — 1–2 дня, ПЦР — 1–3 суток. Заключение УЗИ вы получаете сразу после исследования. Точный срок администратор называет при сдаче анализов.", en: "A full blood count takes a few hours, biochemistry up to a day, hormones one to two days and PCR one to three. The ultrasound report is given immediately. The administrator confirms exact timings when you attend." } },
      { q: { uk: "Чи можна пройти обстеження без призначення лікаря?", ru: "Можно ли пройти обследование без назначения врача?", en: "Can I have tests without a doctor's referral?" },
        a: { uk: "Так, більшість аналізів і УЗД можна замовити самостійно. Але якщо ви не впевнені, що саме потрібно, консультація заощадить час і кошти: лікар призначить лише доречні дослідження й пояснить результати у зв'язку між собою.", ru: "Да, большинство анализов и УЗИ можно заказать самостоятельно. Но если вы не уверены, что именно нужно, консультация сэкономит время и средства: врач назначит только уместные исследования и объяснит результаты во взаимосвязи.", en: "Yes, most tests and scans can be booked directly. If you are unsure what you need, however, a consultation saves time and money: the physician orders only relevant tests and interprets the results together." } },
      { q: { uk: "Чи можна здати аналізи та пройти УЗД за один візит?", ru: "Можно ли сдать анализы и пройти УЗИ за один визит?", en: "Can tests and an ultrasound be done in one visit?" },
        a: { uk: "Так — лабораторія та кабінет УЗД працюють в одному приміщенні центру. Зручно планувати візит на ранок: кров здають натще, а після цього можна поснідати й пройти інструментальні дослідження.", ru: "Да — лаборатория и кабинет УЗИ работают в одном помещении центра. Удобно планировать визит на утро: кровь сдают натощак, а после этого можно позавтракать и пройти инструментальные исследования.", en: "Yes — the laboratory and ultrasound room are in the same building. A morning visit works best: blood is taken fasting, after which you can eat and go on to the imaging." } },
    ],
  },
  {
    type: "category",
    slug: "gynaecology",
    items: [
      { q: { uk: "Що входить у консультацію гінеколога?", ru: "Что входит в консультацию гинеколога?", en: "What does a gynaecology consultation include?" },
        a: { uk: "Збір анамнезу, огляд, за потреби забір мазків і призначення лабораторних досліджень чи УЗД органів малого таза. Наприкінці прийому лікар пояснює ситуацію та складає план спостереження або лікування.", ru: "Сбор анамнеза, осмотр, при необходимости забор мазков и назначение лабораторных исследований или УЗИ органов малого таза. В конце приёма врач объясняет ситуацию и составляет план наблюдения или лечения.", en: "History taking, examination and, where needed, smears plus laboratory tests or a pelvic ultrasound. At the end the physician explains the findings and sets out a plan for monitoring or treatment." } },
      { q: { uk: "Як часто потрібен профілактичний огляд?", ru: "Как часто нужен профилактический осмотр?", en: "How often is a preventive examination needed?" },
        a: { uk: "Раз на рік навіть без скарг. Цитологічне дослідження шийки матки проводять із періодичністю, яку визначає лікар — зазвичай раз на 1–3 роки. У менопаузі або при хронічних станах графік може бути щільнішим.", ru: "Раз в год даже без жалоб. Цитологическое исследование шейки матки проводят с периодичностью, которую определяет врач — обычно раз в 1–3 года. В менопаузе или при хронических состояниях график может быть плотнее.", en: "Once a year, even without symptoms. Cervical cytology is repeated at intervals set by the physician, usually every one to three years. During menopause or with chronic conditions the schedule may be tighter." } },
      { q: { uk: "Які дослідження можна пройти в межах гінекологічного напряму?", ru: "Какие исследования можно пройти в рамках гинекологического направления?", en: "Which investigations are available within the gynaecology service?" },
        a: { uk: "Мазки на флору й онкоцитологію, ПЛР на інфекції, бакпосіви, гормональні панелі, УЗД органів малого таза та молочних залоз. Усе це доступно на місці — у власній лабораторії та кабінеті УЗД центру.", ru: "Мазки на флору и онкоцитологию, ПЦР на инфекции, бакпосевы, гормональные панели, УЗИ органов малого таза и молочных желёз. Всё это доступно на месте — в собственной лаборатории и кабинете УЗИ центра.", en: "Smears for flora and cytology, PCR for infections, cultures, hormone panels, and ultrasound of the pelvis and breasts. All are available on site in the centre's own laboratory and ultrasound room." } },
      { q: { uk: "З якими скаргами найчастіше звертаються до гінеколога?", ru: "С какими жалобами чаще всего обращаются к гинекологу?", en: "What are the most common reasons to see a gynaecologist?" },
        a: { uk: "Порушення менструального циклу, біль унизу живота, зміна характеру виділень, дискомфорт під час близькості, планування вагітності та симптоми менопаузи. Окремий привід — профілактичний огляд без скарг, і це найкращий сценарій.", ru: "Нарушения менструального цикла, боль внизу живота, изменение характера выделений, дискомфорт во время близости, планирование беременности и симптомы менопаузы. Отдельный повод — профилактический осмотр без жалоб, и это лучший сценарий.", en: "Menstrual irregularities, lower abdominal pain, changes in discharge, discomfort during intimacy, pregnancy planning and menopausal symptoms. A preventive check with no symptoms is a reason in itself — and the best one." } },
      { q: { uk: "Чи веде центр пацієнток у період менопаузи?", ru: "Ведёт ли центр пациенток в период менопаузы?", en: "Does the centre care for patients during menopause?" },
        a: { uk: "Так. Ми оцінюємо гормональний статус, стан кісткової тканини та метаболізму, обговорюємо менопаузальну гормональну терапію та її альтернативи. За потреби до ведення долучається ендокринолог центру.", ru: "Да. Мы оцениваем гормональный статус, состояние костной ткани и метаболизма, обсуждаем менопаузальную гормональную терапию и её альтернативы. При необходимости к ведению подключается эндокринолог центра.", en: "Yes. We assess hormonal status, bone health and metabolism, and discuss menopausal hormone therapy and its alternatives. The centre's endocrinologist joins the case where useful." } },
      { q: { uk: "Чи потрібен огляд гінеколога перед інтимними естетичними процедурами?", ru: "Нужен ли осмотр гинеколога перед интимными эстетическими процедурами?", en: "Is a gynaecological examination required before intimate aesthetic treatments?" },
        a: { uk: "Так, він обов'язковий. Перед лазерним омолодженням, біоревіталізацією чи RF-ліфтингом інтимної зони потрібно виключити запальні процеси та інфекції. Такий порядок робить результат прогнозованим і безпечним.", ru: "Да, он обязателен. Перед лазерным омоложением, биоревитализацией или RF-лифтингом интимной зоны нужно исключить воспалительные процессы и инфекции. Такой порядок делает результат прогнозируемым и безопасным.", en: "Yes, it is mandatory. Before intimate laser rejuvenation, biorevitalisation or RF lifting, inflammation and infection must be excluded. This sequence makes the result predictable and safe." } },
      { q: { uk: "У який день циклу краще планувати візит?", ru: "В какой день цикла лучше планировать визит?", en: "Which day of the cycle is best for a visit?" },
        a: { uk: "Для планового огляду — з 5-го по 12-й день циклу, після завершення менструації. УЗД органів малого таза зазвичай призначають на 5–10-й день. За гострих скарг приходьте будь-якого дня.", ru: "Для планового осмотра — с 5-го по 12-й день цикла, после завершения менструации. УЗИ органов малого таза обычно назначают на 5–10-й день. При острых жалобах приходите в любой день.", en: "For a routine examination, days 5–12 of the cycle, once menstruation has ended. Pelvic ultrasound is usually scheduled for days 5–10. With acute symptoms, come any day." } },
    ],
  },
  {
    type: "category",
    slug: "injectable-cosmetology",
    items: [
      { q: { uk: "З якої процедури почати, якщо це перший досвід ін'єкцій?", ru: "С какой процедуры начать, если это первый опыт инъекций?", en: "Which treatment should I start with if it is my first time?" },
        a: { uk: "Найчастіше починають із того, що дає зрозумілий і зворотний результат: біоревіталізації для якості шкіри або ботулінотерапії в зоні міжбрів'я. Обидві методики не змінюють рис обличчя, тому дозволяють спокійно оцінити свої відчуття від процедур.", ru: "Чаще всего начинают с того, что даёт понятный и обратимый результат: биоревитализации для качества кожи или ботулинотерапии в зоне межбровья. Обе методики не меняют черт лица, поэтому позволяют спокойно оценить свои ощущения от процедур.", en: "Most people start with something clear and reversible: biorevitalisation for skin quality, or botulinum therapy in the glabella. Neither changes your features, so you can judge how you feel about injectables without pressure." } },
      { q: { uk: "Як підготуватися до ін'єкційної процедури?", ru: "Как подготовиться к инъекционной процедуре?", en: "How should I prepare for an injectable treatment?" },
        a: { uk: "За 5–7 днів за погодженням із лікарем відмовтеся від препаратів, що розріджують кров, за 2–3 дні — від алкоголю. У день процедури приходьте без макіяжу. При схильності до герпесу лікар призначить противірусну профілактику.", ru: "За 5–7 дней по согласованию с врачом откажитесь от препаратов, разжижающих кровь, за 2–3 дня — от алкоголя. В день процедуры приходите без макияжа. При склонности к герпесу врач назначит противовирусную профилактику.", en: "With your physician's agreement, stop blood-thinning medication five to seven days beforehand and alcohol two to three days before. Come without make-up. If you are prone to herpes, antiviral prophylaxis will be prescribed." } },
      { q: { uk: "Чи можна повернути все як було, якщо результат не сподобається?", ru: "Можно ли вернуть всё как было, если результат не понравится?", en: "Can everything be reversed if I do not like the result?" },
        a: { uk: "Філери на основі гіалуронової кислоти розчиняються ферментом гіалуронідазою — це керована процедура. Ефект ботулотоксину минає самостійно за кілька місяців. Саме зворотність робить ці методики одними з найбезпечніших.", ru: "Филлеры на основе гиалуроновой кислоты растворяются ферментом гиалуронидазой — это управляемая процедура. Эффект ботулотоксина проходит самостоятельно за несколько месяцев. Именно обратимость делает эти методики одними из самых безопасных.", en: "Hyaluronic acid fillers can be dissolved with hyaluronidase, a controlled procedure. Botulinum toxin simply wears off over a few months. This reversibility is what makes these methods among the safest available." } },
      { q: { uk: "Чи потрібні аналізи перед ін'єкційними процедурами?", ru: "Нужны ли анализы перед инъекционными процедурами?", en: "Are tests needed before injectable treatments?" },
        a: { uk: "Для більшості естетичних ін'єкцій окремі аналізи не потрібні — достатньо огляду та збору анамнезу. Виняток — PRP-терапія, перед якою призначають базові аналізи крові, та випадки, коли у вас є хронічні захворювання чи ви приймаєте антикоагулянти.", ru: "Для большинства эстетических инъекций отдельные анализы не нужны — достаточно осмотра и сбора анамнеза. Исключение — PRP-терапия, перед которой назначают базовые анализы крови, и случаи, когда у вас есть хронические заболевания или вы принимаете антикоагулянты.", en: "For most aesthetic injections no separate tests are needed — an examination and history are enough. The exceptions are PRP, which requires baseline blood tests, and cases involving chronic conditions or anticoagulant therapy." } },
    ],
  },
  {
    type: "category",
    slug: "intimate-rejuvenation",
    items: [
      { q: { uk: "Наскільки конфіденційні процедури для інтимної зони?", ru: "Насколько конфиденциальны процедуры для интимной зоны?", en: "How confidential are intimate treatments?" },
        a: { uk: "Повністю. Прийом відбувається в окремому кабінеті, дані пацієнтів захищені лікарською таємницею, а запис в адміністратора не потребує пояснень щодо мети візиту. Ви можете вказати лише «консультація гінеколога».", ru: "Полностью. Приём проходит в отдельном кабинете, данные пациентов защищены врачебной тайной, а запись у администратора не требует объяснений о цели визита. Вы можете указать просто «консультация гинеколога».", en: "Completely. Appointments take place in a private room, patient data is protected by medical confidentiality, and booking requires no explanation of the reason for your visit — 'gynaecology consultation' is enough." } },
      { q: { uk: "Хто виконує процедури для інтимної зони?", ru: "Кто выполняет процедуры для интимной зоны?", en: "Who performs intimate area treatments?" },
        a: { uk: "Лікар-гінеколог після огляду та виключення запальних процесів. Це принципова умова: робота в цій зоні потребує не лише володіння апаратом, а й уміння оцінити стан слизової та тканин.", ru: "Врач-гинеколог после осмотра и исключения воспалительных процессов. Это принципиальное условие: работа в этой зоне требует не только владения аппаратом, но и умения оценить состояние слизистой и тканей.", en: "A gynaecologist, after an examination that rules out inflammation. This is essential: working in this area requires not just operating the device but assessing the mucosa and tissue." } },
    ],
  },
];

seed(batches);
