import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "service",
    slug: "mesotherapy",
    items: [
      { q: { uk: "Які проблеми вирішує мезотерапія обличчя?", ru: "Какие проблемы решает мезотерапия лица?", en: "What concerns does facial mesotherapy address?" },
        a: { uk: "Тьмяний колір обличчя, зневоднення, дрібні зморшки, знижений тонус, підвищена жирність і схильність до висипань. Склад коктейлю підбирають під конкретну задачу, тому одна методика працює для різних запитів.", ru: "Тусклый цвет лица, обезвоженность, мелкие морщины, сниженный тонус, повышенная жирность и склонность к высыпаниям. Состав коктейля подбирают под конкретную задачу, поэтому одна методика работает для разных запросов.", en: "Dull complexion, dehydration, fine lines, reduced tone, excess oil and breakout-prone skin. The cocktail is tailored to the specific goal, so one method covers a range of concerns." } },
      { q: { uk: "Які обмеження після мезотерапії?", ru: "Какие ограничения после мезотерапии?", en: "What restrictions apply after mesotherapy?" },
        a: { uk: "Добу не наносьте макіяж і не вмивайтеся гарячою водою, 48 годин уникайте сауни, басейну, інтенсивних тренувань і алкоголю. Тиждень не використовуйте кислоти й скраби. SPF обов'язковий у будь-яку пору року.", ru: "Сутки не наносите макияж и не умывайтесь горячей водой, 48 часов избегайте сауны, бассейна, интенсивных тренировок и алкоголя. Неделю не используйте кислоты и скрабы. SPF обязателен в любое время года.", en: "For 24 hours avoid make-up and hot water; for 48 hours avoid saunas, pools, intensive exercise and alcohol. Skip acids and scrubs for a week. SPF is essential all year round." } },
      { q: { uk: "Чи можна робити мезотерапію влітку?", ru: "Можно ли делать мезотерапию летом?", en: "Can mesotherapy be done in summer?" },
        a: { uk: "Так, мезотерапія не підвищує фоточутливість, тому її проводять цілий рік. Влітку вона навіть доречна: коктейлі з антиоксидантами допомагають шкірі впоратися з наслідками сонця. Обов'язкова умова — щоденний SPF.", ru: "Да, мезотерапия не повышает фоточувствительность, поэтому её проводят круглый год. Летом она даже уместна: коктейли с антиоксидантами помогают коже справиться с последствиями солнца. Обязательное условие — ежедневный SPF.", en: "Yes — mesotherapy does not increase photosensitivity, so it is performed year-round. In summer it is particularly useful: antioxidant cocktails help the skin cope with sun exposure. Daily SPF remains essential." } },
    ],
  },
  {
    type: "service",
    slug: "monopolar-rf-lifting",
    items: [
      { q: { uk: "Які скарги вирішує монополярний RF-ліфтинг інтимної зони?", ru: "Какие жалобы решает монополярный RF-лифтинг интимной зоны?", en: "Which concerns does monopolar RF lifting of the intimate area address?" },
        a: { uk: "Зниження тонусу тканин після пологів або з віком, сухість слизової, дискомфорт під час близькості, легкі прояви стресового нетримання. Метод безконтактний і не травмує слизову, тому підходить пацієнткам, які не готові до лазерних чи ін'єкційних методик.", ru: "Снижение тонуса тканей после родов или с возрастом, сухость слизистой, дискомфорт во время близости, лёгкие проявления стрессового недержания. Метод бесконтактный и не травмирует слизистую, поэтому подходит пациенткам, не готовым к лазерным или инъекционным методикам.", en: "Loss of tissue tone after childbirth or with age, mucosal dryness, discomfort during intimacy and mild stress incontinence. The method is non-contact and does not injure the mucosa, so it suits patients not ready for laser or injectable options." } },
      { q: { uk: "Чи потрібна підготовка до RF-ліфтингу інтимної зони?", ru: "Нужна ли подготовка к RF-лифтингу интимной зоны?", en: "Is preparation needed for intimate RF lifting?" },
        a: { uk: "Спеціальної підготовки немає, але перед курсом обов'язковий огляд гінеколога — щоб виключити запальні процеси та інфекції. Процедуру не проводять під час менструації. У день сеансу приходьте без косметичних засобів у зоні обробки.", ru: "Специальной подготовки нет, но перед курсом обязателен осмотр гинеколога — чтобы исключить воспалительные процессы и инфекции. Процедуру не проводят во время менструации. В день сеанса приходите без косметических средств в зоне обработки.", en: "No special preparation is needed, but a gynaecological examination is required beforehand to rule out inflammation or infection. The treatment is not performed during menstruation. Come with no cosmetic products in the area." } },
      { q: { uk: "Чи є обмеження після процедури?", ru: "Есть ли ограничения после процедуры?", en: "Are there restrictions afterwards?" },
        a: { uk: "Обмежень практично немає — до звичного ритму можна повертатися одразу. Протягом доби варто утриматися від сауни, гарячої ванни та басейну. Статеве життя зазвичай не обмежують, але точні рекомендації дає лікар після сеансу.", ru: "Ограничений практически нет — к привычному ритму можно возвращаться сразу. В течение суток стоит воздержаться от сауны, горячей ванны и бассейна. Половую жизнь обычно не ограничивают, но точные рекомендации даёт врач после сеанса.", en: "There are virtually none — you can return to your usual routine immediately. Avoid saunas, hot baths and pools for 24 hours. Intimacy is usually unrestricted, but the physician gives precise advice after the session." } },
      { q: { uk: "Чим RF-ліфтинг відрізняється від лазерного інтимного омолодження?", ru: "Чем RF-лифтинг отличается от лазерного интимного омоложения?", en: "How does RF lifting differ from intimate laser rejuvenation?" },
        a: { uk: "RF діє об'ємним прогріванням тканин без пошкодження слизової — це м'якший варіант із нульовим відновленням. Лазер створює контрольовані мікрозони впливу й дає виразніший результат при вираженій атрофії. Що обрати, лікар вирішує після огляду.", ru: "RF действует объёмным прогреванием тканей без повреждения слизистой — это более мягкий вариант с нулевым восстановлением. Лазер создаёт контролируемые микрозоны воздействия и даёт более выраженный результат при выраженной атрофии. Что выбрать, врач решает после осмотра.", en: "RF works by heating the tissue in volume without damaging the mucosa — a gentler option with no downtime. The laser creates controlled microzones and gives a stronger result in pronounced atrophy. The physician chooses after examination." } },
    ],
  },
  {
    type: "service",
    slug: "neck-biorevitalisation",
    items: [
      { q: { uk: "Скільки процедур потрібно для шиї та декольте?", ru: "Сколько процедур нужно для шеи и декольте?", en: "How many sessions are needed for the neck and décolleté?" },
        a: { uk: "Стандартний курс — 3–4 процедури з інтервалом 3–4 тижні. Шкіра цих зон тонша й відновлюється повільніше за шкіру обличчя, тому курс тут рідко буває коротшим. Результат підтримують 1–2 процедурами на рік.", ru: "Стандартный курс — 3–4 процедуры с интервалом 3–4 недели. Кожа этих зон тоньше и восстанавливается медленнее, чем кожа лица, поэтому курс здесь редко бывает короче. Результат поддерживают 1–2 процедурами в год.", en: "A standard course is three to four sessions three to four weeks apart. The skin here is thinner and recovers more slowly than facial skin, so the course is rarely shorter. Results are maintained with one or two sessions a year." } },
      { q: { uk: "Чи можна поєднувати з апаратними процедурами для шиї?", ru: "Можно ли сочетать с аппаратными процедурами для шеи?", en: "Can it be combined with device treatments for the neck?" },
        a: { uk: "Так, і це часто найкращий сценарій: біоревіталізація відновлює зволоженість, а Ultraformer MPT чи EXION працюють із щільністю та тонусом. Процедури розводять у часі — інтервал зазвичай 2–4 тижні, точний план складає лікар.", ru: "Да, и это часто лучший сценарий: биоревитализация восстанавливает увлажнённость, а Ultraformer MPT или EXION работают с плотностью и тонусом. Процедуры разводят во времени — интервал обычно 2–4 недели, точный план составляет врач.", en: "Yes, and it is often the best approach: biorevitalisation restores hydration while Ultraformer MPT or EXION address density and tone. The sessions are spaced two to four weeks apart, with the exact plan set by the physician." } },
      { q: { uk: "Чи болісна процедура в зоні декольте?", ru: "Болезненна ли процедура в зоне декольте?", en: "Is the treatment painful on the décolleté?" },
        a: { uk: "Зона чутливіша за обличчя, тому аплікаційну анестезію наносять завжди — за 20–30 хвилин до початку. Після цього ін'єкції відчуваються як короткі поколювання. Сама процедура триває близько 20–30 хвилин.", ru: "Зона чувствительнее лица, поэтому аппликационную анестезию наносят всегда — за 20–30 минут до начала. После этого инъекции ощущаются как короткие покалывания. Сама процедура занимает около 20–30 минут.", en: "The area is more sensitive than the face, so topical anaesthetic is always applied 20–30 minutes beforehand. After that the injections feel like brief pinpricks. The session lasts about 20–30 minutes." } },
      { q: { uk: "Що ще допоможе шкірі шиї, крім процедур?", ru: "Что ещё поможет коже шеи, кроме процедур?", en: "What else helps the skin of the neck besides treatments?" },
        a: { uk: "Щоденний SPF на шию та декольте — ці зони отримують багато сонця й рідко захищені. Додайте догляд із ретиноїдами чи пептидами за призначенням лікаря, стежте за поставою та висотою подушки. Без цього ефект курсу тримається помітно менше.", ru: "Ежедневный SPF на шею и декольте — эти зоны получают много солнца и редко защищены. Добавьте уход с ретиноидами или пептидами по назначению врача, следите за осанкой и высотой подушки. Без этого эффект курса держится заметно меньше.", en: "Daily SPF on the neck and décolleté — these areas get plenty of sun and are rarely protected. Add retinoid or peptide care as prescribed, and watch your posture and pillow height. Without this, the results of a course fade noticeably faster." } },
    ],
  },
  {
    type: "service",
    slug: "nose-contouring",
    items: [
      { q: { uk: "Скільки триває процедура корекції носа філером?", ru: "Сколько длится процедура коррекции носа филлером?", en: "How long does non-surgical nose correction take?" },
        a: { uk: "Саме введення займає 15–20 хвилин, разом з оглядом, розміткою та анестезією — близько 40 хвилин. Результат видно одразу на кріслі, і ви можете оцінити профіль ще до завершення візиту.", ru: "Само введение занимает 15–20 минут, вместе с осмотром, разметкой и анестезией — около 40 минут. Результат виден сразу в кресле, и вы можете оценить профиль ещё до завершения визита.", en: "The injection itself takes 15–20 minutes; with examination, marking and anaesthesia, allow about 40 minutes. The result is visible immediately, so you can assess your profile before you leave." } },
      { q: { uk: "Який період відновлення після контурної пластики носа?", ru: "Какой период восстановления после контурной пластики носа?", en: "What is the recovery like after non-surgical rhinoplasty?" },
        a: { uk: "Відновлення мінімальне: незначний набряк тримається 1–2 дні, іноді з'являються точкові синці. Два тижні не носіть окуляри з тиском на спинку носа, уникайте сауни, спорту й масажу зони. До роботи можна повертатися того ж дня.", ru: "Восстановление минимальное: незначительный отёк держится 1–2 дня, иногда появляются точечные синяки. Две недели не носите очки с давлением на спинку носа, избегайте сауны, спорта и массажа зоны. К работе можно возвращаться в тот же день.", en: "Recovery is minimal: slight swelling for one to two days and occasional pinpoint bruising. For two weeks avoid glasses that press on the bridge, saunas, exercise and massaging the area. You can return to work the same day." } },
      { q: { uk: "Чи можна скоригувати асиметрію кінчика носа?", ru: "Можно ли скорректировать асимметрию кончика носа?", en: "Can tip asymmetry be corrected?" },
        a: { uk: "Так, легку асиметрію кінчика й невелику опущеність можна скоригувати мікрооб'ємами філера — це одна з типових задач методики. Виражені деформації, наслідки травм чи проблеми з диханням філером не вирішуються: тут потрібна консультація хірурга.", ru: "Да, лёгкую асимметрию кончика и небольшую опущенность можно скорректировать микрообъёмами филлера — это одна из типичных задач методики. Выраженные деформации, последствия травм или проблемы с дыханием филлером не решаются: здесь нужна консультация хирурга.", en: "Yes — slight tip asymmetry and a mildly drooping tip can be corrected with micro-volumes of filler, a typical use of the method. Marked deformities, trauma sequelae or breathing problems cannot be solved with filler and require a surgical consultation." } },
      { q: { uk: "Чи є протипоказання до безопераційної корекції носа?", ru: "Есть ли противопоказания к безоперационной коррекции носа?", en: "Are there contraindications to non-surgical nose correction?" },
        a: { uk: "Так: перенесена ринопластика без узгодження з хірургом, активні запалення чи інфекції в зоні, вагітність і лактація, порушення згортання крові, автоімунні захворювання в загостренні. Наявність постійних (перманентних) філерів у носі також є протипоказанням.", ru: "Да: перенесённая ринопластика без согласования с хирургом, активные воспаления или инфекции в зоне, беременность и лактация, нарушения свёртывания крови, аутоиммунные заболевания в обострении. Наличие постоянных (перманентных) филлеров в носу также является противопоказанием.", en: "Yes: previous rhinoplasty without surgical clearance, active inflammation or infection in the area, pregnancy and breastfeeding, clotting disorders and autoimmune disease in flare. Existing permanent fillers in the nose are also a contraindication." } },
    ],
  },
  {
    type: "service",
    slug: "nutraceuticals",
    items: [
      { q: { uk: "Які аналізи потрібні для підбору нутрицевтиків?", ru: "Какие анализы нужны для подбора нутрицевтиков?", en: "Which tests are needed to choose nutraceuticals?" },
        a: { uk: "Базовий набір: загальний аналіз крові, феритин, вітамін D, В12, магній, цинк, гомоцистеїн, показники щитоподібної залози та ліпідний профіль. За показаннями лікар додає гормональну панель або маркери запалення. Призначення без аналізів — це вгадування, а не терапія.", ru: "Базовый набор: общий анализ крови, ферритин, витамин D, B12, магний, цинк, гомоцистеин, показатели щитовидной железы и липидный профиль. По показаниям врач добавляет гормональную панель или маркеры воспаления. Назначение без анализов — это угадывание, а не терапия.", en: "The core set: full blood count, ferritin, vitamin D, B12, magnesium, zinc, homocysteine, thyroid markers and a lipid profile. The physician adds hormone panels or inflammatory markers where indicated. Prescribing without tests is guesswork, not therapy." } },
      { q: { uk: "Через скільки часу буде помітний ефект від нутрицевтиків?", ru: "Через сколько времени будет заметен эффект от нутрицевтиков?", en: "How soon will I notice an effect from nutraceuticals?" },
        a: { uk: "Перші зміни самопочуття — енергія, сон, стан шкіри — зазвичай з'являються через 4–8 тижнів. Лабораторні показники змінюються повільніше: контрольні аналізи призначають через 3 місяці. Швидкий ефект «за тиждень» здебільшого означає ефект очікування.", ru: "Первые изменения самочувствия — энергия, сон, состояние кожи — обычно появляются через 4–8 недель. Лабораторные показатели меняются медленнее: контрольные анализы назначают через 3 месяца. Быстрый эффект «за неделю» чаще всего означает эффект ожидания.", en: "Changes in how you feel — energy, sleep, skin — usually appear after four to eight weeks. Laboratory markers shift more slowly, with follow-up tests at three months. An effect within a week is usually expectation rather than physiology." } },
    ],
  },
  {
    type: "service",
    slug: "photorejuvenation",
    items: [
      { q: { uk: "Як підготуватися до фотоомолодження?", ru: "Как подготовиться к фотоомоложению?", en: "How should I prepare for photorejuvenation?" },
        a: { uk: "За 2–4 тижні відмовтеся від засмаги, солярію й автозасмаги — процедуру проводять лише на незасмаглій шкірі. За 5–7 днів припиніть кислоти та ретиноїди. Повідомте лікаря про прийом фотосенсибілізуючих препаратів, зокрема окремих антибіотиків.", ru: "За 2–4 недели откажитесь от загара, солярия и автозагара — процедуру проводят только на незагорелой коже. За 5–7 дней прекратите кислоты и ретиноиды. Сообщите врачу о приёме фотосенсибилизирующих препаратов, в частности отдельных антибиотиков.", en: "Avoid sun, solariums and self-tanner for two to four weeks — the treatment is performed only on untanned skin. Stop acids and retinoids five to seven days beforehand. Tell the physician about any photosensitising medication, including certain antibiotics." } },
      { q: { uk: "Які обмеження після фотоомолодження?", ru: "Какие ограничения после фотоомоложения?", en: "What restrictions apply after photorejuvenation?" },
        a: { uk: "SPF 50+ щодня протягом щонайменше місяця, без прямого сонця та солярію. Добу уникайте сауни, басейну й інтенсивних тренувань. Оброблені пігментні плями темнішають і сходять самостійно — здирати кірочки не можна.", ru: "SPF 50+ ежедневно в течение как минимум месяца, без прямого солнца и солярия. Сутки избегайте сауны, бассейна и интенсивных тренировок. Обработанные пигментные пятна темнеют и сходят самостоятельно — сдирать корочки нельзя.", en: "SPF 50+ daily for at least a month, with no direct sun or solariums. Avoid saunas, pools and intensive exercise for 24 hours. Treated spots darken and shed on their own — never pick the crusts." } },
      { q: { uk: "Кому не підходить фотоомолодження?", ru: "Кому не подходит фотоомоложение?", en: "Who is not suitable for photorejuvenation?" },
        a: { uk: "Процедуру не проводять на засмаглій шкірі, при вагітності, активних запаленнях і герпесі в зоні обробки, прийомі ізотретиноїну, фотодерматозах та деяких автоімунних станах. Для темних фототипів лікар обирає інші методики.", ru: "Процедуру не проводят на загорелой коже, при беременности, активных воспалениях и герпесе в зоне обработки, приёме изотретиноина, фотодерматозах и некоторых аутоиммунных состояниях. Для тёмных фототипов врач выбирает другие методики.", en: "It is not performed on tanned skin, during pregnancy, with active inflammation or herpes in the area, on isotretinoin, or with photodermatoses and some autoimmune conditions. For darker phototypes the physician selects other methods." } },
      { q: { uk: "Чи допомагає фотоомолодження при розширених порах і тьмяному тоні?", ru: "Помогает ли фотоомоложение при расширенных порах и тусклом тоне?", en: "Does photorejuvenation help with enlarged pores and dull tone?" },
        a: { uk: "Так, IPL вирівнює тон і додає шкірі сяйва вже після перших сеансів, а курс помітно покращує загальну якість шкіри. Для вираженого звуження пор ефективніші фракційні методики — лікар може поєднати їх у межах одного плану.", ru: "Да, IPL выравнивает тон и добавляет коже сияния уже после первых сеансов, а курс заметно улучшает общее качество кожи. Для выраженного сужения пор эффективнее фракционные методики — врач может объединить их в рамках одного плана.", en: "Yes — IPL evens the tone and adds radiance from the first sessions, and a full course noticeably improves overall skin quality. For marked pore refinement, fractional methods work better and can be combined within one plan." } },
    ],
  },
  {
    type: "service",
    slug: "pigmentation-removal",
    items: [
      { q: { uk: "Через що з'являються пігментні плями?", ru: "Из-за чего появляются пигментные пятна?", en: "Why do pigmented spots appear?" },
        a: { uk: "Найчастіша причина — ультрафіолет, який накопичується роками. Далі йдуть гормональні чинники (вагітність, контрацептиви, порушення роботи щитоподібної залози), запалення після акне чи травм і прийом фотосенсибілізуючих препаратів. Тому лікар спершу з'ясовує причину — інакше плями повертаються.", ru: "Самая частая причина — ультрафиолет, который накапливается годами. Далее идут гормональные факторы (беременность, контрацептивы, нарушения работы щитовидной железы), воспаление после акне или травм и приём фотосенсибилизирующих препаратов. Поэтому врач сначала выясняет причину — иначе пятна возвращаются.", en: "The commonest cause is ultraviolet exposure accumulated over years. Then come hormonal factors (pregnancy, contraceptives, thyroid disorders), inflammation after acne or injury, and photosensitising medication. The physician establishes the cause first — otherwise the spots return." } },
      { q: { uk: "Чи можна прибрати мелазму лазером?", ru: "Можно ли убрать мелазму лазером?", en: "Can melasma be removed with a laser?" },
        a: { uk: "Мелазма — окремий випадок, і агресивні методики можуть її погіршити. Тут потрібен обережний підхід: м'які параметри, домашній догляд з освітлювальними засобами, суворий фотозахист і робота з гормональним фоном. Повного «одноразового» видалення не буває, метою є контроль.", ru: "Мелазма — отдельный случай, и агрессивные методики могут её ухудшить. Здесь нужен осторожный подход: мягкие параметры, домашний уход с осветляющими средствами, строгая фотозащита и работа с гормональным фоном. Полного «одноразового» удаления не бывает, целью является контроль.", en: "Melasma is a special case and aggressive treatment can worsen it. It needs a cautious approach: gentle settings, home care with brightening agents, strict photoprotection and attention to hormones. There is no one-off cure — the goal is control." } },
      { q: { uk: "Що робити, щоб пігментація не повернулася?", ru: "Что делать, чтобы пигментация не вернулась?", en: "How can I stop pigmentation from returning?" },
        a: { uk: "Щоденний SPF 50+ навіть узимку та в похмуру погоду, головний убір улітку, антиоксидантний догляд і відмова від солярію. Якщо причина гормональна, потрібен контроль разом з ендокринологом або гінекологом. Без цього нові плями з'являться навіть після ідеально проведеного курсу.", ru: "Ежедневный SPF 50+ даже зимой и в пасмурную погоду, головной убор летом, антиоксидантный уход и отказ от солярия. Если причина гормональная, нужен контроль вместе с эндокринологом или гинекологом. Без этого новые пятна появятся даже после идеально проведённого курса.", en: "Daily SPF 50+, even in winter and cloudy weather, a hat in summer, antioxidant skincare and no solariums. If the cause is hormonal, it needs managing with an endocrinologist or gynaecologist. Without this, new spots appear even after a perfectly executed course." } },
      { q: { uk: "Чи можна видаляти пігментацію на руках і декольте?", ru: "Можно ли удалять пигментацию на руках и декольте?", en: "Can pigmentation on the hands and décolleté be treated?" },
        a: { uk: "Так, це поширений запит — саме ці зони найчастіше видають вік. Шкіра там тонша й відновлюється повільніше, тому лікар працює м'якшими параметрами, а курс може бути на 1–2 сеанси довшим, ніж для обличчя.", ru: "Да, это распространённый запрос — именно эти зоны чаще всего выдают возраст. Кожа там тоньше и восстанавливается медленнее, поэтому врач работает более мягкими параметрами, а курс может быть на 1–2 сеанса длиннее, чем для лица.", en: "Yes, and it is a common request — these areas often reveal age first. The skin is thinner and recovers more slowly, so gentler settings are used and the course may run one or two sessions longer than for the face." } },
    ],
  },
];

seed(batches);
