import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "service",
    slug: "hair-mesotherapy",
    items: [
      { q: { uk: "Що входить до складу коктейлю для мезотерапії волосся?", ru: "Что входит в состав коктейля для мезотерапии волос?", en: "What is in a hair mesotherapy cocktail?" },
        a: { uk: "Склад підбирають індивідуально: зазвичай це вітаміни групи B, біотин, амінокислоти, мікроелементи (цинк, мідь, залізо), пептиди та гіалуронова кислота. Пропорції залежать від причини випадіння й даних аналізів, тому універсального коктейлю не існує.", ru: "Состав подбирают индивидуально: обычно это витамины группы B, биотин, аминокислоты, микроэлементы (цинк, медь, железо), пептиды и гиалуроновая кислота. Пропорции зависят от причины выпадения и данных анализов, поэтому универсального коктейля не существует.", en: "The formula is individual: usually B-group vitamins, biotin, amino acids, trace elements (zinc, copper, iron), peptides and hyaluronic acid. The proportions depend on the cause of the hair loss and your test results, so there is no universal cocktail." } },
      { q: { uk: "Чи можна мити голову після мезотерапії?", ru: "Можно ли мыть голову после мезотерапии?", en: "Can I wash my hair after mesotherapy?" },
        a: { uk: "Мити голову можна через 24 години після сеансу — м'яким шампунем і теплою, не гарячою водою. Того ж дня краще утриматися від сауни, басейну, інтенсивних тренувань і фарбування волосся.", ru: "Мыть голову можно через 24 часа после сеанса — мягким шампунем и тёплой, не горячей водой. В тот же день лучше воздержаться от сауны, бассейна, интенсивных тренировок и окрашивания волос.", en: "You can wash your hair 24 hours after the session, using a mild shampoo and warm rather than hot water. On the day itself, avoid saunas, swimming pools, intensive exercise and hair colouring." } },
      { q: { uk: "Які аналізи варто здати перед курсом проти випадіння волосся?", ru: "Какие анализы стоит сдать перед курсом против выпадения волос?", en: "Which tests should I do before a hair loss course?" },
        a: { uk: "Найчастіше це загальний аналіз крові, феритин і сироваткове залізо, вітамін D, гормони щитоподібної залози, за показаннями — статеві гормони. Випадіння часто є симптомом дефіциту або гормонального збою, і без корекції причини місцева терапія дає нестійкий ефект.", ru: "Чаще всего это общий анализ крови, ферритин и сывороточное железо, витамин D, гормоны щитовидной железы, по показаниям — половые гормоны. Выпадение часто является симптомом дефицита или гормонального сбоя, и без коррекции причины местная терапия даёт нестойкий эффект.", en: "Typically a full blood count, ferritin and serum iron, vitamin D, thyroid hormones and, where indicated, sex hormones. Hair loss is often a symptom of deficiency or hormonal imbalance, and local therapy alone gives unstable results if the cause is untreated." } },
      { q: { uk: "Чи можна поєднувати мезотерапію волосся з PRP-терапією?", ru: "Можно ли сочетать мезотерапию волос с PRP-терапией?", en: "Can hair mesotherapy be combined with PRP therapy?" },
        a: { uk: "Так, це поширена комбінація: мезотерапія забезпечує фолікули нутрієнтами, PRP додає власні фактори росту. Процедури чергують з інтервалом, який визначає лікар — зазвичай 1–2 тижні. Такий протокол дає виразніший результат, ніж кожна методика окремо.", ru: "Да, это распространённая комбинация: мезотерапия обеспечивает фолликулы нутриентами, PRP добавляет собственные факторы роста. Процедуры чередуют с интервалом, который определяет врач — обычно 1–2 недели. Такой протокол даёт более выраженный результат, чем каждая методика по отдельности.", en: "Yes, it is a common pairing: mesotherapy supplies nutrients to the follicles while PRP adds your own growth factors. The sessions are alternated at intervals set by the physician, usually one to two weeks, which gives a stronger result than either alone." } },
    ],
  },
  {
    type: "service",
    slug: "hormonal-balance",
    items: [
      { q: { uk: "Які симптоми вказують на гормональний дисбаланс?", ru: "Какие симптомы указывают на гормональный дисбаланс?", en: "Which symptoms point to a hormonal imbalance?" },
        a: { uk: "Найчастіше це хронічна втома без причини, порушення сну, зміни ваги при незмінному харчуванні, зниження лібідо, дратівливість, випадіння волосся, сухість шкіри, у жінок — збої циклу. Окремо ці ознаки неспецифічні, тому підтвердити або спростувати їх може лише лабораторна діагностика.", ru: "Чаще всего это хроническая усталость без причины, нарушения сна, изменения веса при неизменном питании, снижение либидо, раздражительность, выпадение волос, сухость кожи, у женщин — сбои цикла. По отдельности эти признаки неспецифичны, поэтому подтвердить или опровергнуть их может только лабораторная диагностика.", en: "Most often unexplained fatigue, disturbed sleep, weight changes despite an unchanged diet, reduced libido, irritability, hair loss, dry skin and, in women, cycle irregularities. Individually these signs are non-specific, so only laboratory testing can confirm or exclude an imbalance." } },
      { q: { uk: "Чи працює програма для чоловіків?", ru: "Работает ли программа для мужчин?", en: "Does the programme work for men?" },
        a: { uk: "Так, чоловічий протокол — окремий напрям. Ми оцінюємо загальний і вільний тестостерон, ГЗСГ, естрадіол, пролактин, ЛГ і ФСГ, показники метаболізму та щитоподібної залози. Корекція починається зі способу життя й дефіцитів, а замісна терапія розглядається лише за підтвердженими показаннями.", ru: "Да, мужской протокол — отдельное направление. Мы оцениваем общий и свободный тестостерон, ГСПГ, эстрадиол, пролактин, ЛГ и ФСГ, показатели метаболизма и щитовидной железы. Коррекция начинается с образа жизни и дефицитов, а заместительная терапия рассматривается только при подтверждённых показаниях.", en: "Yes — the male protocol is a distinct track. We assess total and free testosterone, SHBG, oestradiol, prolactin, LH and FSH, along with metabolic and thyroid markers. Correction starts with lifestyle and deficiencies; replacement therapy is considered only on confirmed indications." } },
      { q: { uk: "Чи обов'язкова гормональна терапія в межах програми?", ru: "Обязательна ли гормональная терапия в рамках программы?", en: "Is hormone therapy always part of the programme?" },
        a: { uk: "Ні. У багатьох випадках достатньо корекції сну, харчування, дефіцитів вітамінів і мікроелементів та рівня стресу — показники повертаються до норми без препаратів. Гормональну терапію призначають лише за чіткими показаннями й під регулярним лабораторним контролем.", ru: "Нет. Во многих случаях достаточно коррекции сна, питания, дефицитов витаминов и микроэлементов и уровня стресса — показатели возвращаются к норме без препаратов. Гормональную терапию назначают только по чётким показаниям и под регулярным лабораторным контролем.", en: "No. In many cases correcting sleep, nutrition, vitamin and mineral deficiencies and stress is enough to bring markers back to normal without medication. Hormone therapy is prescribed only on clear indications and with regular laboratory monitoring." } },
    ],
  },
  {
    type: "service",
    slug: "hydrafacial",
    items: [
      { q: { uk: "Кому підходить HydraFacial?", ru: "Кому подходит HydraFacial?", en: "Who is HydraFacial suitable for?" },
        a: { uk: "Практично всім типам шкіри — від зневодненої та чутливої до жирної зі схильністю до комедонів. Насадки й сироватки підбирають під конкретний стан шкіри. Обмеження стосуються активних запалень, герпесу в стадії загострення та пошкодженої шкіри в зоні обробки.", ru: "Практически всем типам кожи — от обезвоженной и чувствительной до жирной со склонностью к комедонам. Насадки и сыворотки подбирают под конкретное состояние кожи. Ограничения касаются активных воспалений, герпеса в стадии обострения и повреждённой кожи в зоне обработки.", en: "Almost every skin type, from dehydrated and sensitive to oily and congestion-prone. Tips and serums are selected for your specific condition. Restrictions apply to active inflammation, a herpes flare or broken skin in the treatment area." } },
      { q: { uk: "Чи є реабілітація після HydraFacial?", ru: "Есть ли реабилитация после HydraFacial?", en: "Is there downtime after HydraFacial?" },
        a: { uk: "Немає. Шкіра одразу виглядає чистішою та зволоженою, макіяж можна нанести того ж дня. Саме тому процедуру часто роблять напередодні важливих подій — вона не дає непередбачуваних реакцій.", ru: "Нет. Кожа сразу выглядит чище и увлажнённее, макияж можно нанести в тот же день. Именно поэтому процедуру часто делают накануне важных событий — она не даёт непредсказуемых реакций.", en: "None. The skin looks cleaner and more hydrated immediately and make-up can be applied the same day. This is why it is often booked before an important event — it produces no unpredictable reactions." } },
      { q: { uk: "Чи допомагає HydraFacial при чорних цятках і розширених порах?", ru: "Помогает ли HydraFacial при чёрных точках и расширенных порах?", en: "Does HydraFacial help with blackheads and enlarged pores?" },
        a: { uk: "Так, вакуумна екстракція м'яко видаляє вміст пор без травматичної механічної чистки. Пори візуально звужуються, шкіра стає рівнішою. При стійких розширених порах лікар може додати лазерні методики для довшого ефекту.", ru: "Да, вакуумная экстракция мягко удаляет содержимое пор без травматичной механической чистки. Поры визуально сужаются, кожа становится ровнее. При стойких расширенных порах врач может добавить лазерные методики для более длительного эффекта.", en: "Yes — vacuum extraction gently clears the pores without traumatic manual cleansing. Pores look tighter and the skin smoother. For persistently enlarged pores the physician may add laser treatments for a longer-lasting effect." } },
      { q: { uk: "Чи можна робити HydraFacial перед важливою подією?", ru: "Можно ли делать HydraFacial перед важным событием?", en: "Can I have HydraFacial before an important event?" },
        a: { uk: "Так, це одна з небагатьох процедур, доречних напередодні. Оптимально запланувати сеанс за 1–3 дні до події: шкіра встигає заспокоїтися, а сяйво тримається кілька днів. Уперше краще прийти хоча б за тиждень — щоб оцінити реакцію шкіри.", ru: "Да, это одна из немногих процедур, уместных накануне. Оптимально запланировать сеанс за 1–3 дня до события: кожа успевает успокоиться, а сияние держится несколько дней. Впервые лучше прийти хотя бы за неделю — чтобы оценить реакцию кожи.", en: "Yes — it is one of the few treatments suitable just beforehand. Ideally book it one to three days before: the skin settles and the glow lasts several days. For a first session, come at least a week ahead so you can see how your skin responds." } },
    ],
  },
  {
    type: "service",
    slug: "intimate-biorevitalisation",
    items: [
      { q: { uk: "Які скарги вирішує інтимна біоревіталізація?", ru: "Какие жалобы решает интимная биоревитализация?", en: "Which concerns does intimate biorevitalisation address?" },
        a: { uk: "Насамперед сухість і печіння слизової, дискомфорт під час близькості, відчуття стягнення та підвищену чутливість до подразнень. Такі скарги часто виникають у менопаузі, після пологів, на тлі гормональної терапії або лікування онкозахворювань.", ru: "Прежде всего сухость и жжение слизистой, дискомфорт во время близости, ощущение стянутости и повышенную чувствительность к раздражениям. Такие жалобы часто возникают в менопаузе, после родов, на фоне гормональной терапии или лечения онкозаболеваний.", en: "Chiefly dryness and burning of the mucosa, discomfort during intimacy, a feeling of tightness and heightened sensitivity to irritation. These complaints are common in menopause, after childbirth, during hormone therapy or after cancer treatment." } },
      { q: { uk: "Скільки процедур потрібно для результату?", ru: "Сколько процедур нужно для результата?", en: "How many sessions are needed?" },
        a: { uk: "Часто достатньо однієї процедури — полегшення відчувається вже за кілька днів. При вираженій атрофії слизової лікар може призначити 2–3 сеанси з інтервалом 3–4 тижні. Схему визначають після огляду.", ru: "Часто достаточно одной процедуры — облегчение чувствуется уже через несколько дней. При выраженной атрофии слизистой врач может назначить 2–3 сеанса с интервалом 3–4 недели. Схему определяют после осмотра.", en: "One session is often enough — relief is usually felt within a few days. With pronounced mucosal atrophy the physician may plan two or three sessions three to four weeks apart. The schedule is set after examination." } },
      { q: { uk: "Які обмеження після процедури?", ru: "Какие ограничения после процедуры?", en: "What restrictions apply afterwards?" },
        a: { uk: "Протягом 5–7 днів утримайтеся від статевих контактів, басейну, сауни, гарячої ванни та інтенсивних тренувань. Носіть вільну білизну з натуральних тканин. Усі індивідуальні рекомендації лікар дає одразу після процедури.", ru: "В течение 5–7 дней воздержитесь от половых контактов, бассейна, сауны, горячей ванны и интенсивных тренировок. Носите свободное бельё из натуральных тканей. Все индивидуальные рекомендации врач даёт сразу после процедуры.", en: "For 5–7 days avoid intercourse, swimming pools, saunas, hot baths and intensive exercise, and wear loose natural-fibre underwear. The physician gives individual aftercare instructions immediately after the treatment." } },
      { q: { uk: "Чи можна поєднувати процедуру з лазерним інтимним омолодженням?", ru: "Можно ли сочетать процедуру с лазерным интимным омоложением?", en: "Can it be combined with intimate laser rejuvenation?" },
        a: { uk: "Так, методики працюють у різних площинах: лазер стимулює вироблення власного колагену, гіалуронова кислота одразу дає зволоження. Зазвичай їх розводять у часі — інтервал визначає лікар за станом тканин, найчастіше 2–4 тижні.", ru: "Да, методики работают в разных плоскостях: лазер стимулирует выработку собственного коллагена, гиалуроновая кислота сразу даёт увлажнение. Обычно их разводят во времени — интервал определяет врач по состоянию тканей, чаще всего 2–4 недели.", en: "Yes — they work in different ways: the laser stimulates your own collagen, while hyaluronic acid provides immediate hydration. They are usually spaced apart, most often by two to four weeks, as decided by the physician." } },
    ],
  },
  {
    type: "service",
    slug: "intimate-whitening",
    items: [
      { q: { uk: "Скільки процедур потрібно для вирівнювання тону?", ru: "Сколько процедур нужно для выравнивания тона?", en: "How many sessions are needed to even out the tone?" },
        a: { uk: "Зазвичай курс складається з 2–3 процедур з інтервалом 4–6 тижнів. Перші зміни помітні вже після першого сеансу, а фінальний результат оцінюють через місяць після завершення курсу. Кількість сеансів залежить від вираженості пігментації.", ru: "Обычно курс состоит из 2–3 процедур с интервалом 4–6 недель. Первые изменения заметны уже после первого сеанса, а финальный результат оценивают через месяц после завершения курса. Количество сеансов зависит от выраженности пигментации.", en: "A course usually consists of two or three sessions four to six weeks apart. Changes are visible after the first session, with the final result assessed a month after the course ends. The number depends on how pronounced the pigmentation is." } },
      { q: { uk: "Через що темніє шкіра в інтимній зоні?", ru: "Из-за чего темнеет кожа в интимной зоне?", en: "Why does skin in the intimate area darken?" },
        a: { uk: "Найчастіші причини — тертя об тісний одяг, гоління та депіляція, післязапальна пігментація, гормональні зміни й надлишкова вага. Тому поряд із процедурою лікар обговорює й побутові чинники: без них пігментація повертається.", ru: "Самые частые причины — трение о тесную одежду, бритьё и депиляция, поствоспалительная пигментация, гормональные изменения и избыточный вес. Поэтому наряду с процедурой врач обсуждает и бытовые факторы: без этого пигментация возвращается.", en: "The commonest causes are friction from tight clothing, shaving and depilation, post-inflammatory pigmentation, hormonal changes and excess weight. That is why the physician also addresses everyday factors — without that, the pigmentation returns." } },
      { q: { uk: "Чи є протипоказання до лазерного відбілювання інтимних зон?", ru: "Есть ли противопоказания к лазерному отбеливанию интимных зон?", en: "Are there contraindications to intimate laser lightening?" },
        a: { uk: "Так: вагітність і лактація, гострі запальні процеси та інфекції в зоні обробки, герпес у стадії загострення, схильність до келоїдних рубців, прийом ізотретиноїну, свіжа засмага. Лікар-гінеколог перевіряє всі пункти на консультації перед процедурою.", ru: "Да: беременность и лактация, острые воспалительные процессы и инфекции в зоне обработки, герпес в стадии обострения, склонность к келоидным рубцам, приём изотретиноина, свежий загар. Врач-гинеколог проверяет все пункты на консультации перед процедурой.", en: "Yes: pregnancy and breastfeeding, acute inflammation or infection in the area, an active herpes flare, a tendency to keloid scarring, isotretinoin treatment and fresh tanning. The gynaecologist checks all of these at the consultation." } },
      { q: { uk: "Чи потрібна підготовка до процедури?", ru: "Нужна ли подготовка к процедуре?", en: "Is any preparation required?" },
        a: { uk: "За 5–7 днів до сеансу утримайтеся від гоління, воскової депіляції та скрабів у зоні обробки, за 2 тижні — від засмаги. У день процедури приходьте без косметичних засобів на шкірі. Гінеколог проводить огляд, щоб виключити запальні процеси.", ru: "За 5–7 дней до сеанса воздержитесь от бритья, восковой депиляции и скрабов в зоне обработки, за 2 недели — от загара. В день процедуры приходите без косметических средств на коже. Гинеколог проводит осмотр, чтобы исключить воспалительные процессы.", en: "Avoid shaving, waxing and scrubs in the area for 5–7 days beforehand, and sun exposure for two weeks. Come with no cosmetic products on the skin on the day. The gynaecologist examines you first to rule out inflammation." } },
    ],
  },
  {
    type: "service",
    slug: "intimate-zone-biorevitalisation",
    items: [
      { q: { uk: "Чи болісна біоревіталізація інтимної зони?", ru: "Болезненна ли биоревитализация интимной зоны?", en: "Is biorevitalisation of the intimate area painful?" },
        a: { uk: "Аплікаційну анестезію наносять за 20–30 хвилин до початку, тому ін'єкції відчуваються як тиск і легке поколювання. Багато препаратів додатково містять лідокаїн. Уся процедура триває близько 20–30 хвилин.", ru: "Аппликационную анестезию наносят за 20–30 минут до начала, поэтому инъекции ощущаются как давление и лёгкое покалывание. Многие препараты дополнительно содержат лидокаин. Вся процедура занимает около 20–30 минут.", en: "Topical anaesthetic is applied 20–30 minutes beforehand, so the injections feel like pressure and mild tingling. Many products also contain lidocaine. The whole procedure takes about 20–30 minutes." } },
      { q: { uk: "Чи допомагає процедура після пологів?", ru: "Помогает ли процедура после родов?", en: "Does the treatment help after childbirth?" },
        a: { uk: "Так, це поширений запит: гіалуронова кислота покращує якість тканин, робить рубці м'якшими й повертає тургор. Процедуру проводять після завершення лактації та відновлення циклу — зазвичай не раніше ніж через 6–8 місяців після пологів.", ru: "Да, это распространённый запрос: гиалуроновая кислота улучшает качество тканей, делает рубцы мягче и возвращает тургор. Процедуру проводят после завершения лактации и восстановления цикла — обычно не ранее чем через 6–8 месяцев после родов.", en: "Yes, it is a common request: hyaluronic acid improves tissue quality, softens scars and restores turgor. It is performed after breastfeeding has ended and the cycle has returned — usually no earlier than six to eight months post partum." } },
      { q: { uk: "Хто виконує процедуру?", ru: "Кто выполняет процедуру?", en: "Who performs the procedure?" },
        a: { uk: "Процедуру виконує лікар-гінеколог після огляду та виключення запальних процесів. Це принципово: робота із зовнішніми статевими органами потребує знання анатомії зони й уміння оцінити стан тканин, а не лише навички ін'єкцій.", ru: "Процедуру выполняет врач-гинеколог после осмотра и исключения воспалительных процессов. Это принципиально: работа с наружными половыми органами требует знания анатомии зоны и умения оценить состояние тканей, а не только навыка инъекций.", en: "It is performed by a gynaecologist after an examination that rules out inflammation. This matters: working with the external genitalia requires knowledge of the anatomy and the ability to assess tissue, not just injection technique." } },
      { q: { uk: "Чи є вікові обмеження для процедури?", ru: "Есть ли возрастные ограничения для процедуры?", en: "Are there age limits for this treatment?" },
        a: { uk: "Процедуру проводять повнолітнім пацієнткам. Верхньої вікової межі немає — у зрілому віці й менопаузі запит на відновлення тургору тканин навіть частіший. Рішення завжди ухвалює лікар за станом тканин, а не за віком у паспорті.", ru: "Процедуру проводят совершеннолетним пациенткам. Верхней возрастной границы нет — в зрелом возрасте и менопаузе запрос на восстановление тургора тканей даже чаще. Решение всегда принимает врач по состоянию тканей, а не по возрасту в паспорте.", en: "It is performed on adult patients only. There is no upper age limit — in later life and menopause the need to restore tissue turgor is if anything more common. The decision is based on tissue condition, not on age." } },
    ],
  },
  {
    type: "service",
    slug: "iv-therapy",
    items: [
      { q: { uk: "Чи є протипоказання до IV-терапії?", ru: "Есть ли противопоказания к IV-терапии?", en: "Are there contraindications to IV therapy?" },
        a: { uk: "Так: вагітність і лактація без окремого призначення, ниркова та серцева недостатність, гострі інфекційні стани, онкологія в активній фазі, алергія на компоненти коктейлю. Тому перед першою інфузією лікар проводить консультацію та за потреби призначає аналізи.", ru: "Да: беременность и лактация без отдельного назначения, почечная и сердечная недостаточность, острые инфекционные состояния, онкология в активной фазе, аллергия на компоненты коктейля. Поэтому перед первой инфузией врач проводит консультацию и при необходимости назначает анализы.", en: "Yes: pregnancy and breastfeeding without specific indication, kidney or heart failure, acute infection, active oncological disease and allergy to any component. This is why the first infusion is always preceded by a consultation and, if needed, tests." } },
      { q: { uk: "Чим внутрішньовенне введення краще за вітаміни в таблетках?", ru: "Чем внутривенное введение лучше витаминов в таблетках?", en: "Why choose an infusion over oral vitamins?" },
        a: { uk: "При інфузії речовини потрапляють одразу в кровотік, оминаючи травний тракт, — біодоступність близька до 100%, тоді як при пероральному прийомі засвоюється лише частина. Це важливо при порушеннях всмоктування або коли потрібен швидкий ефект. У багатьох випадках достатньо таблетованих форм — вибір робить лікар.", ru: "При инфузии вещества попадают сразу в кровоток, минуя пищеварительный тракт, — биодоступность близка к 100%, тогда как при пероральном приёме усваивается лишь часть. Это важно при нарушениях всасывания или когда нужен быстрый эффект. Во многих случаях достаточно таблетированных форм — выбор делает врач.", en: "An infusion delivers nutrients straight into the bloodstream, bypassing the gut, so bioavailability is close to 100%, whereas only part of an oral dose is absorbed. This matters with absorption problems or when a fast effect is needed. In many cases oral forms are sufficient — the physician decides." } },
    ],
  },
];

seed(batches);
