import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "service",
    slug: "ultraformer-mpt-body",
    items: [
      { q: { uk: "Кому підходить Ultraformer MPT для тіла?", ru: "Кому подходит Ultraformer MPT для тела?", en: "Who is Ultraformer MPT for the body suitable for?" },
        a: { uk: "Тим, у кого шкіра втратила пружність після схуднення, вагітності або з віком: м'який живіт, в'яла шкіра внутрішньої поверхні стегон і рук. Методика працює саме зі шкірою — жир вона не прибирає, для цього є інші технології.", ru: "Тем, у кого кожа потеряла упругость после похудения, беременности или с возрастом: мягкий живот, дряблая кожа внутренней поверхности бёдер и рук. Методика работает именно с кожей — жир она не убирает, для этого есть другие технологии.", en: "Those whose skin has lost firmness after weight loss, pregnancy or with age: a soft abdomen, lax skin on the inner thighs and arms. It works on the skin itself — it does not remove fat, which other technologies address." } },
      { q: { uk: "Скільки процедур потрібно для тіла?", ru: "Сколько процедур нужно для тела?", en: "How many body sessions are needed?" },
        a: { uk: "Для більшості зон достатньо однієї процедури з повторенням раз на рік. При вираженій в'ялості шкіри лікар може рекомендувати другий сеанс через 3 місяці — коли завершиться перший етап синтезу колагену й буде видно реальний результат.", ru: "Для большинства зон достаточно одной процедуры с повторением раз в год. При выраженной дряблости кожи врач может рекомендовать второй сеанс через 3 месяца — когда завершится первый этап синтеза коллагена и будет виден реальный результат.", en: "For most areas one session a year is enough. With pronounced laxity the physician may suggest a second session after three months, once the first phase of collagen synthesis is complete and the true result is visible." } },
    ],
  },
  {
    type: "service",
    slug: "ultrasound",
    items: [
      { q: { uk: "Які види УЗД можна пройти в GENEVITY?", ru: "Какие виды УЗИ можно пройти в GENEVITY?", en: "Which ultrasound examinations are available at GENEVITY?" },
        a: { uk: "УЗД органів черевної порожнини та нирок, щитоподібної залози, молочних залоз, органів малого таза, судин, суглобів і м'яких тканин, а також еластографію. Дослідження виконують на експертному апараті GE LOGIQ E10.", ru: "УЗИ органов брюшной полости и почек, щитовидной железы, молочных желёз, органов малого таза, сосудов, суставов и мягких тканей, а также эластографию. Исследования выполняют на экспертном аппарате GE LOGIQ E10.", en: "Ultrasound of the abdomen and kidneys, thyroid, breasts, pelvic organs, vessels, joints and soft tissue, plus elastography. Examinations are performed on the expert-class GE LOGIQ E10 system." } },
      { q: { uk: "Скільки триває УЗД-обстеження?", ru: "Сколько длится УЗИ-обследование?", en: "How long does an ultrasound examination take?" },
        a: { uk: "Одна зона займає 15–20 хвилин, комплексне обстеження кількох органів — 30–40 хвилин. Висновок ви отримуєте одразу після дослідження, лікар пояснює його на місці.", ru: "Одна зона занимает 15–20 минут, комплексное обследование нескольких органов — 30–40 минут. Заключение вы получаете сразу после исследования, врач объясняет его на месте.", en: "A single area takes 15–20 minutes; a comprehensive examination of several organs, 30–40 minutes. You receive the report immediately and the physician explains it on the spot." } },
      { q: { uk: "Як підготуватися до УЗД органів малого таза?", ru: "Как подготовиться к УЗИ органов малого таза?", en: "How should I prepare for a pelvic ultrasound?" },
        a: { uk: "Для трансабдомінального дослідження потрібен наповнений сечовий міхур — випийте 0,5–1 л води за годину до візиту. Для трансвагінального навпаки: міхур має бути порожнім. Оптимальний час — 5–10 день циклу, якщо лікар не призначив інакше.", ru: "Для трансабдоминального исследования нужен наполненный мочевой пузырь — выпейте 0,5–1 л воды за час до визита. Для трансвагинального наоборот: пузырь должен быть пустым. Оптимальное время — 5–10 день цикла, если врач не назначил иначе.", en: "For a transabdominal scan the bladder must be full — drink 0.5–1 litre of water an hour before. For a transvaginal scan the bladder should be empty. Days 5–10 of the cycle are ideal unless your physician advises otherwise." } },
      { q: { uk: "Чи безпечне УЗД і як часто його можна робити?", ru: "Безопасно ли УЗИ и как часто его можно делать?", en: "Is ultrasound safe, and how often can it be repeated?" },
        a: { uk: "УЗД не використовує іонізуючого випромінювання, тому безпечне й не має обмежень за кількістю досліджень — його проводять навіть вагітним. Частоту визначає клінічна потреба: для профілактики зазвичай достатньо раз на рік.", ru: "УЗИ не использует ионизирующего излучения, поэтому безопасно и не имеет ограничений по количеству исследований — его проводят даже беременным. Частоту определяет клиническая необходимость: для профилактики обычно достаточно раза в год.", en: "Ultrasound uses no ionising radiation, so it is safe and there is no limit on how often it can be repeated — it is used even in pregnancy. Frequency is driven by clinical need; once a year is usually enough for screening." } },
      { q: { uk: "Що робити, якщо на УЗД виявили відхилення?", ru: "Что делать, если на УЗИ выявили отклонения?", en: "What happens if the ultrasound finds something?" },
        a: { uk: "Лікар УЗД пояснює знахідку одразу й рекомендує наступний крок. Далі можна записатися до профільного спеціаліста центру — ендокринолога, гінеколога, гастроентеролога чи уролога — і за потреби здати аналізи в той самий день.", ru: "Врач УЗИ объясняет находку сразу и рекомендует следующий шаг. Далее можно записаться к профильному специалисту центра — эндокринологу, гинекологу, гастроэнтерологу или урологу — и при необходимости сдать анализы в тот же день.", en: "The sonographer explains the finding immediately and advises the next step. You can then book with the relevant specialist at the centre — endocrinologist, gynaecologist, gastroenterologist or urologist — and have any tests the same day." } },
    ],
  },
  {
    type: "service",
    slug: "ultrasound-diagnostician",
    items: [
      { q: { uk: "Як записатися на прийом до лікаря УЗД?", ru: "Как записаться на приём к врачу УЗИ?", en: "How do I book an appointment with the sonographer?" },
        a: { uk: "Записатися можна онлайн на сайті, за телефонами +380 73 000 0150 і +380 93 000 0150 або в Instagram @genevity.center. Під час запису вкажіть, яке дослідження потрібне — адміністратор надішле рекомендації щодо підготовки.", ru: "Записаться можно онлайн на сайте, по телефонам +380 73 000 0150 и +380 93 000 0150 или в Instagram @genevity.center. При записи укажите, какое исследование нужно — администратор пришлёт рекомендации по подготовке.", en: "Book online on the website, by phone on +380 73 000 0150 or +380 93 000 0150, or via Instagram @genevity.center. Say which examination you need and the administrator will send the preparation instructions." } },
      { q: { uk: "Чи можна пройти кілька досліджень за один візит?", ru: "Можно ли пройти несколько исследований за один визит?", en: "Can several examinations be done in one visit?" },
        a: { uk: "Так, і це зручно — наприклад, УЗД черевної порожнини разом із нирками та щитоподібною залозою. Важливо врахувати підготовку: частина досліджень потребує голодування, інші — наповненого сечового міхура. Адміністратор допоможе скласти правильну послідовність.", ru: "Да, и это удобно — например, УЗИ брюшной полости вместе с почками и щитовидной железой. Важно учесть подготовку: часть исследований требует голодания, другие — наполненного мочевого пузыря. Администратор поможет составить правильную последовательность.", en: "Yes, and it is convenient — for example an abdominal scan together with kidneys and thyroid. Preparation matters: some scans need fasting, others a full bladder. The administrator will arrange the right sequence." } },
      { q: { uk: "На якому обладнанні працює лікар УЗД?", ru: "На каком оборудовании работает врач УЗИ?", en: "What equipment does the sonographer use?" },
        a: { uk: "Дослідження проводять на апараті експертного класу GE LOGIQ E10 із набором датчиків для різних зон і можливістю еластографії. Це дозволяє оцінювати не лише структуру тканини, а і її щільність — важливо, зокрема, при вузлах щитоподібної залози.", ru: "Исследования проводят на аппарате экспертного класса GE LOGIQ E10 с набором датчиков для разных зон и возможностью эластографии. Это позволяет оценивать не только структуру ткани, но и её плотность — важно, в частности, при узлах щитовидной железы.", en: "Examinations are performed on an expert-class GE LOGIQ E10 with a range of probes and elastography. This allows assessment not only of tissue structure but also of stiffness — important, for example, with thyroid nodules." } },
      { q: { uk: "Чи потрібно готуватися до УЗД щитоподібної залози?", ru: "Нужно ли готовиться к УЗИ щитовидной железы?", en: "Is preparation needed for a thyroid ultrasound?" },
        a: { uk: "Ні, спеціальної підготовки немає — приходьте в зручний час. Бажано вдягнути одяг із вільним вирізом і зняти прикраси з шиї. Якщо у вас є попередні протоколи УЗД, візьміть їх — лікарю важливо бачити динаміку.", ru: "Нет, специальной подготовки нет — приходите в удобное время. Желательно надеть одежду со свободным вырезом и снять украшения с шеи. Если у вас есть предыдущие протоколы УЗИ, возьмите их — врачу важно видеть динамику.", en: "No special preparation is needed — come whenever suits you. Wear something with an open neckline and remove necklaces. Bring any previous ultrasound reports: seeing the change over time matters." } },
      { q: { uk: "Чи виконує лікар УЗД дослідження за направленням від інших клінік?", ru: "Выполняет ли врач УЗИ исследования по направлению из других клиник?", en: "Does the sonographer accept referrals from other clinics?" },
        a: { uk: "Так. Візьміть направлення із собою — лікар врахує клінічне питання, на яке потрібно відповісти, і зробить акцент саме на ньому. Висновок ви отримаєте у день обстеження й зможете передати своєму лікарю.", ru: "Да. Возьмите направление с собой — врач учтёт клинический вопрос, на который нужно ответить, и сделает акцент именно на нём. Заключение вы получите в день обследования и сможете передать своему врачу.", en: "Yes. Bring the referral with you — the physician will focus on the clinical question it raises. You receive the report on the day of the scan and can pass it to your own doctor." } },
    ],
  },
  {
    type: "service",
    slug: "underarm-botulinum",
    items: [
      { q: { uk: "Як проходить процедура від пітливості під пахвами?", ru: "Как проходит процедура от потливости под мышками?", en: "What happens during the underarm sweating treatment?" },
        a: { uk: "Лікар визначає зону підвищеного потовиділення, обробляє шкіру антисептиком і виконує серію поверхневих мікроін'єкцій. Уся процедура триває близько 30 хвилин разом із підготовкою. Анестезія зазвичай не потрібна — голки дуже тонкі.", ru: "Врач определяет зону повышенного потоотделения, обрабатывает кожу антисептиком и выполняет серию поверхностных микроинъекций. Вся процедура занимает около 30 минут вместе с подготовкой. Анестезия обычно не нужна — иглы очень тонкие.", en: "The physician maps the area of excess sweating, cleanses the skin and performs a series of superficial micro-injections. The whole appointment takes about 30 minutes including preparation. Anaesthesia is usually unnecessary — the needles are very fine." } },
      { q: { uk: "Які обмеження після процедури?", ru: "Какие ограничения после процедуры?", en: "What restrictions apply afterwards?" },
        a: { uk: "Добу не наносьте дезодорант і не робіть депіляцію зони, 48 годин уникайте сауни, спортзалу та гарячої ванни. Того ж дня можна повертатися до роботи — процедура не залишає слідів.", ru: "Сутки не наносите дезодорант и не делайте депиляцию зоны, 48 часов избегайте сауны, спортзала и горячей ванны. В тот же день можно возвращаться к работе — процедура не оставляет следов.", en: "Avoid deodorant and hair removal in the area for 24 hours, and saunas, the gym and hot baths for 48. You can return to work the same day — the treatment leaves no visible marks." } },
      { q: { uk: "Чи потрібні аналізи перед процедурою?", ru: "Нужны ли анализы перед процедурой?", en: "Are tests needed before the procedure?" },
        a: { uk: "Зазвичай ні. Але якщо надмірна пітливість з'явилася раптово, супроводжується втратою ваги, серцебиттям чи нічною пітливістю, лікар спершу порекомендує обстеження — це може бути ознакою порушення роботи щитоподібної залози чи іншого стану.", ru: "Обычно нет. Но если избыточная потливость появилась внезапно, сопровождается потерей веса, сердцебиением или ночной потливостью, врач сначала порекомендует обследование — это может быть признаком нарушения работы щитовидной железы или другого состояния.", en: "Usually not. But if the sweating started suddenly or comes with weight loss, palpitations or night sweats, the physician will suggest investigation first — it can signal a thyroid or other underlying condition." } },
      { q: { uk: "Чи допомагає ботулінотерапія при пітливості долонь і стоп?", ru: "Помогает ли ботулинотерапия при потливости ладоней и стоп?", en: "Does botulinum therapy help with sweaty palms and feet?" },
        a: { uk: "Так, механізм той самий, але ці зони чутливіші, тому процедуру проводять із додатковим знеболенням і вона триває довше. Доцільність та обсяг лікар визначає на консультації після огляду.", ru: "Да, механизм тот же, но эти зоны чувствительнее, поэтому процедуру проводят с дополнительным обезболиванием и она длится дольше. Целесообразность и объём врач определяет на консультации после осмотра.", en: "Yes, the mechanism is the same, but these areas are more sensitive, so extra anaesthesia is used and the session takes longer. The physician assesses suitability and scope at the consultation." } },
    ],
  },
  {
    type: "service",
    slug: "volnewmer",
    items: [
      { q: { uk: "Кому підходить процедура VOLNEWMER?", ru: "Кому подходит процедура VOLNEWMER?", en: "Who is VOLNEWMER suitable for?" },
        a: { uk: "Тим, хто хоче ущільнити шкіру й підтягнути контур без голок і періоду відновлення. Методика доречна від 30 років для профілактики та після 40 — для роботи з втратою щільності. Її часто обирають пацієнти з чутливою шкірою чи страхом ін'єкцій.", ru: "Тем, кто хочет уплотнить кожу и подтянуть контур без игл и периода восстановления. Методика уместна с 30 лет для профилактики и после 40 — для работы с потерей плотности. Её часто выбирают пациенты с чувствительной кожей или страхом инъекций.", en: "Those who want firmer skin and a lifted contour without needles or downtime. It suits preventive care from 30 and, after 40, work on lost density. It is often chosen by patients with sensitive skin or a fear of injections." } },
      { q: { uk: "Скільки сеансів VOLNEWMER потрібно?", ru: "Сколько сеансов VOLNEWMER нужно?", en: "How many VOLNEWMER sessions are needed?" },
        a: { uk: "Стандартний курс — 3–4 процедури з інтервалом 2–4 тижні. Зволоження й сяйво помітні вже після першого сеансу, а ущільнення шкіри розвивається поступово протягом наступних місяців. Підтримувальні процедури — 1–2 рази на рік.", ru: "Стандартный курс — 3–4 процедуры с интервалом 2–4 недели. Увлажнение и сияние заметны уже после первого сеанса, а уплотнение кожи развивается постепенно в течение следующих месяцев. Поддерживающие процедуры — 1–2 раза в год.", en: "A standard course is three to four sessions two to four weeks apart. Hydration and radiance are visible after the first session, while firming develops over the following months. Maintenance sessions are advised once or twice a year." } },
      { q: { uk: "Чи є протипоказання до VOLNEWMER?", ru: "Есть ли противопоказания к VOLNEWMER?", en: "Are there contraindications to VOLNEWMER?" },
        a: { uk: "Так: вагітність і лактація, кардіостимулятор або інші електронні імплантати, металеві конструкції в зоні обробки, епілепсія, онкологічні захворювання в активній фазі, активні запалення шкіри. Анамнез перевіряють перед курсом.", ru: "Да: беременность и лактация, кардиостимулятор или другие электронные имплантаты, металлические конструкции в зоне обработки, эпилепсия, онкологические заболевания в активной фазе, активные воспаления кожи. Анамнез проверяют перед курсом.", en: "Yes: pregnancy and breastfeeding, a pacemaker or other electronic implants, metal hardware in the treated area, epilepsy, active oncological disease and active skin inflammation. Your history is checked before the course." } },
      { q: { uk: "Чи є обмеження одразу після сеансу?", ru: "Есть ли ограничения сразу после сеанса?", en: "Are there restrictions right after a session?" },
        a: { uk: "Практично немає: легке почервоніння минає за 1–2 години, макіяж можна наносити того ж дня. Добу варто утриматися від сауни й інтенсивних тренувань, а SPF використовувати щодня — це стандартна рекомендація в будь-яку пору року.", ru: "Практически нет: лёгкое покраснение проходит за 1–2 часа, макияж можно наносить в тот же день. Сутки стоит воздержаться от сауны и интенсивных тренировок, а SPF использовать ежедневно — это стандартная рекомендация в любое время года.", en: "Almost none: slight redness settles within an hour or two and make-up can be applied the same day. Avoid saunas and intensive exercise for 24 hours, and use SPF daily — standard advice all year round." } },
    ],
  },
];

seed(batches);
