import { seed, type Batch } from "./run";

const batches: Batch[] = [
  {
    type: "service",
    slug: "jaw-contouring",
    items: [
      { q: { uk: "Кому підходить контурна пластика кутів щелепи?", ru: "Кому подходит контурная пластика углов челюсти?", en: "Who is jawline contouring suitable for?" },
        a: { uk: "Тим, у кого від природи слабко виражена нижня щелепа, розмитий овал або асиметрія профілю, а також коли з віком контур втратив чіткість. Методика працює і для чоловіків, які хочуть виразнішу лінію щелепи. Придатність оцінює лікар за анатомією обличчя.", ru: "Тем, у кого от природы слабо выражена нижняя челюсть, размытый овал или асимметрия профиля, а также когда с возрастом контур потерял чёткость. Методика работает и для мужчин, желающих более выразительную линию челюсти. Пригодность оценивает врач по анатомии лица.", en: "Those with a naturally soft jawline, a blurred contour or profile asymmetry, and anyone whose definition has faded with age. It also suits men who want a stronger jaw. The physician assesses suitability from your facial anatomy." } },
      { q: { uk: "Наскільки болісна процедура?", ru: "Насколько болезненна процедура?", en: "How painful is the procedure?" },
        a: { uk: "Перед введенням наносять аплікаційну анестезію, а більшість щільних філерів містять лідокаїн. Відчуття описують як тиск у зоні введення, а не гострий біль. Сама процедура триває 30–40 хвилин.", ru: "Перед введением наносят аппликационную анестезию, а большинство плотных филлеров содержат лидокаин. Ощущения описывают как давление в зоне введения, а не острую боль. Сама процедура занимает 30–40 минут.", en: "Topical anaesthetic is applied first and most firm fillers contain lidocaine. Patients describe pressure rather than sharp pain. The procedure itself takes 30–40 minutes." } },
      { q: { uk: "Які обмеження після контурної пластики щелепи?", ru: "Какие ограничения после контурной пластики челюсти?", en: "What restrictions apply after jawline filler?" },
        a: { uk: "Протягом 48 годин уникайте спорту, сауни, алкоголю та сну обличчям у подушку. Два тижні не робіть масаж обличчя й апаратні процедури в цій зоні. Стоматологічні втручання краще планувати до процедури або через 2 тижні після неї.", ru: "В течение 48 часов избегайте спорта, сауны, алкоголя и сна лицом в подушку. Две недели не делайте массаж лица и аппаратные процедуры в этой зоне. Стоматологические вмешательства лучше планировать до процедуры или через 2 недели после неё.", en: "For 48 hours avoid exercise, saunas, alcohol and sleeping face-down. For two weeks avoid facial massage and device treatments in the area. Dental work is best scheduled before the treatment or at least two weeks after." } },
      { q: { uk: "Чи не зробить філер обличчя важчим?", ru: "Не сделает ли филлер лицо тяжелее?", en: "Will filler make my face look heavier?" },
        a: { uk: "За коректної техніки — навпаки: чіткіша лінія щелепи візуально підтягує нижню третину й робить овал стрункішим. Ефект «важкого» обличчя виникає при надлишкових об'ємах або введенні в неправильну площину, тому ми працюємо поетапно й з контрольним оглядом.", ru: "При корректной технике — наоборот: более чёткая линия челюсти визуально подтягивает нижнюю треть и делает овал стройнее. Эффект «тяжёлого» лица возникает при избыточных объёмах или введении в неправильную плоскость, поэтому мы работаем поэтапно и с контрольным осмотром.", en: "With correct technique the opposite is true: a defined jawline visually lifts the lower third and slims the contour. A heavy look comes from excessive volume or placement in the wrong plane, which is why we work in stages with a follow-up review." } },
    ],
  },
  {
    type: "service",
    slug: "juvederm",
    items: [
      { q: { uk: "Чим Juvederm відрізняється від інших філерів?", ru: "Чем Juvederm отличается от других филлеров?", en: "How does Juvederm differ from other fillers?" },
        a: { uk: "Juvederm виготовляють за технологією Vycross, яка забезпечує однорідну гладку структуру гелю та передбачувану поведінку в тканинах. Лінійка охоплює препарати різної щільності — від зволожувальних до об'ємоутворювальних. Це дозволяє працювати різними зонами одним протоколом.", ru: "Juvederm изготавливают по технологии Vycross, которая обеспечивает однородную гладкую структуру геля и предсказуемое поведение в тканях. Линейка охватывает препараты разной плотности — от увлажняющих до объёмообразующих. Это позволяет работать разными зонами в одном протоколе.", en: "Juvederm uses Vycross technology, giving a smooth, homogeneous gel that behaves predictably in the tissue. The range spans densities from hydrating to volumising, so several areas can be treated within one protocol." } },
      { q: { uk: "Чи є протипоказання до ін'єкцій Juvederm?", ru: "Есть ли противопоказания к инъекциям Juvederm?", en: "Are there contraindications to Juvederm injections?" },
        a: { uk: "Так: вагітність і лактація, автоімунні захворювання в загостренні, порушення згортання крові, запалення або герпес у зоні введення, алергія на гіалуронову кислоту чи лідокаїн. Лікар перевіряє анамнез перед кожною процедурою.", ru: "Да: беременность и лактация, аутоиммунные заболевания в обострении, нарушения свёртывания крови, воспаление или герпес в зоне введения, аллергия на гиалуроновую кислоту или лидокаин. Врач проверяет анамнез перед каждой процедурой.", en: "Yes: pregnancy and breastfeeding, autoimmune disease in flare, clotting disorders, inflammation or herpes at the injection site, and allergy to hyaluronic acid or lidocaine. The physician reviews your history before every treatment." } },
      { q: { uk: "Коли можна повторити процедуру?", ru: "Когда можно повторить процедуру?", en: "When can the treatment be repeated?" },
        a: { uk: "Корекцію за потреби роблять через 2–4 тижні після першого введення, коли набряк повністю зійшов і результат стабілізувався. Повторну процедуру планують, коли препарат починає розсмоктуватися — залежно від серії та зони це 6–24 місяці.", ru: "Коррекцию при необходимости делают через 2–4 недели после первого введения, когда отёк полностью сошёл и результат стабилизировался. Повторную процедуру планируют, когда препарат начинает рассасываться — в зависимости от серии и зоны это 6–24 месяца.", en: "A top-up, if needed, is done 2–4 weeks after the first treatment, once swelling has resolved and the result has settled. A full repeat is scheduled as the product breaks down — 6–24 months depending on the range and area." } },
      { q: { uk: "Чи виглядатиме результат природно?", ru: "Будет ли результат выглядеть естественно?", en: "Will the result look natural?" },
        a: { uk: "Так, якщо об'єм відповідає анатомії. Ми не «наздоганяємо» модні пропорції, а працюємо з вашими рисами: відновлюємо втрачені об'єми там, де вони були, і залишаємо міміку живою. Краще додати на корекції, ніж перевантажити зону одразу.", ru: "Да, если объём соответствует анатомии. Мы не «догоняем» модные пропорции, а работаем с вашими чертами: восстанавливаем утраченные объёмы там, где они были, и оставляем мимику живой. Лучше добавить на коррекции, чем перегрузить зону сразу.", en: "Yes, provided the volume respects your anatomy. We do not chase trends: we restore volume where it has been lost and keep expression intact. It is always better to add at a top-up than to overfill in one sitting." } },
    ],
  },
  {
    type: "service",
    slug: "laser-bikini",
    items: [
      { q: { uk: "Чим глибоке бікіні відрізняється від класичного?", ru: "Чем глубокое бикини отличается от классического?", en: "What is the difference between a Brazilian and a classic bikini area?" },
        a: { uk: "Класичне бікіні — це зона, що виходить за межі білизни. Глибоке бікіні охоплює всю зону повністю, включно з міжсідничною складкою. Від обраного варіанта залежать час процедури й вартість — уточніть їх під час запису.", ru: "Классическое бикини — это зона, выходящая за пределы белья. Глубокое бикини охватывает всю зону полностью, включая межъягодичную складку. От выбранного варианта зависят время процедуры и стоимость — уточните их при записи.", en: "A classic bikini covers the area outside the underwear line. A Brazilian covers the whole area, including the intergluteal fold. The option you choose affects both session length and price — confirm this when booking." } },
      { q: { uk: "Чи можна робити лазерну епіляцію бікіні під час місячних?", ru: "Можно ли делать лазерную эпиляцию бикини во время месячных?", en: "Can I have bikini laser hair removal during my period?" },
        a: { uk: "Процедуру краще перенести: у ці дні чутливість підвищена, а з гігієнічних міркувань обробка глибокої зони незручна. Оптимально планувати сеанс через кілька днів після завершення менструації. Перенести запис можна безкоштовно, попередивши адміністратора.", ru: "Процедуру лучше перенести: в эти дни чувствительность повышена, а из гигиенических соображений обработка глубокой зоны неудобна. Оптимально планировать сеанс через несколько дней после завершения менструации. Перенести запись можно бесплатно, предупредив администратора.", en: "It is better to reschedule: sensitivity is heightened and treating the deep area is impractical for hygiene reasons. Ideally book a few days after your period ends. Rescheduling is free if you let the administrator know." } },
      { q: { uk: "Чи допомагає лазер від вростання волосся в зоні бікіні?", ru: "Помогает ли лазер от вросших волос в зоне бикини?", en: "Does laser hair removal help with ingrown hairs in the bikini area?" },
        a: { uk: "Так, це одна з головних переваг методу. Лазер руйнує фолікул, тому волосся не пробивається крізь шкіру й вростання поступово зникає вже після перших сеансів. Паралельно зменшуються подразнення та почервоніння після гоління.", ru: "Да, это одно из главных преимуществ метода. Лазер разрушает фолликул, поэтому волос не пробивается сквозь кожу и врастание постепенно исчезает уже после первых сеансов. Параллельно уменьшаются раздражения и покраснения после бритья.", en: "Yes, it is one of the main benefits. The laser destroys the follicle, so hairs no longer break through the skin and ingrowns disappear after the first few sessions. Shaving irritation and redness also subside." } },
      { q: { uk: "Чи можна робити лазерну епіляцію бікіні під час вагітності?", ru: "Можно ли делать лазерную эпиляцию бикини во время беременности?", en: "Can bikini laser hair removal be done during pregnancy?" },
        a: { uk: "Ні, вагітність є протипоказанням — не через доведену шкоду, а тому що досліджень безпеки для цієї групи недостатньо, а гормональні зміни роблять результат непередбачуваним. Курс можна відновити після завершення лактації.", ru: "Нет, беременность является противопоказанием — не из-за доказанного вреда, а потому что исследований безопасности для этой группы недостаточно, а гормональные изменения делают результат непредсказуемым. Курс можно возобновить после завершения лактации.", en: "No — pregnancy is a contraindication, not because harm is proven but because safety data for this group is limited and hormonal changes make results unpredictable. The course can resume once breastfeeding has ended." } },
    ],
  },
  {
    type: "service",
    slug: "laser-legs",
    items: [
      { q: { uk: "Як підготуватися до лазерної епіляції ніг?", ru: "Как подготовиться к лазерной эпиляции ног?", en: "How should I prepare for leg laser hair removal?" },
        a: { uk: "За 2 тижні відмовтеся від сонця, солярію та автозасмаги, за 3–4 тижні — від воску, шугарингу й пінцета: лазеру потрібен корінь волосини. Напередодні зголіть зону станком. У день процедури не наносьте креми, олії та дезодорувальні засоби.", ru: "За 2 недели откажитесь от солнца, солярия и автозагара, за 3–4 недели — от воска, шугаринга и пинцета: лазеру нужен корень волоса. Накануне побрейте зону станком. В день процедуры не наносите кремы, масла и дезодорирующие средства.", en: "Avoid sun, solariums and self-tanner for two weeks, and waxing, sugaring and tweezing for three to four weeks — the laser needs the root. Shave the area the day before. On the day, apply no creams, oils or deodorising products." } },
      { q: { uk: "Чи можна поєднати епіляцію ніг і бікіні за один візит?", ru: "Можно ли объединить эпиляцию ног и бикини за один визит?", en: "Can legs and bikini be treated in one visit?" },
        a: { uk: "Так, це найпоширеніший сценарій. Обробка кількох зон за один візит економить час і зручніша для планування курсу — усі зони йдуть в одному ритмі. Повідомте адміністратора під час запису, щоб зарезервувати достатньо часу.", ru: "Да, это самый распространённый сценарий. Обработка нескольких зон за один визит экономит время и удобнее для планирования курса — все зоны идут в одном ритме. Сообщите администратору при записи, чтобы зарезервировать достаточно времени.", en: "Yes, and it is the most common arrangement. Treating several areas in one visit saves time and keeps the course in sync. Tell the administrator when booking so enough time is reserved." } },
      { q: { uk: "Що робити, якщо після сеансу з'явилося подразнення?", ru: "Что делать, если после сеанса появилось раздражение?", en: "What should I do if irritation appears after a session?" },
        a: { uk: "Легке почервоніння й відчуття тепла впродовж кількох годин — нормальна реакція. Допоможуть прохолодний душ і засіб із пантенолом. Уникайте сауни, басейну та тренувань добу. Якщо реакція зберігається довше або посилюється — зателефонуйте нам, лікар порадить, що робити.", ru: "Лёгкое покраснение и ощущение тепла в течение нескольких часов — нормальная реакция. Помогут прохладный душ и средство с пантенолом. Избегайте сауны, бассейна и тренировок сутки. Если реакция сохраняется дольше или усиливается — позвоните нам, врач подскажет, что делать.", en: "Mild redness and warmth for a few hours is a normal reaction. A cool shower and a panthenol product help. Avoid saunas, pools and workouts for 24 hours. If the reaction persists or worsens, call us and the physician will advise." } },
      { q: { uk: "Коли волосся починає випадати після процедури?", ru: "Когда волосы начинают выпадать после процедуры?", en: "When does the hair start to fall out after a session?" },
        a: { uk: "Оброблені волосини виходять протягом 7–14 днів після сеансу — здається, ніби вони ростуть, але насправді просто виштовхуються зі шкіри. У цей період можна м'яко скрабувати шкіру, але не виривати волосся. Наступний етап росту з'явиться вже рідшим.", ru: "Обработанные волосы выходят в течение 7–14 дней после сеанса — кажется, будто они растут, но на самом деле просто выталкиваются из кожи. В этот период можно мягко скрабировать кожу, но не выдёргивать волосы. Следующий этап роста появится уже более редким.", en: "Treated hairs shed over 7–14 days after the session — it looks like regrowth but they are simply being pushed out. Gentle exfoliation helps; do not pluck. The next phase of growth comes in noticeably sparser." } },
    ],
  },
  {
    type: "service",
    slug: "laser-men",
    items: [
      { q: { uk: "Скільки сеансів потрібно чоловікам?", ru: "Сколько сеансов нужно мужчинам?", en: "How many sessions do men need?" },
        a: { uk: "Чоловіче волосся густіше й міцніше, тому курс зазвичай довший: 8–10 процедур з інтервалом 4–8 тижнів залежно від зони. Спина й груди відповідають повільніше, ніж пахви. Точну кількість лікар називає після оцінки типу волосся та шкіри.", ru: "Мужские волосы гуще и крепче, поэтому курс обычно длиннее: 8–10 процедур с интервалом 4–8 недель в зависимости от зоны. Спина и грудь отвечают медленнее, чем подмышки. Точное количество врач называет после оценки типа волос и кожи.", en: "Men's hair is denser and coarser, so the course is usually longer: 8–10 sessions at 4–8 week intervals depending on the area. The back and chest respond more slowly than the underarms. The physician gives an exact number after assessing your hair and skin." } },
      { q: { uk: "Чи можна не видаляти волосся повністю, а лише проріджувати?", ru: "Можно ли не удалять волосы полностью, а только проредить?", en: "Can hair be thinned rather than removed completely?" },
        a: { uk: "Так, це поширений запит для грудей і живота. Скорочений курс із меншою кількістю сеансів помітно зменшує густоту, залишаючи природний вигляд. Обговоріть бажаний результат із лікарем до початку курсу — від цього залежить кількість процедур.", ru: "Да, это распространённый запрос для груди и живота. Сокращённый курс с меньшим количеством сеансов заметно уменьшает густоту, оставляя естественный вид. Обсудите желаемый результат с врачом до начала курса — от этого зависит количество процедур.", en: "Yes, it is a common request for the chest and abdomen. A shorter course noticeably reduces density while keeping a natural look. Discuss the result you want before starting — it determines how many sessions are planned." } },
    ],
  },
  {
    type: "service",
    slug: "laser-peel",
    items: [
      { q: { uk: "Чим лазерний пілінг відрізняється від хімічного?", ru: "Чем лазерный пилинг отличается от химического?", en: "How does laser peeling differ from a chemical peel?" },
        a: { uk: "Хімічний пілінг працює кислотами, глибина дії залежить від складу й часу експозиції. Лазерний пілінг знімає поверхневий шар точно дозованою енергією й водночас прогріває дерму, стимулюючи колаген. Контроль глибини кращий, а реакція шкіри — передбачуваніша.", ru: "Химический пилинг работает кислотами, глубина действия зависит от состава и времени экспозиции. Лазерный пилинг снимает поверхностный слой точно дозированной энергией и одновременно прогревает дерму, стимулируя коллаген. Контроль глубины лучше, а реакция кожи — предсказуемее.", en: "A chemical peel works with acids, its depth depending on the formula and contact time. A laser peel removes the surface layer with precisely dosed energy while also warming the dermis to stimulate collagen. Depth control is better and the skin's response more predictable." } },
      { q: { uk: "Чи підходить лазерний пілінг для чутливої шкіри?", ru: "Подходит ли лазерный пилинг для чувствительной кожи?", en: "Is laser peeling suitable for sensitive skin?" },
        a: { uk: "Так, за умови коректно підібраних параметрів — лікар працює м'якшими режимами й може розділити курс на більшу кількість делікатних сеансів. При розацеа та активних запаленнях процедуру відкладають до стабілізації стану шкіри.", ru: "Да, при условии корректно подобранных параметров — врач работает более мягкими режимами и может разделить курс на большее количество деликатных сеансов. При розацеа и активных воспалениях процедуру откладывают до стабилизации состояния кожи.", en: "Yes, with correctly chosen settings — the physician uses gentler parameters and may spread the course over more, lighter sessions. With rosacea or active inflammation the treatment is postponed until the skin has settled." } },
      { q: { uk: "Як доглядати за шкірою після лазерного пілінгу?", ru: "Как ухаживать за кожей после лазерного пилинга?", en: "How should I care for my skin after a laser peel?" },
        a: { uk: "Перші дні — м'яке очищення, насичене зволоження та SPF 50+ щодня, навіть у похмуру погоду. Не використовуйте кислоти, ретиноїди й скраби 7–10 днів і не здирайте лусочки. Сауну, басейн і інтенсивний спорт відкладіть на тиждень.", ru: "Первые дни — мягкое очищение, насыщенное увлажнение и SPF 50+ ежедневно, даже в пасмурную погоду. Не используйте кислоты, ретиноиды и скрабы 7–10 дней и не сдирайте чешуйки. Сауну, бассейн и интенсивный спорт отложите на неделю.", en: "For the first days: gentle cleansing, rich moisturising and daily SPF 50+, even in cloudy weather. Avoid acids, retinoids and scrubs for 7–10 days and never pick the flaking skin. Postpone saunas, pools and intensive exercise for a week." } },
      { q: { uk: "Чи можна робити лазерний пілінг у 25 років?", ru: "Можно ли делать лазерный пилинг в 25 лет?", en: "Can a laser peel be done at 25?" },
        a: { uk: "Так, у молодому віці процедуру роблять радше для якості шкіри: рівний тон, гладкість, звуження пор, робота зі слідами постакне. Це не «омолодження на випередження», а догляд із доказовим механізмом. Частоту визначає лікар за станом шкіри.", ru: "Да, в молодом возрасте процедуру делают скорее для качества кожи: ровный тон, гладкость, сужение пор, работа со следами постакне. Это не «омоложение на опережение», а уход с доказательным механизмом. Частоту определяет врач по состоянию кожи.", en: "Yes — at a younger age it is done for skin quality: even tone, smoothness, tighter pores and post-acne marks. It is not pre-emptive anti-ageing but evidence-based skincare. The physician sets the frequency based on your skin." } },
    ],
  },
  {
    type: "service",
    slug: "laser-rejuvenation",
    items: [
      { q: { uk: "Коли буде видно результат лазерного омолодження?", ru: "Когда будет виден результат лазерного омоложения?", en: "When will I see the result of laser rejuvenation?" },
        a: { uk: "Перше враження — свіжий рівний тон — з'являється після завершення лущення, приблизно на 10–14 день. Головний ефект розвивається поступово: синтез нового колагену триває 3–6 місяців, тому шкіра продовжує ущільнюватися й після візиту.", ru: "Первое впечатление — свежий ровный тон — появляется после завершения шелушения, примерно на 10–14 день. Главный эффект развивается постепенно: синтез нового коллагена продолжается 3–6 месяцев, поэтому кожа продолжает уплотняться и после визита.", en: "The first impression — fresh, even tone — appears once flaking finishes, around days 10–14. The main effect builds gradually: new collagen synthesis continues for three to six months, so the skin keeps firming long after the visit." } },
      { q: { uk: "Чи є протипоказання до лазерного омолодження?", ru: "Есть ли противопоказания к лазерному омоложению?", en: "Are there contraindications to laser rejuvenation?" },
        a: { uk: "Так: вагітність і лактація, активні запалення та герпес у зоні обробки, схильність до келоїдів, прийом ізотретиноїну та 6 місяців після нього, свіжа засмага, декомпенсований цукровий діабет. Повний перелік лікар перевіряє на консультації.", ru: "Да: беременность и лактация, активные воспаления и герпес в зоне обработки, склонность к келоидам, приём изотретиноина и 6 месяцев после него, свежий загар, декомпенсированный сахарный диабет. Полный перечень врач проверяет на консультации.", en: "Yes: pregnancy and breastfeeding, active inflammation or herpes in the area, keloid tendency, isotretinoin use and six months afterwards, fresh tanning and uncontrolled diabetes. The physician reviews the full list at the consultation." } },
      { q: { uk: "Які зони можна обробляти, крім обличчя?", ru: "Какие зоны можно обрабатывать, кроме лица?", en: "Which areas besides the face can be treated?" },
        a: { uk: "Найчастіше це шия, зона декольте та кисті рук — вони старіють раніше й видають вік не менше за обличчя. Обробку цих зон часто планують разом з обличчям, щоб результат виглядав цілісним. Параметри для тонкої шкіри лікар підбирає окремо.", ru: "Чаще всего это шея, зона декольте и кисти рук — они стареют раньше и выдают возраст не меньше лица. Обработку этих зон часто планируют вместе с лицом, чтобы результат выглядел целостным. Параметры для тонкой кожи врач подбирает отдельно.", en: "Most often the neck, décolleté and hands — they age earlier and reveal age as much as the face. These are usually treated together with the face so the result looks cohesive, with separate settings chosen for the thinner skin." } },
      { q: { uk: "Скільки часу потрібно взяти на відновлення перед подією?", ru: "Сколько времени нужно заложить на восстановление перед событием?", en: "How far in advance of an event should I book?" },
        a: { uk: "Плануйте процедуру щонайменше за 3–4 тижні до важливої події: цього достатньо, щоб шкіра повністю відновилася й тон вирівнявся. Якщо часу менше, лікар запропонує делікатніші альтернативи — наприклад, HydraFacial.", ru: "Планируйте процедуру минимум за 3–4 недели до важного события: этого достаточно, чтобы кожа полностью восстановилась и тон выровнялся. Если времени меньше, врач предложит более деликатные альтернативы — например, HydraFacial.", en: "Book at least three to four weeks before an important event — enough time for the skin to recover fully and the tone to even out. With less notice, the physician will suggest a gentler option such as HydraFacial." } },
    ],
  },
];

seed(batches);
