/**
 * V2 part A — Контурна пластика + PRP-терапія.
 * Same structure / voice as v1. Apply via `npx tsx scripts/seed-copy-v2a.ts`.
 */
import postgres from "postgres";
import * as fs from "fs";
import * as path from "path";
import { randomUUID } from "crypto";

const envContent = fs.readFileSync(path.resolve(__dirname, "../.env.local"), "utf-8");
const env: Record<string, string> = {};
envContent.split("\n").forEach((l) => {
  const [k, ...v] = l.split("=");
  if (k && v.length) env[k.trim()] = v.join("=").trim();
});
const sql = postgres(env.DATABASE_URL!);

type L = { uk: string; ru: string; en: string };
interface SectionCopy { heading: L; body: L; calloutBody: L; }
interface FaqCopy { question: L; answer: L; }
interface ServiceCopy { slug: string; summary: L; sections: SectionCopy[]; faq: FaqCopy[]; }

const contourPlasty: ServiceCopy = {
  slug: "contour-plasty",
  summary: {
    uk: "Контурна пластика у GENEVITY — корекція овалу обличчя, відновлення об'єму в скулах, підборідді, носогубному трикутнику й губах із філерами на основі гіалуронової кислоти. Працюємо архітектурно: не «додаємо» шкірі об'єм, а повертаємо той, що втратився з віком.",
    ru: "Контурная пластика в GENEVITY — коррекция овала лица, восстановление объёма в скулах, подбородке, носогубном треугольнике и губах филлерами на основе гиалуроновой кислоты. Работаем архитектурно: не «добавляем» коже объём, а возвращаем тот, что потерялся с возрастом.",
    en: "Contour plasty at GENEVITY — facial oval correction, volume restoration in cheekbones, chin, nasolabial area and lips with hyaluronic-acid fillers. We work architecturally: we don't add volume to the skin, we return what age has taken away.",
  },
  sections: [
    {
      heading: { uk: "Що таке контурна пластика обличчя", ru: "Что такое контурная пластика лица", en: "What contour plasty is" },
      body: {
        uk: "Контурна пластика — ін'єкційна корекція форми обличчя за допомогою філерів на основі стабілізованої гіалуронової кислоти. На відміну від біоревіталізації, де препарат зволожує шкіру і розсмоктується за 6–12 місяців, філер утворює щільний гель під шкірою, який повертає об'єм у конкретній зоні й тримається 9–18 місяців.\n\nУ GENEVITY, центрі естетичної медицини у Дніпрі, ми працюємо лише з преміум-лінійками — Juvederm (Volift, Volbella, Voluma, Volux), Restylane (Lyft, Defyne, Refyne, Kysse), Teosyal, Belotero. Для кожної зони обирається свій препарат за щільністю: м'який для губ і носогубних ліній, середньої щільності для щоків і підборіддя, найщільніший — для скульптурної корекції скул. Лікар поєднує 1–3 препарати в одній процедурі залежно від архітектури вашого обличчя.\n\nКлючова відмінність нашого підходу: ми не продаємо «шприц філера», ми продаємо результат. На консультації лікар малює карту об'єму — де його не вистачає, звідки він «поплив», куди повернути. Часто одного шприца вистачає на значно більший ефект, ніж три використані «рівномірно».",
        ru: "Контурная пластика — инъекционная коррекция формы лица с помощью филлеров на основе стабилизированной гиалуроновой кислоты. В отличие от биоревитализации, где препарат увлажняет кожу и рассасывается за 6–12 месяцев, филлер образует плотный гель под кожей, который возвращает объём в конкретной зоне и держится 9–18 месяцев.\n\nВ GENEVITY, центре эстетической медицины в Днепре, мы работаем только с премиум-линейками — Juvederm (Volift, Volbella, Voluma, Volux), Restylane (Lyft, Defyne, Refyne, Kysse), Teosyal, Belotero. Для каждой зоны выбирается свой препарат по плотности: мягкий для губ и носогубных линий, средней плотности для щёк и подбородка, самый плотный — для скульптурной коррекции скул. Врач сочетает 1–3 препарата в одной процедуре в зависимости от архитектуры вашего лица.\n\nКлючевое отличие нашего подхода: мы не продаём «шприц филлера», мы продаём результат. На консультации врач рисует карту объёма — где его не хватает, откуда он «поплыл», куда вернуть. Часто одного шприца хватает на значительно больший эффект, чем три использованные «равномерно».",
        en: "Contour plasty is injectable facial reshaping with stabilised hyaluronic-acid fillers. Unlike biorevitalisation, which hydrates and resolves within 6-12 months, fillers form a dense gel beneath the skin that restores volume in a specific zone and lasts 9-18 months.\n\nAt GENEVITY aesthetic medicine centre in Dnipro we work only with premium lines — Juvederm (Volift, Volbella, Voluma, Volux), Restylane (Lyft, Defyne, Refyne, Kysse), Teosyal, Belotero. Each zone gets a product selected for density: soft for lips and nasolabial lines, medium for cheeks and chin, firmest for sculpting cheekbones. The doctor combines 1-3 preparations in a single session depending on your facial architecture.\n\nThe key difference in our approach: we don't sell \"a syringe of filler\", we sell the result. During consultation the doctor maps volume — where it's lacking, where it has migrated, where to return it. One syringe placed precisely often achieves far more than three used \"evenly\".",
      },
      calloutBody: {
        uk: "Філер — не «повний об'єм на все обличчя». Це точковий інструмент архітектора: 0,3 мл у правильну точку може змінити всю пропорцію обличчя більше, ніж 3 мл, розподілені «рівномірно».",
        ru: "Филлер — не «полный объём на всё лицо». Это точечный инструмент архитектора: 0,3 мл в правильную точку может изменить всю пропорцию лица больше, чем 3 мл, распределённые «равномерно».",
        en: "Filler isn't \"volume for the whole face\". It's an architect's precision tool: 0.3 ml in the right point can reshape the face more than 3 ml spread evenly.",
      },
    },
    {
      heading: { uk: "Показання до контурної пластики", ru: "Показания к контурной пластике", en: "Indications" },
      body: {
        uk: "Контурну пластику призначають, коли шкіра втратила об'єм у конкретних зонах і форма обличчя почала «плавати». Основні показання:\n\n— носогубні складки — виражені лінії від крил носа до кутів рота;\n— маріонеткові лінії — складки від кутів рота до підборіддя, що надають обличчю сумного виразу;\n— втрата об'єму у скулах — «провалення» на латеральній поверхні середньої третини обличчя;\n— слабкий підборіддя — коли профіль «тікає» або контур овалу згладився;\n— корекція форми губ — об'єм, симетрія, форма «арки Купідона», контур;\n— тіні під очима (слізна борозенка) — заповнення западини між нижньою повікою і щокою;\n— тонка поверхня рук, шия, декольте — омолодження «видавальних» зон;\n— асиметрії після травм або природні диспропорції;\n— профілактика вікових змін у 28–40 років, коли об'єм тільки починає «іти».\n\nФілери не працюють зі зморшками від скорочення м'язів — це робота ботулотоксину. Глибокі носогубні складки часто вимагають комплексу: ботокс розслаблює м'яз, філер повертає об'єм.",
        ru: "Контурную пластику назначают, когда кожа потеряла объём в конкретных зонах и форма лица начала «плыть». Основные показания:\n\n— носогубные складки — выраженные линии от крыльев носа к уголкам рта;\n— марионеточные линии — складки от уголков рта к подбородку, придающие лицу грустный вид;\n— потеря объёма в скулах — «проваливание» на латеральной поверхности средней трети лица;\n— слабый подбородок — когда профиль «убегает» или контур овала сгладился;\n— коррекция формы губ — объём, симметрия, форма «арки Купидона», контур;\n— тени под глазами (слёзная борозда) — заполнение впадины между нижним веком и щекой;\n— тонкая поверхность рук, шея, декольте — омоложение «выдающих» зон;\n— асимметрии после травм или природные диспропорции;\n— профилактика возрастных изменений в 28–40 лет, когда объём только начинает «уходить».\n\nФиллеры не работают с морщинами от сокращения мышц — это работа ботулотоксина. Глубокие носогубные складки часто требуют комплекса: ботокс расслабляет мышцу, филлер возвращает объём.",
        en: "Contour plasty is indicated when the skin has lost volume in specific zones and facial shape has started to migrate:\n\n— nasolabial folds — pronounced lines from the nostrils to the corners of the mouth;\n— marionette lines — folds running from the mouth corners toward the chin, giving a sad look;\n— cheekbone volume loss — flattening of the lateral midface;\n— weak chin — a receding profile or smoothed jawline;\n— lip correction — volume, symmetry, Cupid's bow, contour;\n— tear troughs under the eyes — the hollow between lower lid and cheek;\n— thinning hands, neck and décolleté — \"telltale\" zones;\n— post-trauma asymmetries or natural disproportions;\n— preventative age correction at 28-40 when volume is just beginning to drift.\n\nFillers don't address expression lines caused by muscle contraction — that's botulinum territory. Deep nasolabial folds often need both: botulinum to relax the muscle, filler to restore the lost volume.",
      },
      calloutBody: {
        uk: "Філери — не про «додати щось там, де мені хочеться». Лікар дивиться на обличчя цілісно: іноді проблема «губ» вирішується об'ємом у скулах, а «сумного рота» — підтримкою підборіддя.",
        ru: "Филлеры — не про «добавить что-то там, где мне хочется». Врач смотрит на лицо целостно: иногда проблема «губ» решается объёмом в скулах, а «грустного рта» — поддержкой подбородка.",
        en: "Fillers aren't about \"adding something wherever you want it\". The doctor reads the face as a whole: sometimes a \"lip problem\" is solved with cheekbone volume, and a \"sad mouth\" with chin support.",
      },
    },
    {
      heading: { uk: "Процедура контурної пластики: етапи та особливості", ru: "Процедура контурной пластики: этапы и особенности", en: "How a contour-plasty session works" },
      body: {
        uk: "Процедура триває 30–60 хвилин залежно від зон обробки. Основні етапи:\n\n1. Консультація і 3D-картування обличчя. Лікар робить фотопротокол з декількох ракурсів, оцінює симетрію, пропорції, стан шкіри. Разом з вами малюємо карту — де прибирати тіні, де повертати об'єм, де акцентувати форму. Якщо це перша процедура, часто беремо 2-тижневу паузу між консультацією і самою процедурою, щоб ви «поспали» з ідеями.\n\n2. Вибір препаратів. Обираємо філер за щільністю і зоною введення. Для губ — м'який (Juvederm Volbella, Restylane Kysse). Для щоків — середній (Juvederm Voluma). Для скул і підборіддя — щільний (Juvederm Volux, Restylane Lyft).\n\n3. Анестезія. Для більшості зон — аплікаційний лідокаїновий крем на 15 хвилин. Для губ — провідникова анестезія або лідокаїн у самому філері.\n\n4. Техніка введення. Використовуємо два підходи:\n— канюлею (тупокінцевою): менше травми, знижений ризик пошкодження судин, підходить для об'ємних зон (скули, щоки, підборіддя);\n— голкою: точна корекція у маленьких зонах (губи, носогубка, маріонетки).\n\n5. Контроль результату. Після процедури лікар показує вам результат з декількох ракурсів. Якщо потрібна корекція — додаємо мікродози або навпаки розчиняємо зайве гіалуронідазою (препарат, що розщеплює гіалуронову кислоту).",
        ru: "Процедура длится 30–60 минут в зависимости от зон обработки. Основные этапы:\n\n1. Консультация и 3D-картирование лица. Врач делает фотопротокол с нескольких ракурсов, оценивает симметрию, пропорции, состояние кожи. Вместе с вами рисуем карту — где убирать тени, где возвращать объём, где акцентировать форму. Если это первая процедура, часто берём 2-недельную паузу между консультацией и самой процедурой, чтобы вы «поспали» с идеями.\n\n2. Выбор препаратов. Выбираем филлер по плотности и зоне введения. Для губ — мягкий (Juvederm Volbella, Restylane Kysse). Для щёк — средний (Juvederm Voluma). Для скул и подбородка — плотный (Juvederm Volux, Restylane Lyft).\n\n3. Анестезия. Для большинства зон — аппликационный лидокаиновый крем на 15 минут. Для губ — проводниковая анестезия или лидокаин в самом филлере.\n\n4. Техника введения. Используем два подхода:\n— канюлей (тупоконечной): меньше травмы, сниженный риск повреждения сосудов, подходит для объёмных зон (скулы, щёки, подбородок);\n— иглой: точная коррекция в маленьких зонах (губы, носогубка, марионетки).\n\n5. Контроль результата. После процедуры врач показывает вам результат с нескольких ракурсов. Если нужна коррекция — добавляем микродозы или наоборот растворяем лишнее гиалуронидазой (препарат, расщепляющий гиалуроновую кислоту).",
        en: "A session takes 30-60 minutes depending on the treated zones.\n\n1. Consultation and 3D facial mapping. The doctor takes photos from multiple angles, evaluates symmetry, proportions and skin condition. Together we draw the map — where to remove shadows, restore volume, accent shape. For a first session we often take a two-week pause between consultation and the procedure so you can \"sleep on it\".\n\n2. Product selection. The filler is chosen by density and zone. For lips — soft (Juvederm Volbella, Restylane Kysse). For cheeks — medium (Juvederm Voluma). For cheekbones and chin — dense (Juvederm Volux, Restylane Lyft).\n\n3. Anaesthesia. For most zones — topical lidocaine cream for 15 minutes. For lips — nerve-block anaesthesia or lidocaine pre-mixed in the filler.\n\n4. Technique. Two approaches:\n— cannula (blunt-tipped): less trauma, lower vascular risk, ideal for volume zones (cheekbones, cheeks, chin);\n— needle: precise correction in small zones (lips, nasolabial, marionette lines).\n\n5. Review. After the procedure the doctor shows you the result from several angles. If correction is needed — we add microdoses, or dissolve excess filler with hyaluronidase (an enzyme that breaks down hyaluronic acid).",
      },
      calloutBody: {
        uk: "Гіалуронідаза — наш страховий поліс. Якщо вам не подобається результат, якщо хтось колись зробив філери гірше, ніж потрібно, або якщо препарат мігрував — ми можемо його розчинити за 24–48 годин. Це головна перевага гіалуронових філерів над постійними біополімерами.",
        ru: "Гиалуронидаза — наш страховой полис. Если вам не нравится результат, если кто-то когда-то сделал филлеры хуже, чем нужно, или если препарат мигрировал — мы можем его растворить за 24–48 часов. Это главное преимущество гиалуроновых филлеров над постоянными биополимерами.",
        en: "Hyaluronidase is our insurance policy. If you don't like the result, if someone once did fillers wrong, or if the product has migrated — we can dissolve it in 24-48 hours. That's the main advantage of hyaluronic fillers over permanent biopolymers.",
      },
    },
    {
      heading: { uk: "Протипоказання, рекомендації та тривалість ефекту", ru: "Противопоказания, рекомендации и длительность эффекта", en: "Contraindications, aftercare and duration" },
      body: {
        uk: "Протипоказання до контурної пластики — стандартні для ін'єкційних процедур. Абсолютні: вагітність і грудне вигодовування, активні автоімунні стани, порушення згортання крові, онкологія в активній фазі, гіперчутливість до гіалуронової кислоти чи лідокаїну, запалення у зоні ін'єкції. Відносні: прийом антикоагулянтів, загострення хронічних захворювань, активний герпес (процедуру для губ переносимо до ремісії), свіжа імплантація зубних імплантів.\n\nДогляд після контурної пластики:\n— перші 24 години: без сауни, басейну, спорту, солярію, масажу обличчя, активної міміки;\n— перші 48 годин: уникати горизонтального положення на оброблених зонах, не торкатись обличчя руками;\n— перші 2 тижні: активний SPF 30+, відмова від агресивних косметологічних процедур, обмеження алкоголю;\n— повний ефект розкривається на 10–14 день, коли препарат «сідає» на місце і припиняються мікронабряки.\n\nТривалість ефекту залежить від щільності препарату, зони обробки і вашого метаболізму:\n— губи (м'які філери) — 6–9 місяців;\n— носогубні складки — 9–12 місяців;\n— щоки, скули, підборіддя (щільні філери) — 12–18 місяців;\n— тонкі зони (слізна борозенка) — 9–12 місяців.\n\nУ людей з активним спортом, частими поїздками, високим метаболізмом філер розсмоктується на 20–30% швидше. У GENEVITY ведемо карту процедур: знаємо, коли і який препарат ви вводили, і можемо порівняти фото до/після.",
        ru: "Противопоказания к контурной пластике — стандартные для инъекционных процедур. Абсолютные: беременность и грудное вскармливание, активные аутоиммунные состояния, нарушения свёртываемости крови, онкология в активной фазе, гиперчувствительность к гиалуроновой кислоте или лидокаину, воспаление в зоне инъекции. Относительные: приём антикоагулянтов, обострение хронических заболеваний, активный герпес (процедуру для губ переносим до ремиссии), свежая имплантация зубных имплантов.\n\nУход после контурной пластики:\n— первые 24 часа: без сауны, бассейна, спорта, солярия, массажа лица, активной мимики;\n— первые 48 часов: избегать горизонтального положения на обработанных зонах, не трогать лицо руками;\n— первые 2 недели: активный SPF 30+, отказ от агрессивных косметологических процедур, ограничение алкоголя;\n— полный эффект раскрывается на 10–14 день, когда препарат «садится» на место и прекращаются микроотёки.\n\nДлительность эффекта зависит от плотности препарата, зоны обработки и вашего метаболизма:\n— губы (мягкие филлеры) — 6–9 месяцев;\n— носогубные складки — 9–12 месяцев;\n— щёки, скулы, подбородок (плотные филлеры) — 12–18 месяцев;\n— тонкие зоны (слёзная борозда) — 9–12 месяцев.\n\nУ людей с активным спортом, частыми поездками, высоким метаболизмом филлер рассасывается на 20–30% быстрее. В GENEVITY ведём карту процедур: знаем, когда и какой препарат вы вводили, и можем сравнить фото до/после.",
        en: "Contraindications are standard for injectable procedures. Absolute: pregnancy and breastfeeding, active autoimmune states, clotting disorders, active-phase oncology, hypersensitivity to hyaluronic acid or lidocaine, inflammation in the injection area. Relative: anticoagulant therapy, flare-ups of chronic disease, active herpes (lip treatment postponed until remission), recent dental implants.\n\nAftercare:\n— first 24 hours: no sauna, pool, sport, tanning, facial massage or strong facial expressions;\n— first 48 hours: avoid lying face-down on treated zones, don't touch the face with your hands;\n— first 2 weeks: SPF 30+, no aggressive cosmetology, limit alcohol;\n— the full result settles at day 10-14 as the product stabilises and micro-swelling subsides.\n\nDuration depends on product density, zone and metabolism:\n— lips (soft fillers) — 6-9 months;\n— nasolabial folds — 9-12 months;\n— cheeks, cheekbones, chin (dense fillers) — 12-18 months;\n— thin zones (tear troughs) — 9-12 months.\n\nActive athletes, frequent travellers and those with fast metabolism see the filler absorb 20-30% faster. GENEVITY keeps a procedure chart — we know which product went where and can show before/after photos at every follow-up.",
      },
      calloutBody: {
        uk: "Якщо лікар запропонував вам філер із перманентним біополімером (силікон, акрил) — йдіть. Такі препарати практично неможливо видалити, і вони спричиняють найбільшу частину естетичних катастроф, які ми потім розчиняємо і відновлюємо.",
        ru: "Если врач предложил вам филлер с перманентным биополимером (силикон, акрил) — уходите. Такие препараты практически невозможно удалить, и они вызывают большую часть эстетических катастроф, которые мы потом растворяем и восстанавливаем.",
        en: "If a doctor offers you a filler with a permanent biopolymer (silicone, acrylic) — walk away. These can't practically be removed, and they cause most of the aesthetic disasters we later spend sessions correcting.",
      },
    },
  ],
  faq: [
    { question: { uk: "Які препарати використовуються для контурної пластики?", ru: "Какие препараты используются для контурной пластики?", en: "Which products are used?" },
      answer: { uk: "У GENEVITY ми працюємо лише з преміум-лінійками на основі стабілізованої гіалуронової кислоти: Juvederm (Volift, Volbella, Voluma, Volux), Restylane (Lyft, Defyne, Refyne, Kysse), Teosyal Redensity, Belotero Balance. Кожен препарат має свою щільність і призначення: м'які — для губ, середні — для щоків і носогубних, щільні — для скульптурної корекції скул і підборіддя. Ми ніколи не працюємо з перманентними біополімерами.",
        ru: "В GENEVITY мы работаем только с премиум-линейками на основе стабилизированной гиалуроновой кислоты: Juvederm (Volift, Volbella, Voluma, Volux), Restylane (Lyft, Defyne, Refyne, Kysse), Teosyal Redensity, Belotero Balance. Каждый препарат имеет свою плотность и назначение: мягкие — для губ, средние — для щёк и носогубных, плотные — для скульптурной коррекции скул и подбородка. Мы никогда не работаем с перманентными биополимерами.",
        en: "GENEVITY works only with premium stabilised hyaluronic-acid lines: Juvederm (Volift, Volbella, Voluma, Volux), Restylane (Lyft, Defyne, Refyne, Kysse), Teosyal Redensity, Belotero Balance. Each has its own density and purpose — soft for lips, medium for cheeks and nasolabial, dense for sculptural correction of cheekbones and chin. We never use permanent biopolymers." }},
    { question: { uk: "Чи можна поєднувати контурну пластику з іншими процедурами?", ru: "Можно ли сочетать контурную пластику с другими процедурами?", en: "Can contour plasty be combined with other treatments?" },
      answer: { uk: "Так, в більшості випадків контурну пластику поєднують з іншими процедурами для комплексного результату. Класичні комбінації: філери + ботулінотерапія (філер відновлює об'єм, ботокс розслаблює мімічні зморшки — найчастіше робимо за один візит); філери + біоревіталізація (філер для об'єму, біоревіталізація для якості шкіри — з інтервалом 2 тижні); філери + апаратні процедури (Ultraformer, EXION, HydraFacial) з інтервалом 2–4 тижні.",
        ru: "Да, в большинстве случаев контурную пластику сочетают с другими процедурами для комплексного результата. Классические комбинации: филлеры + ботулинотерапия (филлер восстанавливает объём, ботокс расслабляет мимические морщины — чаще всего делаем за один визит); филлеры + биоревитализация (филлер для объёма, биоревитализация для качества кожи — с интервалом 2 недели); филлеры + аппаратные процедуры (Ultraformer, EXION, HydraFacial) с интервалом 2–4 недели.",
        en: "Yes — most patients combine contour plasty with other treatments for a complete result. Classic combinations: fillers + botulinum (filler restores volume, botulinum relaxes expression lines — often done in the same visit); fillers + biorevitalisation (filler for volume, biorevitalisation for skin quality — 2-week interval); fillers + apparatus treatments (Ultraformer, EXION, HydraFacial) with 2-4 week intervals." }},
    { question: { uk: "Як підготуватися до процедури контурної пластики?", ru: "Как подготовиться к процедуре контурной пластики?", en: "How do I prepare for the procedure?" },
      answer: { uk: "За 3–5 днів до процедури: відмовтесь від алкоголю, аспірину і добавок, що розріджують кров (омега-3, вітамін E у високих дозах, гінкго) — якщо немає медичних протипоказань. Не планувати процедуру на день перед важливою подією — можливі невеликі синяки на 4–7 днів. Прийти на процедуру з очищеною шкірою, без макіяжу. Якщо у вас активний герпес — повідомте лікаря, для губ перенесемо процедуру до повної ремісії.",
        ru: "За 3–5 дней до процедуры: откажитесь от алкоголя, аспирина и добавок, разжижающих кровь (омега-3, витамин E в высоких дозах, гинкго) — если нет медицинских противопоказаний. Не планируйте процедуру на день перед важным событием — возможны небольшие синяки на 4–7 дней. Прийти на процедуру с очищенной кожей, без макияжа. Если у вас активный герпес — сообщите врачу, для губ перенесём процедуру до полной ремиссии.",
        en: "3-5 days before: stop alcohol, aspirin and blood-thinning supplements (high-dose omega-3, vitamin E, ginkgo) unless medically required. Don't book the procedure right before an important event — small bruises can last 4-7 days. Come with cleansed skin, no makeup. If you have active herpes — tell the doctor; lip treatment is postponed until remission." }},
    { question: { uk: "Скільки тримається ефект від контурної пластики?", ru: "Сколько держится эффект от контурной пластики?", en: "How long does the result last?" },
      answer: { uk: "Залежить від щільності препарату і зони введення. Губи з м'яким філером — 6–9 місяців, носогубні складки — 9–12 місяців, щоки і скули з щільним філером — 12–18 місяців. У людей з високим метаболізмом (активний спорт, часті перельоти) філер розсмоктується на 20–30% швидше. Регулярна корекція кожні 9–12 місяців допомагає утримати стабільний результат.",
        ru: "Зависит от плотности препарата и зоны введения. Губы с мягким филлером — 6–9 месяцев, носогубные складки — 9–12 месяцев, щёки и скулы с плотным филлером — 12–18 месяцев. У людей с высоким метаболизмом (активный спорт, частые перелёты) филлер рассасывается на 20–30% быстрее. Регулярная коррекция каждые 9–12 месяцев помогает удерживать стабильный результат.",
        en: "Depends on the product density and zone. Lips with soft filler — 6-9 months, nasolabial folds — 9-12 months, cheeks and cheekbones with dense filler — 12-18 months. Active athletes and frequent travellers absorb fillers 20-30% faster. Regular touch-ups every 9-12 months maintain a stable result." }},
    { question: { uk: "Чи будуть синяки чи набряк після процедури?", ru: "Будут ли синяки или отёк после процедуры?", en: "Will there be bruising or swelling?" },
      answer: { uk: "Набряк — нормальна реакція, особливо при обробці губ: максимум на 2–3 день, повністю йде до 10–14 дня. Синяки можливі у 15–20% випадків (частіше при обробці губ і носогубки голкою), проходять за 4–7 днів. Використання канюлі замість голки знижує ризик синяків у рази. Для швидшого відновлення перші 24 години можна прикладати холод (не більше 10 хвилин за раз).",
        ru: "Отёк — нормальная реакция, особенно при обработке губ: максимум на 2–3 день, полностью уходит к 10–14 дню. Синяки возможны в 15–20% случаев (чаще при обработке губ и носогубки иглой), проходят за 4–7 дней. Использование канюли вместо иглы снижает риск синяков в разы. Для более быстрого восстановления первые 24 часа можно прикладывать холод (не более 10 минут за раз).",
        en: "Swelling is a normal reaction, especially with lips: peaks at day 2-3, fully resolves by day 10-14. Bruising is possible in 15-20% of cases (more often with lips and nasolabial with needle technique), resolves in 4-7 days. Cannula technique vs needle reduces bruising risk dramatically. Cold compresses in the first 24 hours (no more than 10 minutes at a time) speed recovery." }},
    { question: { uk: "Скільки коштує контурна пластика у Дніпрі?", ru: "Сколько стоит контурная пластика в Днепре?", en: "What does contour plasty cost in Dnipro?" },
      answer: { uk: "Ціна розраховується за шприц препарату. Вартість одного шприца залежить від лінійки: базові (1 мл) — від нижньої межі прайсу; преміум-філери (Volux, Voluma, Lyft) — дорожче через стабільність і тривалість ефекту. Кількість шприців на одну процедуру — 0,5 до 3+ залежно від зон. На консультації лікар складає точний план: що, в якому об'ємі, в яку зону. Жодних «рахунків-сюрпризів» після процедури — ціна фіксується до першого уколу.",
        ru: "Цена рассчитывается за шприц препарата. Стоимость одного шприца зависит от линейки: базовые (1 мл) — от нижней границы прайса; премиум-филлеры (Volux, Voluma, Lyft) — дороже из-за стабильности и длительности эффекта. Количество шприцов на одну процедуру — 0,5 до 3+ в зависимости от зон. На консультации врач составляет точный план: что, в каком объёме, в какую зону. Никаких «счетов-сюрпризов» после процедуры — цена фиксируется до первого укола.",
        en: "Price is per syringe of product. Cost depends on the line: base (1 ml) at the lower end of the list; premium fillers (Volux, Voluma, Lyft) more because of stability and duration. Per-session count ranges from 0.5 to 3+ syringes depending on zones. At consultation the doctor provides an exact plan — product, volume, zone. No billing surprises — the price is locked before the first injection." }},
  ],
};

const prp: ServiceCopy = {
  slug: "prp-therapy",
  summary: {
    uk: "PRP-терапія у GENEVITY — ін'єкції власної плазми крові, збагаченої тромбоцитами і факторами росту. Природне омолодження без синтетичних препаратів: організм сам підказує шкірі, як відновлюватись, і робить це за власним сценарієм.",
    ru: "PRP-терапия в GENEVITY — инъекции собственной плазмы крови, обогащённой тромбоцитами и факторами роста. Природное омоложение без синтетических препаратов: организм сам подсказывает коже, как восстанавливаться, и делает это по собственному сценарию.",
    en: "PRP therapy at GENEVITY — injections of your own blood plasma, enriched with platelets and growth factors. Natural rejuvenation without synthetic preparations: the body signals the skin how to regenerate, following its own script.",
  },
  sections: [
    {
      heading: { uk: "Що таке PRP-терапія", ru: "Что такое PRP-терапия", en: "What PRP therapy is" },
      body: {
        uk: "PRP-терапія (Platelet-Rich Plasma) — процедура, при якій у шкіру вводиться концентрована плазма крові самого пацієнта, багата на тромбоцити. Тромбоцити несуть у собі фактори росту — молекули, що керують процесами загоєння і регенерації в організмі. Коли така плазма потрапляє у шкіру, ці фактори «будять» фібробласти, активують синтез колагену, покращують мікроциркуляцію.\n\nМетод прийшов у косметологію з ортопедії і стоматології, де його використовують уже понад 30 років для прискорення загоєння. У косметології він відомий як «плазмоліфтинг» або «вампірський ліфтинг». У GENEVITY ми віддаємо перевагу терміну «PRP-терапія» — це професійний, медичний підхід до омолодження, без маркетингової романтизації.\n\nУнікальність PRP у тому, що у вас немає шансу алергії чи відторгнення: препарат походить з вашої ж крові. Ризик імунної реакції — нульовий, ризик інфекції — мінімальний за умови стерильної процедури забору крові і центрифугування. Єдине обмеження — якість плазми залежить від вашого віку і стану здоров'я.",
        ru: "PRP-терапия (Platelet-Rich Plasma) — процедура, при которой в кожу вводится концентрированная плазма крови самого пациента, богатая тромбоцитами. Тромбоциты несут в себе факторы роста — молекулы, управляющие процессами заживления и регенерации в организме. Когда такая плазма попадает в кожу, эти факторы «будят» фибробласты, активируют синтез коллагена, улучшают микроциркуляцию.\n\nМетод пришёл в косметологию из ортопедии и стоматологии, где его используют уже более 30 лет для ускорения заживления. В косметологии он известен как «плазмолифтинг» или «вампирский лифтинг». В GENEVITY мы отдаём предпочтение термину «PRP-терапия» — это профессиональный, медицинский подход к омоложению, без маркетинговой романтизации.\n\nУникальность PRP в том, что у вас нет шансов аллергии или отторжения: препарат происходит из вашей же крови. Риск иммунной реакции — нулевой, риск инфекции — минимальный при условии стерильной процедуры забора крови и центрифугирования. Единственное ограничение — качество плазмы зависит от вашего возраста и состояния здоровья.",
        en: "PRP therapy (Platelet-Rich Plasma) injects the patient's own concentrated blood plasma, rich in platelets, into the skin. Platelets carry growth factors — molecules that orchestrate healing and regeneration in the body. Once in the skin, these factors wake up fibroblasts, activate collagen synthesis and improve microcirculation.\n\nThe method came to cosmetology from orthopaedics and dentistry, where it has been used for over 30 years to accelerate healing. In cosmetology it's also known as \"plasma lifting\" or \"vampire facial\". At GENEVITY we prefer \"PRP therapy\" — a professional, medical term without the marketing romance.\n\nPRP's distinctive feature: zero chance of allergy or rejection because the preparation comes from your own blood. Immune-reaction risk is nil; infection risk is minimal with sterile blood-draw and centrifugation. The only limit is that plasma quality depends on your age and general health.",
      },
      calloutBody: {
        uk: "PRP — не магія, а біохімія. Ваша власна плазма працює настільки добре, наскільки якісна ваша кров. Тому ми не рекомендуємо PRP курцям у активній фазі та людям з серйозними хронічними захворюваннями — ефект буде слабкішим.",
        ru: "PRP — не магия, а биохимия. Ваша собственная плазма работает настолько хорошо, насколько качественная ваша кровь. Поэтому мы не рекомендуем PRP курильщикам в активной фазе и людям с серьёзными хроническими заболеваниями — эффект будет слабее.",
        en: "PRP isn't magic, it's biochemistry. Your own plasma works as well as your blood is healthy. That's why we don't recommend PRP for active smokers or patients with serious chronic conditions — the effect will be weaker.",
      },
    },
    {
      heading: { uk: "Показання та протипоказання", ru: "Показания и противопоказания", en: "Indications and contraindications" },
      body: {
        uk: "Показання до PRP-терапії:\n— зневоднення шкіри, втрата пружності, тьмяний колір обличчя;\n— дрібні та середні зморшки, особливо у зоні навколо очей і губ;\n— відновлення шкіри після тривалої хвороби чи курсу антибіотиків;\n— реабілітація після агресивних процедур (лазерне шліфування, пілінги, оперативні втручання);\n— підготовка шкіри до важливих подій (ефект «свіжої шкіри» через 2 тижні);\n— профілактика вікових змін у 30+;\n— трихологічне PRP — при посіченні, ламкості волосся і початковому випаданні.\n\nPRP особливо цінний як «чиста» альтернатива ін'єкційних процедур для людей з алергіями або підвищеною чутливістю до синтетичних препаратів. Також рекомендуємо для пацієнтів у періоді відновлення після хвороб — коли шкіра потребує м'якого, природного поштовху.\n\nПротипоказання до PRP-терапії:\n— вагітність і грудне вигодовування;\n— онкологічні захворювання в активній фазі (PRP містить фактори росту, які теоретично можуть стимулювати клітинну активність);\n— гематологічні захворювання, тромбоцитопенія, анемія;\n— хронічні захворювання печінки і нирок у стадії декомпенсації;\n— прийом антикоагулянтів, що критично знижують якість плазми;\n— аутоімунні захворювання у фазі загострення;\n— інфекційні захворювання в активній фазі, включно з ВІЛ і гепатитами;\n— місцеві запалення у зоні ін'єкції.",
        ru: "Показания к PRP-терапии:\n— обезвоживание кожи, потеря упругости, тусклый цвет лица;\n— мелкие и средние морщины, особенно в зоне вокруг глаз и губ;\n— восстановление кожи после длительной болезни или курса антибиотиков;\n— реабилитация после агрессивных процедур (лазерная шлифовка, пилинги, оперативные вмешательства);\n— подготовка кожи к важным событиям (эффект «свежей кожи» через 2 недели);\n— профилактика возрастных изменений в 30+;\n— трихологическое PRP — при сечении, ломкости волос и начальном выпадении.\n\nPRP особенно ценен как «чистая» альтернатива инъекционных процедур для людей с аллергиями или повышенной чувствительностью к синтетическим препаратам. Также рекомендуем для пациентов в периоде восстановления после болезней — когда коже нужен мягкий, природный толчок.\n\nПротивопоказания к PRP-терапии:\n— беременность и грудное вскармливание;\n— онкологические заболевания в активной фазе (PRP содержит факторы роста, которые теоретически могут стимулировать клеточную активность);\n— гематологические заболевания, тромбоцитопения, анемия;\n— хронические заболевания печени и почек в стадии декомпенсации;\n— приём антикоагулянтов, критически снижающих качество плазмы;\n— аутоиммунные заболевания в фазе обострения;\n— инфекционные заболевания в активной фазе, включая ВИЧ и гепатиты;\n— местные воспаления в зоне инъекции.",
        en: "Indications: dehydrated skin, loss of firmness, dull complexion; fine and moderate lines, especially around eyes and lips; skin recovery after prolonged illness or antibiotics; rehabilitation after aggressive procedures (laser, peels, surgery); pre-event refresh (the \"fresh skin\" effect at 2 weeks); anti-ageing prevention at 30+; trichology PRP for split ends, brittle hair and early hair loss.\n\nPRP is particularly valuable as a \"clean\" injectable alternative for patients with allergies or sensitivity to synthetic preparations. We also recommend it during post-illness recovery — when the skin needs a gentle, natural push.\n\nContraindications: pregnancy and breastfeeding; active-phase oncology (PRP contains growth factors that could theoretically stimulate cellular activity); haematological disorders, thrombocytopenia, anaemia; decompensated chronic liver or kidney disease; anticoagulant therapy that critically reduces plasma quality; autoimmune flare-ups; active infections including HIV and hepatitis; local inflammation in the injection area.",
      },
      calloutBody: {
        uk: "PRP не конкурує з біоревіталізацією чи мезотерапією — це інший інструмент. Плазма дає сигнал, гіалуронова кислота дає субстрат, вітамінні коктейлі — живлення. У комплексі ці процедури доповнюють одна одну; кожна окремо має свою сильну сторону.",
        ru: "PRP не конкурирует с биоревитализацией или мезотерапией — это другой инструмент. Плазма даёт сигнал, гиалуроновая кислота даёт субстрат, витаминные коктейли — питание. В комплексе эти процедуры дополняют друг друга; каждая отдельно имеет свою сильную сторону.",
        en: "PRP doesn't compete with biorevitalisation or mesotherapy — it's a different tool. Plasma gives the signal, hyaluronic acid gives the substrate, vitamin cocktails give nutrition. Together they complement each other; each has its own strength.",
      },
    },
    {
      heading: { uk: "Як проходить процедура PRP-терапії", ru: "Как проходит процедура PRP-терапии", en: "How a PRP session works" },
      body: {
        uk: "Процедура PRP-терапії триває 60–90 хвилин разом із забором крові та центрифугуванням. Основні етапи:\n\n1. Забір крові. Лікар бере 10–30 мл венозної крові у спеціальні вакуумні пробірки з антикоагулянтом. Процес стандартний, як для звичайних аналізів, займає 3–5 хвилин.\n\n2. Центрифугування. Пробірки кладуться у центрифугу на 8–15 хвилин. За цей час кров розділяється на три фракції: еритроцити (знизу), лейкоцити (середина), плазма з тромбоцитами (зверху). Нас цікавить верхній шар — платзбагачена плазма (PRP).\n\n3. Підготовка шкіри. Поки центрифуга працює, лікар підготовлює шкіру: демакіяж, обробка антисептиком, аплікаційна анестезія лідокаїновим кремом на 15–20 хвилин.\n\n4. Ін'єкції. Плазма набирається у шприц і вводиться у шкіру тонкою голкою за мезотерапевтичною технікою — по мікродозі у множинні точки. Зона обробки — обличчя, шия, декольте, тильна поверхня рук, волосиста частина голови (залежно від показань).\n\n5. Завершення. Нанесення заспокійливого крему. У місцях ін'єкцій можливі легкі почервоніння і набряклість — проходять за 24–48 годин.\n\nКурс: оптимально 3–4 процедури з інтервалом 3–4 тижні. Підтримка — 1 процедура на 6–12 місяців. Результат накопичувальний: перша процедура — свіжість, друга — пружність, третя-четверта — стабільне омолодження.",
        ru: "Процедура PRP-терапии длится 60–90 минут вместе с забором крови и центрифугированием. Основные этапы:\n\n1. Забор крови. Врач берёт 10–30 мл венозной крови в специальные вакуумные пробирки с антикоагулянтом. Процесс стандартный, как для обычных анализов, занимает 3–5 минут.\n\n2. Центрифугирование. Пробирки кладутся в центрифугу на 8–15 минут. За это время кровь разделяется на три фракции: эритроциты (снизу), лейкоциты (середина), плазма с тромбоцитами (сверху). Нас интересует верхний слой — плазма, обогащённая тромбоцитами (PRP).\n\n3. Подготовка кожи. Пока центрифуга работает, врач подготавливает кожу: демакияж, обработка антисептиком, аппликационная анестезия лидокаиновым кремом на 15–20 минут.\n\n4. Инъекции. Плазма набирается в шприц и вводится в кожу тонкой иглой по мезотерапевтической технике — по микродозе в множественные точки. Зона обработки — лицо, шея, декольте, тыльная поверхность рук, волосистая часть головы (в зависимости от показаний).\n\n5. Завершение. Нанесение успокаивающего крема. В местах инъекций возможны лёгкие покраснения и отёчность — проходят за 24–48 часов.\n\nКурс: оптимально 3–4 процедуры с интервалом 3–4 недели. Поддержка — 1 процедура в 6–12 месяцев. Результат накопительный: первая процедура — свежесть, вторая — упругость, третья-четвёртая — стабильное омоложение.",
        en: "A PRP session runs 60-90 minutes including blood draw and centrifugation.\n\n1. Blood draw. The doctor takes 10-30 ml of venous blood into special vacuum tubes with anticoagulant. Standard procedure, 3-5 minutes.\n\n2. Centrifugation. Tubes go into a centrifuge for 8-15 minutes. The blood separates into three fractions: erythrocytes (bottom), leukocytes (middle), plasma with platelets (top). The top layer — platelet-rich plasma — is what we want.\n\n3. Skin preparation. While the centrifuge runs, the doctor prepares the skin: makeup removal, antiseptic, topical lidocaine cream for 15-20 minutes.\n\n4. Injections. Plasma is drawn into a syringe and injected with a fine needle using mesotherapy technique — microdoses into many points. Treatment area: face, neck, décolleté, backs of hands, scalp (depending on indications).\n\n5. Finish. Calming cream. Mild redness and swelling at injection sites are possible, resolving in 24-48 hours.\n\nCourse: ideally 3-4 sessions at 3-4 week intervals. Maintenance: one session every 6-12 months. Results are cumulative: first session — freshness; second — firmness; third-fourth — stable rejuvenation.",
      },
      calloutBody: {
        uk: "Якість PRP залежить від центрифуги. Дешеві моделі дають меншу концентрацію тромбоцитів, ніж заявлено. У GENEVITY використовуємо сертифіковані медичні системи з триразовим центрифугуванням — такі дають стабільну концентрацію 4–6× від початкової.",
        ru: "Качество PRP зависит от центрифуги. Дешёвые модели дают меньшую концентрацию тромбоцитов, чем заявлено. В GENEVITY используем сертифицированные медицинские системы с трёхкратным центрифугированием — такие дают стабильную концентрацию 4–6× от исходной.",
        en: "PRP quality depends on the centrifuge. Cheaper models deliver less platelet concentration than advertised. GENEVITY uses certified medical systems with triple centrifugation — producing stable concentrations 4-6× above baseline.",
      },
    },
    {
      heading: { uk: "Переваги та обмеження методу", ru: "Преимущества и ограничения метода", en: "Strengths and limitations" },
      body: {
        uk: "Переваги PRP-терапії:\n\n— Біосумісність. Використовується ваша власна плазма — нульовий ризик алергії, відторгнення, алергенних реакцій.\n— Природний механізм. PRP не «додає» шкірі речовин ззовні, а стимулює її власні резерви. Результат завжди природний за рахунок вашої ж біології.\n— Універсальність. Працює і при вікових змінах, і при постакне, і при відновленні після хвороб, і у трихології.\n— Добра поєднуваність. Чудово комбінується з мезотерапією, біоревіталізацією, апаратними процедурами. Особливо цінний у комплексних програмах після лазерних процедур.\n— Мінімальна реабілітація. Соціально «невидима» процедура: легкі почервоніння проходять за декілька годин.\n\nОбмеження методу:\n\n— Залежність від стану здоров'я пацієнта. Молода, здорова плазма працює помітно краще, ніж плазма пацієнта з анемією, хронічними захворюваннями, активним курінням.\n— Необхідність курсу. Одна процедура — слабкий ефект. Стабільний результат — лише після 3–4 процедур.\n— Менш виражений ефект, ніж у філерів і екзосом. PRP — про якість шкіри, не про реструктуризацію обличчя.\n— Неможливість корекції. На відміну від гіалуронових філерів, PRP не можна «розчинити»: після ін'єкції плазма розподіляється по тканинах і стає частиною шкіри.\n— Вартість. Якісна PRP-процедура дорожча, ніж може здатись: у неї входить робота лікаря, стерильна обладнання, сертифікована центрифуга.",
        ru: "Преимущества PRP-терапии:\n\n— Биосовместимость. Используется ваша собственная плазма — нулевой риск аллергии, отторжения, аллергенных реакций.\n— Природный механизм. PRP не «добавляет» коже веществ извне, а стимулирует её собственные резервы. Результат всегда естественный за счёт вашей же биологии.\n— Универсальность. Работает и при возрастных изменениях, и при постакне, и при восстановлении после болезней, и в трихологии.\n— Хорошая сочетаемость. Прекрасно комбинируется с мезотерапией, биоревитализацией, аппаратными процедурами. Особенно ценна в комплексных программах после лазерных процедур.\n— Минимальная реабилитация. Социально «невидимая» процедура: лёгкие покраснения проходят за несколько часов.\n\nОграничения метода:\n\n— Зависимость от состояния здоровья пациента. Молодая, здоровая плазма работает заметно лучше, чем плазма пациента с анемией, хроническими заболеваниями, активным курением.\n— Необходимость курса. Одна процедура — слабый эффект. Стабильный результат — только после 3–4 процедур.\n— Менее выраженный эффект, чем у филлеров и экзосом. PRP — о качестве кожи, не о реструктуризации лица.\n— Невозможность коррекции. В отличие от гиалуроновых филлеров, PRP нельзя «растворить»: после инъекции плазма распределяется по тканям и становится частью кожи.\n— Стоимость. Качественная PRP-процедура дороже, чем может показаться: в неё входит работа врача, стерильное оборудование, сертифицированная центрифуга.",
        en: "Strengths of PRP therapy:\n\n— Biocompatibility. Your own plasma — zero risk of allergy, rejection or allergenic reactions.\n— Natural mechanism. PRP doesn't add external substances but activates the skin's own reserves. Results look natural because they come from your biology.\n— Versatility. Works for ageing, post-acne, recovery after illness and trichology.\n— Combines well. Pairs beautifully with mesotherapy, biorevitalisation and apparatus treatments — especially valuable in complex programs after laser procedures.\n— Minimal downtime. Socially invisible: mild redness clears in a few hours.\n\nLimitations:\n\n— Patient-health dependent. Young, healthy plasma works noticeably better than plasma from patients with anaemia, chronic conditions or active smoking.\n— Course required. A single session has weak effects. Stable results need 3-4 sessions.\n— Less pronounced than fillers or exosomes. PRP addresses skin quality, not facial restructuring.\n— No reversal. Unlike hyaluronic fillers, PRP can't be \"dissolved\" — once injected, plasma diffuses into tissue.\n— Cost. Quality PRP is more expensive than it might look: doctor's time, sterile equipment, certified centrifuge.",
      },
      calloutBody: {
        uk: "Якщо хтось пропонує вам «PRP за ціною мезотерапії» — запитайте про центрифугу і сертифікат. Дешева PRP — це часто звичайна плазма без достатньої концентрації тромбоцитів. Ви платите за ту ж процедуру, але отримуєте 30% результату.",
        ru: "Если кто-то предлагает вам «PRP по цене мезотерапии» — спросите о центрифуге и сертификате. Дешёвая PRP — это часто обычная плазма без достаточной концентрации тромбоцитов. Вы платите за ту же процедуру, но получаете 30% результата.",
        en: "If someone offers \"PRP at the price of mesotherapy\" — ask about the centrifuge and certification. Cheap PRP is often just ordinary plasma without sufficient platelet concentration. You pay for the same procedure but get 30% of the result.",
      },
    },
  ],
  faq: [
    { question: { uk: "Скільки триває ефект від PRP-терапії?", ru: "Сколько держится эффект от PRP-терапии?", en: "How long does PRP last?" },
      answer: { uk: "Після повного курсу з 3–4 процедур результат тримається 6–12 місяців. Точна тривалість залежить від віку, загального стану здоров'я, способу життя. У молодих пацієнтів (до 35 років) результат зазвичай стабільніший і довший. Для підтримки рекомендуємо 1 процедуру на 6–9 місяців.",
        ru: "После полного курса из 3–4 процедур результат держится 6–12 месяцев. Точная длительность зависит от возраста, общего состояния здоровья, образа жизни. У молодых пациентов (до 35 лет) результат обычно стабильнее и длительнее. Для поддержки рекомендуем 1 процедуру в 6–9 месяцев.",
        en: "After a full course of 3-4 sessions the result lasts 6-12 months. Duration depends on age, general health, lifestyle. For younger patients (under 35) the result is usually more stable and longer-lasting. Maintenance: one session every 6-9 months." }},
    { question: { uk: "Чи болюча процедура PRP-терапії?", ru: "Болезненная ли процедура PRP-терапии?", en: "Is PRP painful?" },
      answer: { uk: "Забір крові — як звичайний аналіз, мінімум дискомфорту. Самі ін'єкції — з легкими поколюваннями, але не болючі завдяки аплікаційній анестезії (лідокаїновий крем на 15–20 хвилин перед процедурою). Більшість пацієнтів оцінюють дискомфорт на 2–3 з 10 за шкалою болю.",
        ru: "Забор крови — как обычный анализ, минимум дискомфорта. Сами инъекции — с лёгкими покалываниями, но не болезненные благодаря аппликационной анестезии (лидокаиновый крем на 15–20 минут перед процедурой). Большинство пациентов оценивают дискомфорт на 2–3 из 10 по шкале боли.",
        en: "Blood draw is like a standard lab test — minimal discomfort. The injections feel like light pinching but aren't painful thanks to topical anaesthesia (lidocaine cream for 15-20 minutes before). Most patients rate discomfort at 2-3 out of 10." }},
    { question: { uk: "Скільки сеансів PRP-терапії необхідно для досягнення результату?", ru: "Сколько сеансов PRP-терапии необходимо для достижения результата?", en: "How many PRP sessions are needed?" },
      answer: { uk: "Мінімальний курс — 3 процедури з інтервалом 3–4 тижні. Оптимальний — 4 процедури, особливо для зрілої шкіри або постакне. Перша процедура дає ефект свіжості, друга закріплює пружність, третя-четверта забезпечують стабільне глибоке омолодження. Для трихологічного PRP (волосся) курс може бути довшим — 4–6 процедур.",
        ru: "Минимальный курс — 3 процедуры с интервалом 3–4 недели. Оптимальный — 4 процедуры, особенно для зрелой кожи или постакне. Первая процедура даёт эффект свежести, вторая закрепляет упругость, третья-четвёртая обеспечивают стабильное глубокое омоложение. Для трихологического PRP (волосы) курс может быть длиннее — 4–6 процедур.",
        en: "Minimum course: 3 sessions at 3-4 week intervals. Optimal: 4 sessions, especially for mature skin or post-acne. The first session delivers freshness, the second consolidates firmness, the third-fourth establish stable deep rejuvenation. Trichology PRP for hair often needs a longer course — 4-6 sessions." }},
    { question: { uk: "Чи можна поєднувати PRP-терапію з іншими косметологічними процедурами?", ru: "Можно ли сочетать PRP-терапию с другими косметологическими процедурами?", en: "Can PRP be combined with other treatments?" },
      answer: { uk: "Так, PRP чудово поєднується з більшістю процедур. Класичні комбінації: PRP + біоревіталізація (підсилюють одна одну, робимо з інтервалом 1–2 тижні); PRP + мезотерапія (одна процедура — регенерація, інша — живлення); PRP + мікронідлінг (часто роблять в один день — канали у шкірі дозволяють плазмі проникнути глибше); PRP після лазерного шліфування — прискорює відновлення шкіри у рази.",
        ru: "Да, PRP прекрасно сочетается с большинством процедур. Классические комбинации: PRP + биоревитализация (усиливают друг друга, делаем с интервалом 1–2 недели); PRP + мезотерапия (одна процедура — регенерация, другая — питание); PRP + микронидлинг (часто делают в один день — каналы в коже позволяют плазме проникнуть глубже); PRP после лазерной шлифовки — ускоряет восстановление кожи в разы.",
        en: "Yes — PRP combines well with most procedures. Classic combinations: PRP + biorevitalisation (mutually reinforcing, 1-2 week interval); PRP + mesotherapy (one is regeneration, the other nourishment); PRP + microneedling (often done the same day — the channels let plasma penetrate deeper); PRP after laser resurfacing — accelerates skin recovery multiple times over." }},
    { question: { uk: "Які побічні ефекти можливі після PRP?", ru: "Какие побочные эффекты возможны после PRP?", en: "What side effects are possible?" },
      answer: { uk: "Побічні ефекти PRP — мінімальні, оскільки препарат власний. Можливі: легкі почервоніння у місцях ін'єкцій (проходять за 2–6 годин), короткочасна набряклість (до 24 годин), невеликі гематоми у 10–15% випадків (4–7 днів). Дуже рідко — головний біль або короткочасне нездужання в перші години після процедури. Серйозні ускладнення практично неможливі за умови сертифікованого обладнання і стерильної техніки.",
        ru: "Побочные эффекты PRP — минимальные, поскольку препарат собственный. Возможны: лёгкие покраснения в местах инъекций (проходят за 2–6 часов), кратковременная отёчность (до 24 часов), небольшие гематомы в 10–15% случаев (4–7 дней). Очень редко — головная боль или кратковременное недомогание в первые часы после процедуры. Серьёзные осложнения практически невозможны при условии сертифицированного оборудования и стерильной техники.",
        en: "Side effects are minimal since the preparation is your own. Possible: mild redness at injection sites (2-6 hours), brief swelling (up to 24 hours), small bruises in 10-15% of cases (4-7 days). Rarely — headache or brief malaise in the first few hours. Serious complications are effectively impossible with certified equipment and sterile technique." }},
    { question: { uk: "Скільки коштує PRP-терапія у Дніпрі?", ru: "Сколько стоит PRP-терапия в Днепре?", en: "What does PRP cost in Dnipro?" },
      answer: { uk: "Ціна однієї процедури PRP-терапії залежить від об'єму забраної крові, зони обробки і техніки введення (мануальна, з мезоінжектором, комбінована з мікронідлінгом). У GENEVITY базова вартість однієї процедури вказана у прайсі на цій сторінці; курс із 3–4 процедур пропонуємо за зниженою ціною за сеанс. Ціна включає роботу лікаря, стерильну систему забору крові, сертифіковане центрифугування.",
        ru: "Цена одной процедуры PRP-терапии зависит от объёма забираемой крови, зоны обработки и техники введения (мануальная, с мезоинжектором, комбинированная с микронидлингом). В GENEVITY базовая стоимость одной процедуры указана в прайсе на этой странице; курс из 3–4 процедур предлагаем по сниженной цене за сеанс. Цена включает работу врача, стерильную систему забора крови, сертифицированное центрифугирование.",
        en: "Single-session price depends on the blood volume drawn, treatment area and technique (manual, meso-injector, or combined with microneedling). GENEVITY's base single-session pricing is on the list on this page; a 3-4 session course is offered at a reduced per-session rate. The price includes the doctor's time, sterile blood-draw system and certified centrifugation." }},
  ],
};

async function applyService(copy: ServiceCopy) {
  const svc = await sql`SELECT id FROM services WHERE slug = ${copy.slug} LIMIT 1`;
  if (!svc[0]) { console.error(`✗ ${copy.slug} not found`); return; }
  const id = svc[0].id as string;
  await sql`UPDATE services SET summary_uk=${copy.summary.uk}, summary_ru=${copy.summary.ru}, summary_en=${copy.summary.en} WHERE id=${id}`;
  await sql`DELETE FROM content_sections WHERE owner_type='service' AND owner_id=${id}`;
  await sql`DELETE FROM faq_items WHERE owner_type='service' AND owner_id=${id}`;
  const sectionIds: string[] = [];
  for (let i = 0; i < copy.sections.length; i++) {
    const s = copy.sections[i]; const sid = randomUUID(); sectionIds.push(sid);
    const data = { heading: s.heading, body: s.body, calloutBody: s.calloutBody, heroImage: null };
    await sql`INSERT INTO content_sections (id, owner_type, owner_id, sort_order, section_type, data) VALUES (${sid}, 'service', ${id}, ${i}, 'richText'::section_type, ${JSON.stringify(data)}::jsonb)`;
  }
  for (let i = 0; i < copy.faq.length; i++) {
    const f = copy.faq[i];
    await sql`INSERT INTO faq_items (owner_type, owner_id, sort_order, question_uk, question_ru, question_en, answer_uk, answer_ru, answer_en) VALUES ('service', ${id}, ${i}, ${f.question.uk}, ${f.question.ru}, ${f.question.en}, ${f.answer.uk}, ${f.answer.ru}, ${f.answer.en})`;
  }
  const order = [...sectionIds.map((s) => `section:${s}`), "faq", "doctors", "equipment", "relatedServices", "finalCTA"];
  await sql`UPDATE services SET block_order=${order} WHERE id=${id}`;
  console.log(`✓ ${copy.slug} — ${copy.sections.length} sections, ${copy.faq.length} FAQs`);
}

async function main() {
  for (const c of [contourPlasty, prp]) await applyService(c);
  await sql.end();
  console.log("\nV2a DONE — continuing with V2b (stem cells + rejuran)");
}
main().catch((e) => { console.error(e); process.exit(1); });
