/**
 * V3a — EMFACE, VOLNEWMER, EXION, Ultraformer MPT
 * Apparatus cosmetology, face-focused energy devices.
 * Run: npx tsx scripts/seed-copy-v3a.ts
 */
import postgres from "postgres";
import * as fs from "fs";
import * as path from "path";
import { randomUUID } from "crypto";

const envContent = fs.readFileSync(path.resolve(__dirname, "../.env.local"), "utf-8");
const env: Record<string, string> = {};
envContent.split("\n").forEach((l) => {
  const [k, ...v] = l.split("=");
  if (k && v.length) env[k.trim()] = v.join("=").trim();
});
const sql = postgres(env.DATABASE_URL!);

type L = { uk: string; ru: string; en: string };
interface SectionCopy { heading: L; body: L; calloutBody: L; }
interface FaqCopy { question: L; answer: L; }
interface ServiceCopy { slug: string; summary: L; sections: SectionCopy[]; faq: FaqCopy[]; }

const SERVICES: ServiceCopy[] = [
  {
    slug: "emface",
    summary: {
      uk: "EMFACE у GENEVITY — єдина безін'єкційна процедура, яка одночасно зміцнює м'язовий каркас обличчя і підвищує щільність шкіри. Синхронізована дія RF-енергії та HIFES-імпульсів — без голок, без відновлення, із задокументованим скороченням зморшок на 37% після курсу.",
      ru: "EMFACE в GENEVITY — единственная безинъекционная процедура, которая одновременно укрепляет мышечный каркас лица и повышает плотность кожи. Синхронизированное действие RF-энергии и HIFES-импульсов — без игл, без восстановления, с задокументированным сокращением морщин на 37% после курса.",
      en: "EMFACE at GENEVITY — the only needle-free procedure that simultaneously strengthens the facial muscle framework and increases skin density. Synchronised RF energy and HIFES impulses — no needles, no downtime, with documented wrinkle reduction of 37% after a course.",
    },
    sections: [
      {
        heading: { uk: "Як працює EMFACE", ru: "Как работает EMFACE", en: "How EMFACE works" },
        body: {
          uk: "EMFACE — апаратна процедура від BTL Aesthetics, яка поєднує дві технології в одному накладному аплікаторі: радіочастотний нагрів (RF) і HIFES — High-Intensity Facial Electromagnetic Stimulation.\n\nRF-енергія нагріває дерму до 40–43°C, що запускає неоколагенез і неоеластиногенез — утворення нових волокон колагену та еластину. Шкіра стає щільнішою, пружнішою, дрібніші зморшки розгладжуються.\n\nHIFES-імпульси синхронно скорочують мімічні м'язи з частотою й інтенсивністю, недосяжною при звичайних тренуваннях. За одну 20-хвилинну сесію м'яз отримує близько 20 000 скорочень. Результат — підвищення тонусу м'язів-ліфтерів обличчя (musculus zygomaticus, musculus risorius, лобовий і скроневий м'яз), що механічно піднімає тканини і відновлює вертикальний вектор, втрачений з роком.\n\nСтандартний курс — 4 сесії з інтервалом 5–7 днів. Клінічні дослідження BTL показують: після курсу скорочення зморшок на 37%, підвищення тонусу м'язів на 23%, підйом брів на 4,7 мм — верифіковані дані з опублікованих peer-reviewed досліджень.\n\nПроцедура не потребує анестезії, не залишає слідів на шкірі, не обмежує соціальну активність.",
          ru: "EMFACE — аппаратная процедура от BTL Aesthetics, совмещающая две технологии в одном накладном аппликаторе: радиочастотный нагрев (RF) и HIFES — High-Intensity Facial Electromagnetic Stimulation.\n\nRF-энергия нагревает дерму до 40–43°C, запуская неоколлагенез и неоэластиногенез — образование новых волокон коллагена и эластина. Кожа становится плотнее, эластичнее, мелкие морщины разглаживаются.\n\nHIFES-импульсы синхронно сокращают мимические мышцы с частотой и интенсивностью, недостижимой при обычных тренировках. За одну 20-минутную сессию мышца получает около 20 000 сокращений. Результат — повышение тонуса мышц-лифтеров лица (musculus zygomaticus, musculus risorius, лобовая и височная мышца), что механически поднимает ткани и восстанавливает вертикальный вектор, утраченный с годами.\n\nСтандартный курс — 4 сессии с интервалом 5–7 дней. Клинические исследования BTL показывают: после курса сокращение морщин на 37%, повышение тонуса мышц на 23%, подъём бровей на 4,7 мм — верифицированные данные из опубликованных peer-reviewed исследований.\n\nПроцедура не требует анестезии, не оставляет следов на коже, не ограничивает социальную активность.",
          en: "EMFACE is a device-based procedure from BTL Aesthetics combining two technologies in one adhesive applicator: radiofrequency heating (RF) and HIFES — High-Intensity Facial Electromagnetic Stimulation.\n\nRF energy heats the dermis to 40–43°C, triggering neocollagenesis and neoelastinogenesis — the formation of new collagen and elastin fibres. The skin becomes denser, more elastic, and fine lines smooth out.\n\nHIFES impulses synchronously contract the expression muscles at a frequency and intensity impossible to achieve with ordinary exercise. In a single 20-minute session, the muscle receives approximately 20,000 contractions. The result is improved tone in the facial lifting muscles (musculus zygomaticus, musculus risorius, frontalis and temporalis), which mechanically elevates tissue and restores the vertical vector lost over the years.\n\nThe standard course is 4 sessions at 5–7 day intervals. BTL clinical studies show: after the course — 37% wrinkle reduction, 23% muscle tone improvement, 4.7 mm eyebrow elevation — all verified in published peer-reviewed research.\n\nNo anaesthesia, no visible marks on skin, no social downtime.",
        },
        calloutBody: {
          uk: "EMFACE — не альтернатива ботоксу і не альтернатива філерам. Це інший вектор роботи: зміцнення анатомічного каркасу, а не корекція слідів його слабкості. Найкращий результат — в комбінації, а не замість.",
          ru: "EMFACE — не альтернатива ботоксу и не альтернатива филлерам. Это другой вектор работы: укрепление анатомического каркаса, а не коррекция следов его слабости. Лучший результат — в комбинации, а не вместо.",
          en: "EMFACE is not an alternative to botox or fillers. It works on a different vector: strengthening the anatomical framework rather than correcting the signs of its weakness. Best results come in combination, not instead.",
        },
      },
      {
        heading: { uk: "Кому підходить EMFACE", ru: "Кому подходит EMFACE", en: "Who EMFACE is for" },
        body: {
          uk: "EMFACE ефективний у тих ситуаціях, коли обличчя втрачає не лише об'єм і пружність шкіри, але й тонус м'язового каркасу — що відбувається починаючи з 30–35 років.\n\nГоловні показання:\n— опущення брів і повік (птоз), ранній або початковий ступінь;\n— втрата чіткості овалу обличчя через слабкість musculus platysma і кутових м'язів;\n— горизонтальні зморшки на чолі — ознака гіперактивності лобового м'яза, що компенсує слабкість верхнього ліфтера;\n— загальна «стомленість» обличчя — воно виглядає сумнішим або старшим, ніж людина себе відчуває;\n— профілактика вікових змін у 30–40 років, коли симптоми ще відсутні, але м'язовий тонус починає знижуватися;\n— альтернатива ін'єкціям — для тих, хто уникає голок з принципу або через медичні протипоказання.\n\nКурс EMFACE добре комбінується з:\n— ботулінотерапією (RF посилює регенерацію навколо ін'єкцій);\n— філерами (м'язовий тонус утримує введений об'єм у правильній позиції довше);\n— Ultraformer MPT (HIFU на глибоку SMAS-зону + EMFACE на поверхневий м'язовий шар).\n\nНЕ підходить для: вагітних, людей із кардіостимуляторами та металевими імплантами в зоні лікування, епілепсії, активних запальних процесів на шкірі, тяжкого птозу що потребує хірургії.",
          ru: "EMFACE эффективен в тех ситуациях, когда лицо теряет не только объём и упругость кожи, но и тонус мышечного каркаса — что происходит начиная с 30–35 лет.\n\nГлавные показания:\n— опущение бровей и век (птоз), ранняя или начальная степень;\n— потеря чёткости овала лица из-за слабости musculus platysma и угловых мышц;\n— горизонтальные морщины на лбу — признак гиперактивности лобовой мышцы, компенсирующей слабость верхнего лифтера;\n— общая «усталость» лица — оно выглядит грустнее или старше, чем человек себя чувствует;\n— профилактика возрастных изменений в 30–40 лет, когда симптомы ещё отсутствуют, но мышечный тонус начинает снижаться;\n— альтернатива инъекциям — для тех, кто избегает игл принципиально или по медицинским противопоказаниям.\n\nКурс EMFACE хорошо комбинируется с:\n— ботулинотерапией (RF усиливает регенерацию вокруг инъекций);\n— филлерами (мышечный тонус удерживает введённый объём в правильной позиции дольше);\n— Ultraformer MPT (HIFU на глубокую SMAS-зону + EMFACE на поверхностный мышечный слой).\n\nНЕ подходит для: беременных, людей с кардиостимуляторами и металлическими имплантами в зоне лечения, эпилепсии, активных воспалительных процессов на коже, тяжёлого птоза, требующего хирургии.",
          en: "EMFACE is most effective when the face is losing not just volume and skin elasticity, but also the tone of the muscular framework — something that begins in the mid-30s.\n\nMain indications:\n— brow and eyelid ptosis, early or mild degree;\n— loss of jaw-oval definition due to weakness in the platysma and corner muscles;\n— horizontal forehead lines — a sign that the frontalis is overworking to compensate for a weak upper lifter;\n— general facial 'tiredness' — the face reads as sadder or older than the person feels;\n— prevention of ageing changes in the 30s–40s, when symptoms are still absent but muscle tone is beginning to decline;\n— an alternative to injections for those who avoid needles on principle or for medical reasons.\n\nEMFACE combines well with:\n— botulinum therapy (RF enhances tissue regeneration around injection sites);\n— fillers (improved muscle tone holds the injected volume in the right position longer);\n— Ultraformer MPT (HIFU targets the deep SMAS layer while EMFACE works the superficial muscle layer).\n\nNOT suitable for: pregnancy, pacemakers or metal implants in the treatment zone, epilepsy, active skin inflammation, severe ptosis requiring surgery.",
        },
        calloutBody: {
          uk: "Ефект EMFACE накопичується і продовжується після курсу: колагенез триває 3–6 місяців після останньої сесії. Перша помітна різниця — зазвичай після 2-ї процедури, пік результату — через 3 місяці після курсу.",
          ru: "Эффект EMFACE накапливается и продолжается после курса: коллагенез длится 3–6 месяцев после последней сессии. Первая заметная разница — обычно после 2-й процедуры, пик результата — через 3 месяца после курса.",
          en: "EMFACE's effect accumulates and continues after the course: collagenesis continues for 3-6 months after the last session. The first noticeable change usually comes after the 2nd session; the peak result arrives about 3 months post-course.",
        },
      },
      {
        heading: { uk: "Як проходить процедура", ru: "Как проходит процедура", en: "What a session is like" },
        body: {
          uk: "Сесія EMFACE триває 20 хвилин. Пацієнт лежить горизонтально, на шкіру наносяться 4 аплікатори — на лоб і на щоки. Жодної голки, жодного гелю, жодної анестезії не потрібно.\n\nПід час процедури відчувається тепло від RF і ритмічні скорочення м'язів від HIFES — як «тремтіння» або «легкі судоми». Інтенсивність налаштовується під комфорт пацієнта. Більшість клієнтів описують відчуття як «дивно, але не боляче» і засинають під час сесії.\n\nПісля процедури:\n— шкіра може бути злегка рожевою 30–60 хвилин (нормальна реакція на RF-нагрів);\n— м'язи щік і чола можуть відчуватися «напруженими», як після тренування — проходить протягом доби;\n— макіяж — одразу; спорт, сауна, пілінг — наступного дня.\n\nСтандартний курс — 4 сесії. Підтримуючий сеанс — 1 раз на 3–6 місяців. Для тих, хто робить EMFACE вперше: рекомендуємо зробити фото до 1-ї і через 2 тижні після 4-ї сесії — зміна рельєфу й підйом брів помітні на фото, навіть коли на дзеркалі їх «не видно».",
          ru: "Сессия EMFACE длится 20 минут. Пациент лежит горизонтально, на кожу накладываются 4 аппликатора — на лоб и на щёки. Никакой иглы, никакого геля, никакой анестезии не нужно.\n\nВо время процедуры ощущается тепло от RF и ритмичные сокращения мышц от HIFES — как «дрожание» или «лёгкие судороги». Интенсивность настраивается под комфорт пациента. Большинство клиентов описывают ощущения как «странно, но не больно» и засыпают во время сессии.\n\nПосле процедуры:\n— кожа может быть слегка розовой 30–60 минут (нормальная реакция на RF-нагрев);\n— мышцы щёк и лба могут ощущаться «напряжёнными», как после тренировки — проходит в течение суток;\n— макияж — сразу; спорт, сауна, пилинг — на следующий день.\n\nСтандартный курс — 4 сессии. Поддерживающий сеанс — 1 раз в 3–6 месяцев. Для тех, кто делает EMFACE впервые: рекомендуем сделать фото до 1-й и через 2 недели после 4-й сессии — изменение рельефа и подъём бровей заметны на фото, даже когда в зеркале их «не видно».",
          en: "An EMFACE session takes 20 minutes. The patient lies down; four applicators are placed on the face — forehead and cheeks. No needle, no gel, no anaesthesia.\n\nDuring the session you feel warmth from the RF and rhythmic muscle contractions from HIFES — a 'trembling' or 'mild twitching'. Intensity is adjusted to patient comfort. Most clients describe it as 'strange but not painful' and many doze off.\n\nAfterward:\n— slight skin redness for 30-60 minutes (normal RF reaction);\n— the cheek and forehead muscles may feel 'tensed', like after a workout — resolves within a day;\n— makeup immediately; exercise, sauna, peels — the next day.\n\nStandard course: 4 sessions. Maintenance: once every 3-6 months. For first-timers: take photos before session 1 and two weeks after session 4 — the change in contour and brow elevation shows clearly in photos even when it seems invisible in the mirror.",
        },
        calloutBody: {
          uk: "20 хвилин — це рівно стільки, скільки займає сесія. Ми не розтягуємо час і не доповнюємо процедуру платними «бонусами». Якщо потрібно більше впливу — вирішуємо на повторному огляді.",
          ru: "20 минут — это ровно столько, сколько занимает сессия. Мы не растягиваем время и не дополняем процедуру платными «бонусами». Если нужно больше воздействия — решаем на повторном осмотре.",
          en: "20 minutes is exactly how long a session takes. We don't stretch the time or add paid 'bonuses'. If more treatment is needed, we decide at the follow-up visit.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "Скільки коштує EMFACE у GENEVITY?", ru: "Сколько стоит EMFACE в GENEVITY?", en: "How much does EMFACE cost at GENEVITY?" },
        answer: { uk: "Актуальні ціни на EMFACE вказані у прайс-листі на цій сторінці. Стандартний курс — 4 сесії; за наявності акцій або пакетного запису ціна може відрізнятися — уточнюйте при бронюванні.", ru: "Актуальные цены на EMFACE указаны в прайс-листе на этой странице. Стандартный курс — 4 сессии; при наличии акций или пакетной записи цена может отличаться — уточняйте при бронировании.", en: "Current EMFACE prices are on the price list on this page. The standard course is 4 sessions; promotional or package rates may differ — confirm when booking." },
      },
      {
        question: { uk: "Після скількох процедур видно результат?", ru: "После скольких процедур виден результат?", en: "After how many sessions is the result visible?" },
        answer: { uk: "Перша помітна різниця — після 2-ї сесії (зазвичай пружніша шкіра і легкий підйом рельєфу). Повний результат розкривається через 2–3 місяці після завершення курсу з 4 сесій, поки активний неоколагенез.", ru: "Первая заметная разница — после 2-й сессии (обычно более упругая кожа и лёгкий подъём рельефа). Полный результат раскрывается через 2–3 месяца после завершения курса из 4 сессий, пока активен неоколлагенез.", en: "The first noticeable change is usually after session 2 (firmer skin, slight lift in contour). The full result unfolds 2-3 months after completing the 4-session course, while neocollagenesis is still active." },
      },
      {
        question: { uk: "EMFACE чи ботокс — що вибрати?", ru: "EMFACE или ботокс — что выбрать?", en: "EMFACE or botox — which to choose?" },
        answer: { uk: "Вони вирішують різні задачі. Ботокс розслаблює гіперактивний м'яз, що залишив слід-зморшку. EMFACE зміцнює весь м'язовий каркас, відновлюючи вертикальний вектор тканин. Оптимально — поєднувати: спочатку курс EMFACE, потім ботокс за показаннями в окремих зонах.", ru: "Они решают разные задачи. Ботокс расслабляет гиперактивную мышцу, которая оставила след-морщину. EMFACE укрепляет весь мышечный каркас, восстанавливая вертикальный вектор тканей. Оптимально — сочетать: сначала курс EMFACE, затем ботокс по показаниям в отдельных зонах.", en: "They solve different problems. Botox relaxes a hyperactive muscle that has left a wrinkle. EMFACE strengthens the entire muscular framework, restoring the vertical tissue vector. The optimal approach is to combine: an EMFACE course first, then botox as indicated in specific zones." },
      },
      {
        question: { uk: "Як довго тримається ефект EMFACE?", ru: "Как долго держится эффект EMFACE?", en: "How long does the EMFACE effect last?" },
        answer: { uk: "Ефект від курсу 4 сесій тримається 6–12 місяців залежно від вихідного тонусу м'язів і способу життя. Підтримуючий сеанс раз на 3–6 місяців подовжує результат.", ru: "Эффект от курса 4 сессий держится 6–12 месяцев в зависимости от исходного тонуса мышц и образа жизни. Поддерживающий сеанс раз в 3–6 месяцев продлевает результат.", en: "The effect from a 4-session course lasts 6-12 months depending on baseline muscle tone and lifestyle. A maintenance session every 3-6 months extends the result." },
      },
      {
        question: { uk: "Чи є протипоказання до EMFACE?", ru: "Есть ли противопоказания к EMFACE?", en: "Are there contraindications to EMFACE?" },
        answer: { uk: "Абсолютні: вагітність, кардіостимулятор або будь-який металевий імплант у зоні лікування, епілепсія, активні запальні процеси на шкірі обличчя. Відносні: ботокс менш ніж 2 тижні тому (краще почекати 2 тижні після ін'єкцій), важкий птоз що потребує хірургії.", ru: "Абсолютные: беременность, кардиостимулятор или любой металлический имплант в зоне лечения, эпилепсия, активные воспалительные процессы на коже лица. Относительные: ботокс менее 2 недель назад (лучше подождать 2 недели после инъекций), тяжёлый птоз, требующий хирургии.", en: "Absolute: pregnancy, pacemaker or any metal implant in the treatment zone, epilepsy, active facial skin inflammation. Relative: botox less than 2 weeks ago (better to wait), severe ptosis requiring surgery." },
      },
    ],
  },

  // ─── VOLNEWMER ─────────────────────────────────────────────────────────────
  {
    slug: "volnewmer",
    summary: {
      uk: "VOLNEWMER у GENEVITY — монополярна RF-терапія для глибокого прогрівання дерми та підшкірних тканин: стимулює синтез нового колагену, підтягує контур обличчя, покращує тонус шкіри шиї та декольте. Без голок, без реабілітації, результат накопичується протягом 3–6 місяців.",
      ru: "VOLNEWMER в GENEVITY — монополярная RF-терапия для глубокого прогрева дермы и подкожных тканей: стимулирует синтез нового коллагена, подтягивает контур лица, улучшает тонус кожи шеи и декольте. Без игл, без реабилитации, результат накапливается в течение 3–6 месяцев.",
      en: "VOLNEWMER at GENEVITY — monopolar RF therapy for deep dermis and subcutaneous tissue heating: stimulates new collagen synthesis, tightens facial contour, improves neck and décolletage tone. No needles, no downtime, results accumulate over 3-6 months.",
    },
    sections: [
      {
        heading: { uk: "Як працює VOLNEWMER", ru: "Как работает VOLNEWMER", en: "How VOLNEWMER works" },
        body: {
          uk: "VOLNEWMER — апарат монополярної радіочастотної терапії від BTL Aesthetics. На відміну від біполярного RF (поверхневий нагрів між двома електродами на шкірі), монополярна система створює електромагнітне поле між аплікатором і заземлюючим електродом на тілі пацієнта. Завдяки цьому енергія проникає значно глибше — в підшкірну жирову клітковину (1,5–2 см) — і рівномірно нагріває глибокі шари дерми та субдермальний шар.\n\nЩо відбувається у тканинах:\n— При нагріві до 40–43°C фібробласти активізуються і посилено синтезують проколаген. Новий колаген дозріває протягом 3–6 місяців після процедури — тому ефект накопичується і продовжується довго після завершення курсу.\n— Одночасний нагрів жирової клітковини стимулює ліполіз у поверхневих ліпідних структурах, що знижує набряклість і покращує рельєф (особливо у зоні обличчя «другий підборіддя»).\n— Тепловий ефект скорочує наявні колагенові волокна («вплив на старий колаген»), що дає негайний підтягуючий ефект вже після першої процедури.\n\nSTANDARD VOLNEWMER має 4 режими: FACE (обличчя і шия), BODY (тіло, живіт, стегна), EYE (периорбітальна зона), PLUS (посилений нагрів для щільних тканин). GENEVITY використовує всі режими залежно від зони і завдання.",
          ru: "VOLNEWMER — аппарат монополярной радиочастотной терапии от BTL Aesthetics. В отличие от биполярного RF (поверхностный нагрев между двумя электродами на коже), монополярная система создаёт электромагнитное поле между аппликатором и заземляющим электродом на теле пациента. Благодаря этому энергия проникает значительно глубже — в подкожную жировую клетчатку (1,5–2 см) — и равномерно нагревает глубокие слои дермы и субдермальный слой.\n\nЧто происходит в тканях:\n— При нагреве до 40–43°C фибробласты активизируются и усиленно синтезируют проколлаген. Новый коллаген созревает в течение 3–6 месяцев после процедуры — поэтому эффект накапливается и продолжается долго после завершения курса.\n— Одновременный нагрев жировой клетчатки стимулирует липолиз в поверхностных липидных структурах, что снижает отёчность и улучшает рельеф (особенно в зоне «второй подбородок»).\n— Тепловой эффект сокращает имеющиеся коллагеновые волокна («воздействие на старый коллаген»), что даёт немедленный лифтинговый эффект уже после первой процедуры.\n\nSTANDARD VOLNEWMER имеет 4 режима: FACE (лицо и шея), BODY (тело, живот, бёдра), EYE (периорбитальная зона), PLUS (усиленный нагрев для плотных тканей). GENEVITY использует все режимы в зависимости от зоны и задачи.",
          en: "VOLNEWMER is a monopolar radiofrequency therapy device from BTL Aesthetics. Unlike bipolar RF (surface heating between two electrodes on the skin), a monopolar system creates an electromagnetic field between the applicator and a grounding electrode placed on the patient's body. This allows the energy to penetrate considerably deeper — into the subcutaneous fat layer (1.5–2 cm) — uniformly heating the deep dermis and subdermal layer.\n\nWhat happens in the tissues:\n— Heating to 40–43°C activates fibroblasts, which ramp up procollagen synthesis. The new collagen matures over 3–6 months after the procedure — so the effect accumulates and continues well beyond the end of the course.\n— Simultaneous heating of the fat tissue stimulates lipolysis in superficial lipid structures, reducing puffiness and improving contour (especially in the submental/double-chin zone).\n— The thermal effect contracts existing collagen fibres ('old collagen impact'), giving an immediate tightening effect even after the first session.\n\nThe STANDARD VOLNEWMER has 4 modes: FACE (face and neck), BODY (abdomen, thighs), EYE (periorbital zone), PLUS (higher-intensity heating for dense tissue). GENEVITY uses all modes depending on the zone and goal.",
        },
        calloutBody: {
          uk: "Незручна правда про RF-апарати: ефект сильно залежить від температури у тканинах. Дешевший апарат часто не досягає терапевтичного нагріву — і дає слабкий результат. Ми контролюємо температуру шкіри у реальному часі під час кожної сесії VOLNEWMER.",
          ru: "Неудобная правда об RF-аппаратах: эффект сильно зависит от температуры в тканях. Более дешёвый аппарат часто не достигает терапевтического нагрева — и даёт слабый результат. Мы контролируем температуру кожи в реальном времени во время каждой сессии VOLNEWMER.",
          en: "The uncomfortable truth about RF devices: the effect depends heavily on reaching therapeutic temperature in the tissue. A cheaper device often fails to achieve this — and delivers weak results. We monitor skin temperature in real time during every VOLNEWMER session.",
        },
      },
      {
        heading: { uk: "Показання та зони роботи", ru: "Показания и зоны работы", en: "Indications and treatment zones" },
        body: {
          uk: "VOLNEWMER підходить для тих, хто хоче підтягнути шкіру і покращити контур без ін'єкцій і хірургії. Ефективні зони:\n\n— Обличчя. Підйом опущених тканин нижньої третини (брилі, кут щелепи). Покращення якості шкіри — її щільності і зволоженості (RF стимулює синтез гіалуронової кислоти у дермі).\n— Шия і декольте. Підтягування шкіри шиї — класична зона для VOLNEWMER. Поверхневий птоз шкіри, зморшки декольте — хороший відгук на монополярний RF.\n— Периорбітальна зона. Режим EYE — деліктний нагрів шкіри навколо очей: зменшення дрібних «гусячих лапок», покращення якості шкіри верхньої та нижньої повіки.\n— «Другий підборіддя». Поєднання ліполітичного та колагеностимулюючого ефекту дає помітний результат у цій зоні вже після 2–3 сесій.\n\nПоказання:\n— птоз і гравітаційне зміщення тканин обличчя;\n— зниження тургору і пружності шкіри;\n— поверхнева ліподистрофія (другий підборіддя, «бульдожні щоки»);\n— дрібні і середні зморшки (RF ефективніший при ранніх зморшках);\n— профілактика вікових змін.\n\nНЕ підходить при:\n— вагітності і грудному вигодовуванні;\n— кардіостимуляторі або металевих імплантах у зоні лікування;\n— злоякісних новоутвореннях;\n— активних запальних процесах шкіри.\n\nОптимально: курс 4–6 сесій з інтервалом 1–2 тижні, підтримка 1–2 рази на рік.",
          ru: "VOLNEWMER подходит для тех, кто хочет подтянуть кожу и улучшить контур без инъекций и хирургии. Эффективные зоны:\n\n— Лицо. Подъём опущенных тканей нижней трети (брыли, угол челюсти). Улучшение качества кожи — её плотности и увлажнённости (RF стимулирует синтез гиалуроновой кислоты в дерме).\n— Шея и декольте. Подтяжка кожи шеи — классическая зона для VOLNEWMER. Поверхностный птоз кожи, морщины декольте — хороший отклик на монополярный RF.\n— Периорбитальная зона. Режим EYE — деликатный нагрев кожи вокруг глаз: уменьшение мелких «гусиных лапок», улучшение качества кожи верхнего и нижнего века.\n— «Второй подбородок». Сочетание липолитического и коллагеностимулирующего эффекта даёт заметный результат в этой зоне уже после 2–3 сессий.\n\nПоказания:\n— птоз и гравитационное смещение тканей лица;\n— снижение тургора и упругости кожи;\n— поверхностная липодистрофия (второй подбородок, «бульдожьи щёки»);\n— мелкие и средние морщины (RF эффективнее при ранних морщинах);\n— профилактика возрастных изменений.\n\nНЕ подходит при:\n— беременности и грудном вскармливании;\n— кардиостимуляторе или металлических имплантах в зоне лечения;\n— злокачественных новообразованиях;\n— активных воспалительных процессах кожи.\n\nОптимально: курс 4–6 сессий с интервалом 1–2 недели, поддержка 1–2 раза в год.",
          en: "VOLNEWMER is for those who want to tighten skin and improve contour without injections or surgery. Effective zones:\n\n— Face. Lifting of descended lower-face tissue (jowls, jawline angle). Improving skin quality — density and hydration (RF stimulates hyaluronic acid synthesis in the dermis).\n— Neck and décolletage. Neck skin tightening is a classic VOLNEWMER zone. Surface ptosis, décolletage wrinkles — good response to monopolar RF.\n— Periorbital zone. EYE mode — gentle heating of the skin around the eyes: reduction of fine crow's feet, improving upper and lower lid skin quality.\n— Submental ('double chin'). The combination of lipolytic and collagen-stimulating effects delivers noticeable results in this zone after 2-3 sessions.\n\nIndications:\n— facial ptosis and gravitational tissue displacement;\n— loss of skin turgor and elasticity;\n— surface lipodystrophy (double chin, jowls);\n— fine-to-medium wrinkles (RF is most effective on early lines);\n— prevention of age-related changes.\n\nNOT suitable for: pregnancy, pacemaker or metal implants in the treatment zone, malignant tumours, active skin inflammation.\n\nOptimal: 4-6 session course at 1-2 week intervals, maintenance 1-2 times a year.",
        },
        calloutBody: {
          uk: "VOLNEWMER не робить ліфтинг на рівні SMAS-фасції — це зона HIFU (Ultraformer MPT). RF ліфтингує дерму і гіподерму. Комбінація VOLNEWMER + Ultraformer MPT вирішує обидва рівні одночасно.",
          ru: "VOLNEWMER не делает лифтинг на уровне SMAS-фасции — это зона HIFU (Ultraformer MPT). RF лифтингует дерму и гиподерму. Комбинация VOLNEWMER + Ultraformer MPT решает оба уровня одновременно.",
          en: "VOLNEWMER does not lift at the SMAS-fascia level — that is HIFU territory (Ultraformer MPT). RF lifts the dermis and hypodermis. Combining VOLNEWMER + Ultraformer MPT addresses both levels simultaneously.",
        },
      },
      {
        heading: { uk: "Що відбувається на сесії", ru: "Что происходит на сессии", en: "What happens during a session" },
        body: {
          uk: "Сесія VOLNEWMER для обличчя займає 30–45 хвилин, для комплексної зони (обличчя + шия + декольте) — до 60 хвилин. Послідовність:\n\n1. Очищення і розмітка. Шкіра очищається, косметолог розмічає зони впливу і встановлює заземлюючий електрод на спину або стегно.\n\n2. Нанесення провідного гелю. RF-аплікатор рухається по шкірі з гелем — він забезпечує рівномірний контакт і ковзання. На периорбітальну зону (режим EYE) гель не потрібен — спеціальний аплікатор без геля.\n\n3. Розігрів і підтримка температури. Косметолог контролює температуру шкіри пірометром: ціль — досягнути 40–42°C і підтримувати її 3–5 хвилин у кожній зоні. Це критично для ефективності: саме при цій температурі активуються фібробласти.\n\n4. Відчуття. Приємне тепло з наростанням. Інтенсивність налаштовується. Більшість клієнтів розслабляються або дрімають.\n\nПісля сесії:\n— шкіра може бути рожевою 30–60 хвилин, відчуватися теплою;\n— легкий набряк в перші 2–4 години (норма, особливо у зоні очей);\n— макіяж через 2 години; спорт, сауна — наступного дня;\n— SPF 30+ бажаний протягом 2 тижнів після процедури.",
          ru: "Сессия VOLNEWMER для лица занимает 30–45 минут, для комплексной зоны (лицо + шея + декольте) — до 60 минут. Последовательность:\n\n1. Очищение и разметка. Кожа очищается, косметолог размечает зоны воздействия и устанавливает заземляющий электрод на спину или бедро.\n\n2. Нанесение проводящего геля. RF-аппликатор движется по коже с гелем — он обеспечивает равномерный контакт и скольжение. На периорбитальную зону (режим EYE) гель не нужен — специальный аппликатор без геля.\n\n3. Разогрев и поддержание температуры. Косметолог контролирует температуру кожи пирометром: цель — достичь 40–42°C и поддерживать её 3–5 минут в каждой зоне. Это критично для эффективности: именно при этой температуре активируются фибробласты.\n\n4. Ощущения. Приятное тепло с нарастанием. Интенсивность настраивается. Большинство клиентов расслабляются или дремлют.\n\nПосле сессии:\n— кожа может быть розовой 30–60 минут, ощущаться тёплой;\n— лёгкий отёк в первые 2–4 часа (норма, особенно в зоне глаз);\n— макияж через 2 часа; спорт, сауна — на следующий день;\n— SPF 30+ желателен в течение 2 недель после процедуры.",
          en: "A VOLNEWMER session for the face takes 30-45 minutes; a combined zone (face + neck + décolletage) up to 60 minutes.\n\n1. Cleansing and mapping. Skin is cleansed, the specialist marks the treatment zones and places the grounding electrode on the back or thigh.\n\n2. Conductive gel. The RF applicator moves across the skin with gel for even contact and glide. The periorbital zone (EYE mode) uses a special gel-free applicator.\n\n3. Heating and temperature maintenance. The specialist monitors skin temperature with a pyrometer: the target is 40–42°C, maintained for 3-5 minutes per zone. This is critical to efficacy — fibroblasts activate at exactly this temperature.\n\n4. Sensations. Comfortable warmth building gradually. Intensity is adjustable. Most clients relax or doze.\n\nAfter the session:\n— skin may appear pink for 30-60 minutes and feel warm;\n— mild swelling for 2-4 hours (normal, especially around the eyes);\n— makeup after 2 hours; exercise, sauna — next day;\n— SPF 30+ recommended for 2 weeks post-treatment.",
        },
        calloutBody: {
          uk: "Ми наносимо гель у правильній кількості і контролюємо температуру пірометром під час кожного руху аплікатором. Якщо температура нижча за 40°C — ефект буде мінімальним. Більшість слабких результатів від RF у клініках — це результат поверхневого нагріву.",
          ru: "Мы наносим гель в правильном количестве и контролируем температуру пирометром во время каждого движения аппликатором. Если температура ниже 40°C — эффект будет минимальным. Большинство слабых результатов от RF в клиниках — это результат поверхностного нагрева.",
          en: "We apply the right amount of gel and monitor temperature with a pyrometer during every applicator pass. If the temperature stays below 40°C the effect will be minimal. Most weak RF results seen elsewhere come from insufficient heating depth.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "Скільки потрібно сесій VOLNEWMER?", ru: "Сколько нужно сессий VOLNEWMER?", en: "How many VOLNEWMER sessions are needed?" },
        answer: { uk: "Стандартний курс — 4–6 сесій з інтервалом 1–2 тижні. Для профілактики і молодих клієнтів — 3–4. Для вираженого птозу — 6. Підтримуючий сеанс — раз на 3–6 місяців.", ru: "Стандартный курс — 4–6 сессий с интервалом 1–2 недели. Для профилактики и молодых клиентов — 3–4. При выраженном птозе — 6. Поддерживающий сеанс — раз в 3–6 месяцев.", en: "Standard course: 4-6 sessions at 1-2 week intervals. For prevention and younger clients: 3-4. For pronounced ptosis: 6. Maintenance: once every 3-6 months." },
      },
      {
        question: { uk: "Чи боляче робити VOLNEWMER?", ru: "Больно ли делать VOLNEWMER?", en: "Is VOLNEWMER painful?" },
        answer: { uk: "Ні. Відчуття — приємне тепло. Інтенсивність налаштовується під ваш комфорт. Анестезія не потрібна. Процедура вважається однією з найкомфортніших серед апаратних.", ru: "Нет. Ощущения — приятное тепло. Интенсивность настраивается под ваш комфорт. Анестезия не нужна. Процедура считается одной из самых комфортных среди аппаратных.", en: "No. The sensation is comfortable warmth. Intensity is adjusted to your comfort. No anaesthesia needed. It's considered one of the most comfortable device-based treatments." },
      },
      {
        question: { uk: "Через скільки видно результат VOLNEWMER?", ru: "Через сколько виден результат VOLNEWMER?", en: "When does the VOLNEWMER result become visible?" },
        answer: { uk: "Перший ефект («старий» колаген скорочується) — після 1–2 сесій. Основний результат від нового колагену проявляється через 1–3 місяці після курсу і продовжує розкриватися до 6 місяців.", ru: "Первый эффект («старый» коллаген сокращается) — после 1–2 сессий. Основной результат от нового коллагена проявляется через 1–3 месяца после курса и продолжает раскрываться до 6 месяцев.", en: "The initial effect ('old' collagen contraction) appears after 1-2 sessions. The main result from new collagen becomes visible 1-3 months after the course and continues developing for up to 6 months." },
      },
      {
        question: { uk: "Чим VOLNEWMER відрізняється від Ultraformer MPT?", ru: "Чем VOLNEWMER отличается от Ultraformer MPT?", en: "How does VOLNEWMER differ from Ultraformer MPT?" },
        answer: { uk: "VOLNEWMER — монополярний RF, нагріває дерму і гіподерму (до 2 см). Ultraformer MPT — HIFU, фокусований ультразвук, що проникає до SMAS-фасції (4,5 мм і глибше). При вираженому птозі потрібні обидва рівні. При профілактиці або легких змінах — VOLNEWMER достатньо.", ru: "VOLNEWMER — монополярный RF, нагревает дерму и гиподерму (до 2 см). Ultraformer MPT — HIFU, фокусированный ультразвук, проникающий до SMAS-фасции (4,5 мм и глубже). При выраженном птозе нужны оба уровня. При профилактике или лёгких изменениях — VOLNEWMER достаточно.", en: "VOLNEWMER is monopolar RF, heating the dermis and hypodermis (up to 2 cm). Ultraformer MPT is HIFU, focused ultrasound reaching the SMAS fascia (4.5 mm and deeper). For pronounced ptosis, both levels are needed. For prevention or mild changes, VOLNEWMER alone is sufficient." },
      },
    ],
  },

  // ─── EXION ──────────────────────────────────────────────────────────────────
  {
    slug: "exion",
    summary: {
      uk: "EXION у GENEVITY — апарат BTL, що поєднує монополярний RF та AI-керований ультразвук для глибокого стимулювання синтезу гіалуронової кислоти і колагену. Також доступна версія з фракційними мікроголками для корекції рубців і текстури шкіри — з мінімальним реабілітаційним часом.",
      ru: "EXION в GENEVITY — аппарат BTL, совмещающий монополярный RF и AI-управляемый ультразвук для глубокой стимуляции синтеза гиалуроновой кислоты и коллагена. Также доступна версия с фракционными микроиглами для коррекции рубцов и текстуры кожи — с минимальным реабилитационным временем.",
      en: "EXION at GENEVITY — a BTL device combining monopolar RF and AI-guided ultrasound for deep stimulation of hyaluronic acid and collagen synthesis. A fractional microneedling version is also available for scar and skin-texture correction — with minimal downtime.",
    },
    sections: [
      {
        heading: { uk: "Що таке EXION і чим він відрізняється", ru: "Что такое EXION и чем он отличается", en: "What EXION is and what sets it apart" },
        body: {
          uk: "EXION — апаратна платформа нового покоління від BTL Aesthetics. Головна відмінність від класичних RF-апаратів — інтеграція монополярної радіочастотної енергії з AI-керованим ультразвуковим зображенням у реальному часі.\n\nЯк це працює:\n— RF-компонент нагріває дерму до терапевтичної температури (40–43°C), стимулюючи фібробласти виробляти колаген і еластин.\n— Ультразвуковий модуль (не фокусований HIFU, а спрямований ультразвук) додатково стимулює синтез гіалуронової кислоти у дермі — ефект, який раніше можна було отримати лише ін'єкційно.\n— Штучний інтелект EXION моніторить реакцію тканин і в реальному часі коригує параметри енергії, щоб підтримувати оптимальну температуру — без перегріву і без «холодних зон».\n\nРезультат поєднання RF + AI-ультразвук:\n— Щільніша і зволоженіша шкіра (гіалуронова кислота — природний зволожувач дерми);\n— Зменшення дрібних зморшок і покращення текстури;\n— Підтягуючий ліфтинговий ефект через стимуляцію колагенових волокон.\n\nEXION FACE — аплікатор для обличчя, шиї, декольте, рук.\nEXION BODY — аплікатор для тіла (живіт, стегна, сідниці, руки).\nEXION MICRONEEDLE (PRIME) — RF + мікроголки для глибокого фракційного впливу.\n\nFDA-схвалена технологія. Клінічно підтверджено: збільшення гіалуронової кислоти у дермі на 168%, виробництва колагену — на 26% після курсу.",
          ru: "EXION — аппаратная платформа нового поколения от BTL Aesthetics. Главное отличие от классических RF-аппаратов — интеграция монополярной радиочастотной энергии с AI-управляемым ультразвуковым изображением в реальном времени.\n\nКак это работает:\n— RF-компонент нагревает дерму до терапевтической температуры (40–43°C), стимулируя фибробласты производить коллаген и эластин.\n— Ультразвуковой модуль (не фокусированный HIFU, а направленный ультразвук) дополнительно стимулирует синтез гиалуроновой кислоты в дерме — эффект, который раньше можно было получить только инъекционно.\n— Искусственный интеллект EXION мониторит реакцию тканей и в реальном времени корректирует параметры энергии, чтобы поддерживать оптимальную температуру — без перегрева и без «холодных зон».\n\nРезультат сочетания RF + AI-ультразвук:\n— Более плотная и увлажнённая кожа (гиалуроновая кислота — природный увлажнитель дермы);\n— Уменьшение мелких морщин и улучшение текстуры;\n— Лифтинговый эффект за счёт стимуляции коллагеновых волокон.\n\nEXION FACE — аппликатор для лица, шеи, декольте, рук.\nEXION BODY — аппликатор для тела (живот, бёдра, ягодицы, руки).\nEXION MICRONEEDLE (PRIME) — RF + микроиглы для глубокого фракционного воздействия.\n\nFDA-одобренная технология. Клинически подтверждено: увеличение гиалуроновой кислоты в дерме на 168%, выработки коллагена — на 26% после курса.",
          en: "EXION is a next-generation platform from BTL Aesthetics. Its key differentiator from classic RF devices is the integration of monopolar radiofrequency energy with AI-guided real-time ultrasound imaging.\n\nHow it works:\n— The RF component heats the dermis to therapeutic temperature (40–43°C), stimulating fibroblasts to produce collagen and elastin.\n— The ultrasound module (not focused HIFU, but directed ultrasound) additionally stimulates hyaluronic acid synthesis in the dermis — an effect previously achievable only via injection.\n— EXION's AI monitors tissue response and adjusts energy parameters in real time to maintain optimal temperature — no overheating, no 'cold zones'.\n\nThe result of RF + AI-ultrasound:\n— Denser, more hydrated skin (hyaluronic acid is the dermis's natural moisturiser);\n— Reduction of fine lines and improved texture;\n— Lifting effect through collagen fibre stimulation.\n\nEXION FACE — applicator for face, neck, décolletage, hands.\nEXION BODY — applicator for abdomen, thighs, glutes, arms.\nEXION MICRONEEDLE (PRIME) — RF + microneedles for deep fractional treatment.\n\nFDA-approved technology. Clinically confirmed: 168% increase in dermal hyaluronic acid, 26% increase in collagen production after a course.",
        },
        calloutBody: {
          uk: "EXION — перша процедура, яка стимулює синтез власної гіалуронової кислоти без ін'єкцій. Ефект накопичується поступово, але зберігається довше, ніж від введеного філера — оскільки шкіра навчається виробляти кислоту сама.",
          ru: "EXION — первая процедура, стимулирующая синтез собственной гиалуроновой кислоты без инъекций. Эффект накапливается постепенно, но сохраняется дольше, чем от введённого филлера — поскольку кожа учится вырабатывать кислоту сама.",
          en: "EXION is the first procedure to stimulate native hyaluronic acid synthesis without injections. The effect builds gradually but lasts longer than injected filler — because the skin learns to produce hyaluronic acid itself.",
        },
      },
      {
        heading: { uk: "Показання та протоколи", ru: "Показания и протоколы", en: "Indications and protocols" },
        body: {
          uk: "EXION FACE ефективний при:\n— зниженні тургору і пружності шкіри обличчя, шиї, декольте, рук;\n— дрібних і середніх зморшках;\n— тьмяному, «стомленому» тоні шкіри — EXION помітно покращує текстуру і свіжість вже після 2–3 сесій;\n— підготовці шкіри перед ін'єкційними процедурами (RF підвищує рецептивність тканин);\n— реабілітації шкіри після агресивних процедур.\n\nEXION MICRONEEDLE (PRIME) показаний при:\n— рубцях після акне (атрофічних, поверхневих);\n— пострубцевій гіперпігментації;\n— розширених порах;\n— нерівній текстурі шкіри.\n\nФракційний мікрогольний RF діє у двох шарах одночасно: мікроголки механічно руйнують рубцеву тканину і стимулюють регенерацію, а RF-енергія через голки нагріває глибші шари — прискорює вироблення нового колагену і скорочує реабілітацію (порівняно з класичним фракційним CO₂-лазером час відновлення — 2–3 дні замість 7–10).\n\nКурс EXION FACE: 4–6 сесій, інтервал 2–4 тижні.\nКурс EXION PRIME: 3–4 сесії з інтервалом 4–6 тижнів.\nПідтримка: 1–2 рази на рік.",
          ru: "EXION FACE эффективен при:\n— снижении тургора и упругости кожи лица, шеи, декольте, рук;\n— мелких и средних морщинах;\n— тусклом, «усталом» тоне кожи — EXION заметно улучшает текстуру и свежесть уже после 2–3 сессий;\n— подготовке кожи перед инъекционными процедурами (RF повышает рецептивность тканей);\n— реабилитации кожи после агрессивных процедур.\n\nEXION MICRONEEDLE (PRIME) показан при:\n— рубцах после акне (атрофических, поверхностных);\n— пострубцовой гиперпигментации;\n— расширенных порах;\n— неровной текстуре кожи.\n\nФракционный микроигольный RF действует в двух слоях одновременно: микроиглы механически разрушают рубцовую ткань и стимулируют регенерацию, а RF-энергия через иглы нагревает более глубокие слои — ускоряет выработку нового коллагена и сокращает реабилитацию (по сравнению с классическим фракционным CO₂-лазером время восстановления — 2–3 дня вместо 7–10).\n\nКурс EXION FACE: 4–6 сессий, интервал 2–4 недели.\nКурс EXION PRIME: 3–4 сессии с интервалом 4–6 недель.\nПоддержка: 1–2 раза в год.",
          en: "EXION FACE is effective for:\n— loss of turgor and elasticity in face, neck, décolletage, hands;\n— fine-to-medium wrinkles;\n— dull, 'tired' skin tone — EXION noticeably improves texture and radiance after 2-3 sessions;\n— skin preparation before injections (RF increases tissue receptivity);\n— skin rehabilitation after aggressive treatments.\n\nEXION MICRONEEDLE (PRIME) is indicated for:\n— post-acne scars (atrophic, superficial);\n— post-inflammatory hyperpigmentation;\n— enlarged pores;\n— uneven skin texture.\n\nFractional microneedling RF works in two layers simultaneously: microneedles mechanically disrupt scar tissue and stimulate regeneration, while RF energy through the needles heats deeper layers — accelerating new collagen production and shortening downtime (compared to classic fractional CO₂ laser: 2-3 days recovery vs 7-10).\n\nEXION FACE course: 4-6 sessions, every 2-4 weeks.\nEXION PRIME course: 3-4 sessions, every 4-6 weeks.\nMaintenance: 1-2 times a year.",
        },
        calloutBody: {
          uk: "EXION PRIME — не альтернатива CO₂-лазеру для глибоких рубців. Для поверхневих і середніх — так, з меншим відновленням. Для глибоких атрофічних рубців з вираженим рельєфом — ми будемо чесні: AcuPulse CO₂ дасть кращий результат.",
          ru: "EXION PRIME — не альтернатива CO₂-лазеру для глубоких рубцов. Для поверхностных и средних — да, с меньшим восстановлением. Для глубоких атрофических рубцов с выраженным рельефом — мы будем честны: AcuPulse CO₂ даст лучший результат.",
          en: "EXION PRIME is not an alternative to CO₂ laser for deep scars. For superficial and medium scars — yes, with less downtime. For deep atrophic scars with pronounced texture — we'll be honest: AcuPulse CO₂ delivers a better result.",
        },
      },
      {
        heading: { uk: "Процедура та реабілітація", ru: "Процедура и реабилитация", en: "The procedure and recovery" },
        body: {
          uk: "EXION FACE:\nТривалість — 30–45 хвилин на зону. Анестезія не потрібна. Гель на шкіру, аплікатор рухається плавно зі стабільним контактом. Температура шкіри контролюється AI в реальному часі — спеціаліст відстежує показники на дисплеї. Відчуття — рівне тепло без пульсацій. Після — легке почервоніння 30–60 хвилин. Ніяких обмежень у соціальній активності.\n\nEXION PRIME (мікрогольна RF):\nТривалість — 20–40 хвилин. Обов'язкова аплікаційна анестезія (крем на 30–45 хвилин до процедури). Голки (0,5–3,5 мм, налаштовується) проникають у шкіру зі швидкістю 9000 обертів/хв — мінімальна травма для кожного мікроканалу. RF-енергія подається через голки в момент занурення. Після процедури шкіра виглядає «обпаленою» — рожева, з дрібними точками. Протягом 24–48 годин — рожевість і відчуття стягнутості, можливий невеликий набряк. На 3-й день шкіра починає злущуватись, на 5–7-й — повна нормалізація. Макіяж — на 3-й день. Активний сонцезахист (SPF 50) — 4 тижні після.\n\nПротипоказання для обох версій: вагітність, кардіостимулятор, метал у зоні лікування, злоякісні утворення, активне запалення шкіри. Для PRIME також: активний герпес, нещодавній (менш ніж 2 тижні) пілінг або лазерна процедура.",
          ru: "EXION FACE:\nПродолжительность — 30–45 минут на зону. Анестезия не нужна. Гель на кожу, аппликатор движется плавно со стабильным контактом. Температура кожи контролируется AI в реальном времени — специалист отслеживает показатели на дисплее. Ощущения — ровное тепло без пульсаций. После — лёгкое покраснение 30–60 минут. Никаких ограничений в социальной активности.\n\nEXION PRIME (микроигольный RF):\nПродолжительность — 20–40 минут. Обязательная аппликационная анестезия (крем на 30–45 минут до процедуры). Иглы (0,5–3,5 мм, настраивается) проникают в кожу со скоростью 9000 оборотов/мин — минимальная травма для каждого микроканала. RF-энергия подаётся через иглы в момент погружения. После процедуры кожа выглядит «обожжённой» — розовая, с мелкими точками. В течение 24–48 часов — розовость и ощущение стянутости, возможен небольшой отёк. На 3-й день кожа начинает шелушиться, на 5–7-й — полная нормализация. Макияж — на 3-й день. Активная солнцезащита (SPF 50) — 4 недели после.\n\nПротивопоказания для обеих версий: беременность, кардиостимулятор, металл в зоне лечения, злокачественные образования, активное воспаление кожи. Для PRIME также: активный герпес, недавний (менее 2 недель) пилинг или лазерная процедура.",
          en: "EXION FACE:\nDuration: 30-45 minutes per zone. No anaesthesia. Gel on skin, applicator moves smoothly with stable contact. Skin temperature is monitored by AI in real time — the specialist reads the display. Sensation: even warmth without pulsation. Afterward: mild redness for 30-60 minutes. No social restrictions.\n\nEXION PRIME (microneedling RF):\nDuration: 20-40 minutes. Topical anaesthetic cream is required (30-45 minutes before). Needles (0.5-3.5 mm, adjustable) penetrate at 9,000 rpm — minimal trauma per micro-channel. RF energy is delivered through the needles at the moment of insertion. Post-procedure the skin looks 'inflamed' — pink with small dots. For 24-48 hours: redness, tightness, possible mild swelling. By day 3 peeling begins; by days 5-7 full normalisation. Makeup on day 3. Active sun protection (SPF 50) for 4 weeks.\n\nContraindications for both: pregnancy, pacemaker, metal implants in treatment zone, malignant tumours, active skin inflammation. For PRIME also: active herpes, recent peel or laser treatment within 2 weeks.",
        },
        calloutBody: {
          uk: "Перед EXION PRIME обов'язково повідомте, чи у вас є схильність до герпесу — ми призначимо профілактичний противірусний препарат. Одна забута таблетка — і герпес може висипати на весь рот після процедури.",
          ru: "Перед EXION PRIME обязательно сообщите, есть ли у вас склонность к герпесу — мы назначим профилактический противовирусный препарат. Одна забытая таблетка — и герпес может высыпать на всё лицо после процедуры.",
          en: "Before EXION PRIME, tell us if you're prone to herpes — we'll prescribe a prophylactic antiviral. One forgotten tablet and herpes can break out across the entire mouth area after the procedure.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "EXION чи VOLNEWMER — в чому різниця?", ru: "EXION или VOLNEWMER — в чём разница?", en: "EXION vs VOLNEWMER — what's the difference?" },
        answer: { uk: "VOLNEWMER — класичний монополярний RF, перевірений ліфтинг і колагеностимуляція. EXION додає AI-контроль температури і ультразвукову стимуляцію синтезу гіалуронової кислоти. EXION — технологічно складніший і трохи дорожчий. Для базового омолодження — VOLNEWMER. Для вираженого дефіциту гіалуронки і текстурних проблем — EXION.", ru: "VOLNEWMER — классический монополярный RF, проверенный лифтинг и коллагеностимуляция. EXION добавляет AI-контроль температуры и ультразвуковую стимуляцию синтеза гиалуроновой кислоты. EXION — технологически сложнее и немного дороже. Для базового омоложения — VOLNEWMER. При выраженном дефиците гиалуронки и текстурных проблемах — EXION.", en: "VOLNEWMER is classic monopolar RF — proven lifting and collagen stimulation. EXION adds AI temperature control and ultrasound-driven hyaluronic acid synthesis. EXION is technically more advanced and slightly more expensive. For basic rejuvenation — VOLNEWMER. For significant hyaluronic acid deficit and texture issues — EXION." },
      },
      {
        question: { uk: "Чи можна робити EXION під час вагітності?", ru: "Можно ли делать EXION во время беременности?", en: "Can EXION be done during pregnancy?" },
        answer: { uk: "Ні. Вагітність — абсолютне протипоказання для будь-якого апаратного впливу RF або ультразвуку.", ru: "Нет. Беременность — абсолютное противопоказание для любого аппаратного воздействия RF или ультразвука.", en: "No. Pregnancy is an absolute contraindication for any device-based RF or ultrasound treatment." },
      },
      {
        question: { uk: "Скільки часу потрібно на відновлення після EXION PRIME?", ru: "Сколько времени нужно на восстановление после EXION PRIME?", en: "How long is the recovery after EXION PRIME?" },
        answer: { uk: "2–3 дні рожевості і стягнутості, на 3–5-й день — шелушіння. Повна нормалізація до 7-го дня. Для порівняння: після AcuPulse CO₂ відновлення займає 7–10 днів.", ru: "2–3 дня розовости и стянутости, на 3–5-й день — шелушение. Полная нормализация к 7-му дню. Для сравнения: после AcuPulse CO₂ восстановление занимает 7–10 дней.", en: "2-3 days of pinkness and tightness, peeling on days 3-5, full normalisation by day 7. For comparison: AcuPulse CO₂ requires 7-10 days of recovery." },
      },
      {
        question: { uk: "EXION допомагає від рубців після акне?", ru: "EXION помогает от рубцов после акне?", en: "Does EXION help with acne scars?" },
        answer: { uk: "EXION PRIME (мікрогольна версія) — так, ефективна при поверхневих і середніх атрофічних рубцях. Для глибоких ice-pick рубців — краще AcuPulse CO₂ або комбінація методів. На консультації лікар визначить оптимальний протокол під ваш тип рубців.", ru: "EXION PRIME (микроигольная версия) — да, эффективна при поверхностных и средних атрофических рубцах. Для глубоких ice-pick рубцов — лучше AcuPulse CO₂ или комбинация методов. На консультации врач определит оптимальный протокол под ваш тип рубцов.", en: "EXION PRIME (microneedling version) — yes, effective for superficial and medium atrophic scars. For deep ice-pick scars — AcuPulse CO₂ or a combination approach is better. At the consultation the doctor will determine the optimal protocol for your scar type." },
      },
    ],
  },

  // ─── ULTRAFORMER MPT ────────────────────────────────────────────────────────
  {
    slug: "ultraformer-mpt",
    summary: {
      uk: "Ultraformer MPT у GENEVITY — HIFU-апарат нового покоління для нехірургічного SMAS-ліфтингу обличчя, шиї та підборіддя. Фокусований ультразвук досягає тих же шарів, що і хірургічний ліфтинг, але без розрізів і відновлення. Видимий ефект — після одного сеансу, пік результату — через 3–6 місяців.",
      ru: "Ultraformer MPT в GENEVITY — HIFU-аппарат нового поколения для нехирургического SMAS-лифтинга лица, шеи и подбородка. Фокусированный ультразвук достигает тех же слоёв, что и хирургический лифтинг, но без разрезов и восстановления. Видимый эффект — после одного сеанса, пик результата — через 3–6 месяцев.",
      en: "Ultraformer MPT at GENEVITY — a next-generation HIFU device for non-surgical SMAS lifting of the face, neck and chin. Focused ultrasound reaches the same layers as a surgical lift — without incisions or recovery. A visible effect after one session, the peak result at 3-6 months.",
    },
    sections: [
      {
        heading: { uk: "HIFU і SMAS: чому це важливо", ru: "HIFU и SMAS: почему это важно", en: "HIFU and SMAS: why it matters" },
        body: {
          uk: "Ultraformer MPT — апарат корейського виробника CLASSYS, один з лідерів серед HIFU-платформ для медичної естетики. HIFU — High-Intensity Focused Ultrasound, фокусований ультразвук высокої інтенсивності.\n\nЧому хірурги давно звертають увагу на SMAS:\nSMAS (Superficial Musculo-Aponeurotic System) — глибока м'язово-апоневротична фасція, яка «тримає» обличчя на своєму місці. Саме вона опускається з роком і тягне за собою щоки, кути рота і шкіру шиї. Хірургічний ліфтинг (платизмопластика, SMAS-ліфтинг) працює з нею через розрізи. HIFU — перша технологія, що дозволила дістатися до SMAS без скальпеля.\n\nЯк Ultraformer MPT фокусує ультразвук:\nАплікатор випромінює ультразвукові хвилі, що фокусуються в точці на заданій глибині — 1,5 мм (поверхнева дерма), 3 мм (глибока дерма), 4,5 мм (SMAS-фасція). У точці фокусу температура миттєво досягає 65–70°C — утворюється термічна коагуляційна точка (thermal coagulation point, TCP). При цьому оточуючі тканини не ушкоджуються — ультразвук проходить крізь них без нагріву.\n\nМасив TCP (тисячі точок за сесію) стискає SMAS-волокна (негайний ліфтинг) і запускає каскад регенерації — новий колаген і еластин протягом 3–6 місяців (відтермінований, накопичуючий ефект).\n\nUltraformer MPT відрізняється від попередніх HIFU-систем:\n— Мікро і мегафокусований HIFU (MPT — Multi Pulse Technology) забезпечує більш щільний масив TCP при меншій кількості теплових точок — менш болісно, більш рівномірно;\n— Швидкість пострілів: 1 лінія (2 см) — менш ніж за 1 секунду;\n— Мікрофокусований режим (1,5 мм) — для делікатних зон (навколо рота, очей, шиї);\n— Оновлені трансдюсери підтримують точне фокусування і після тисяч процедур.",
          ru: "Ultraformer MPT — аппарат корейского производителя CLASSYS, один из лидеров среди HIFU-платформ для медицинской эстетики. HIFU — High-Intensity Focused Ultrasound, фокусированный ультразвук высокой интенсивности.\n\nПочему хирурги давно обращают внимание на SMAS:\nSMAS (Superficial Musculo-Aponeurotic System) — глубокая мышечно-апоневротическая фасция, которая «держит» лицо на своём месте. Именно она опускается с годами и тянет за собой щёки, углы рта и кожу шеи. Хирургический лифтинг (платизмопластика, SMAS-лифтинг) работает с ней через разрезы. HIFU — первая технология, позволившая добраться до SMAS без скальпеля.\n\nКак Ultraformer MPT фокусирует ультразвук:\nАппликатор излучает ультразвуковые волны, которые фокусируются в точке на заданной глубине — 1,5 мм (поверхностная дерма), 3 мм (глубокая дерма), 4,5 мм (SMAS-фасция). В точке фокуса температура мгновенно достигает 65–70°C — образуется тепловая коагуляционная точка (thermal coagulation point, TCP). При этом окружающие ткани не повреждаются — ультразвук проходит сквозь них без нагрева.\n\nМассив TCP (тысячи точек за сессию) сжимает SMAS-волокна (немедленный лифтинг) и запускает каскад регенерации — новый коллаген и эластин в течение 3–6 месяцев (отсроченный, накапливающийся эффект).\n\nUltraformer MPT отличается от предыдущих HIFU-систем:\n— Микро и мегафокусированный HIFU (MPT — Multi Pulse Technology) обеспечивает более плотный массив TCP при меньшем количестве тепловых точек — менее болезненно, более равномерно;\n— Скорость выстрелов: 1 линия (2 см) — менее чем за 1 секунду;\n— Микрофокусированный режим (1,5 мм) — для деликатных зон (вокруг рта, глаз, шеи);\n— Обновлённые трансдюсеры сохраняют точную фокусировку после тысяч процедур.",
          en: "Ultraformer MPT is a device by Korean manufacturer CLASSYS, one of the leaders in HIFU platforms for medical aesthetics. HIFU — High-Intensity Focused Ultrasound.\n\nWhy SMAS matters:\nSMAS (Superficial Musculo-Aponeurotic System) is the deep musculoaponeurotic fascia that holds the face in position. It descends with age, pulling the cheeks, mouth corners and neck skin with it. Surgical lifting (platysmaplasty, SMAS lift) addresses it through incisions. HIFU was the first technology to reach the SMAS without a scalpel.\n\nHow Ultraformer MPT focuses ultrasound:\nThe applicator emits ultrasound waves that focus at a set depth — 1.5 mm (superficial dermis), 3 mm (deep dermis), 4.5 mm (SMAS fascia). At the focal point, temperature instantly reaches 65–70°C — creating a thermal coagulation point (TCP). Surrounding tissue is not damaged — ultrasound passes through it without heating.\n\nThe TCP array (thousands of points per session) contracts SMAS fibres (immediate lift) and triggers a regeneration cascade — new collagen and elastin over 3–6 months (a delayed, accumulating effect).\n\nUltraformer MPT versus older HIFU systems:\n— Micro and mega-focused HIFU (MPT — Multi Pulse Technology) delivers a denser TCP array with fewer heat points — less painful, more uniform;\n— Shot speed: 1 line (2 cm) in under 1 second;\n— Micro-focused mode (1.5 mm) for delicate zones (around the mouth, eyes, neck);\n— Updated transducers maintain precise focus even after thousands of procedures.",
        },
        calloutBody: {
          uk: "Ultraformer MPT — найближче, що існує до хірургічного ліфтингу без хірургії. Але це не одне й те саме: при вираженому птозі другого і третього ступеня — лише хірург дасть стабільний результат. HIFU — для першого ступеня птозу і профілактики.",
          ru: "Ultraformer MPT — ближайшее к хирургическому лифтингу без хирургии. Но это не одно и то же: при выраженном птозе второй и третьей степени — только хирург даст стабильный результат. HIFU — для первой степени птоза и профилактики.",
          en: "Ultraformer MPT is the closest thing to a surgical lift without surgery. But they are not the same: for pronounced grade-2 and grade-3 ptosis, only a surgeon delivers a stable result. HIFU is for grade-1 ptosis and prevention.",
        },
      },
      {
        heading: { uk: "Кому і для яких зон", ru: "Кому и для каких зон", en: "Who it's for and which zones" },
        body: {
          uk: "Ultraformer MPT ефективний для:\n\n— Підйому брів і відкриття погляду. Трансдюсер 1,5 мм на лоб і скроневу зону — підйом брів на 2–5 мм, що помітно «відкриває» очі.\n— Ліфтингу нижньої третини обличчя. Оброблення зони від вилиць до підщелепного кута трансдюсерами 3 мм і 4,5 мм — підтяжка щік, скорочення «брилів», чіткіший кут щелепи.\n— Ліфтингу шиї. Шкіра шиї — одна з кращих зон відгуку на HIFU. Видима підтяжка після 1 сесії.\n— Корекції підборіддя. Субментальна зона (другий підборіддя): поєднання ліполітичного і ліфтингового ефектів HIFU.\n— Зони навколо рота. Дрібні вертикальні зморшки («кодова замок»), опущені кути губ — мікрофокусний режим 1,5 мм.\n\nОптимальний вік і стан:\n— від 30 років для профілактики;\n— найкращий відгук при легкому і помірному птозі (1–2 ступінь);\n— шкіра достатнього тургору (при дуже тонкій і дуже в'ялій шкірі ефект менший);\n— для клієнтів, які хочуть уникнути хірургії або не готові до реабілітаційного часу ліфтингу.\n\nNOT показано: при важкому птозі 3-го ступеня, дуже тонкій атрофічній шкірі, металевих імплантах у зоні, вагітності, онкологічних захворюваннях, активній запальній шкірі.",
          ru: "Ultraformer MPT эффективен для:\n\n— Подъёма бровей и открытия взгляда. Трансдюсер 1,5 мм на лоб и височную зону — подъём бровей на 2–5 мм, что заметно «открывает» глаза.\n— Лифтинга нижней трети лица. Обработка зоны от скул до подчелюстного угла трансдюсерами 3 мм и 4,5 мм — подтяжка щёк, сокращение «брылей», более чёткий угол челюсти.\n— Лифтинга шеи. Кожа шеи — одна из лучших зон отклика на HIFU. Заметная подтяжка после 1 сессии.\n— Коррекции подбородка. Субментальная зона (второй подбородок): сочетание липолитического и лифтингового эффектов HIFU.\n— Зоны вокруг рта. Мелкие вертикальные морщины («кодовый замок»), опущенные углы губ — микрофокусный режим 1,5 мм.\n\nОптимальный возраст и состояние:\n— от 30 лет для профилактики;\n— лучший отклик при лёгком и умеренном птозе (1–2 степень);\n— кожа достаточного тургора (при очень тонкой и очень вялой коже эффект меньше);\n— для клиентов, которые хотят избежать хирургии или не готовы к реабилитационному времени лифтинга.\n\nNOT показано: при тяжёлом птозе 3-й степени, очень тонкой атрофичной коже, металлических имплантах в зоне, беременности, онкологических заболеваниях, активном воспалении кожи.",
          en: "Ultraformer MPT is effective for:\n\n— Brow lift and eye opening. 1.5 mm transducer on the forehead and temporal zone — brow elevation of 2-5 mm, noticeably 'opening' the eyes.\n— Lower-face lift. Treating the zone from cheekbones to the mandibular angle with 3 mm and 4.5 mm transducers — cheek tightening, jowl reduction, sharper jaw angle.\n— Neck lift. Neck skin is one of the best HIFU response zones. Visible tightening after 1 session.\n— Chin correction. Submental zone (double chin): combining HIFU's lipolytic and lifting effects.\n— Perioral zone. Fine vertical lip lines ('bar code'), descended mouth corners — micro-focused 1.5 mm mode.\n\nOptimal age and condition:\n— from age 30 for prevention;\n— best response with mild to moderate ptosis (grade 1-2);\n— sufficient skin turgor (very thin, very lax skin responds less);\n— for clients who want to avoid surgery or cannot afford surgical downtime.\n\nNOT indicated for: severe grade-3 ptosis, very thin atrophic skin, metal implants in the treatment zone, pregnancy, oncological disease, active skin inflammation.",
        },
        calloutBody: {
          uk: "Головна помилка при HIFU — «більше пострілів — кращий результат». Надмірна кількість TCP у одній зоні може призвести до нерівного рельєфу і набряку на тижні. Ми суворо дотримуємось протокольних параметрів і не «переобробляємо» зони заради відчуття «краще зробили».",
          ru: "Главная ошибка при HIFU — «больше выстрелов — лучший результат». Избыточное количество TCP в одной зоне может привести к неровному рельефу и отёку на недели. Мы строго соблюдаем протокольные параметры и не «переобрабатываем» зоны ради ощущения «лучше сделали».",
          en: "The main HIFU mistake is 'more shots = better result'. Excessive TCP density in one zone can cause uneven texture and weeks of swelling. We strictly follow protocol parameters and never over-treat zones for the feeling of having done more.",
        },
      },
      {
        heading: { uk: "Як проходить сесія Ultraformer MPT", ru: "Как проходит сессия Ultraformer MPT", en: "The Ultraformer MPT session" },
        body: {
          uk: "Одна сесія Ultraformer MPT для повного обличчя займає 45–90 хвилин залежно від кількості зон і протоколу.\n\nПідготовка: очищення шкіри, нанесення ультразвукового гелю. Анестезія — за бажанням клієнта. При стандартному протоколі більшість клієнтів обходяться без неї. Для підвищеної чутливості — аплікаційний крем за 30 хвилин до процедури.\n\nСама процедура:\n— Лікар визначає глибину і трансдюсер для кожної зони;\n— Аплікатор притискається до шкіри з гелем, система автоматично підтверджує фокусування;\n— «Постріли» — миттєві, часто без помітного відчуття (особливо на чолі і шиї). Чутливіші зони — навколо роту, підборіддя;\n— Відчуття: від легкого поколювання до короткого, різкого болю залежно від зони і налаштування (інтенсивність регулюється).\n\nПісля процедури:\n— легка набряклість 24–48 годин — нормальна реакція на теплове ушкодження;\n— в окремих клієнтів — синяки в зоні щелепи (рідко, 5–10%);\n— поодинокі відчуття оніміння або «мурашок» у зоні лікування — минають за 1–2 тижні;\n— макіяж — наступного дня;\n— обмежень по роботі немає.\n\nЕфект: перший видимий підйом — одразу і в перші 2 тижні (скорочення SMAS). Основний колагеновий результат — через 3–6 місяців. Тривалість — 12–18 місяців для більшості пацієнтів. Повторна сесія — через 12–18 місяців.",
          ru: "Одна сессия Ultraformer MPT для полного лица занимает 45–90 минут в зависимости от количества зон и протокола.\n\nПодготовка: очищение кожи, нанесение ультразвукового геля. Анестезия — по желанию клиента. При стандартном протоколе большинство клиентов обходятся без неё. Для повышенной чувствительности — аппликационный крем за 30 минут до процедуры.\n\nСама процедура:\n— Врач определяет глубину и трансдюсер для каждой зоны;\n— Аппликатор прижимается к коже с гелем, система автоматически подтверждает фокусировку;\n— «Выстрелы» — мгновенные, часто без заметного ощущения (особенно на лбу и шее). Более чувствительные зоны — вокруг рта, подбородок;\n— Ощущения: от лёгкого покалывания до короткой, резкой боли в зависимости от зоны и настройки (интенсивность регулируется).\n\nПосле процедуры:\n— лёгкая отёчность 24–48 часов — нормальная реакция на тепловое повреждение;\n— у отдельных клиентов — синяки в зоне челюсти (редко, 5–10%);\n— единичные ощущения онемения или «мурашек» в зоне лечения — проходят за 1–2 недели;\n— макияж — на следующий день;\n— ограничений по работе нет.\n\nЭффект: первый видимый подъём — сразу и в первые 2 недели (сокращение SMAS). Основной коллагеновый результат — через 3–6 месяцев. Продолжительность — 12–18 месяцев для большинства пациентов. Повторная сессия — через 12–18 месяцев.",
          en: "A full-face Ultraformer MPT session takes 45-90 minutes depending on the number of zones and protocol.\n\nPreparation: skin cleansing, application of ultrasound gel. Anaesthesia is at the client's discretion. With the standard protocol most clients manage without it. For higher sensitivity — topical cream 30 minutes before.\n\nThe procedure itself:\n— The doctor selects depth and transducer for each zone;\n— The applicator is pressed to the gel-coated skin; the system auto-confirms focus;\n— 'Shots' are instantaneous, often barely noticeable (especially on forehead and neck). More sensitive zones: around the mouth, chin;\n— Sensations range from a mild tingle to a brief sharp sting depending on zone and intensity (intensity is adjustable).\n\nAfterward:\n— mild swelling for 24-48 hours — normal thermal response;\n— occasional bruising along the jawline (rare, 5-10%);\n— isolated numbness or 'pins and needles' in the treatment zone — resolves within 1-2 weeks;\n— makeup the next day;\n— no work restrictions.\n\nEffect: first visible lift immediately and in the first 2 weeks (SMAS contraction). Main collagen result at 3-6 months. Duration: 12-18 months for most patients. Repeat session: after 12-18 months.",
        },
        calloutBody: {
          uk: "Перший ефект Ultraformer MPT видно одразу після процедури — але не приймайте це за фінальний результат. Після зняття набряку в перші 2–3 дні обличчя може виглядати «як до» — це нормально. Головний результат накопичується 3–6 місяців.",
          ru: "Первый эффект Ultraformer MPT виден сразу после процедуры — но не принимайте это за финальный результат. После спадения отёка в первые 2–3 дня лицо может выглядеть «как до» — это нормально. Главный результат накапливается 3–6 месяцев.",
          en: "The first effect of Ultraformer MPT is visible immediately after the procedure — but don't take it for the final result. Once the swelling subsides in the first 2-3 days, the face may look 'the same as before' — this is normal. The main result builds over 3-6 months.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "Скільки коштує Ultraformer MPT у Дніпрі?", ru: "Сколько стоит Ultraformer MPT в Днепре?", en: "How much does Ultraformer MPT cost in Dnipro?" },
        answer: { uk: "Ціна залежить від кількості зон і кількості ліній (пострілів). Базовий прайс на Ultraformer MPT у GENEVITY вказаний на цій сторінці. Точна вартість визначається на консультації після оцінки зон і протоколу.", ru: "Цена зависит от количества зон и количества линий (выстрелов). Базовый прайс на Ultraformer MPT в GENEVITY указан на этой странице. Точная стоимость определяется на консультации после оценки зон и протокола.", en: "The price depends on the number of zones and lines (shots). The base price for Ultraformer MPT at GENEVITY is on this page. The exact cost is confirmed at the consultation after evaluating zones and protocol." },
      },
      {
        question: { uk: "Скільки сесій Ultraformer MPT потрібно?", ru: "Сколько сессий Ultraformer MPT нужно?", en: "How many Ultraformer MPT sessions are needed?" },
        answer: { uk: "Зазвичай 1 сесія на рік для підтримки результату. Деяким клієнтам до 35 років і з легким птозом — 1 сесії достатньо на 18 місяців. При вираженому птозі — можливі 2 сесії з інтервалом 6 місяців у перший рік.", ru: "Обычно 1 сессия в год для поддержания результата. Некоторым клиентам до 35 лет и с лёгким птозом — 1 сессии достаточно на 18 месяцев. При выраженном птозе — возможны 2 сессии с интервалом 6 месяцев в первый год.", en: "Usually 1 session per year to maintain results. Some clients under 35 with mild ptosis find 1 session sufficient for 18 months. For pronounced ptosis: 2 sessions at 6-month intervals in the first year may be indicated." },
      },
      {
        question: { uk: "Боляче робити Ultraformer MPT?", ru: "Больно ли делать Ultraformer MPT?", en: "Is Ultraformer MPT painful?" },
        answer: { uk: "Залежить від зони і порогу болю. Чоло, шия — зазвичай комфортно. Підборіддя, кути щелепи — може бути різке короткочасне відчуття. Більшість клієнтів описують як «терпимо». Анестезуючий крем на 30 хвилин знімає більшість дискомфорту.", ru: "Зависит от зоны и болевого порога. Лоб, шея — обычно комфортно. Подбородок, углы челюсти — может быть резкое кратковременное ощущение. Большинство клиентов описывают как «терпимо». Анестезирующий крем на 30 минут снимает большую часть дискомфорта.", en: "It depends on the zone and pain threshold. Forehead and neck — typically comfortable. Chin, jaw angles — can be briefly sharp. Most clients describe it as 'manageable'. Topical cream for 30 minutes removes most of the discomfort." },
      },
      {
        question: { uk: "Чи можна поєднувати Ultraformer MPT з ботоксом або філерами?", ru: "Можно ли сочетать Ultraformer MPT с ботоксом или филлерами?", en: "Can Ultraformer MPT be combined with botox or fillers?" },
        answer: { uk: "Так, і це часто дає кращий результат. Стандартний інтервал: Ultraformer MPT → 2 тижні → ін'єкції. Або навпаки: ін'єкції → 2–4 тижні → Ultraformer MPT. Одночасно в один день — не рекомендуємо (набряки можуть накладатися).", ru: "Да, и это часто даёт лучший результат. Стандартный интервал: Ultraformer MPT → 2 недели → инъекции. Или наоборот: инъекции → 2–4 недели → Ultraformer MPT. Одновременно в один день — не рекомендуем (отёки могут накладываться).", en: "Yes, and this often gives the best result. Standard interval: Ultraformer MPT → 2 weeks → injections. Or: injections → 2-4 weeks → Ultraformer MPT. Same-day combination is not recommended (swelling may compound)." },
      },
      {
        question: { uk: "Як довго тримається результат Ultraformer MPT?", ru: "Как долго держится результат Ultraformer MPT?", en: "How long does the Ultraformer MPT result last?" },
        answer: { uk: "12–18 місяців для більшості пацієнтів. Залежить від вихідного тонусу шкіри, способу життя і темпу вікових змін. Регулярні сесії раз на рік сповільнюють природний птоз.", ru: "12–18 месяцев для большинства пациентов. Зависит от исходного тонуса кожи, образа жизни и темпа возрастных изменений. Регулярные сессии раз в год замедляют естественный птоз.", en: "12-18 months for most patients. Depends on baseline skin tone, lifestyle and the rate of natural ageing. Regular annual sessions slow natural ptosis progression." },
      },
    ],
  },
];

async function seedService(copy: ServiceCopy) {
  const svc = await sql`SELECT id FROM services WHERE slug = ${copy.slug} LIMIT 1`;
  if (!svc[0]) { console.error(`Service "${copy.slug}" not found — skip`); return; }
  const serviceId = svc[0].id as string;

  await sql`UPDATE services SET summary_uk=${copy.summary.uk}, summary_ru=${copy.summary.ru}, summary_en=${copy.summary.en} WHERE id=${serviceId}`;
  await sql`DELETE FROM content_sections WHERE owner_type='service' AND owner_id=${serviceId}`;
  await sql`DELETE FROM faq_items WHERE owner_type='service' AND owner_id=${serviceId}`;

  const sectionIds: string[] = [];
  for (let i = 0; i < copy.sections.length; i++) {
    const s = copy.sections[i];
    const id = randomUUID();
    sectionIds.push(id);
    const data = { heading: s.heading, body: s.body, calloutBody: s.calloutBody, heroImage: null };
    await sql`INSERT INTO content_sections(id,owner_type,owner_id,sort_order,section_type,data) VALUES(${id},'service',${serviceId},${i},'richText'::section_type,${JSON.stringify(data)}::jsonb)`;
  }
  for (let i = 0; i < copy.faq.length; i++) {
    const f = copy.faq[i];
    await sql`INSERT INTO faq_items(owner_type,owner_id,sort_order,question_uk,question_ru,question_en,answer_uk,answer_ru,answer_en) VALUES('service',${serviceId},${i},${f.question.uk},${f.question.ru},${f.question.en},${f.answer.uk},${f.answer.ru},${f.answer.en})`;
  }

  const newOrder = [...sectionIds.map(id => `section:${id}`), "faq", "doctors", "equipment", "relatedServices", "finalCTA"];
  await sql`UPDATE services SET block_order=${newOrder} WHERE id=${serviceId}`;
  console.log(`✓ ${copy.slug} — ${copy.sections.length} sections, ${copy.faq.length} FAQs`);
}

async function main() {
  for (const svc of SERVICES) await seedService(svc);
  await sql.end();
  console.log("\nV3a DONE — EMFACE, VOLNEWMER, EXION, Ultraformer MPT. Continue with v3b for body sculpting services.");
}
main().catch(e => { console.error(e); process.exit(1); });
