/**
 * V3c — M22 Stellar Black, Splendor X, HydraFacial, AcuPulse CO₂
 * Final apparatus-cosmetology services: IPL, laser epilation, facial, fractional CO₂.
 * Run: npx tsx scripts/seed-copy-v3c.ts
 */
import postgres from "postgres";
import * as fs from "fs";
import * as path from "path";
import { randomUUID } from "crypto";

const envContent = fs.readFileSync(path.resolve(__dirname, "../.env.local"), "utf-8");
const env: Record<string, string> = {};
envContent.split("\n").forEach((l) => {
  const [k, ...v] = l.split("=");
  if (k && v.length) env[k.trim()] = v.join("=").trim();
});
const sql = postgres(env.DATABASE_URL!);

type L = { uk: string; ru: string; en: string };
interface SectionCopy { heading: L; body: L; calloutBody: L; }
interface FaqCopy { question: L; answer: L; }
interface ServiceCopy { slug: string; summary: L; sections: SectionCopy[]; faq: FaqCopy[]; }

const SERVICES: ServiceCopy[] = [
  // ─── M22 STELLAR BLACK ─────────────────────────────────────────────────────
  {
    slug: "m22-stellar-black",
    summary: {
      uk: "M22 Stellar Black у GENEVITY — мультиплатформна система Lumenis: IPL-фотоомолодження, лікування пігментації, судинних зірочок і розацеа, фракційне оновлення шкіри ResurFX. Єдиний апарат, що об'єднує кілька довжин хвиль і модулів у одній платформі для індивідуальних протоколів.",
      ru: "M22 Stellar Black в GENEVITY — мультиплатформенная система Lumenis: IPL-фотоомоложение, лечение пигментации, сосудистых звёздочек и розацеа, фракционное обновление кожи ResurFX. Единственный аппарат, объединяющий несколько длин волн и модулей в одной платформе для индивидуальных протоколов.",
      en: "M22 Stellar Black at GENEVITY — Lumenis's multiplatform system: IPL photo-rejuvenation, treatment of pigmentation, vascular lesions and rosacea, ResurFX fractional skin renewal. The only device combining multiple wavelengths and modules in one platform for customised protocols.",
    },
    sections: [
      {
        heading: { uk: "Що вміє M22 Stellar Black", ru: "Что умеет M22 Stellar Black", en: "What M22 Stellar Black does" },
        body: {
          uk: "M22 Stellar Black — флагманська система Lumenis (Ізраїль), один з найбільш клінічно досліджених апаратів в естетичній медицині. Назва «Stellar Black» відображає оновлену версію платформи M22 з розширеним набором модулів.\n\nМодулі M22 Stellar Black у GENEVITY:\n\n1. IPL (Intense Pulsed Light) — інтенсивний імпульсний світло. Широкосмуговий фільтрований світловий потік, що за допомогою відповідних фільтрів Tax обирає довжину хвилі під конкретну мішень:\n— хромофор меланіну (520–1064 нм) → пігментні плями, лентиго, постзапальна гіперпігментація;\n— хромофор оксигемоглобіну (530–600 нм) → капілярна сітка, судинні зірочки, розацеа, купероз;\n— загальна фотостимуляція (560–1200 нм) → фотоомолодження, покращення тонусу і рівномірності кольору шкіри.\n\n2. ResurFX — фракційний нефракційний лазерний модуль (1565 нм). Нефляційний (non-ablative): не видаляє верхній шар шкіри, а формує масив мікро-теплових зон у дермі, стимулюючи неоколагенез. Ефективний при:\n— зморшках і нерівній текстурі;\n— розтяжках (стріях);\n— рубцях після акне;\n— збільшених порах.\n\n3. OPT (Optimal Pulse Technology) — патентована технологія рівного розподілу енергії у кожному імпульсі. Стандартний IPL дає «пікову» енергію на початку імпульсу і спадну — в кінці. OPT тримає рівну «площадку» — менше болю, менше ризику опіків, кращий результат.\n\nРезультат IPL-курсу: рівний тон шкіри, зменшення судинних і пігментних дефектів, загальне омолодження. M22 — один з небагатьох IPL-апаратів з доказовою базою рівня FDA і CE класу IIb.",
          ru: "M22 Stellar Black — флагманская система Lumenis (Израиль), один из наиболее клинически исследованных аппаратов в эстетической медицине.\n\nМодули M22 Stellar Black в GENEVITY:\n\n1. IPL (Intense Pulsed Light) — интенсивный импульсный свет. Широкополосный фильтрованный световой поток, который с помощью соответствующих фильтров выбирает длину волны под конкретную мишень:\n— хромофор меланина (520–1064 нм) → пигментные пятна, лентиго, поствоспалительная гиперпигментация;\n— хромофор оксигемоглобина (530–600 нм) → капиллярная сетка, сосудистые звёздочки, розацеа, купероз;\n— общая фотостимуляция (560–1200 нм) → фотоомоложение, улучшение тонуса и равномерности цвета кожи.\n\n2. ResurFX — фракционный нефляционный лазерный модуль (1565 нм). Не удаляет верхний слой кожи, а формирует массив микро-тепловых зон в дерме, стимулируя неоколлагенез. Эффективен при:\n— морщинах и неровной текстуре;\n— растяжках (стриях);\n— рубцах после акне;\n— расширенных порах.\n\n3. OPT (Optimal Pulse Technology) — патентованная технология равного распределения энергии в каждом импульсе. Стандартный IPL даёт «пиковую» энергию в начале импульса и спадающую — в конце. OPT держит ровную «площадку» — меньше боли, меньше риска ожогов, лучший результат.\n\nРезультат IPL-курса: ровный тон кожи, уменьшение сосудистых и пигментных дефектов, общее омоложение.",
          en: "M22 Stellar Black is Lumenis's flagship system (Israel), one of the most clinically studied devices in aesthetic medicine.\n\nM22 Stellar Black modules at GENEVITY:\n\n1. IPL (Intense Pulsed Light). Broad-spectrum filtered light that, through the appropriate cut-off filters, selects the target wavelength:\n— melanin chromophore (520–1064 nm) → pigment spots, lentigines, post-inflammatory hyperpigmentation;\n— oxyhaemoglobin chromophore (530–600 nm) → capillary network, vascular lesions, rosacea, couperose;\n— general photostimulation (560–1200 nm) → photo-rejuvenation, improved skin tone and colour uniformity.\n\n2. ResurFX — fractional non-ablative laser module (1565 nm). Doesn't remove the top skin layer; creates a micro-thermal zone array in the dermis, stimulating neocollagenesis. Effective for:\n— wrinkles and uneven texture;\n— stretch marks (striae);\n— post-acne scars;\n— enlarged pores.\n\n3. OPT (Optimal Pulse Technology) — patented even-energy-distribution technology. Standard IPL delivers peak energy at the start of a pulse and declining energy toward the end. OPT maintains a flat 'plateau' — less pain, lower burn risk, better results.\n\nIPL course results: even skin tone, reduced vascular and pigment defects, general rejuvenation. M22 is one of the few IPL devices with an evidence base at FDA and CE class IIb level.",
        },
        calloutBody: {
          uk: "IPL і лазер — не одне й те саме. IPL — широкосмуговий, менш точний, але більш versatile (вирішує кілька проблем за сесію). Лазер — монохроматичний, точніший, ефективніший при конкретній мішені (наприклад, лазерна епіляція). Ми підбираємо метод під проблему, а не навпаки.",
          ru: "IPL и лазер — не одно и то же. IPL — широкополосный, менее точный, но более versatile (решает несколько проблем за сессию). Лазер — монохроматический, более точный, эффективнее при конкретной мишени (например, лазерная эпиляция). Мы подбираем метод под проблему, а не наоборот.",
          en: "IPL and laser are not the same. IPL is broad-spectrum, less precise, but more versatile (addresses several problems in one session). Laser is monochromatic, more precise, more effective for a specific target (e.g., hair removal). We select the method for the problem, not the other way round.",
        },
      },
      {
        heading: { uk: "Що лікує IPL: пігмент, судини, рівний тон", ru: "Что лечит IPL: пигмент, сосуды, ровный тон", en: "What IPL treats: pigment, vessels, even tone" },
        body: {
          uk: "IPL M22 Stellar Black ефективний при:\n\nПігментація:\n— сонячне лентиго (вікові плями, «веснянки» від сонця);\n— постзапальна гіперпігментація (сліди від прищів, подразнення);\n— дифузна нерівномірна пігментація.\n\nСудинні дефекти:\n— судинні зірочки на обличчі (телеангіектазії) — ніс, щоки, скроні;\n— купероз — дифузне почервоніння на щоках і носі;\n— розацеа (еритематозно-телеангіектатичний тип) — IPL є частиною стандартного протоколу лікування;\n— почервоніння і судинна реакція після хімічного пілінгу або агресивних процедур.\n\nЗагальне фотоомолодження:\n— нерівний тон і сірий колір шкіри;\n— дрібні зморшки від фотостаріння;\n— тьмяна, «стомлена» шкіра.\n\nResurFX (фракційний модуль) ефективний при:\n— поверхневих і середніх зморшках;\n— рубцях після акне;\n— стріях (розтяжках);\n— нерівній текстурі шкіри.\n\nОптимальний курс IPL: 3–5 сесій з інтервалом 3–4 тижні. Перша сесія — тест реакції шкіри, подальші — наростаюча корекція.\n\nВАЖЛИВО: IPL не підходить для засмаглої шкіри. Процедури — строго у несонячний сезон або з обов'язковим суворим фотозахистом. Засмага за 2 тижні до — стоп.\n\nПротипоказання: вагітність, активний герпес у зоні, прийом фотосенсибілізуючих препаратів (ретиноїди, тетрациклін), злоякісні утворення, фотодерматоз, меланодермія (мелазма — обговорюємо окремо).",
          ru: "IPL M22 Stellar Black эффективен при:\n\nПигментация:\n— солнечное лентиго (возрастные пятна, «веснушки» от солнца);\n— поствоспалительная гиперпигментация (следы от прыщей, раздражения);\n— диффузная неравномерная пигментация.\n\nСосудистые дефекты:\n— сосудистые звёздочки на лице (телеангиэктазии) — нос, щёки, виски;\n— купероз — диффузное покраснение на щёках и носу;\n— розацеа (эритематозно-телеангиэктатический тип) — IPL является частью стандартного протокола лечения;\n— покраснение и сосудистая реакция после химического пилинга или агрессивных процедур.\n\nОбщее фотоомоложение:\n— неровный тон и серый цвет кожи;\n— мелкие морщины от фотостарения;\n— тусклая, «усталая» кожа.\n\nResurFX (фракционный модуль) эффективен при:\n— поверхностных и средних морщинах;\n— рубцах после акне;\n— стриях (растяжках);\n— неровной текстуре кожи.\n\nОптимальный курс IPL: 3–5 сессий с интервалом 3–4 недели.\n\nВАЖНО: IPL не подходит для загорелой кожи. Процедуры — строго в несолнечный сезон или при строгой фотозащите. Загар за 2 недели до — стоп.\n\nПротивопоказания: беременность, активный герпес в зоне, приём фотосенсибилизирующих препаратов (ретиноиды, тетрациклин), злокачественные образования, фотодерматоз.",
          en: "M22 Stellar Black IPL is effective for:\n\nPigmentation:\n— solar lentigines ('age spots', sun-induced freckles);\n— post-inflammatory hyperpigmentation (acne marks, irritation);\n— diffuse uneven pigmentation.\n\nVascular lesions:\n— facial telangiectasia (vascular spiders) — nose, cheeks, temples;\n— couperose — diffuse redness on cheeks and nose;\n— rosacea (erythematotelangiectatic type) — IPL is part of the standard treatment protocol;\n— redness and vascular reaction after chemical peels or aggressive procedures.\n\nGeneral photo-rejuvenation:\n— uneven skin tone and grey complexion;\n— fine lines from photoageing;\n— dull, 'tired' skin.\n\nResurFX (fractional module) is effective for:\n— superficial to medium wrinkles;\n— post-acne scars;\n— stretch marks (striae);\n— uneven skin texture.\n\nOptimal IPL course: 3-5 sessions at 3-4 week intervals.\n\nIMPORTANT: IPL is not suitable for tanned skin. Procedures must be scheduled in the non-sunny season or with strict photoprotection. A tan within 2 weeks prior — stop.\n\nContraindications: pregnancy, active herpes in the zone, photosensitising medications (retinoids, tetracycline), malignant tumours, photodermatosis.",
        },
        calloutBody: {
          uk: "Меланодермія (мелазма) — особливий випадок: IPL може погіршити її при неправильному підборі параметрів. Перед лікуванням мелазми на M22 ми обов'язково проводимо диференціальну діагностику і обговорюємо ризики.",
          ru: "Меланодермия (мелазма) — особый случай: IPL может ухудшить её при неправильном подборе параметров. Перед лечением мелазмы на M22 мы обязательно проводим дифференциальную диагностику и обсуждаем риски.",
          en: "Melasma is a special case: IPL can worsen it with incorrect parameters. Before treating melasma on M22 we always perform differential diagnosis and discuss the risks.",
        },
      },
      {
        heading: { uk: "Як проходить процедура і що очікувати", ru: "Как проходит процедура и что ожидать", en: "How the procedure runs and what to expect" },
        body: {
          uk: "Сесія IPL на M22 Stellar Black:\n— Підготовка: демакіяж, нанесення охолоджуючого гелю. Підбір фільтра і параметрів під тип шкіри і мішень (пігмент, судини, фотоомолодження).\n— Захист очей: світлонепроникні окуляри обов'язкові.\n— Процедура: аплікатор IPL накладається на шкіру і «клікає» — кожен клік дає одну або серію імпульсів. Відчуття — легке пощипування і тепло, як від удару гумкою. ОPT-технологія значно знижує дискомфорт порівняно зі старим IPL.\n— Тривалість: повне обличчя — 20–30 хвилин. Точкова корекція (зона носа, щоки) — 10–15 хвилин.\n— Після: шкіра рожева 2–4 години. Пігментні плями — темніють і «відшаровуються» протягом 7–14 днів (нормально!). Судини — зникають або блідніють протягом 1–2 тижнів.\n— Обов'язково: SPF 50+ щодня протягом 4 тижнів після кожної сесії. Без фотозахисту — ризик повернення пігментації.\n\nСесія ResurFX:\n— Тривалість: 20–30 хвилин на зону.\n— Анестезія: аплікаційний крем за 30 хвилин (рекомендовано).\n— Відчуття: поколювання, тепло. Після — шкіра рожева 24–48 годин, легке шелушіння 3–5 днів. Без соціальних обмежень з 2–3 дня.",
          ru: "Сессия IPL на M22 Stellar Black:\n— Подготовка: демакияж, нанесение охлаждающего геля. Подбор фильтра и параметров под тип кожи и мишень (пигмент, сосуды, фотоомоложение).\n— Защита глаз: светонепроницаемые очки обязательны.\n— Процедура: аппликатор IPL накладывается на кожу и «кликает» — каждый клик даёт один или серию импульсов. Ощущения — лёгкое пощипывание и тепло. OPT-технология значительно снижает дискомфорт по сравнению со старым IPL.\n— Продолжительность: полное лицо — 20–30 минут. Точечная коррекция — 10–15 минут.\n— После: кожа розовая 2–4 часа. Пигментные пятна — темнеют и «отшелушиваются» в течение 7–14 дней (нормально!). Сосуды — исчезают или бледнеют в течение 1–2 недель.\n— Обязательно: SPF 50+ ежедневно в течение 4 недель после каждой сессии.\n\nСессия ResurFX:\n— Продолжительность: 20–30 минут на зону.\n— Анестезия: аппликационный крем за 30 минут (рекомендуется).\n— Ощущения: покалывание, тепло. После — кожа розовая 24–48 часов, лёгкое шелушение 3–5 дней.",
          en: "IPL session on M22 Stellar Black:\n— Preparation: make-up removal, cooling gel applied. Filter and parameters selected for skin type and target (pigment, vessels, photo-rejuvenation).\n— Eye protection: opaque goggles mandatory.\n— Procedure: the IPL applicator is placed on skin and 'clicks' — each click delivers one or a series of pulses. Sensation: mild stinging and warmth, like an elastic band snap. OPT technology significantly reduces discomfort versus older IPL.\n— Duration: full face 20-30 minutes; targeted correction (nose, cheeks) 10-15 minutes.\n— Afterward: skin pink for 2-4 hours. Pigment spots — darken and 'shed' over 7-14 days (normal!). Vessels — disappear or fade within 1-2 weeks.\n— Essential: SPF 50+ daily for 4 weeks after every session. Without photoprotection — risk of pigmentation return.\n\nResurFX session:\n— Duration: 20-30 minutes per zone.\n— Anaesthesia: topical cream 30 minutes before (recommended).\n— Sensations: tingling, warmth. Afterward: skin pink 24-48 hours, mild peeling 3-5 days. No social restrictions from day 2-3.",
        },
        calloutBody: {
          uk: "Потемніння пігментних плям після IPL — не ускладнення, а нормальна реакція. Пігмент підіймається до поверхні і «лущиться» з верхнім шаром клітин. Якщо не лупити і не терти — через 10–14 днів шкіра рівна. Якщо зривати — залишається слід.",
          ru: "Потемнение пигментных пятен после IPL — не осложнение, а нормальная реакция. Пигмент поднимается к поверхности и «шелушится» с верхним слоем клеток. Если не щипать и не тереть — через 10–14 дней кожа ровная. Если срывать — остаётся след.",
          en: "Darkening of pigment spots after IPL is not a complication — it's a normal response. The pigment rises to the surface and 'sheds' with the top layer of cells. Leave it alone — within 10-14 days the skin is even. Pick at it — and a mark remains.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "Скільки сесій IPL потрібно для пігментації?", ru: "Сколько сессий IPL нужно для пигментации?", en: "How many IPL sessions for pigmentation?" },
        answer: { uk: "Зазвичай 3–5 сесій з інтервалом 3–4 тижні. Точне число — після оцінки типу і глибини пігментації. Сонячне лентиго — реагує на 1–2 сесію. Дифузна пігментація — потребує повного курсу.", ru: "Обычно 3–5 сессий с интервалом 3–4 недели. Точное число — после оценки типа и глубины пигментации. Солнечное лентиго — реагирует на 1–2 сессию. Диффузная пигментация — требует полного курса.", en: "Usually 3-5 sessions at 3-4 week intervals. The exact number depends on pigmentation type and depth. Solar lentigines respond after 1-2 sessions. Diffuse pigmentation requires a full course." },
      },
      {
        question: { uk: "Чи можна робити IPL влітку?", ru: "Можно ли делать IPL летом?", en: "Can IPL be done in summer?" },
        answer: { uk: "Дуже обережно. IPL не рекомендований при активній засмазі або протягом 2 тижнів після засмагання. Ризик постзапальної гіперпігментації суттєво вищий. В ідеалі — осінь-зима-рання весна. Якщо влітку — тільки при суворому SPF 50+.", ru: "Очень осторожно. IPL не рекомендован при активном загаре или в течение 2 недель после загорания. Риск поствоспалительной гиперпигментации существенно выше. В идеале — осень-зима-ранняя весна.", en: "With great caution. IPL is not recommended with an active tan or within 2 weeks of tanning. The risk of post-inflammatory hyperpigmentation is substantially higher. Ideally: autumn-winter-early spring." },
      },
      {
        question: { uk: "IPL від розацеа — це ефективно?", ru: "IPL от розацеа — это эффективно?", en: "Is IPL effective for rosacea?" },
        answer: { uk: "Так — для еритематозно-телеангіектатичного типу (почервоніння і судинна сітка). IPL включений до міжнародних протоколів лікування розацеа. Ефект не постійний: розацеа потребує підтримуючих сесій 1–2 рази на рік. Пустульозний тип розацеа — спочатку медикаментозне лікування.", ru: "Да — для эритематозно-телеангиэктатического типа (покраснение и сосудистая сетка). IPL включён в международные протоколы лечения розацеа. Эффект не постоянный: розацеа требует поддерживающих сессий 1–2 раза в год.", en: "Yes — for the erythematotelangiectatic type (redness and vascular network). IPL is included in international rosacea treatment protocols. The effect isn't permanent: rosacea requires maintenance sessions 1-2 times a year. Papulopustular rosacea — medical treatment first." },
      },
      {
        question: { uk: "Чим ResurFX відрізняється від AcuPulse CO₂?", ru: "Чем ResurFX отличается от AcuPulse CO₂?", en: "How does ResurFX differ from AcuPulse CO₂?" },
        answer: { uk: "ResurFX — нефляційний (non-ablative): не знімає верхній шар шкіри, відновлення 2–3 дні. AcuPulse — абляційний CO₂: видаляє епідерміс у зонах обробки, відновлення 7–10 днів. AcuPulse дає більш виражений результат при рубцях і глибоких зморшках; ResurFX — мягший, без явного простою.", ru: "ResurFX — нефляционный (non-ablative): не снимает верхний слой кожи, восстановление 2–3 дня. AcuPulse — абляционный CO₂: удаляет эпидермис в зонах обработки, восстановление 7–10 дней. AcuPulse даёт более выраженный результат при рубцах и глубоких морщинах; ResurFX — мягче, без явного простоя.", en: "ResurFX is non-ablative: no skin surface removal, 2-3 days recovery. AcuPulse is ablative CO₂: removes epidermis in treatment zones, 7-10 days recovery. AcuPulse delivers stronger results for scars and deep wrinkles; ResurFX is gentler, with no visible downtime." },
      },
    ],
  },

  // ─── SPLENDOR X ────────────────────────────────────────────────────────────
  {
    slug: "splendor-x",
    summary: {
      uk: "Splendor X у GENEVITY — лазер для епіляції з технологією BLEND X від Candela: одночасна дія двох довжин хвиль (755 нм олександрит + 1064 нм Nd:YAG) для безпечної і ефективної епіляції будь-якого типу шкіри — включно з темними і засмаглими. Квадратний аплікатор, без перекриттів і пропусків.",
      ru: "Splendor X в GENEVITY — лазер для эпиляции с технологией BLEND X от Candela: одновременное действие двух длин волн (755 нм александрит + 1064 нм Nd:YAG) для безопасной и эффективной эпиляции любого типа кожи — включая тёмную и загорелую. Квадратный аппликатор, без перекрытий и пропусков.",
      en: "Splendor X at GENEVITY — a Candela laser for hair removal with BLEND X technology: simultaneous dual wavelengths (755 nm alexandrite + 1064 nm Nd:YAG) for safe and effective hair removal on any skin type — including dark and tanned skin. Square applicator, no overlaps or missed spots.",
    },
    sections: [
      {
        heading: { uk: "Чому Splendor X і що таке BLEND X", ru: "Почему Splendor X и что такое BLEND X", en: "Why Splendor X and what BLEND X is" },
        body: {
          uk: "Splendor X — лазер для фотоепіляції від Candela (США), однієї з найстаріших і найбільш авторитетних компаній в естетичній лазерній медицині.\n\nГоловна особливість — технологія BLEND X:\nТрадиційні лазерні системи використовують одну довжину хвилі. Олександритовий лазер (755 нм) — ефективніший для світлої шкіри з темним волоссям. Nd:YAG (1064 нм) — безпечніший для темних типів шкіри, проникає глибше, але менш ефективний на тонких волоссях. BLEND X — патентована технологія Candela, що об'єднує обидва лазери в одному аплікаторі, які діють одночасно в кожному імпульсі:\n— 755 нм прицільно знищує меланін у волосяному фолікулі (висока ефективність);\n— 1064 нм проникає глибше і нагріває тканини навколо фолікула (знижує ризик для темної шкіри).\n\nРезультат BLEND X:\n— ефективна епіляція для всіх типів шкіри Fitzpatrick I–VI, включно з темними;\n— безпечне використання на засмаглій шкірі (з обережністю);\n— ефективність на тонкому темному волоссі, де 1064 нм один недостатній.\n\nКвадратний аплікатор 24×24 мм:\n— покриває більшу площу за одне натискання без округлих перекриттів;\n— рівномірна обробка без пропусків і «хмарної» картини, типової для круглих аплікаторів;\n— суттєво швидша обробка великих зон (ноги, спина, живіт).\n\nОхолоджуюча система Zimmer — підтримує кріокулінг поверхні шкіри до -4°C під час кожного імпульсу. Мінімальний дискомфорт, захист епідермісу.",
          ru: "Splendor X — лазер для фотоэпиляции от Candela (США), одной из старейших и наиболее авторитетных компаний в эстетической лазерной медицине.\n\nГлавная особенность — технология BLEND X:\nТрадиционные лазерные системы используют одну длину волны. Александритовый лазер (755 нм) — эффективнее для светлой кожи с тёмными волосами. Nd:YAG (1064 нм) — безопаснее для тёмных типов кожи, проникает глубже, но менее эффективен на тонких волосах. BLEND X — патентованная технология Candela, объединяющая оба лазера в одном аппликаторе, действующих одновременно в каждом импульсе:\n— 755 нм прицельно уничтожает меланин в волосяном фолликуле (высокая эффективность);\n— 1064 нм проникает глубже и нагревает ткани вокруг фолликула (снижает риск для тёмной кожи).\n\nРезультат BLEND X:\n— эффективная эпиляция для всех типов кожи Fitzpatrick I–VI, включая тёмные;\n— безопасное использование на загорелой коже (с осторожностью);\n— эффективность на тонком тёмном волосе, где 1064 нм один недостаточен.\n\nКвадратный аппликатор 24×24 мм:\n— покрывает большую площадь за одно нажатие без круглых перекрытий;\n— равномерная обработка без пропусков;\n— существенно быстрее обработка больших зон (ноги, спина, живот).",
          en: "Splendor X is a laser hair removal system from Candela (USA), one of the oldest and most respected companies in aesthetic laser medicine.\n\nThe key feature is BLEND X technology:\nTraditional laser systems use a single wavelength. Alexandrite (755 nm) — more effective for fair skin with dark hair. Nd:YAG (1064 nm) — safer for darker skin types, penetrates deeper, but less effective on fine hair. BLEND X is Candela's patented technology combining both lasers in one applicator, firing simultaneously in every pulse:\n— 755 nm precisely destroys melanin in the hair follicle (high efficacy);\n— 1064 nm penetrates deeper and heats tissue around the follicle (reduced risk for dark skin).\n\nBLEND X results:\n— effective hair removal for all Fitzpatrick skin types I-VI, including dark;\n— safe use on tanned skin (with caution);\n— effectiveness on fine dark hair where 1064 nm alone is insufficient.\n\nSquare applicator 24×24 mm:\n— covers a larger area per pulse without round overlaps;\n— uniform treatment without missed spots or the 'cloud' pattern typical of round applicators;\n— significantly faster coverage of large zones (legs, back, abdomen).\n\nZimmer cooling system — maintains skin surface cryo-cooling to -4°C during every pulse. Minimal discomfort, epidermal protection.",
        },
        calloutBody: {
          uk: "Лазерна епіляція не «назавжди» у прямому сенсі — вона виключає волосяні фолікули у фазі активного росту. Нові фолікули, що прокидаються від гормональних змін, можуть давати поодиноке нове волосся. Саме тому після основного курсу потрібна підтримуюча сесія 1–2 рази на рік.",
          ru: "Лазерная эпиляция не «навсегда» в прямом смысле — она исключает волосяные фолликулы в фазе активного роста. Новые фолликулы, пробуждающиеся от гормональных изменений, могут давать единичные новые волосы. Именно поэтому после основного курса нужна поддерживающая сессия 1–2 раза в год.",
          en: "Laser hair removal is not 'permanent' in the literal sense — it eliminates hair follicles in the active growth phase. New follicles awakened by hormonal changes can produce occasional new hairs. That's why maintenance sessions 1-2 times a year are needed after the main course.",
        },
      },
      {
        heading: { uk: "Зони, підготовка і курс", ru: "Зоны, подготовка и курс", en: "Zones, preparation and course" },
        body: {
          uk: "Splendor X на Splendor X виконується для всіх стандартних зон епіляції:\n\nОбличчя і шия:\n— верхня губа, підборіддя, бакенбарди, шия, міжбрів'я;\n— особливо ефективний при гормональному гіпертрихозі.\n\nТіло:\n— пахви — одна з найпопулярніших зон, зазвичай 5–7 сесій;\n— бікіні (класичне, глибоке, повне «бразильське»);\n— ноги (гомілки, стегна, повністю);\n— живіт, спина, груди (чоловіча і жіноча зони);\n— руки (передпліччя, плечі).\n\nЩо впливає на кількість сесій:\n— Фаза росту. Лазер діє тільки на волосся у фазі анагену (активного росту). Одночасно в анагені — 20–30% волосся. Тому потрібно кілька сесій з інтервалами.\n— Колір і товщина волосся. Темне, жорстке — відмінний відгук. Світле, тонке, пушкове (vellus) — значно нижчий (лазер потребує меланіну).\n— Гормональний фон. При СПКЯ або гіперандрогенемії — волосся відростає швидше, курс може бути довшим.\n\nСтандартний курс: 6–8 сесій для більшості зон. Інтервал між сесіями:\n— обличчя: 4–6 тижнів;\n— тіло: 6–8 тижнів.\n\nПідготовка до сесії:\n— поголити зону за день до процедури (НЕ воскувати, НЕ пінцетом за 4 тижні до);\n— без засмаги 2 тижні до і 2 тижні після;\n— SPF 50+ між сесіями на відкриті зони;\n— уникати антибіотиків тетрациклінового ряду і ретиноїдів перед процедурою.\n\nПротипоказання: вагітність, активні висипи у зоні (акне, герпес), меланома або підозра на неї, прийом фотосенсибілізаторів.",
          ru: "Splendor X выполняется для всех стандартных зон эпиляции:\n\nЛицо и шея:\n— верхняя губа, подбородок, бакенбарды, шея, межбровье;\n— особенно эффективен при гормональном гипертрихозе.\n\nТело:\n— подмышки — одна из самых популярных зон, обычно 5–7 сессий;\n— бикини (классическое, глубокое, полное «бразильское»);\n— ноги (голени, бёдра, полностью);\n— живот, спина, грудь (мужская и женская зоны);\n— руки (предплечья, плечи).\n\nЧто влияет на количество сессий:\n— Фаза роста. Лазер действует только на волос в фазе анагена (активного роста). Одновременно в анагене — 20–30% волос. Поэтому нужно несколько сессий.\n— Цвет и толщина волоса. Тёмное, жёсткое — отличный отклик. Светлое, тонкое, пушковое (vellus) — значительно ниже.\n— Гормональный фон. При СПКЯ или гиперандрогенемии — волосы отрастают быстрее.\n\nСтандартный курс: 6–8 сессий. Интервал:\n— лицо: 4–6 недель;\n— тело: 6–8 недель.\n\nПодготовка:\n— побрить зону за день до процедуры (НЕ воском, НЕ пинцетом за 4 недели до);\n— без загара 2 недели до и 2 после;\n— SPF 50+ между сессиями.",
          en: "Splendor X is available for all standard hair removal zones:\n\nFace and neck:\n— upper lip, chin, sideburns, neck, inter-brow;\n— especially effective for hormonal hypertrichosis.\n\nBody:\n— underarms — one of the most popular zones, usually 5-7 sessions;\n— bikini (classic, deep, full 'Brazilian');\n— legs (lower legs, thighs, full);\n— abdomen, back, chest (male and female zones);\n— arms (forearms, upper arms).\n\nWhat affects the number of sessions:\n— Growth phase. The laser targets hair only in the anagen phase (active growth). Only 20-30% of hair is in anagen at once — hence multiple sessions.\n— Hair colour and thickness. Dark, coarse — excellent response. Fair, fine, vellus hair — significantly lower (the laser needs melanin).\n— Hormonal status. With PCOS or hyperandrogenaemia — hair regrows faster, the course may be longer.\n\nStandard course: 6-8 sessions. Intervals:\n— face: 4-6 weeks;\n— body: 6-8 weeks.\n\nPreparation:\n— shave the zone the day before (do NOT wax or tweeze within 4 weeks prior);\n— no tanning 2 weeks before and 2 weeks after;\n— SPF 50+ between sessions on exposed zones.",
        },
        calloutBody: {
          uk: "Якщо ваш фотограф говорить, що «для нас краще воскування — воно виймає волосся з коренем», то він має рацію для однієї процедури. Але за 4 тижні до лазерної сесії — тільки голити, жодного воску. Інакше у фолікулі не буде волоссини, і лазер нічого не знищить.",
          ru: "Если ваш мастер говорит, что «для нас лучше воск — он вытаскивает волос с корнем», то он прав для одной процедуры. Но за 4 недели до лазерной сессии — только брить, никакого воска. Иначе в фолликуле не будет волоска, и лазер ничего не уничтожит.",
          en: "If your beauty technician says 'waxing is better — it pulls the hair from the root', they're right for one treatment. But 4 weeks before a laser session — shave only, no wax. Otherwise the follicle has no hair and the laser has nothing to destroy.",
        },
      },
      {
        heading: { uk: "Сесія, відчуття і реабілітація", ru: "Сессия, ощущения и реабилитация", en: "Session, sensations and recovery" },
        body: {
          uk: "Тривалість сесії:\n— пахви — 5–10 хвилин;\n— бікіні (повне) — 20–30 хвилин;\n— ноги (повністю) — 30–45 хвилин;\n— спина — 20–30 хвилин.\n\nОхолодження і дискомфорт:\nSplendor X оснащений системою Zimmer Cryo 6, яка обдуває шкіру холодним повітрям (-4°C) безпосередньо під час кожного імпульсу. Відчуття — короткий «щипок» і моментальне охолодження. Більшість клієнтів не потребують анестезії. Для чутливих зон (бікіні, пахви) — аплікаційний крем за 30 хвилин за бажанням.\n\nПісля сесії:\n— легке почервоніння і «мурашки» навколо фолікулів (перифолікулярна реакція) — нормально, проходить за 30–60 хвилин;\n— через 1–3 тижні — оброблені волосся «випадають» (фолікул виштовхує відмерлий стержень) — не вщипувати;\n— між сесіями — тільки голити, не воскувати;\n— SPF 50+ на оброблені відкриті зони;\n— без сауни, басейну, активного спорту 24–48 годин після;\n— уникати дезодорантів і парфумів на пахвах у перший день.",
          ru: "Продолжительность сессии:\n— подмышки — 5–10 минут;\n— бикини (полное) — 20–30 минут;\n— ноги (полностью) — 30–45 минут;\n— спина — 20–30 минут.\n\nОхлаждение и дискомфорт:\nSplendor X оснащён системой Zimmer Cryo 6, которая обдувает кожу холодным воздухом (-4°C) непосредственно во время каждого импульса. Ощущения — короткий «щипок» и моментальное охлаждение. Большинство клиентов не нуждаются в анестезии. Для чувствительных зон (бикини, подмышки) — аппликационный крем за 30 минут по желанию.\n\nПосле сессии:\n— лёгкое покраснение и «мурашки» вокруг фолликулов (перифолликулярная реакция) — нормально, проходит за 30–60 минут;\n— через 1–3 недели — обработанные волосы «выпадают» (фолликул выталкивает отмерший стержень) — не выщипывать;\n— между сессиями — только брить;\n— SPF 50+ на обработанные открытые зоны;\n— без сауны, бассейна, активного спорта 24–48 часов после.",
          en: "Session duration:\n— underarms: 5-10 minutes;\n— bikini (full): 20-30 minutes;\n— legs (full): 30-45 minutes;\n— back: 20-30 minutes.\n\nCooling and discomfort:\nSplendor X is equipped with Zimmer Cryo 6, which blows cold air (-4°C) directly during every pulse. Sensation: a brief 'snap' and immediate cooling. Most clients don't need anaesthesia. For sensitive zones (bikini, underarms) — topical cream 30 minutes before if desired.\n\nAfterward:\n— mild redness and 'goosebumps' around follicles (perifollicular response) — normal, resolves in 30-60 minutes;\n— 1-3 weeks later — treated hairs 'shed' (the follicle pushes out the dead shaft) — do not tweeze;\n— between sessions: shave only, no waxing;\n— SPF 50+ on treated exposed zones;\n— no sauna, pool, intense exercise for 24-48 hours;\n— avoid deodorants and perfume on underarms the first day.",
        },
        calloutBody: {
          uk: "«Волосся стало рости знову» після 6 сесій — найчастіше означає, що деякі фолікули були в режимі спокою (телоген) під час сесій і не потрапили під дію лазера. 1–2 підтримуючі сесії вирішують цю ситуацію. Повне «повернення» волосся — ознака того, що у клініці не дотримувалися інтервалів або потужності.",
          ru: "«Волосы снова начали расти» после 6 сессий — чаще всего означает, что некоторые фолликулы находились в режиме покоя (телоген) во время сессий и не попали под воздействие лазера. 1–2 поддерживающие сессии решают эту ситуацию. Полное «возвращение» волос — признак того, что в клинике не соблюдались интервалы или мощность.",
          en: "'Hair started growing back' after 6 sessions usually means some follicles were in the resting phase (telogen) during sessions and weren't targeted. 1-2 maintenance sessions resolve this. Complete 'return' of hair is a sign that intervals or power settings weren't followed correctly at the clinic.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "Скільки сесій лазерної епіляції потрібно?", ru: "Сколько сессий лазерной эпиляции нужно?", en: "How many laser hair removal sessions are needed?" },
        answer: { uk: "Стандартний курс — 6–8 сесій. На обличчі — частіше 8–10 через гормональний вплив. Після курсу 1–2 підтримуючі сесії на рік.", ru: "Стандартный курс — 6–8 сессий. На лице — чаще 8–10 из-за гормонального влияния. После курса 1–2 поддерживающие сессии в год.", en: "Standard course: 6-8 sessions. On the face — often 8-10 due to hormonal influence. After the course: 1-2 maintenance sessions per year." },
      },
      {
        question: { uk: "Чи підходить лазерна епіляція для темної шкіри?", ru: "Подходит ли лазерная эпиляция для тёмной кожи?", en: "Is laser hair removal suitable for dark skin?" },
        answer: { uk: "Splendor X з технологією BLEND X — так, він безпечний для типів Fitzpatrick V–VI. 1064 нм Nd:YAG мінімізує ризик для темної шкіри. Але перше тестове опромінення і правильні параметри — обов'язкові.", ru: "Splendor X с технологией BLEND X — да, он безопасен для типов Fitzpatrick V–VI. 1064 нм Nd:YAG минимизирует риск для тёмной кожи. Но первое тестовое облучение и правильные параметры — обязательны.", en: "Splendor X with BLEND X technology — yes, it's safe for Fitzpatrick types V-VI. The 1064 nm Nd:YAG minimises risk for dark skin. But a test patch and correct parameters are mandatory." },
      },
      {
        question: { uk: "Чи боляче робити лазерну епіляцію на Splendor X?", ru: "Больно ли делать лазерную эпиляцию на Splendor X?", en: "Is laser hair removal on Splendor X painful?" },
        answer: { uk: "Значно комфортніше, ніж на старих системах. Zimmer Cryo 6 охолоджує шкіру під час кожного імпульсу — відчуття як «щипок гумки» + миттєве охолодження. Більшість клієнтів добре переносять без анестезії.", ru: "Значительно комфортнее, чем на старых системах. Zimmer Cryo 6 охлаждает кожу во время каждого импульса — ощущения как «щипок резинки» + мгновенное охлаждение. Большинство клиентов хорошо переносят без анестезии.", en: "Significantly more comfortable than on older systems. Zimmer Cryo 6 cools the skin during every pulse — the sensation is a 'rubber-band snap' + instant cooling. Most clients tolerate it well without anaesthesia." },
      },
      {
        question: { uk: "Чому між сесіями потрібно голити, а не воскувати?", ru: "Почему между сессиями нужно брить, а не использовать воск?", en: "Why shave between sessions rather than wax?" },
        answer: { uk: "Лазер знищує меланін усередині волосяного фолікула. Якщо волосся виймається з коренем (воск, шугаринг, пінцет) — фолікул порожній, і лазер не матиме мішені. Голити — значить залишати корінь нетронутим для наступної сесії.", ru: "Лазер уничтожает меланин внутри волосяного фолликула. Если волос вытаскивается с корнем (воск, шугаринг, пинцет) — фолликул пуст, и лазеру не будет мишени. Брить — значит оставлять корень нетронутым для следующей сессии.", en: "The laser destroys melanin inside the hair follicle. If the hair is removed from the root (wax, sugaring, tweezers) — the follicle is empty and the laser has no target. Shaving leaves the root intact for the next session." },
      },
    ],
  },

  // ─── HYDRAFACIAL ───────────────────────────────────────────────────────────
  {
    slug: "hydrafacial",
    summary: {
      uk: "HydraFacial у GENEVITY — багатоетапна процедура на апараті BeautyAngel з технологією Vortex-Fusion: очищення, ексфоліація, видалення комедонів, зволоження та захист в одній сесії. Ефект помітний одразу, без почервоніння і відновлення — підходить навіть для чутливої шкіри.",
      ru: "HydraFacial в GENEVITY — многоэтапная процедура на аппарате BeautyAngel с технологией Vortex-Fusion: очищение, эксфолиация, удаление комедонов, увлажнение и защита в одной сессии. Эффект заметен сразу, без покраснения и восстановления — подходит даже для чувствительной кожи.",
      en: "HydraFacial at GENEVITY — a multi-step procedure with Vortex-Fusion technology: cleansing, exfoliation, comedone extraction, hydration and protection in a single session. The effect is visible immediately, without redness or downtime — suitable even for sensitive skin.",
    },
    sections: [
      {
        heading: { uk: "Що відбувається на HydraFacial і чому це не звичайна чистка", ru: "Что происходит на HydraFacial и почему это не обычная чистка", en: "What happens in a HydraFacial and why it's not a regular facial" },
        body: {
          uk: "HydraFacial — запатентована система, що поєднує кілька дій в одній процедурі через спеціалізовані наконечники апарата:\n\nЕтап 1 — Cleanse + Peel (очищення і ексфоліація):\nМ'яке відшелушування верхнього шару ороговілих клітин за допомогою комбінації глюконолактону (PHA-кислота) і саліцилової кислоти. Кислоти у концентрації, що не дає почервоніння, але ефективно готує шкіру до наступних кроків.\n\nЕтап 2 — Extract + Hydrate (вакуумне очищення і зволоження):\nTip Vortex — воронкоподібний наконечник, що одночасно:\n— вакуумом витягує вміст пор (комедони, сальні пробки) без механічного тиску;\n— вводить у пори зволожуючу сироватку.\n\nЕтап 3 — Fuse + Protect (насичення і захист):\nФінальний антиоксидантний комплекс (гіалуронова кислота + пептиди + AGF — автологічний фактор росту або рослинні замінники) вводиться у шкіру вортексним методом — глибше, ніж при звичайному нанесенні.\n\nЧому HydraFacial відрізняється від апаратного пілінгу або мануальної чистки:\n— Мануальна чистка — механічний тиск, почервоніння на 1–2 дні, ризик травми пор;\n— Ультразвукова чистка — поверхнева, не витягує глибокі комедони;\n— Хімічний пілінг — ексфоліація без глибокого очищення пор;\n— HydraFacial — одночасно і очищення, і зволоження, і ексфоліація в одній безболісній сесії.\n\nРезультат після першої процедури: шкіра свіжа, рівна, зволожена, пори помітно чистіші. Без почервоніння, без «голого вигляду» після агресивних процедур. Виходити одразу з клініки — без макіяжу.",
          ru: "HydraFacial — запатентованная система, объединяющая несколько действий в одной процедуре через специализированные наконечники аппарата:\n\nЭтап 1 — Cleanse + Peel (очищение и эксфолиация):\nМягкое отшелушивание верхнего слоя ороговевших клеток с помощью комбинации глюконолактона (PHA-кислота) и салициловой кислоты.\n\nЭтап 2 — Extract + Hydrate (вакуумное очищение и увлажнение):\nTip Vortex — воронкообразный наконечник, который одновременно:\n— вакуумом извлекает содержимое пор (комедоны, сальные пробки) без механического давления;\n— вводит в поры увлажняющую сыворотку.\n\nЭтап 3 — Fuse + Protect (насыщение и защита):\nФинальный антиоксидантный комплекс (гиалуроновая кислота + пептиды + AGF) вводится в кожу вортексным методом — глубже, чем при обычном нанесении.\n\nПочему HydraFacial отличается от аппаратного пилинга или мануальной чистки:\n— Мануальная чистка — механическое давление, покраснение на 1–2 дня;\n— Ультразвуковая чистка — поверхностная;\n— Химический пилинг — эксфолиация без глубокого очищения пор;\n— HydraFacial — одновременно и очищение, и увлажнение, и эксфолиация.\n\nРезультат: кожа свежая, ровная, увлажнённая, поры заметно чище. Без покраснения. Выходить сразу без макияжа.",
          en: "HydraFacial is a patented system that combines multiple actions in one procedure through specialised device tips:\n\nStep 1 — Cleanse + Peel:\nGentle exfoliation of the surface dead-cell layer using a combination of gluconolactone (PHA acid) and salicylic acid — at concentrations that deliver results without causing redness.\n\nStep 2 — Extract + Hydrate:\nThe Vortex tip simultaneously:\n— uses vacuum to extract pore contents (comedones, sebaceous plugs) without mechanical pressure;\n— infuses a hydrating serum into the pores.\n\nStep 3 — Fuse + Protect:\nA final antioxidant complex (hyaluronic acid + peptides + AGF — autologous growth factor or plant-based equivalent) is delivered into the skin via the vortex method — deeper than topical application.\n\nWhy HydraFacial differs from device peels or manual extraction:\n— Manual extraction: mechanical pressure, redness for 1-2 days, pore trauma risk;\n— Ultrasound facial: surface only, doesn't clear deep comedones;\n— Chemical peel: exfoliation without deep pore cleansing;\n— HydraFacial: cleansing + hydration + exfoliation in one painless session.\n\nResult after one session: fresh, even, hydrated skin with visibly cleaner pores. No redness, no raw look. You can walk out without makeup immediately.",
        },
        calloutBody: {
          uk: "HydraFacial — одна з небагатьох процедур, яку можна робити щомісяця і яка підходить для будь-якого типу шкіри, включно з чутливою, тонкою і схильною до розацеа. Ми часто рекомендуємо її як «базу» перед більш серйозними процедурами.",
          ru: "HydraFacial — одна из немногих процедур, которую можно делать ежемесячно и которая подходит для любого типа кожи, включая чувствительную, тонкую и склонную к розацеа. Мы часто рекомендуем её как «базу» перед более серьёзными процедурами.",
          en: "HydraFacial is one of the few procedures that can be done monthly and that suits every skin type, including sensitive, thin and rosacea-prone skin. We often recommend it as a 'base' procedure before more intensive treatments.",
        },
      },
      {
        heading: { uk: "Для кого і для чого HydraFacial", ru: "Для кого и для чего HydraFacial", en: "Who HydraFacial is for and what it addresses" },
        body: {
          uk: "HydraFacial підходить практично всім і не вимагає підготовки або відновлення. Основні показання:\n\n— Жирна шкіра і розширені пори. Вакуумне очищення без травми — ефективна альтернатива мануальному видаленню комедонів.\n— Чутлива і реактивна шкіра. Один з небагатьох апаратних методів без ризику роздратування: PHA-кислоти м'якші за AHA/BHA, немає механічного тиску, немає болю.\n— Розацеа і купероз. На відміну від пілінгів — не провокує судинну реакцію. Навпаки: зменшує реактивність через глибоке зволоження.\n— Зневоднена і тьмяна шкіра. Гіалуронова кислота і пептиди на 3-му кроці — видима «свіжість» і зволоженість одразу після.\n— Вугровий висип (акне, comedonal акне). Регулярні HydraFacial кожні 3–4 тижні — частина комплексного протоколу при нежирному акне. Запалення (пустули) — не обробляємо.\n— Передсвяткова підготовка. Популярний як «express glow» перед важливою подією.\n— Підтримуючий догляд між більш агресивними процедурами (лазер, пілінги, мікрогольна RF).\n\nHydraFacial + бустери:\nОпціонально до процедури або між кроками можна додати спеціалізовані бустерні сироватки:\n— Growth Factor — для зрілої шкіри, антивікова дія;\n— Britenol — відбілювання, корекція пігментації;\n— DermaBuilder — щільність і пружність;\n— Rozatrol — для чутливої, схильної до почервоніння шкіри.\n\nПротипоказань практично немає — крім активних запальних висипів у зоні обробки, відкритих ран, вагітності (уточнювати).",
          ru: "HydraFacial подходит практически всем и не требует подготовки или восстановления.\n\n— Жирная кожа и расширенные поры. Вакуумное очищение без травмы — эффективная альтернатива мануальному удалению комедонов.\n— Чувствительная и реактивная кожа. Один из немногих аппаратных методов без риска раздражения.\n— Розацеа и купероз. В отличие от пилингов — не провоцирует сосудистую реакцию.\n— Обезвоженная и тусклая кожа. Гиалуроновая кислота и пептиды на 3-м шаге — видимая «свежесть» сразу после.\n— Угревая сыпь (акне). Регулярные HydraFacial каждые 3–4 недели — часть комплексного протокола при ненасыщенном акне.\n— Предпраздничная подготовка.\n— Поддерживающий уход между более агрессивными процедурами.\n\nHydraFacial + бустеры:\n— Growth Factor — для зрелой кожи;\n— Britenol — отбеливание, коррекция пигментации;\n— DermaBuilder — плотность и упругость;\n— Rozatrol — для чувствительной, склонной к покраснению кожи.",
          en: "HydraFacial is suitable for virtually everyone and requires no preparation or downtime.\n\n— Oily skin and enlarged pores. Vacuum extraction without trauma — an effective alternative to manual comedone removal.\n— Sensitive and reactive skin. One of the few device methods without irritation risk: PHA acids are gentler than AHA/BHA, no mechanical pressure, no pain.\n— Rosacea and couperose. Unlike peels — doesn't trigger a vascular response. Deep hydration actually reduces skin reactivity.\n— Dehydrated and dull skin. Hyaluronic acid and peptides in step 3 — visible freshness and glow immediately after.\n— Acne (comedonal acne). Regular HydraFacial every 3-4 weeks as part of a comprehensive non-inflammatory acne protocol. Active pustules — not treated.\n— Pre-event glow preparation.\n— Maintenance between more aggressive procedures (laser, peels, microneedling RF).\n\nHydraFacial + boosters:\n— Growth Factor — for mature skin, anti-ageing;\n— Britenol — brightening, pigmentation correction;\n— DermaBuilder — density and firmness;\n— Rozatrol — for sensitive, redness-prone skin.\n\nAlmost no contraindications — except active inflammation at the treatment site, open wounds, and pregnancy (confirm).",
        },
        calloutBody: {
          uk: "Якщо у вас акне з пустулами і запаленнями — HydraFacial в активній фазі не робимо. Спочатку виходимо з запалення (дерматолог + терапія), потім запускаємо підтримуючий HydraFacial для профілактики нових комедонів.",
          ru: "Если у вас акне с пустулами и воспалениями — HydraFacial в активной фазе не делаем. Сначала выходим из воспаления (дерматолог + терапия), затем запускаем поддерживающий HydraFacial для профилактики новых комедонов.",
          en: "If you have acne with active pustules and inflammation — we don't do HydraFacial in the active phase. First we resolve the inflammation (dermatologist + therapy), then we introduce maintenance HydraFacial to prevent new comedone formation.",
        },
      },
      {
        heading: { uk: "Процедура: 30–45 хвилин вашого часу", ru: "Процедура: 30–45 минут вашего времени", en: "The procedure: 30-45 minutes of your time" },
        body: {
          uk: "Стандартна сесія HydraFacial — 30 хвилин. Розширена (з бустерами і масажем) — до 60 хвилин.\n\n1. Консультація і аналіз шкіри. Спеціаліст оцінює стан шкіри, визначає зони уваги (Т-зона, пори, пігментація) і підбирає бустери за потреби.\n\n2. Крок 1 — Cleanse + Peel. Наконечник з PHA/SA обробляє шкіру обличчя рівними рухами. Відчуття — легке поколювання, тепло, комфортно.\n\n3. Крок 2 — Extract + Hydrate. Tip Vortex «присмоктується» до пор — чути характерний звук (вакуум). Видно, скільки виходить вмісту пор у прозорому збірнику (так, це трохи лячно, але дуже показово). Відчуття — легке натягування шкіри, без болю.\n\n4. Крок 3 — Fuse + Protect. Антиоксидантний бустер наноситься і «вганяється» у шкіру вортексним рухом.\n\n5. Фінальний крем і SPF (опціонально).\n\nПісля процедури:\n— шкіра виглядає свіжою і рожевою — як після хорошого сну, не як після процедури;\n— макіяж одразу;\n— ніяких обмежень;\n— ефект помітний 7–10 днів, потім поступово зменшується.\n\nОптимальна частота: 1 раз на 3–4 тижні для підтримки тонусу і чистоти шкіри.",
          ru: "Стандартная сессия HydraFacial — 30 минут. Расширенная (с бустерами и массажем) — до 60 минут.\n\n1. Консультация и анализ кожи.\n\n2. Шаг 1 — Cleanse + Peel. Наконечник с PHA/SA обрабатывает кожу лица. Ощущения — лёгкое покалывание, тепло, комфортно.\n\n3. Шаг 2 — Extract + Hydrate. Tip Vortex «присасывается» к порам — слышен характерный звук (вакуум). Ощущения — лёгкое натяжение кожи, без боли.\n\n4. Шаг 3 — Fuse + Protect. Антиоксидантный бустер наносится вортексным движением.\n\n5. Финальный крем и SPF.\n\nПосле процедуры:\n— кожа выглядит свежей и розовой;\n— макияж сразу;\n— никаких ограничений;\n— эффект заметен 7–10 дней.\n\nОптимальная частота: 1 раз в 3–4 недели.",
          en: "Standard HydraFacial session: 30 minutes. Extended (with boosters and massage): up to 60 minutes.\n\n1. Consultation and skin analysis. The specialist assesses skin condition, identifies concern zones and selects boosters if needed.\n\n2. Step 1 — Cleanse + Peel. The PHA/SA tip moves evenly across the face. Sensation: mild tingle, warmth, comfortable.\n\n3. Step 2 — Extract + Hydrate. The Vortex tip adheres to pores — you hear the characteristic vacuum sound. You can see how much is extracted in the transparent reservoir. Sensation: gentle pulling, no pain.\n\n4. Step 3 — Fuse + Protect. The antioxidant booster is applied and worked into skin with vortex motion.\n\n5. Final moisturiser and SPF (optional).\n\nAfterward:\n— skin looks fresh and glowing — like after good sleep, not like after a procedure;\n— makeup immediately;\n— no restrictions;\n— the effect is visible for 7-10 days, then gradually fades.\n\nOptimal frequency: once every 3-4 weeks to maintain skin clarity and tone.",
        },
        calloutBody: {
          uk: "HydraFacial — це не разова процедура «до пляжу». Шкіра, яка отримує регулярне глибоке зволоження і очищення раз на місяць, реагує на будь-яке наступне лікування краще і швидше. Ми бачимо це на фактичних результатах клієнтів.",
          ru: "HydraFacial — это не разовая процедура «к пляжу». Кожа, которая получает регулярное глубокое увлажнение и очищение раз в месяц, реагирует на любое последующее лечение лучше и быстрее. Мы видим это на фактических результатах клиентов.",
          en: "HydraFacial is not a one-time 'beach prep' procedure. Skin that receives regular deep hydration and cleansing monthly responds to any subsequent treatment better and faster. We see this in actual client outcomes.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "Як часто можна робити HydraFacial?", ru: "Как часто можно делать HydraFacial?", en: "How often can HydraFacial be done?" },
        answer: { uk: "Раз на 3–4 тижні — оптимально. При акне і дуже жирній шкірі — можна частіше, кожні 2–3 тижні. Це безпечно.", ru: "Раз в 3–4 недели — оптимально. При акне и очень жирной коже — можно чаще, каждые 2–3 недели. Это безопасно.", en: "Once every 3-4 weeks is optimal. For acne and very oily skin — can be more frequent, every 2-3 weeks. This is safe." },
      },
      {
        question: { uk: "Чи підходить HydraFacial для чутливої шкіри?", ru: "Подходит ли HydraFacial для чувствительной кожи?", en: "Is HydraFacial suitable for sensitive skin?" },
        answer: { uk: "Так, це одна з найкомфортніших апаратних процедур для чутливої шкіри. PHA-кислоти не дають почервоніння. Вакуумне очищення без механічного тиску. Можна навіть при розацеа (без пустульозних форм).", ru: "Да, это одна из самых комфортных аппаратных процедур для чувствительной кожи. PHA-кислоты не дают покраснения. Вакуумное очищение без механического давления. Можно даже при розацеа (без пустулёзных форм).", en: "Yes, it's one of the most comfortable device-based treatments for sensitive skin. PHA acids don't cause redness. Vacuum extraction without mechanical pressure. Even suitable for rosacea (non-pustular forms)." },
      },
      {
        question: { uk: "Чи є відновлення після HydraFacial?", ru: "Есть ли восстановление после HydraFacial?", en: "Is there any downtime after HydraFacial?" },
        answer: { uk: "Немає. Шкіра свіжа і рожева 30–60 хвилин після, потім нормальний вигляд. Макіяж одразу. Жодних обмежень.", ru: "Нет. Кожа свежая и розовая 30–60 минут после, затем нормальный вид. Макияж сразу. Никаких ограничений.", en: "None. Skin is fresh and rosy for 30-60 minutes, then normal appearance. Makeup immediately. No restrictions at all." },
      },
    ],
  },

  // ─── ACUPULSE CO₂ ──────────────────────────────────────────────────────────
  {
    slug: "acupulse-co2",
    summary: {
      uk: "AcuPulse CO₂ у GENEVITY — фракційний CO₂-лазер Lumenis для глибокого шліфування шкіри: видалення рубців після акне, корекція вікових зморшок, вирівнювання тону і текстури шкіри. Найбільш ефективна абляційна процедура з підтвердженою базою клінічних досліджень — і відповідним відновленням.",
      ru: "AcuPulse CO₂ в GENEVITY — фракционный CO₂-лазер Lumenis для глубокой шлифовки кожи: удаление рубцов после акне, коррекция возрастных морщин, выравнивание тона и текстуры кожи. Наиболее эффективная абляционная процедура с подтверждённой базой клинических исследований — и соответствующим восстановлением.",
      en: "AcuPulse CO₂ at GENEVITY — Lumenis's fractional CO₂ laser for deep skin resurfacing: removal of post-acne scars, correction of age wrinkles, evening of skin tone and texture. The most effective ablative procedure with a confirmed clinical evidence base — and corresponding recovery.",
    },
    sections: [
      {
        heading: { uk: "Що таке фракційний CO₂ лазер і чому AcuPulse", ru: "Что такое фракционный CO₂-лазер и почему AcuPulse", en: "What a fractional CO₂ laser is and why AcuPulse" },
        body: {
          uk: "CO₂-лазер (10 600 нм) — абляційний лазер: він буквально випаровує тканину шкіри у зонах обробки. Це найбільш ефективна технологія для:\n— шліфування глибоких зморшок;\n— видалення рубців (атрофічних, після акне);\n— корекції нерівного рельєфу;\n— лікування кератозу, невусів, фотостаріння.\n\nФракційний режим (AcuPulse Fractional CO₂):\nТрадиційний «суцільний» CO₂-лазер (повна абляція) — надзвичайно ефективний, але дає тижні відновлення і суттєві ризики. Фракційна технологія (FX) вирішила цю проблему: лазер обробляє не всю поверхню шкіри, а тисячі мікроколонок (фракцій) — залишаючи між ними нетронуті «острівці» шкіри. Ці острівці стають джерелом швидкої регенерації: шкіра відновлюється значно швидше, ніж при повній абляції.\n\nAcuPulse від Lumenis — чому саме він:\n— Lumenis — розробник оригінального CO₂-лазера для медицини (патент 1990-х). AcuPulse — нащадок цієї лінійки з оновленою оптикою;\n— SmartPulse Technology — контроль тривалості кожного мікроімпульсу для точної глибини абляції без зайвого теплового пошкодження;\n— Два режими: AcuPulse Fractional (FX, менший downtime) і AcuPulse Total (суцільний, більший ефект, більший downtime);\n— Підтверджена FDA ефективність для лікування зморшок, рубців і акне-рубців.\n\nAcuPulse — найбільш «важка» лазерна процедура в нашому арсеналі. Ми вибираємо її тоді, коли глибина проблеми вимагає саме такого підходу — і коли клієнт готовий до відновлення.",
          ru: "CO₂-лазер (10 600 нм) — абляционный лазер: он буквально испаряет ткань кожи в зонах обработки. Это наиболее эффективная технология для:\n— шлифовки глубоких морщин;\n— удаления рубцов (атрофических, после акне);\n— коррекции неровного рельефа;\n— лечения кератоза, невусов, фотостарения.\n\nФракционный режим (AcuPulse Fractional CO₂):\nТрадиционный «сплошной» CO₂-лазер — чрезвычайно эффективен, но даёт недели восстановления. Фракционная технология (FX) решила эту проблему: лазер обрабатывает не всю поверхность кожи, а тысячи микроколонок, оставляя нетронутые «островки» кожи. Эти островки становятся источником быстрой регенерации.\n\nAcuPulse от Lumenis:\n— Lumenis — разработчик оригинального CO₂-лазера для медицины. AcuPulse — наследник этой линейки;\n— SmartPulse Technology — контроль длительности каждого микроимпульса для точной глубины абляции;\n— Два режима: AcuPulse Fractional (FX, меньший downtime) и AcuPulse Total (сплошной);\n— FDA-подтверждённая эффективность для лечения морщин и рубцов.",
          en: "CO₂ laser (10,600 nm) is an ablative laser: it literally vaporises skin tissue in the treated zones. It's the most effective technology for:\n— resurfacing deep wrinkles;\n— scar removal (atrophic, post-acne);\n— correcting uneven texture;\n— treating keratosis, nevi, photoageing.\n\nFractional mode (AcuPulse Fractional CO₂):\nTraditional 'fully ablative' CO₂ laser is extremely effective but requires weeks of recovery. Fractional technology (FX) solved this: the laser treats thousands of micro-columns rather than the entire surface, leaving intact 'islands' of skin between them. These islands drive rapid regeneration — recovery is dramatically shorter than with full ablation.\n\nAcuPulse by Lumenis — why specifically:\n— Lumenis invented the original medical CO₂ laser (1990s patent). AcuPulse is that lineage's descendant with updated optics;\n— SmartPulse Technology — controls each micro-pulse duration for precise ablation depth without excess thermal damage;\n— Two modes: AcuPulse Fractional (FX, less downtime) and AcuPulse Total (full ablation, greater effect, greater downtime);\n— FDA-confirmed efficacy for wrinkles, scars and acne scars.\n\nAcuPulse is the most demanding laser procedure in our arsenal. We choose it when the depth of the problem genuinely calls for it — and when the client is prepared for recovery.",
        },
        calloutBody: {
          uk: "AcuPulse — не процедура «перед вечіркою». Відновлення займає 7–10 днів, і перші 3–5 з них виходити з дому в громадські місця некомфортно. Ми говоримо це одразу — щоб ваш графік був підготовлений.",
          ru: "AcuPulse — не процедура «перед вечеринкой». Восстановление занимает 7–10 дней, и первые 3–5 из них выходить на люди некомфортно. Мы говорим об этом сразу — чтобы ваш график был подготовлен.",
          en: "AcuPulse is not a pre-party procedure. Recovery takes 7-10 days, and for the first 3-5 of those it's uncomfortable to be in public. We say this upfront — so your schedule is prepared.",
        },
      },
      {
        heading: { uk: "Показання: рубці, зморшки, оновлення шкіри", ru: "Показания: рубцы, морщины, обновление кожи", en: "Indications: scars, wrinkles, skin renewal" },
        body: {
          uk: "AcuPulse CO₂ показаний при:\n\nРубці після акне:\n— Атрофічні рубці типу «ice pick» (вузькі глибокі), «boxcar» (широкі з чіткими краями), «rolling» (хвилясті);\n— CO₂-лазер — метод вибору для ice-pick і boxcar рубців: повна абляція в зоні рубця + стимуляція регенерації → рубцева тканина замінюється новим колагеном;\n— Результат після 1 сесії: 30–60% покращення. Курс 2–3 сесій з інтервалом 3–6 місяців — кумулятивний ефект.\n\nВікові зморшки і фотостаріння:\n— Глибокі зморшки навколо рота («кодовий замок»), зморшки на повіках, носогубні складки від мімічного старіння;\n— Нерівна текстура шкіри, розширені пори, фотостаріння;\n— Лентиго, дифузна пігментація, кератоз.\n\nПеріорбітальна зона:\n— AcuPulse — один з небагатьох методів, ефективних для зморшок на нижніх і верхніх повіках. Дерматологічне шліфування периорбітальної зони — точна задача, що вимагає досвідченого оператора.\n\nRozтяжки (стрії):\n— Свіжі (червоні/фіолетові) — кращий відгук. Старі білі стрії — обмежена ефективність.\n\nСхема лікування:\n— 1 сесія для «загального оновлення» (фракційний, менша потужність);\n— 2–3 сесії для глибоких рубців (фракційний або total за показаннями);\n— Інтервал між сесіями: 3–6 місяців.\n\nПротипоказання: вагітність, активний герпес у зоні, прийом ізотретиноїну (акутан) менш ніж 12 місяців тому, темний тип шкіри Fitzpatrick V–VI (ризик гіперпігментації), схильність до келоїдних рубців, активні запальні захворювання шкіри.",
          ru: "AcuPulse CO₂ показан при:\n\nРубцы после акне:\n— Атрофические рубцы типа «ice pick», «boxcar», «rolling»;\n— CO₂-лазер — метод выбора для ice-pick и boxcar рубцов;\n— Результат после 1 сессии: 30–60% улучшения. Курс 2–3 сессии с интервалом 3–6 месяцев.\n\nВозрастные морщины и фотостарение:\n— Глубокие морщины вокруг рта, морщины на веках, носогубные складки;\n— Неровная текстура, расширенные поры, фотостарение;\n— Лентиго, диффузная пигментация, кератоз.\n\nПериорбитальная зона:\n— AcuPulse — один из немногих методов, эффективных для морщин на веках.\n\nСтрии:\n— Свежие (красные/фиолетовые) — лучший отклик.\n\nСхема лечения:\n— 1 сессия для «общего обновления»;\n— 2–3 сессии для глубоких рубцов;\n— Интервал: 3–6 месяцев.\n\nПротивопоказания: беременность, активный герпес в зоне, изотретиноин менее 12 месяцев назад, тёмный тип кожи Fitzpatrick V–VI, склонность к келоидам, активные воспаления кожи.",
          en: "AcuPulse CO₂ is indicated for:\n\nPost-acne scars:\n— Atrophic scars: ice-pick (narrow, deep), boxcar (wide, defined edges), rolling (wave-like);\n— CO₂ laser is the method of choice for ice-pick and boxcar scars: full ablation of scar tissue + regeneration stimulation → scar tissue replaced by new collagen;\n— Result after 1 session: 30-60% improvement. A course of 2-3 sessions at 3-6 month intervals delivers a cumulative effect.\n\nAge-related wrinkles and photoageing:\n— Deep perioral wrinkles ('bar code'), eyelid wrinkles, nasolabial folds from expression ageing;\n— Uneven texture, enlarged pores, photoageing;\n— Lentigines, diffuse pigmentation, keratosis.\n\nPeriorbital zone:\n— AcuPulse is one of the few effective methods for upper and lower eyelid wrinkles. Periorbital resurfacing requires an experienced operator.\n\nStretch marks:\n— Fresh (red/purple): better response. Old white striae: limited efficacy.\n\nTreatment schedule:\n— 1 session for general renewal (fractional, lower power);\n— 2-3 sessions for deep scars (fractional or total as indicated);\n— 3-6 month intervals between sessions.\n\nContraindications: pregnancy, active herpes in the zone, isotretinoin use within 12 months, dark skin types Fitzpatrick V-VI (hyperpigmentation risk), keloid tendency, active skin inflammation.",
        },
        calloutBody: {
          uk: "Ізотретиноїн (Роаккутан, Акнекутан) підвищує ризик рубцювання після CO₂-лазера. Якщо ви приймали ізотретиноїн — інтервал до процедури мінімум 12 місяців. Це не «рекомендація» — це клінічний стандарт безпеки.",
          ru: "Изотретиноин (Роаккутан, Акнекутан) повышает риск рубцевания после CO₂-лазера. Если вы принимали изотретиноин — интервал до процедуры минимум 12 месяцев. Это не «рекомендация» — это клинический стандарт безопасности.",
          en: "Isotretinoin (Roaccutane, Aknenormin) increases the scarring risk after CO₂ laser. If you've taken isotretinoin — the interval before the procedure is a minimum of 12 months. This is not a 'recommendation' — it's a clinical safety standard.",
        },
      },
      {
        heading: { uk: "Процедура, відновлення і догляд", ru: "Процедура, восстановление и уход", en: "Procedure, recovery and aftercare" },
        body: {
          uk: "Підготовка:\n— за 2–4 тижні — курс зволожуючих засобів і SPF, відмова від ретиноїдів;\n— при схильності до герпесу — профілактичний антивірусний препарат;\n— за 30–60 хвилин до — анестезуючий крем (аплікаційна анестезія).\n\nСесія (фракційний режим):\n— 30–60 хвилин залежно від зони;\n— лазерний наконечник сканує шкіру рівномірно за секції;\n— відчуття: тепло + поколювання при фракційному режимі, помірний дискомфорт;\n— для total-режиму або глибоких параметрів — можлива місцева анестезія ін'єкцією.\n\nПерші 24–48 годин:\n— набряк (особливо периорбітально — повіки можуть набрякнути);\n— почервоніння, шкіра виглядає «обпаленою»;\n— відчуття стягнутості, можливий легкий ексудат;\n— охолоджуючі серветки, призначений спеціаліст режим зволоження.\n\nДень 3–5:\n— набряк спадає;\n— шкіра починає відшаровуватись (не відривати!);\n— виглядає «як після сонячного опіку»;\n— виходити в людні місця некомфортно.\n\nДень 5–10:\n— шелушіння завершується;\n— нова шкіра рожева, тонка, реактивна;\n— строгий SPF 50+.\n\nПісля 2 тижнів:\n— шкіра нормалізується, рожевість зменшується;\n— видимий початковий результат.\n\nПовна нормалізація — через 4–6 тижнів. SPF 50+ — 3 місяці після процедури без пропусків.\n\nДлогостроковий результат:\n— помітний через 3–6 місяців, поки активний неоколагенез;\n— для рубців — максимальний ефект через 6–12 місяців після курсу.",
          ru: "Подготовка:\n— за 2–4 недели — курс увлажняющих средств и SPF, отказ от ретиноидов;\n— при склонности к герпесу — профилактический противовирусный препарат;\n— за 30–60 минут — анестезирующий крем.\n\nСессия (фракционный режим):\n— 30–60 минут в зависимости от зоны;\n— ощущения: тепло + покалывание.\n\nПервые 24–48 часов:\n— отёк (особенно периорбитально);\n— покраснение, кожа выглядит «обожжённой»;\n— ощущение стянутости.\n\nДень 3–5:\n— отёк спадает;\n— кожа начинает отшелушиваться (не срывать!);\n— выглядит «как после солнечного ожога».\n\nДень 5–10:\n— шелушение завершается;\n— новая кожа розовая, тонкая;\n— строгий SPF 50+.\n\nПолная нормализация — через 4–6 недель. SPF 50+ — 3 месяца после процедуры.\n\nДолгосрочный результат:\n— заметен через 3–6 месяцев;\n— для рубцов — максимальный эффект через 6–12 месяцев.",
          en: "Preparation:\n— 2-4 weeks before: a course of moisturisers and SPF; stop retinoids;\n— if herpes-prone: prophylactic antiviral;\n— 30-60 minutes before: topical anaesthetic cream.\n\nSession (fractional mode):\n— 30-60 minutes depending on zone;\n— the laser tip scans skin evenly in sections;\n— sensations: warmth + tingling in fractional mode, moderate discomfort;\n— local injection anaesthesia possible for total mode or deep parameters.\n\nFirst 24-48 hours:\n— swelling (especially periorbital — eyelids may swell);\n— redness, skin looks 'burned';\n— tightness, possible mild exudate;\n— cooling compresses, specialist-prescribed hydration protocol.\n\nDay 3-5:\n— swelling subsides;\n— skin begins peeling (do not peel it off!);\n— looks 'like a sunburn';\n— uncomfortable in public.\n\nDay 5-10:\n— peeling completes;\n— new skin is pink, thin, reactive;\n— strict SPF 50+.\n\nAfter 2 weeks:\n— skin normalises, pinkness reduces;\n— initial visible result apparent.\n\nFull normalisation: 4-6 weeks. SPF 50+ for 3 months post-procedure without exception.\n\nLong-term result:\n— visible at 3-6 months while neocollagenesis is active;\n— for scars: maximum effect at 6-12 months post-course.",
        },
        calloutBody: {
          uk: "Якщо шкіра відшаровується після AcuPulse — не допомагайте їй руками. Передчасне видалення корочок і шелушіння подовжує відновлення і підвищує ризик ускладнень. Час і правильний догляд — єдине, що потрібно.",
          ru: "Если кожа отшелушивается после AcuPulse — не помогайте ей руками. Преждевременное удаление корочек и шелушения продлевает восстановление и повышает риск осложнений. Время и правильный уход — единственное, что нужно.",
          en: "If your skin is peeling after AcuPulse — don't help it with your hands. Removing crusts and peeling prematurely prolongs recovery and increases complication risk. Time and correct aftercare are the only things needed.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "AcuPulse CO₂ від рубців після акне — скільки сесій?", ru: "AcuPulse CO₂ от рубцов после акне — сколько сессий?", en: "How many AcuPulse CO₂ sessions for post-acne scars?" },
        answer: { uk: "2–3 сесії з інтервалом 3–6 місяців для більшості типів рубців. Глибокі ice-pick рубці можуть потребувати 3–4 сесій або комбінації з підсічкою (subcision) перед лазером. Після кожної сесії — 30–60% покращення.", ru: "2–3 сессии с интервалом 3–6 месяцев для большинства типов рубцов. Глубокие ice-pick рубцы могут потребовать 3–4 сессий или комбинации с подсечкой (subcision) перед лазером.", en: "2-3 sessions at 3-6 month intervals for most scar types. Deep ice-pick scars may need 3-4 sessions or a combination with subcision before the laser. Each session delivers 30-60% improvement." },
      },
      {
        question: { uk: "Чи боляче CO₂ лазерне шліфування?", ru: "Больно ли CO₂ лазерное шлифование?", en: "Is CO₂ laser resurfacing painful?" },
        answer: { uk: "З аплікаційною анестезією (крем за 30–60 хвилин) — помірно. Відчуття тепла і поколювання під час сесії, потім печіння 2–4 години після. Для глибоких параметрів — пропонуємо місцеву ін'єкційну анестезію.", ru: "С аппликационной анестезией (крем за 30–60 минут) — умеренно. Ощущения тепла и покалывания во время сессии, затем жжение 2–4 часа после. Для глубоких параметров — предлагаем местную инъекционную анестезию.", en: "With topical anaesthetic cream (30-60 minutes prior) — moderate. Warmth and tingling during the session, then a burning sensation for 2-4 hours after. For deeper parameters — we offer local injection anaesthesia." },
      },
      {
        question: { uk: "Чи можна робити AcuPulse на темній шкірі?", ru: "Можно ли делать AcuPulse на тёмной коже?", en: "Can AcuPulse be done on dark skin?" },
        answer: { uk: "З великою обережністю. Типи Fitzpatrick V–VI — підвищений ризик постзапальної гіперпігментації після CO₂. Для темних типів шкіри з рубцями — спочатку оцінюємо альтернативи (EXION PRIME, підсічка) і обговорюємо ризики на консультації.", ru: "С большой осторожностью. Типы Fitzpatrick V–VI — повышенный риск поствоспалительной гиперпигментации после CO₂. Для тёмных типов кожи с рубцами — сначала оцениваем альтернативы и обсуждаем риски.", en: "With great caution. Fitzpatrick types V-VI have elevated post-inflammatory hyperpigmentation risk after CO₂. For dark skin with scars — we first evaluate alternatives (EXION PRIME, subcision) and discuss risks at consultation." },
      },
      {
        question: { uk: "Скільки часу займає відновлення після AcuPulse?", ru: "Сколько времени занимает восстановление после AcuPulse?", en: "How long is the recovery after AcuPulse?" },
        answer: { uk: "7–10 днів до соціально прийнятного вигляду. Перші 3–5 днів — набряк і відшарування, виходити некомфортно. Повна нормалізація — 4–6 тижнів. SPF 50+ суворо — 3 місяці.", ru: "7–10 дней до социально приемлемого вида. Первые 3–5 дней — отёк и шелушение, выходить некомфортно. Полная нормализация — 4–6 недель. SPF 50+ строго — 3 месяца.", en: "7-10 days to a socially acceptable appearance. First 3-5 days: swelling and peeling, uncomfortable in public. Full normalisation: 4-6 weeks. SPF 50+ strictly for 3 months." },
      },
      {
        question: { uk: "Як підготуватися до AcuPulse CO₂?", ru: "Как подготовиться к AcuPulse CO₂?", en: "How to prepare for AcuPulse CO₂?" },
        answer: { uk: "За 2–4 тижні: відмова від ретиноїдів, посилений SPF 50+, зволожуючий режим. За 1 тиждень: відмова від алкоголю, НПЗП, кроворозріджуючих. При схильності до герпесу — антивіруси за 2 дні до. Прийдіть без макіяжу. Після — підготуйте план відновлення: не планувати важливих подій у перші 10 днів.", ru: "За 2–4 недели: отказ от ретиноидов, усиленный SPF 50+, увлажняющий режим. За 1 неделю: отказ от алкоголя, НПВП, кроворазжижающих. При склонности к герпесу — антивирусы за 2 дня до. Придите без макияжа. После — подготовьте план восстановления: не планировать важных событий в первые 10 дней.", en: "2-4 weeks before: stop retinoids, boost SPF 50+, hydrating routine. 1 week before: stop alcohol, NSAIDs, blood thinners. If herpes-prone: antivirals starting 2 days before. Come without makeup. Afterward: prepare a recovery plan — do not schedule important events for the first 10 days." },
      },
    ],
  },
];

async function seedService(copy: ServiceCopy) {
  const svc = await sql`SELECT id FROM services WHERE slug = ${copy.slug} LIMIT 1`;
  if (!svc[0]) { console.error(`Service "${copy.slug}" not found — skip`); return; }
  const serviceId = svc[0].id as string;

  await sql`UPDATE services SET summary_uk=${copy.summary.uk}, summary_ru=${copy.summary.ru}, summary_en=${copy.summary.en} WHERE id=${serviceId}`;
  await sql`DELETE FROM content_sections WHERE owner_type='service' AND owner_id=${serviceId}`;
  await sql`DELETE FROM faq_items WHERE owner_type='service' AND owner_id=${serviceId}`;

  const sectionIds: string[] = [];
  for (let i = 0; i < copy.sections.length; i++) {
    const s = copy.sections[i];
    const id = randomUUID();
    sectionIds.push(id);
    const data = { heading: s.heading, body: s.body, calloutBody: s.calloutBody, heroImage: null };
    await sql`INSERT INTO content_sections(id,owner_type,owner_id,sort_order,section_type,data) VALUES(${id},'service',${serviceId},${i},'richText'::section_type,${JSON.stringify(data)}::jsonb)`;
  }
  for (let i = 0; i < copy.faq.length; i++) {
    const f = copy.faq[i];
    await sql`INSERT INTO faq_items(owner_type,owner_id,sort_order,question_uk,question_ru,question_en,answer_uk,answer_ru,answer_en) VALUES('service',${serviceId},${i},${f.question.uk},${f.question.ru},${f.question.en},${f.answer.uk},${f.answer.ru},${f.answer.en})`;
  }

  const newOrder = [...sectionIds.map(id => `section:${id}`), "faq", "doctors", "equipment", "relatedServices", "finalCTA"];
  await sql`UPDATE services SET block_order=${newOrder} WHERE id=${serviceId}`;
  console.log(`✓ ${copy.slug} — ${copy.sections.length} sections, ${copy.faq.length} FAQs`);
}

async function main() {
  for (const svc of SERVICES) await seedService(svc);
  await sql.end();
  console.log("\nV3c DONE — M22 Stellar Black, Splendor X, HydraFacial, AcuPulse CO₂.");
  console.log("All 11 apparatus-cosmetology services have copy. Continue with V4 for intimate-rejuvenation, laser-hair-removal, and longevity categories.");
}
main().catch(e => { console.error(e); process.exit(1); });
