/**
 * V2 part B — Терапія стовбуровими клітинами + Rejuran.
 * Apply: `npx tsx scripts/seed-copy-v2b.ts`
 */
import postgres from "postgres";
import * as fs from "fs";
import * as path from "path";
import { randomUUID } from "crypto";

const envContent = fs.readFileSync(path.resolve(__dirname, "../.env.local"), "utf-8");
const env: Record<string, string> = {};
envContent.split("\n").forEach((l) => {
  const [k, ...v] = l.split("=");
  if (k && v.length) env[k.trim()] = v.join("=").trim();
});
const sql = postgres(env.DATABASE_URL!);

type L = { uk: string; ru: string; en: string };
interface SectionCopy { heading: L; body: L; calloutBody: L; }
interface FaqCopy { question: L; answer: L; }
interface ServiceCopy { slug: string; summary: L; sections: SectionCopy[]; faq: FaqCopy[]; }

const stemCell: ServiceCopy = {
  slug: "stem-cell-therapy",
  summary: {
    uk: "Омолодження стовбуровими клітинами у GENEVITY — процедура регенеративної медицини нового покоління, при якій у шкіру вводять концентрат мезенхімальних стовбурових клітин. Фундаментальне омолодження на клітинному рівні, на межі косметології і медицини.",
    ru: "Омоложение стволовыми клетками в GENEVITY — процедура регенеративной медицины нового поколения, при которой в кожу вводят концентрат мезенхимальных стволовых клеток. Фундаментальное омоложение на клеточном уровне, на грани косметологии и медицины.",
    en: "Stem cell rejuvenation at GENEVITY — next-generation regenerative medicine: injections of concentrated mesenchymal stem cells into the skin. Fundamental, cell-level rejuvenation at the border of cosmetology and medicine.",
  },
  sections: [
    {
      heading: { uk: "Що таке омолодження стовбуровими клітинами", ru: "Что такое омоложение стволовыми клетками", en: "What stem-cell rejuvenation is" },
      body: {
        uk: "Стовбурові клітини — це клітини-попередники, здатні диференціюватись у будь-який тип клітин організму: фібробласти, кератиноцити, клітини судин. Вони є «сировиною», з якої шкіра відновлюється все життя. З віком кількість активних стовбурових клітин у тканинах падає — і саме це, поряд із втратою колагену, визначає видиме старіння.\n\nОмолодження стовбуровими клітинами — процедура, при якій у шкіру вводять концентрат сертифікованих мезенхімальних стовбурових клітин або їхніх похідних (факторів росту, секретому) для стимуляції власних регенеративних процесів. Метод знаходиться на межі косметології і регенеративної медицини; застосовується при складних випадках, коли класичні ін'єкційні процедури вже не дають глибокого результату.\n\nУ GENEVITY, Дніпро, ми використовуємо сертифіковані препарати на основі стовбурових клітин та їхнього секретому — продукти південнокорейських та європейських виробників, зареєстровані у Міжнародному реєстрі регенеративної медицини. Процедуру проводять лікарі із профільною освітою у регенеративній медицині, а не косметологи загального профілю.",
        ru: "Стволовые клетки — это клетки-предшественники, способные дифференцироваться в любой тип клеток организма: фибробласты, кератиноциты, клетки сосудов. Они являются «сырьём», из которого кожа восстанавливается всю жизнь. С возрастом количество активных стволовых клеток в тканях падает — и именно это, наряду с потерей коллагена, определяет видимое старение.\n\nОмоложение стволовыми клетками — процедура, при которой в кожу вводят концентрат сертифицированных мезенхимальных стволовых клеток или их производных (факторов роста, секретома) для стимуляции собственных регенеративных процессов. Метод находится на грани косметологии и регенеративной медицины; применяется в сложных случаях, когда классические инъекционные процедуры уже не дают глубокого результата.\n\nВ GENEVITY, Днепр, мы используем сертифицированные препараты на основе стволовых клеток и их секретома — продукты южнокорейских и европейских производителей, зарегистрированные в Международном реестре регенеративной медицины. Процедуру проводят врачи с профильным образованием в регенеративной медицине, а не косметологи общего профиля.",
        en: "Stem cells are precursor cells capable of differentiating into any type of cell in the body: fibroblasts, keratinocytes, vascular cells. They're the \"raw material\" from which the skin rebuilds itself throughout life. With age, the number of active stem cells in tissues decreases — and this, alongside collagen loss, is what defines visible ageing.\n\nStem-cell rejuvenation is a procedure in which a concentrate of certified mesenchymal stem cells (or their derivatives — growth factors, secretome) is introduced into the skin to stimulate its own regenerative processes. The method sits at the frontier of cosmetology and regenerative medicine; it's used in complex cases where classical injectable procedures no longer deliver deep results.\n\nAt GENEVITY, Dnipro, we use certified preparations based on stem cells and their secretome — products from South Korean and European manufacturers registered in the International Regenerative Medicine Registry. The procedure is performed by doctors with specialist training in regenerative medicine, not general-profile cosmetologists.",
      },
      calloutBody: {
        uk: "Якщо вам пропонують «стовбурові клітини» за ціною звичайної мезотерапії — це маркетинг. Справжні препарати стовбурових клітин коштують у десятки разів дорожче, бо виробляються у сертифікованих біотехнологічних лабораторіях за жорсткими протоколами холодового ланцюга.",
        ru: "Если вам предлагают «стволовые клетки» по цене обычной мезотерапии — это маркетинг. Настоящие препараты стволовых клеток стоят в десятки раз дороже, потому что производятся в сертифицированных биотехнологических лабораториях по жёстким протоколам холодовой цепи.",
        en: "If someone offers \"stem cells\" at the price of ordinary mesotherapy — it's marketing. Real stem-cell preparations cost dozens of times more because they're produced in certified biotech labs under strict cold-chain protocols.",
      },
    },
    {
      heading: { uk: "Переваги та показання", ru: "Преимущества и показания", en: "Advantages and indications" },
      body: {
        uk: "Омолодження стовбуровими клітинами вирішує ті завдання, які не під силу класичній ін'єкційній косметології. Головні переваги:\n\n— Глибина ефекту. Процедура працює не у поверхневих шарах, а на рівні клітинного оновлення. Ефект накопичується протягом 3–6 місяців і тримається 1–2 роки.\n— Активація власних ресурсів. На відміну від філерів і біоревіталізаторів, які «додають» шкірі речовини, стовбурові клітини стимулюють її самостійно виробляти колаген, еластин, гіалуронову кислоту.\n— Універсальність впливу. Одночасно покращуються щільність, еластичність, тон, текстура шкіри; зменшуються зморшки, пігментація, рубці.\n— Природний вигляд. Без ефекту «заповнення» чи зміни рис.\n\nПоказання до омолодження стовбуровими клітинами:\n— виражене біологічне старіння шкіри у 45+;\n— фотостаріння (шкіра після активного сонця);\n— втрата щільності і пружності, що не відновлюється класичними процедурами;\n— глибокі атрофічні рубці (постакне, постоперативні);\n— гіперпігментація, мелазма, стійкі пост-запальні плями;\n— реабілітація після серйозних процедур (лазерне шліфування, глибокі пілінги, пластика);\n— трихологічні показання: виражене випадання волосся, ослаблення фолікулів;\n— комплексне омолодження у складних випадках, коли інші процедури не дали очікуваного результату.",
        ru: "Омоложение стволовыми клетками решает те задачи, которые не под силу классической инъекционной косметологии. Главные преимущества:\n\n— Глубина эффекта. Процедура работает не в поверхностных слоях, а на уровне клеточного обновления. Эффект накапливается в течение 3–6 месяцев и держится 1–2 года.\n— Активация собственных ресурсов. В отличие от филлеров и биоревитализаторов, которые «добавляют» коже вещества, стволовые клетки стимулируют её самостоятельно производить коллаген, эластин, гиалуроновую кислоту.\n— Универсальность воздействия. Одновременно улучшаются плотность, эластичность, тон, текстура кожи; уменьшаются морщины, пигментация, рубцы.\n— Естественный вид. Без эффекта «заполнения» или изменения черт.\n\nПоказания к омоложению стволовыми клетками:\n— выраженное биологическое старение кожи в 45+;\n— фотостарение (кожа после активного солнца);\n— потеря плотности и упругости, не восстанавливаемая классическими процедурами;\n— глубокие атрофические рубцы (постакне, послеоперационные);\n— гиперпигментация, мелазма, стойкие пост-воспалительные пятна;\n— реабилитация после серьёзных процедур (лазерная шлифовка, глубокие пилинги, пластика);\n— трихологические показания: выраженное выпадение волос, ослабление фолликулов;\n— комплексное омоложение в сложных случаях, когда другие процедуры не дали ожидаемого результата.",
        en: "Stem-cell rejuvenation addresses problems that classical injectable cosmetology can't solve.\n\n— Depth. Works at the level of cellular renewal rather than surface layers. Effects accumulate over 3-6 months and last 1-2 years.\n— Activates your own resources. Unlike fillers and biorevitalisers that add substances, stem cells stimulate the skin to produce its own collagen, elastin and hyaluronic acid.\n— Universal action. Density, elasticity, tone and texture improve simultaneously; lines, pigmentation and scars all soften.\n— Natural look. No filling effect, no changed features.\n\nIndications:\n— pronounced biological skin ageing at 45+;\n— photo-ageing;\n— loss of density and elasticity that classical procedures can't restore;\n— deep atrophic scars (post-acne, post-surgical);\n— hyperpigmentation, melasma, persistent post-inflammatory marks;\n— recovery after major procedures (laser resurfacing, deep peels, plastic surgery);\n— trichology indications: pronounced hair loss, weakened follicles;\n— complex rejuvenation cases where other procedures didn't deliver expected results.",
      },
      calloutBody: {
        uk: "Стовбурові клітини — не «перша процедура». У 25–35 років зазвичай вистачає біоревіталізації і мезотерапії. Коли ці процедури перестають давати очікуваний результат — це сигнал, що організм потребує більш глибокого інструменту.",
        ru: "Стволовые клетки — не «первая процедура». В 25–35 лет обычно хватает биоревитализации и мезотерапии. Когда эти процедуры перестают давать ожидаемый результат — это сигнал, что организм нуждается в более глубоком инструменте.",
        en: "Stem cells aren't a \"first procedure\". In your 20s and early 30s, biorevitalisation and mesotherapy are usually enough. When those stop delivering the expected result — that's the signal your body needs a deeper tool.",
      },
    },
    {
      heading: { uk: "Як проходить процедура", ru: "Как проходит процедура", en: "How the procedure works" },
      body: {
        uk: "Процедура омолодження стовбуровими клітинами триває 90–120 хвилин. Етапи:\n\n1. Розширена консультація і діагностика. Перед процедурою — огляд стану шкіри, аналіз способу життя, оцінка попередніх процедур і їх результатів. За потреби призначаємо аналізи крові для виключення протипоказань.\n\n2. Вибір препарату. Залежно від стану шкіри і мети процедури обираємо один з варіантів: концентрат стовбурових клітин, секретом стовбурових клітин (фактори росту без самих клітин), або комбінований препарат. Препарат відкриваємо при вас з сертифікатом і серійним номером.\n\n3. Підготовка шкіри. Демакіяж, очищення, за потреби — м'який ензимний пілінг, обов'язкова аплікаційна анестезія на 20–30 хвилин.\n\n4. Введення препарату. Використовуємо комбіновану техніку: \n— мануальна мезотерапія тонкою голкою у зонах максимальної проблеми;\n— мікронідлінг для глобальної обробки шкіри — створює канали, через які препарат глибше проникає у шкіру;\n— прямі ін'єкції канюлею у зони з максимальною атрофією.\n\n5. Завершення. Нанесення відновлюючого крему з факторами росту, заспокійлива маска. Протягом 24 годин — ретельний догляд за шкірою: без активних засобів, м'яке очищення, SPF.\n\nКурс — зазвичай 1–3 процедури з інтервалом 2–3 місяці. Частота залежить від препарату і мети: для підтримки достатньо 1 процедури на рік; при складних випадках (глибоке постакне, виражене фотостаріння) — курс з 2–3 процедур у перший рік.",
        ru: "Процедура омоложения стволовыми клетками длится 90–120 минут. Этапы:\n\n1. Расширенная консультация и диагностика. Перед процедурой — осмотр состояния кожи, анализ образа жизни, оценка предыдущих процедур и их результатов. При необходимости назначаем анализы крови для исключения противопоказаний.\n\n2. Выбор препарата. В зависимости от состояния кожи и цели процедуры выбираем один из вариантов: концентрат стволовых клеток, секретом стволовых клеток (факторы роста без самих клеток), или комбинированный препарат. Препарат открываем при вас с сертификатом и серийным номером.\n\n3. Подготовка кожи. Демакияж, очищение, при необходимости — мягкий энзимный пилинг, обязательная аппликационная анестезия на 20–30 минут.\n\n4. Введение препарата. Используем комбинированную технику:\n— мануальная мезотерапия тонкой иглой в зонах максимальной проблемы;\n— микронидлинг для глобальной обработки кожи — создаёт каналы, через которые препарат глубже проникает в кожу;\n— прямые инъекции канюлей в зоны с максимальной атрофией.\n\n5. Завершение. Нанесение восстанавливающего крема с факторами роста, успокаивающая маска. В течение 24 часов — тщательный уход за кожей: без активных средств, мягкое очищение, SPF.\n\nКурс — обычно 1–3 процедуры с интервалом 2–3 месяца. Частота зависит от препарата и цели: для поддержки достаточно 1 процедуры в год; при сложных случаях (глубокое постакне, выраженное фотостарение) — курс из 2–3 процедур в первый год.",
        en: "A session runs 90-120 minutes.\n\n1. Extended consultation and diagnostics. Skin examination, lifestyle review, assessment of previous procedures and their outcomes. If needed we order blood work to rule out contraindications.\n\n2. Product selection. Depending on skin condition and goal: concentrated stem cells, stem-cell secretome (growth factors without the cells themselves), or a combined preparation. The vial is opened in your presence with certificate and serial number.\n\n3. Skin preparation. Makeup removal, cleansing, optional gentle enzymatic peel, mandatory topical anaesthetic for 20-30 minutes.\n\n4. Introduction. Combined technique:\n— manual mesotherapy with a fine needle in zones of maximum concern;\n— microneedling for global skin treatment — channels allow deeper product penetration;\n— direct cannula injections into zones of maximum atrophy.\n\n5. Finish. Restorative growth-factor cream, calming mask. For 24 hours: meticulous skincare — no actives, gentle cleansing, SPF.\n\nCourse: typically 1-3 sessions with 2-3 month intervals. Frequency depends on preparation and goal: for maintenance, one session per year; for complex cases (deep post-acne, pronounced photo-ageing), a course of 2-3 sessions in the first year.",
      },
      calloutBody: {
        uk: "Результат стовбурових клітин — повільний і тривалий. Не чекайте «до і після» через тиждень. Справжній ефект розкривається через 3–4 місяці, коли активовані стовбурові клітини встигли створити новий колаген, еластин і відновити шкіру зсередини.",
        ru: "Результат стволовых клеток — медленный и длительный. Не ждите «до и после» через неделю. Настоящий эффект раскрывается через 3–4 месяца, когда активированные стволовые клетки успели создать новый коллаген, эластин и восстановить кожу изнутри.",
        en: "Stem-cell results are slow and lasting. Don't expect a \"before and after\" in a week. The real effect unfolds over 3-4 months as activated stem cells produce new collagen, elastin and rebuild the skin from within.",
      },
    },
    {
      heading: { uk: "Протипоказання та безпека", ru: "Противопоказания и безопасность", en: "Contraindications and safety" },
      body: {
        uk: "Протипоказання до омолодження стовбуровими клітинами:\n— вагітність і грудне вигодовування;\n— онкологічні захворювання в активній фазі, а також протягом 5 років після ремісії (стовбурові клітини містять фактори росту, які теоретично можуть прискорити ріст пухлинних клітин);\n— аутоімунні захворювання у фазі загострення;\n— трансплантація органів в анамнезі, прийом імуносупресорів;\n— інфекційні захворювання в активній фазі (включно з ВІЛ, гепатитами);\n— тяжкі захворювання печінки і нирок у стадії декомпенсації;\n— порушення згортання крові;\n— вік до 25 років (процедура не показана молодим пацієнтам з активними власними стовбуровими клітинами).\n\nПобічні ефекти — мінімальні, оскільки препарат біосумісний:\n— почервоніння у місцях ін'єкцій (до 6–8 годин);\n— набряклість (1–2 доби);\n— мікросиняки при мікронідлінгу (4–7 днів);\n— шкірне лущення на 3–5 день як ознака активної регенерації;\n— дуже рідко — підвищена сухість шкіри перший тиждень.\n\nСерйозні ускладнення можливі тільки у випадку порушення протоколів (несертифікований препарат, порушення холодового ланцюга, нестерильна техніка) — чого у GENEVITY не буває. Усі препарати мають сертифікат походження, і ми відкриваємо флакон при вас.",
        ru: "Противопоказания к омоложению стволовыми клетками:\n— беременность и грудное вскармливание;\n— онкологические заболевания в активной фазе, а также в течение 5 лет после ремиссии (стволовые клетки содержат факторы роста, которые теоретически могут ускорить рост опухолевых клеток);\n— аутоиммунные заболевания в фазе обострения;\n— трансплантация органов в анамнезе, приём иммуносупрессоров;\n— инфекционные заболевания в активной фазе (включая ВИЧ, гепатиты);\n— тяжёлые заболевания печени и почек в стадии декомпенсации;\n— нарушения свёртываемости крови;\n— возраст до 25 лет (процедура не показана молодым пациентам с активными собственными стволовыми клетками).\n\nПобочные эффекты — минимальны, поскольку препарат биосовместим:\n— покраснение в местах инъекций (до 6–8 часов);\n— отёчность (1–2 суток);\n— микросиняки при микронидлинге (4–7 дней);\n— кожное шелушение на 3–5 день как признак активной регенерации;\n— очень редко — повышенная сухость кожи первую неделю.\n\nСерьёзные осложнения возможны только в случае нарушения протоколов (несертифицированный препарат, нарушение холодовой цепи, нестерильная техника) — чего в GENEVITY не бывает. Все препараты имеют сертификат происхождения, и мы открываем флакон при вас.",
        en: "Contraindications: pregnancy and breastfeeding; active-phase oncology, plus 5 years post-remission (stem cells contain growth factors that could theoretically accelerate tumour growth); autoimmune flare-ups; organ transplant history, immunosuppressant use; active infections (including HIV and hepatitis); severe decompensated liver or kidney disease; clotting disorders; age under 25 (not indicated for young patients with active endogenous stem cells).\n\nSide effects are minimal thanks to biocompatibility: redness at injection sites (6-8 hours); swelling (1-2 days); micro-bruises with microneedling (4-7 days); light peeling at day 3-5 as a sign of active regeneration; rarely — increased dryness in the first week.\n\nSerious complications only happen when protocols are broken (unverified preparation, broken cold chain, non-sterile technique) — which doesn't happen at GENEVITY. Every preparation has a certificate of origin, and we open the vial in your presence.",
      },
      calloutBody: {
        uk: "Онкологія в анамнезі — не абсолютне протипоказання, а питання консенсусу з онкологом. Ми завжди просимо офіційну довідку від вашого лікуючого онколога з дозволом на регенеративну терапію. Без неї процедуру не проводимо — відповідальність за здоров'я важливіша за продаж процедури.",
        ru: "Онкология в анамнезе — не абсолютное противопоказание, а вопрос консенсуса с онкологом. Мы всегда просим официальную справку от вашего лечащего онколога с разрешением на регенеративную терапию. Без неё процедуру не проводим — ответственность за здоровье важнее продажи процедуры.",
        en: "A history of cancer isn't an absolute contraindication — it's a matter of consensus with your oncologist. We always ask for a formal clearance from your treating oncologist permitting regenerative therapy. Without it, we don't do the procedure — health responsibility comes before selling the treatment.",
      },
    },
  ],
  faq: [
    { question: { uk: "Які результати можна очікувати після омолодження стовбуровими клітинами?", ru: "Какие результаты можно ожидать после омоложения стволовыми клетками?", en: "What results can I expect?" },
      answer: { uk: "Через 1 місяць: помітне покращення якості шкіри, свіжість, легке «світіння». Через 3 місяці: відчутне збільшення щільності шкіри, зменшення глибоких зморшок, вирівнювання тону. Через 6 місяців: комплексне омолодження на 5–10 років з глибоким «структурним» результатом, який не дають інші процедури. Важливо: перші тижні ефект може здаватись слабким — процес регенерації тривалий за своєю природою.",
        ru: "Через 1 месяц: заметное улучшение качества кожи, свежесть, лёгкое «свечение». Через 3 месяца: ощутимое увеличение плотности кожи, уменьшение глубоких морщин, выравнивание тона. Через 6 месяцев: комплексное омоложение на 5–10 лет с глубоким «структурным» результатом, который не дают другие процедуры. Важно: первые недели эффект может казаться слабым — процесс регенерации длительный по своей природе.",
        en: "At 1 month: noticeable improvement in skin quality, freshness, a light glow. At 3 months: a tangible increase in skin density, softened deep lines, tone evening. At 6 months: a 5-10 year complex rejuvenation with a \"structural\" depth other procedures don't deliver. Note: in the first few weeks the effect can seem weak — regeneration is slow by nature." }},
    { question: { uk: "Скільки триває ефект від процедури?", ru: "Сколько держится эффект от процедуры?", en: "How long does the result last?" },
      answer: { uk: "Після повного курсу (1–3 процедури) ефект тримається 1–2 роки. Це найдовший результат серед усіх ін'єкційних процедур омолодження. Для підтримки рекомендуємо 1 процедуру на рік — вона утримує «клітинну активність» шкіри на високому рівні.",
        ru: "После полного курса (1–3 процедуры) эффект держится 1–2 года. Это самый длительный результат среди всех инъекционных процедур омоложения. Для поддержки рекомендуем 1 процедуру в год — она поддерживает «клеточную активность» кожи на высоком уровне.",
        en: "After a full course (1-3 sessions) the result lasts 1-2 years. It's the longest-lasting result of any injectable rejuvenation procedure. For maintenance we recommend one session per year — it sustains the skin's \"cellular activity\" at a high level." }},
    { question: { uk: "Чи безпечне омолодження стовбуровими клітинами?", ru: "Безопасно ли омоложение стволовыми клетками?", en: "Is stem-cell rejuvenation safe?" },
      answer: { uk: "За умови сертифікованого препарату, дотримання холодового ланцюга і стерильної техніки — так, дуже безпечне. Препарати, які ми використовуємо у GENEVITY, проходять повну перевірку на мікроорганізми, вірусні інфекції, онкогенність. Проте процедура вимагає правильного підбору: є абсолютні протипоказання (онкологія, аутоімунні стани), і саме тому перед нею ми проводимо розширену консультацію і, за потреби, додаткові аналізи.",
        ru: "При условии сертифицированного препарата, соблюдения холодовой цепи и стерильной техники — да, очень безопасно. Препараты, которые мы используем в GENEVITY, проходят полную проверку на микроорганизмы, вирусные инфекции, онкогенность. Однако процедура требует правильного подбора: есть абсолютные противопоказания (онкология, аутоиммунные состояния), и именно поэтому перед ней мы проводим расширенную консультацию и, при необходимости, дополнительные анализы.",
        en: "With a certified preparation, proper cold chain and sterile technique — yes, very safe. The preparations we use at GENEVITY go through full testing for microorganisms, viral infection and oncogenicity. But the procedure needs proper patient selection: there are absolute contraindications (oncology, autoimmune states), which is why we do an extended consultation and, if needed, additional lab work before it." }},
    { question: { uk: "Чи можна поєднувати цю процедуру з іншими методами омолодження?", ru: "Можно ли сочетать эту процедуру с другими методами омоложения?", en: "Can this be combined with other rejuvenation methods?" },
      answer: { uk: "Так, стовбурові клітини можна поєднувати практично з усіма процедурами, і часто таке поєднання дає найкращий результат. Класичні пари: стовбурові клітини + ботулінотерапія (комплекс для зрілої шкіри); стовбурові клітини + філери (філер відновлює об'єм, стовбурові клітини — якість шкіри); стовбурові клітини після лазерного шліфування — прискорюють регенерацію у рази. Не рекомендуємо поєднувати з глибокими пілінгами чи лазером у один день — з інтервалом 2–4 тижні.",
        ru: "Да, стволовые клетки можно сочетать практически со всеми процедурами, и часто такое сочетание даёт лучший результат. Классические пары: стволовые клетки + ботулинотерапия (комплекс для зрелой кожи); стволовые клетки + филлеры (филлер восстанавливает объём, стволовые клетки — качество кожи); стволовые клетки после лазерной шлифовки — ускоряют регенерацию в разы. Не рекомендуем сочетать с глубокими пилингами или лазером в один день — с интервалом 2–4 недели.",
        en: "Yes, stem cells combine with almost all procedures, and the combination often delivers the best result. Classic pairings: stem cells + botulinum (complex for mature skin); stem cells + fillers (filler restores volume, stem cells restore skin quality); stem cells after laser resurfacing — accelerate regeneration multiple times. We don't combine with deep peels or laser on the same day — a 2-4 week interval instead." }},
    { question: { uk: "Як часто можна проводити омолодження стовбуровими клітинами?", ru: "Как часто можно проводить омоложение стволовыми клетками?", en: "How often can it be done?" },
      answer: { uk: "Повторні процедури — не частіше, ніж раз на 6 місяців при курсовому застосуванні, і не частіше, ніж раз на рік при підтримці. Занадто часті процедури не дають додаткового результату — шкіра не встигає реалізувати попередню «хвилю» регенерації. Оптимальна схема: курс з 2–3 процедур у перший рік при глибоких показаннях, потім підтримка 1 процедура на рік.",
        ru: "Повторные процедуры — не чаще, чем раз в 6 месяцев при курсовом применении, и не чаще, чем раз в год при поддержке. Слишком частые процедуры не дают дополнительного результата — кожа не успевает реализовать предыдущую «волну» регенерации. Оптимальная схема: курс из 2–3 процедур в первый год при глубоких показаниях, затем поддержка 1 процедура в год.",
        en: "Not more often than once every 6 months during a course, and not more often than once a year for maintenance. Too-frequent sessions don't add benefit — the skin doesn't have time to complete the previous regeneration wave. Optimal protocol: a course of 2-3 sessions in the first year for deep indications, then maintenance of one session per year." }},
    { question: { uk: "Скільки коштує омолодження стовбуровими клітинами у Дніпрі?", ru: "Сколько стоит омоложение стволовыми клетками в Днепре?", en: "How much does it cost in Dnipro?" },
      answer: { uk: "Омолодження стовбуровими клітинами — найдорожча процедура у нашій лінійці через вартість сировини (сертифіковані препарати стовбурових клітин виробляються у мінімальній кількості біотехнологічних лабораторій світу). Ціна залежить від препарату, площі обробки і комбінації технік. У GENEVITY базову вартість вказано у прайсі на цій сторінці; курс із 2–3 процедур пропонуємо за зниженою ціною за сеанс.",
        ru: "Омоложение стволовыми клетками — самая дорогая процедура в нашей линейке из-за стоимости сырья (сертифицированные препараты стволовых клеток производятся в минимальном количестве биотехнологических лабораторий мира). Цена зависит от препарата, площади обработки и комбинации техник. В GENEVITY базовая стоимость указана в прайсе на этой странице; курс из 2–3 процедур предлагаем по сниженной цене за сеанс.",
        en: "Stem-cell rejuvenation is the most expensive procedure in our line-up because of raw-material cost — certified stem-cell preparations are produced in a handful of biotech labs worldwide. Price depends on preparation, area and combined techniques. GENEVITY's base price is on the list on this page; a course of 2-3 sessions is offered at a reduced per-session rate." }},
  ],
};

const rejuran: ServiceCopy = {
  slug: "rejuran",
  summary: {
    uk: "Rejuran у GENEVITY — корейська процедура ін'єкційного омолодження полінуклеотидами, виділеними з ДНК лосося. Не філер, не біоревіталізація — інший клас препаратів, який відновлює структуру шкіри на молекулярному рівні. Золотий стандарт при пост-акне, тонких лініях, шкірі після лазерних процедур.",
    ru: "Rejuran в GENEVITY — корейская процедура инъекционного омоложения полинуклеотидами, выделенными из ДНК лосося. Не филлер, не биоревитализация — другой класс препаратов, восстанавливающий структуру кожи на молекулярном уровне. Золотой стандарт при постакне, тонких линиях, коже после лазерных процедур.",
    en: "Rejuran at GENEVITY — a Korean injectable rejuvenation procedure using polynucleotides derived from salmon DNA. Not a filler or biorevitaliser — a separate class of preparation that rebuilds skin structure at the molecular level. The gold standard for post-acne, fine lines, and skin recovery after laser procedures.",
  },
  sections: [
    {
      heading: { uk: "Що таке Rejuran", ru: "Что такое Rejuran", en: "What Rejuran is" },
      body: {
        uk: "Rejuran — ін'єкційний препарат на основі полінуклеотидів (ПН), отриманих із ДНК тихоокеанського лосося. Полінуклеотиди — це короткі фрагменти ДНК, які є універсальним «будівельним матеріалом» для клітин і потужними стимуляторами регенерації. На відміну від філерів (гіалуронова кислота) і біоревіталізаторів (гіалуронова кислота з добавками), Rejuran не заповнює і не зволожує. Він запускає шкіру відновлюватись: активує фібробласти, стимулює синтез колагену, покращує мікроциркуляцію, зміцнює міжклітинну матрицю.\n\nРозроблений у Південній Кореї лабораторією PharmaResearch, Rejuran стрімко став одним з найбільш клінічно досліджених препаратів регенеративної косметології. У південнокорейських клініках процедура посідає перше місце за кількістю повторних візитів — пацієнти повертаються на неї роками.\n\nУ лінійці Rejuran є три основні препарати: Rejuran Healer (базовий, для омолодження і відновлення структури шкіри), Rejuran S (посилений для роботи з рубцями і стриями), Rejuran I (для зони навколо очей — м'якший за текстурою). У GENEVITY, Дніпро, ми працюємо з усіма трьома, обираючи під конкретну задачу.",
        ru: "Rejuran — инъекционный препарат на основе полинуклеотидов (ПН), полученных из ДНК тихоокеанского лосося. Полинуклеотиды — это короткие фрагменты ДНК, являющиеся универсальным «строительным материалом» для клеток и мощными стимуляторами регенерации. В отличие от филлеров (гиалуроновая кислота) и биоревитализаторов (гиалуроновая кислота с добавками), Rejuran не заполняет и не увлажняет. Он запускает кожу восстанавливаться: активирует фибробласты, стимулирует синтез коллагена, улучшает микроциркуляцию, укрепляет межклеточную матрицу.\n\nРазработанный в Южной Корее лабораторией PharmaResearch, Rejuran стремительно стал одним из самых клинически исследованных препаратов регенеративной косметологии. В южнокорейских клиниках процедура занимает первое место по количеству повторных визитов — пациенты возвращаются на неё годами.\n\nВ линейке Rejuran есть три основных препарата: Rejuran Healer (базовый, для омоложения и восстановления структуры кожи), Rejuran S (усиленный для работы с рубцами и стриями), Rejuran I (для зоны вокруг глаз — мягче по текстуре). В GENEVITY, Днепр, мы работаем со всеми тремя, выбирая под конкретную задачу.",
        en: "Rejuran is an injectable preparation based on polynucleotides (PN) derived from the DNA of Pacific salmon. Polynucleotides are short DNA fragments that serve as universal \"building blocks\" for cells and powerful regenerative stimulators. Unlike fillers (hyaluronic acid) and biorevitalisers (hyaluronic acid with additives), Rejuran doesn't fill or hydrate. It triggers the skin to rebuild itself: activates fibroblasts, stimulates collagen synthesis, improves microcirculation, strengthens the intercellular matrix.\n\nDeveloped in South Korea by PharmaResearch, Rejuran has quickly become one of the most clinically studied preparations in regenerative cosmetology. In South Korean clinics the procedure ranks first for repeat visits — patients return to it year after year.\n\nThe Rejuran line has three main preparations: Rejuran Healer (base, for rejuvenation and skin structure restoration), Rejuran S (enhanced for scars and stretch marks), Rejuran I (for the eye area — softer texture). At GENEVITY Dnipro we work with all three, choosing for the specific goal.",
      },
      calloutBody: {
        uk: "Rejuran — це «дієтолог для шкіри», а не «косметолог». Він не обмежує, не заповнює, не приховує проблему. Він навчає шкіру правильно функціонувати — і результат тримається, навіть коли процедури давно закінчились.",
        ru: "Rejuran — это «диетолог для кожи», а не «косметолог». Он не ограничивает, не заполняет, не скрывает проблему. Он учит кожу правильно функционировать — и результат держится, даже когда процедуры давно закончились.",
        en: "Rejuran is a \"nutritionist for the skin\" rather than a cosmetologist. It doesn't restrict, doesn't fill, doesn't hide the problem. It teaches the skin to function properly — and the result holds long after the course has ended.",
      },
    },
    {
      heading: { uk: "Показання та цільова аудиторія", ru: "Показания и целевая аудитория", en: "Indications and ideal candidates" },
      body: {
        uk: "Rejuran — одна з найбільш універсальних процедур регенеративної косметології. Показання:\n\n— постакне: атрофічні рубці, поствуглеві плями, нерівний рельєф шкіри (Rejuran — золотий стандарт при постакне, часто дає результат, співставний з лазерним шліфуванням, але без реабілітації);\n— тонка, зневоднена шкіра з втратою пружності;\n— перші ознаки фотостаріння: дрібні зморшки, втрата тонусу;\n— зона навколо очей: сухість, «курячі лапки», втрата пружності (Rejuran I);\n— шкіра після лазерних процедур: прискорення регенерації у рази;\n— стрії (розтяжки) — особливо свіжі, у перший рік після появи (Rejuran S);\n— підготовка шкіри до важливих подій (курс дає помітне оновлення за 2 місяці);\n— профілактика вікових змін у 28+ і комплексне омолодження у 35+.\n\nЦільова аудиторія: пацієнти 28–55 років, які хочуть роботу з якістю шкіри, а не з об'ємом; люди з проблемною шкірою у минулому (постакне); активні мандрівники, у яких шкіра часто страждає від клімату; чоловіки (Rejuran чудово підходить чоловічій шкірі, яка потребує щільності без філерного об'єму).\n\nRejuran не підходить: тим, хто чекає від процедури «одразу помітного результату» (ефект розкривається 2–3 місяці); тим, хто шукає корекції об'єму обличчя (це робота філерів).",
        ru: "Rejuran — одна из самых универсальных процедур регенеративной косметологии. Показания:\n\n— постакне: атрофические рубцы, постугревые пятна, неровный рельеф кожи (Rejuran — золотой стандарт при постакне, часто даёт результат, сопоставимый с лазерной шлифовкой, но без реабилитации);\n— тонкая, обезвоженная кожа с потерей упругости;\n— первые признаки фотостарения: мелкие морщины, потеря тонуса;\n— зона вокруг глаз: сухость, «гусиные лапки», потеря упругости (Rejuran I);\n— кожа после лазерных процедур: ускорение регенерации в разы;\n— стрии (растяжки) — особенно свежие, в первый год после появления (Rejuran S);\n— подготовка кожи к важным событиям (курс даёт заметное обновление за 2 месяца);\n— профилактика возрастных изменений в 28+ и комплексное омоложение в 35+.\n\nЦелевая аудитория: пациенты 28–55 лет, которые хотят работу с качеством кожи, а не с объёмом; люди с проблемной кожей в прошлом (постакне); активные путешественники, у которых кожа часто страдает от климата; мужчины (Rejuran прекрасно подходит мужской коже, которая нуждается в плотности без филлерного объёма).\n\nRejuran не подходит: тем, кто ждёт от процедуры «сразу заметного результата» (эффект раскрывается 2–3 месяца); тем, кто ищет коррекции объёма лица (это работа филлеров).",
        en: "Rejuran is one of the most versatile regenerative-cosmetology procedures.\n\nIndications:\n— post-acne: atrophic scars, post-inflammatory marks, uneven texture (Rejuran is the gold standard for post-acne, often delivering results comparable to laser resurfacing but without the downtime);\n— thin, dehydrated skin with lost firmness;\n— early photo-ageing signs: fine lines, loss of tone;\n— eye area: dryness, crow's feet, loss of firmness (Rejuran I);\n— skin after laser treatments: accelerates regeneration multiple times;\n— stretch marks — especially fresh ones in the first year (Rejuran S);\n— pre-event preparation (a course delivers noticeable renewal in 2 months);\n— anti-ageing prevention at 28+ and complex rejuvenation at 35+.\n\nIdeal candidates: patients 28-55 who want to address skin quality rather than volume; people with post-acne history; frequent travellers whose skin suffers from climate change; men (Rejuran suits male skin beautifully — it needs density without filler volume).\n\nRejuran isn't for: those expecting an instant \"before/after\" (the effect develops over 2-3 months); those seeking facial volume correction (that's filler territory)." ,
      },
      calloutBody: {
        uk: "При постакне Rejuran часто дає кращий результат, ніж лазерне шліфування: без соціальної реабілітації, без ризику гіперпігментації, без агресивного впливу на шкіру. Рубці не просто згладжуються — вони перебудовуються зсередини.",
        ru: "При постакне Rejuran часто даёт лучший результат, чем лазерная шлифовка: без социальной реабилитации, без риска гиперпигментации, без агрессивного воздействия на кожу. Рубцы не просто сглаживаются — они перестраиваются изнутри.",
        en: "For post-acne, Rejuran often delivers better results than laser resurfacing: no social downtime, no risk of hyperpigmentation, no aggressive skin impact. Scars aren't just smoothed — they're rebuilt from within.",
      },
    },
    {
      heading: { uk: "Як проходить процедура", ru: "Как проходит процедура", en: "How a Rejuran session works" },
      body: {
        uk: "Процедура Rejuran триває 30–60 хвилин залежно від площі обробки. Етапи:\n\n1. Консультація і вибір препарату. Лікар оцінює стан шкіри, обговорює з вами цілі, підбирає потрібний варіант лінійки (Healer / S / I). Для першої процедури рекомендуємо зробити фотопротокол — щоб за 2–3 місяці ми могли порівняти результат об'єктивно.\n\n2. Підготовка. Демакіяж, обробка антисептиком, обов'язково — аплікаційна анестезія лідокаїновим кремом на 20–25 хвилин (Rejuran відчувається болючіше за біоревіталізацію через щільність препарату).\n\n3. Техніка введення. Rejuran вводиться мануально тонкою голкою за мезотерапевтичною технікою — у множинні точки у верхньо-середній шар дерми. На 1 мл препарату припадає приблизно 40–60 ін'єкцій. Для зони навколо очей використовуємо канюлю.\n\n4. Пост-процедурна обробка. Нанесення заспокійливої маски або сироватки з пептидами. Пояснення правил догляду: 24 години без сауни, басейну, спорту, масажу; 2 тижні активного SPF; м'яке очищення перші 3–5 днів.\n\n5. Курс. Оптимальний курс — 3–4 процедури з інтервалом 3–4 тижні. Для складних випадків (виражене постакне, стрії) — 5–6 процедур. Підтримка — 1 процедура на 6 місяців.\n\nПерші результати: свіжість шкіри — через тиждень, помітна щільність — через 1 місяць, повний ефект (перебудова рубців, зменшення зморшок, стабільне сяйво) — через 2–3 місяці після завершення курсу.",
        ru: "Процедура Rejuran длится 30–60 минут в зависимости от площади обработки. Этапы:\n\n1. Консультация и выбор препарата. Врач оценивает состояние кожи, обсуждает с вами цели, подбирает нужный вариант линейки (Healer / S / I). Для первой процедуры рекомендуем сделать фотопротокол — чтобы через 2–3 месяца мы могли сравнить результат объективно.\n\n2. Подготовка. Демакияж, обработка антисептиком, обязательно — аппликационная анестезия лидокаиновым кремом на 20–25 минут (Rejuran ощущается болезненнее биоревитализации из-за плотности препарата).\n\n3. Техника введения. Rejuran вводится мануально тонкой иглой по мезотерапевтической технике — в множественные точки в верхне-средний слой дермы. На 1 мл препарата приходится примерно 40–60 инъекций. Для зоны вокруг глаз используем канюлю.\n\n4. Постпроцедурная обработка. Нанесение успокаивающей маски или сыворотки с пептидами. Объяснение правил ухода: 24 часа без сауны, бассейна, спорта, массажа; 2 недели активного SPF; мягкое очищение первые 3–5 дней.\n\n5. Курс. Оптимальный курс — 3–4 процедуры с интервалом 3–4 недели. Для сложных случаев (выраженное постакне, стрии) — 5–6 процедур. Поддержка — 1 процедура в 6 месяцев.\n\nПервые результаты: свежесть кожи — через неделю, заметная плотность — через 1 месяц, полный эффект (перестройка рубцов, уменьшение морщин, стабильное сияние) — через 2–3 месяца после завершения курса.",
        en: "A Rejuran session takes 30-60 minutes depending on the treated area.\n\n1. Consultation and product selection. The doctor evaluates the skin, discusses goals, selects the right preparation (Healer / S / I). For the first session we recommend a photo protocol — so we can compare objectively 2-3 months on.\n\n2. Preparation. Makeup removal, antiseptic, mandatory topical lidocaine cream for 20-25 minutes (Rejuran feels more uncomfortable than biorevitalisation due to product density).\n\n3. Technique. Rejuran is injected manually with a fine needle using mesotherapy technique — into multiple points in the upper-mid dermis. 1 ml of product takes around 40-60 injections. For the eye area we use a cannula.\n\n4. Post-procedure care. Calming mask or peptide serum. Aftercare briefing: 24 hours without sauna, pool, sport or massage; 2 weeks of active SPF; gentle cleansing for the first 3-5 days.\n\n5. Course. Optimal course: 3-4 sessions at 3-4 week intervals. Complex cases (pronounced post-acne, stretch marks): 5-6 sessions. Maintenance: one session every 6 months.\n\nFirst results: skin freshness within a week, visible density at 1 month, full effect (scar remodelling, line softening, stable glow) at 2-3 months after the course.",
      },
      calloutBody: {
        uk: "Rejuran — одна з найболючіших ін'єкційних процедур за суб'єктивними відчуттями. Але біль — це важлива ознака того, що препарат активний і добре розподіляється у шкірі. Ми пропонуємо підсилену анестезію і техніки дистракції — дискомфорт знижується, але не зникає повністю. Це процедура, яка себе виправдовує.",
        ru: "Rejuran — одна из самых болезненных инъекционных процедур по субъективным ощущениям. Но боль — это важный признак того, что препарат активен и хорошо распределяется в коже. Мы предлагаем усиленную анестезию и техники дистракции — дискомфорт снижается, но не исчезает полностью. Это процедура, которая себя оправдывает.",
        en: "Rejuran is one of the more uncomfortable injectables by subjective sensation. But discomfort is an important sign that the product is active and distributing well in the skin. We offer enhanced anaesthesia and distraction techniques — discomfort drops but doesn't fully disappear. It's a procedure that earns its result.",
      },
    },
    {
      heading: { uk: "Переваги Rejuran порівняно з іншими ін'єкціями", ru: "Преимущества Rejuran по сравнению с другими инъекциями", en: "How Rejuran compares to other injectables" },
      body: {
        uk: "Rejuran не замінює інших процедур — він займає власну нішу в ін'єкційній регенеративній косметології. Основні переваги:\n\n— Глибокий структурний результат. Якщо біоревіталізація працює з зволоженням, а філери — з об'ємом, Rejuran перебудовує саму структуру шкіри: щільність, еластичність, якість дерми. Це те, що класичні процедури дають слабше.\n— Довгий ефект. Одного курсу з 3–4 процедур вистачає на 9–12 місяців стабільного результату. Це довше, ніж у мезотерапії, і часто — довше, ніж у біоревіталізації.\n— Ефективність при постакне. Rejuran — один з небагатьох неінвазивних інструментів, який реально перебудовує атрофічні рубці. Результат порівнянний з лазерним шліфуванням, але без соціальної реабілітації і ризиків пігментації.\n— Підходить чоловікам. Чоловіча шкіра потребує щільності, а не об'єму — Rejuran дає саме це, без ефекту «напомпованості», який турбує чоловіків при розмові про філери.\n— Універсальність зон. Крім обличчя — чудово працює на шиї, декольте, тильній поверхні рук, зоні грудей, стриях.\n\nВажливо розуміти обмеження: Rejuran не дає миттєвого «вау-ефекту» і не корегує об'єм. Це довгостроковий інструмент: якщо вам потрібен ефект до завтра — це ботокс або мезотерапія; якщо ви готові інвестувати у якість шкіри на роки — це Rejuran.",
        ru: "Rejuran не заменяет других процедур — он занимает собственную нишу в инъекционной регенеративной косметологии. Основные преимущества:\n\n— Глубокий структурный результат. Если биоревитализация работает с увлажнением, а филлеры — с объёмом, Rejuran перестраивает саму структуру кожи: плотность, эластичность, качество дермы. Это то, что классические процедуры дают слабее.\n— Длительный эффект. Одного курса из 3–4 процедур хватает на 9–12 месяцев стабильного результата. Это дольше, чем у мезотерапии, и часто — дольше, чем у биоревитализации.\n— Эффективность при постакне. Rejuran — один из немногих неинвазивных инструментов, который реально перестраивает атрофические рубцы. Результат сопоставим с лазерной шлифовкой, но без социальной реабилитации и рисков пигментации.\n— Подходит мужчинам. Мужская кожа нуждается в плотности, а не в объёме — Rejuran даёт именно это, без эффекта «напомпованности», который беспокоит мужчин при разговоре о филлерах.\n— Универсальность зон. Кроме лица — прекрасно работает на шее, декольте, тыльной поверхности рук, зоне груди, стриях.\n\nВажно понимать ограничения: Rejuran не даёт мгновенного «вау-эффекта» и не корректирует объём. Это долгосрочный инструмент: если вам нужен эффект до завтра — это ботокс или мезотерапия; если вы готовы инвестировать в качество кожи на годы — это Rejuran.",
        en: "Rejuran doesn't replace other procedures — it occupies its own niche in regenerative injectables.\n\n— Deep structural result. If biorevitalisation works on hydration and fillers on volume, Rejuran rebuilds the structure itself: density, elasticity, dermal quality. That's where classical procedures are weaker.\n— Long-lasting. One course of 3-4 sessions holds for 9-12 months of stable result. Longer than mesotherapy, often longer than biorevitalisation.\n— Effectiveness with post-acne. Rejuran is one of the few non-invasive tools that genuinely remodels atrophic scars. Results comparable to laser resurfacing, but without social downtime or pigmentation risks.\n— Suits men. Male skin needs density, not volume — Rejuran delivers exactly that, without the \"puffy\" look that puts men off fillers.\n— Works across zones. Beyond the face — beautifully on neck, décolleté, backs of hands, chest, stretch marks.\n\nUnderstand the limits: Rejuran doesn't deliver an instant \"wow effect\" and doesn't correct volume. It's a long-term tool: if you need a result by tomorrow, that's botulinum or mesotherapy; if you're ready to invest in skin quality for years — that's Rejuran.",
      },
      calloutBody: {
        uk: "У Південній Кореї Rejuran називають «skin booster номер один». У Європі процедура поки не настільки популярна — частково через те, що результат повільний, і клініки, орієнтовані на «миттєвий ефект», не готові її пропонувати. GENEVITY обирає процедури за результатом, а не за маркетингом.",
        ru: "В Южной Корее Rejuran называют «skin booster номер один». В Европе процедура пока не настолько популярна — отчасти из-за того, что результат медленный, и клиники, ориентированные на «мгновенный эффект», не готовы её предлагать. GENEVITY выбирает процедуры по результату, а не по маркетингу.",
        en: "In South Korea, Rejuran is called \"skin booster number one\". In Europe the procedure is less established — partly because results are slow, and clinics that market \"instant effects\" aren't equipped to offer it. GENEVITY chooses procedures by result, not by marketing.",
      },
    },
  ],
  faq: [
    { question: { uk: "Скільки вартує процедура Rejuran у Дніпрі?", ru: "Сколько стоит процедура Rejuran в Днепре?", en: "How much does Rejuran cost in Dnipro?" },
      answer: { uk: "Вартість однієї процедури Rejuran залежить від обраного препарату (Healer — базовий, S — посилений для рубців, I — для зони навколо очей), об'єму препарату (1 мл, 2 мл) і техніки введення. У GENEVITY базову ціну однієї процедури зазначено у прайсі на цій сторінці; курс із 3–4 процедур пропонуємо за зниженою ціною за сеанс. Rejuran у нас коштує дорожче, ніж біоревіталізація, бо препарат імпортний, сертифікований, і результат на роки.",
        ru: "Стоимость одной процедуры Rejuran зависит от выбранного препарата (Healer — базовый, S — усиленный для рубцов, I — для зоны вокруг глаз), объёма препарата (1 мл, 2 мл) и техники введения. В GENEVITY базовая цена одной процедуры указана в прайсе на этой странице; курс из 3–4 процедур предлагаем по сниженной цене за сеанс. Rejuran у нас стоит дороже, чем биоревитализация, потому что препарат импортный, сертифицированный, и результат на годы.",
        en: "Single-session price depends on the preparation (Healer — base, S — enhanced for scars, I — eye area), volume (1 ml, 2 ml), and injection technique. GENEVITY's base per-session pricing is on the list; a 3-4 session course is offered at a reduced per-session rate. Rejuran costs more than biorevitalisation because the preparation is imported, certified, and delivers multi-year results." }},
    { question: { uk: "Які ін'єкції Rejuran використовують у GENEVITY?", ru: "Какие инъекции Rejuran используют в GENEVITY?", en: "Which Rejuran injections does GENEVITY use?" },
      answer: { uk: "Ми працюємо з усією оригінальною лінійкою від PharmaResearch (Південна Корея): Rejuran Healer (базовий препарат для омолодження і зміцнення шкіри), Rejuran S (посилена концентрація полінуклеотидів, для атрофічних рубців і стрій), Rejuran I (з лідокаїном у складі, спеціально для чутливої зони навколо очей). Вибір препарату — на консультації, залежно від вашої шкіри і цілей. Ми ніколи не використовуємо неоригінальні аналоги.",
        ru: "Мы работаем со всей оригинальной линейкой от PharmaResearch (Южная Корея): Rejuran Healer (базовый препарат для омоложения и укрепления кожи), Rejuran S (усиленная концентрация полинуклеотидов, для атрофических рубцов и стрий), Rejuran I (с лидокаином в составе, специально для чувствительной зоны вокруг глаз). Выбор препарата — на консультации, в зависимости от вашей кожи и целей. Мы никогда не используем неоригинальные аналоги.",
        en: "We work with the full original line from PharmaResearch (South Korea): Rejuran Healer (base preparation for rejuvenation and skin strengthening), Rejuran S (higher polynucleotide concentration, for atrophic scars and stretch marks), Rejuran I (with lidocaine, specifically for the sensitive eye area). Selection happens at consultation based on your skin and goals. We never use non-original alternatives." }},
    { question: { uk: "Через скільки видно результат від процедури Rejuran?", ru: "Через сколько виден результат от процедуры Rejuran?", en: "When will I see Rejuran results?" },
      answer: { uk: "Перші зміни — через 5–7 днів: шкіра виглядає свіжіше, зменшуються дрібні зморшки. Помітне ущільнення — через 3–4 тижні після першої процедури. Повний ефект розкривається через 2–3 місяці після завершення курсу з 3–4 процедур, коли стимульовані фібробласти завершили виробництво нового колагену. Саме тому Rejuran не підходить для «екстреного» ефекту перед подією — потрібно планувати курс.",
        ru: "Первые изменения — через 5–7 дней: кожа выглядит свежее, уменьшаются мелкие морщины. Заметное уплотнение — через 3–4 недели после первой процедуры. Полный эффект раскрывается через 2–3 месяца после завершения курса из 3–4 процедур, когда стимулированные фибробласты завершили производство нового коллагена. Именно поэтому Rejuran не подходит для «экстренного» эффекта перед событием — нужно планировать курс.",
        en: "First changes at 5-7 days: skin looks fresher, fine lines soften. Noticeable tightening at 3-4 weeks after the first session. Full effect at 2-3 months after a full course of 3-4 sessions — when stimulated fibroblasts have finished producing new collagen. That's why Rejuran isn't suitable for emergency pre-event work — you need to plan the course." }},
    { question: { uk: "Чи болюча процедура Rejuran?", ru: "Болезненная ли процедура Rejuran?", en: "Is Rejuran painful?" },
      answer: { uk: "Так, Rejuran відчувається болючіше, ніж класичні ін'єкційні процедури — через щільність препарату і те, що введення відбувається у більш глибокий шар шкіри. Але дискомфорт керований: аплікаційна анестезія лідокаїновим кремом на 20–25 хвилин суттєво знижує чутливість. Rejuran I містить лідокаїн у самому препараті, тому переноситься найкомфортніше. Більшість пацієнтів оцінюють дискомфорт на 4–5 з 10 — це терпимо, але помітно.",
        ru: "Да, Rejuran ощущается болезненнее, чем классические инъекционные процедуры — из-за плотности препарата и того, что введение происходит в более глубокий слой кожи. Но дискомфорт управляем: аппликационная анестезия лидокаиновым кремом на 20–25 минут существенно снижает чувствительность. Rejuran I содержит лидокаин в самом препарате, поэтому переносится наиболее комфортно. Большинство пациентов оценивают дискомфорт на 4–5 из 10 — это терпимо, но заметно.",
        en: "Yes, Rejuran feels more uncomfortable than classical injectables because of product density and the deeper injection layer. But discomfort is manageable: topical lidocaine cream for 20-25 minutes significantly reduces sensitivity. Rejuran I contains lidocaine in the preparation itself, so it's most comfortable. Most patients rate the discomfort at 4-5 out of 10 — tolerable but noticeable." }},
    { question: { uk: "Чи можна поєднувати Rejuran з ботоксом або філерами?", ru: "Можно ли сочетать Rejuran с ботоксом или филлерами?", en: "Can Rejuran be combined with botulinum or fillers?" },
      answer: { uk: "Так, усі три процедури чудово доповнюють одна одну, бо працюють з різними задачами: ботокс — з мімічними зморшками, філери — з об'ємом, Rejuran — зі структурою і якістю шкіри. Класична комплексна схема: ботокс + філери + курс Rejuran протягом 3 місяців. Інтервал між Rejuran і ботоксом/філерами — 1–2 тижні для комфорту шкіри. Після завершення курсу Rejuran шкіра стає «базою» високої якості, на якій ботокс і філери дають кращий результат.",
        ru: "Да, все три процедуры прекрасно дополняют друг друга, потому что работают с разными задачами: ботокс — с мимическими морщинами, филлеры — с объёмом, Rejuran — со структурой и качеством кожи. Классическая комплексная схема: ботокс + филлеры + курс Rejuran в течение 3 месяцев. Интервал между Rejuran и ботоксом/филлерами — 1–2 недели для комфорта кожи. После завершения курса Rejuran кожа становится «базой» высокого качества, на которой ботокс и филлеры дают лучший результат.",
        en: "Yes — all three complement each other because they address different goals: botulinum for expression lines, fillers for volume, Rejuran for structure and skin quality. Classic comprehensive plan: botulinum + fillers + Rejuran course over 3 months. Interval between Rejuran and botulinum/fillers: 1-2 weeks for skin comfort. After a Rejuran course the skin becomes a high-quality \"base\" on which botulinum and fillers deliver better results." }},
    { question: { uk: "Які протипоказання до процедури Rejuran?", ru: "Какие противопоказания к процедуре Rejuran?", en: "What are the contraindications?" },
      answer: { uk: "Стандартні для ін'єкційних процедур: вагітність і грудне вигодовування, гіперчутливість до полінуклеотидів або компонентів препарату (украй рідко, але можливо), активні запальні процеси у зоні ін'єкції, активні інфекційні захворювання, аутоімунні стани у фазі загострення, онкологічні захворювання в активній фазі, порушення згортання крові, прийом антикоагулянтів. Специфічне протипоказання — алергія на рибні продукти (Rejuran виготовляється з ДНК лосося). На консультації лікар обов'язково уточнює анамнез.",
        ru: "Стандартные для инъекционных процедур: беременность и грудное вскармливание, гиперчувствительность к полинуклеотидам или компонентам препарата (крайне редко, но возможно), активные воспалительные процессы в зоне инъекции, активные инфекционные заболевания, аутоиммунные состояния в фазе обострения, онкологические заболевания в активной фазе, нарушения свёртываемости крови, приём антикоагулянтов. Специфическое противопоказание — аллергия на рыбные продукты (Rejuran изготавливается из ДНК лосося). На консультации врач обязательно уточняет анамнез.",
        en: "Standard for injectables: pregnancy and breastfeeding; hypersensitivity to polynucleotides or the preparation (very rare but possible); active inflammation in the injection zone; active-phase infections; autoimmune flare-ups; active-phase oncology; clotting disorders; anticoagulant therapy. Specific: allergy to fish products (Rejuran is made from salmon DNA). The doctor always reviews your medical history at consultation." }},
  ],
};

async function applyService(copy: ServiceCopy) {
  const svc = await sql`SELECT id FROM services WHERE slug = ${copy.slug} LIMIT 1`;
  if (!svc[0]) { console.error(`✗ ${copy.slug} not found`); return; }
  const id = svc[0].id as string;
  await sql`UPDATE services SET summary_uk=${copy.summary.uk}, summary_ru=${copy.summary.ru}, summary_en=${copy.summary.en} WHERE id=${id}`;
  await sql`DELETE FROM content_sections WHERE owner_type='service' AND owner_id=${id}`;
  await sql`DELETE FROM faq_items WHERE owner_type='service' AND owner_id=${id}`;
  const sectionIds: string[] = [];
  for (let i = 0; i < copy.sections.length; i++) {
    const s = copy.sections[i]; const sid = randomUUID(); sectionIds.push(sid);
    const data = { heading: s.heading, body: s.body, calloutBody: s.calloutBody, heroImage: null };
    await sql`INSERT INTO content_sections (id, owner_type, owner_id, sort_order, section_type, data) VALUES (${sid}, 'service', ${id}, ${i}, 'richText'::section_type, ${JSON.stringify(data)}::jsonb)`;
  }
  for (let i = 0; i < copy.faq.length; i++) {
    const f = copy.faq[i];
    await sql`INSERT INTO faq_items (owner_type, owner_id, sort_order, question_uk, question_ru, question_en, answer_uk, answer_ru, answer_en) VALUES ('service', ${id}, ${i}, ${f.question.uk}, ${f.question.ru}, ${f.question.en}, ${f.answer.uk}, ${f.answer.ru}, ${f.answer.en})`;
  }
  const order = [...sectionIds.map((s) => `section:${s}`), "faq", "doctors", "equipment", "relatedServices", "finalCTA"];
  await sql`UPDATE services SET block_order=${order} WHERE id=${id}`;
  console.log(`✓ ${copy.slug} — ${copy.sections.length} sections, ${copy.faq.length} FAQs`);
}

async function main() {
  for (const c of [stemCell, rejuran]) await applyService(c);
  await sql.end();
  console.log("\nV2b DONE — next: V2c (Juvederm + PolyPhil)");
}
main().catch((e) => { console.error(e); process.exit(1); });
