/**
 * V3b — EMSCULPT NEO, Ultraformer MPT Body, EXION Body
 * Apparatus cosmetology, body-focused services.
 * Run: npx tsx scripts/seed-copy-v3b.ts
 */
import postgres from "postgres";
import * as fs from "fs";
import * as path from "path";
import { randomUUID } from "crypto";

const envContent = fs.readFileSync(path.resolve(__dirname, "../.env.local"), "utf-8");
const env: Record<string, string> = {};
envContent.split("\n").forEach((l) => {
  const [k, ...v] = l.split("=");
  if (k && v.length) env[k.trim()] = v.join("=").trim();
});
const sql = postgres(env.DATABASE_URL!);

type L = { uk: string; ru: string; en: string };
interface SectionCopy { heading: L; body: L; calloutBody: L; }
interface FaqCopy { question: L; answer: L; }
interface ServiceCopy { slug: string; summary: L; sections: SectionCopy[]; faq: FaqCopy[]; }

const SERVICES: ServiceCopy[] = [
  // ─── EMSCULPT NEO ──────────────────────────────────────────────────────────
  {
    slug: "emsculpt-neo",
    summary: {
      uk: "EMSCULPT NEO у GENEVITY — єдина сертифікована апаратна процедура, яка одночасно нарощує м'язи і зменшує жирові відкладення. Синхронізована дія HIFEM і RF за 30 хвилин відповідає 20 000 м'язових скорочень. Клінічно підтверджено: +25% до м'язової маси, –30% жиру після курсу.",
      ru: "EMSCULPT NEO в GENEVITY — единственная сертифицированная аппаратная процедура, которая одновременно наращивает мышцы и уменьшает жировые отложения. Синхронизированное действие HIFEM и RF за 30 минут эквивалентно 20 000 мышечных сокращений. Клинически подтверждено: +25% мышечной массы, –30% жира после курса.",
      en: "EMSCULPT NEO at GENEVITY — the only certified device procedure that simultaneously builds muscle and reduces fat. Synchronised HIFEM and RF in 30 minutes equates to 20,000 muscle contractions. Clinically confirmed: +25% muscle mass, –30% fat after a course.",
    },
    sections: [
      {
        heading: { uk: "Як EMSCULPT NEO будує м'язи і спалює жир одночасно", ru: "Как EMSCULPT NEO строит мышцы и сжигает жир одновременно", en: "How EMSCULPT NEO builds muscle and burns fat simultaneously" },
        body: {
          uk: "EMSCULPT NEO — апарат BTL Aesthetics другого покоління (NEO — наступник першого EMSCULPT). Поєднує дві незалежні технології в одному аплікаторі:\n\nHIFEM (High-Intensity Focused Electromagnetic field):\nЕлектромагнітне поле надвисокої інтенсивності примушує м'язи скорочуватися з такою частотою і силою, яка неможлива при довільних тренуваннях. Тип скорочення — супрамаксимальний: м'яз активується на 100% (при звичайному тренуванні — 30–40%). За 30-хвилинну сесію — близько 20 000 таких скорочень. Результат: гіпертрофія і гіперплазія м'язових волокон — м'яз не просто «тонізується», а фізично збільшується у обсязі.\n\nRF (RadioFrequency — монополярний режим):\nОдночасно нагріває підшкірну жирову клітковину до 43–45°C. При цій температурі жирові клітини (адипоцити) зазнають апоптозу — запрограмованої клітинної загибелі. Мертві адипоцити виводяться лімфатичною системою протягом кількох тижнів після процедури.\n\nСинергія двох технологій у одному аплікаторі — ключова перевага NEO над класичним EMSCULPT: RF прогріває жир і одночасно підвищує ефективність м'язових скорочень (підігрітий м'яз скорочується ефективніше).\n\nКлінічні дані (BTL Aesthetics, peer-reviewed):\n— збільшення м'язової маси: +25% у зоні обробки;\n— зменшення жирових відкладень: –30%;\n— зменшення об'єму живота: –6 см у середньому;\n— зміцнення м'язів кора та відновлення діастазу прямих м'язів живота.\n\nFDA-схвалена технологія. 30+ клінічних досліджень.",
          ru: "EMSCULPT NEO — аппарат BTL Aesthetics второго поколения (NEO — наследник первого EMSCULPT). Совмещает две независимые технологии в одном аппликаторе:\n\nHIFEM (High-Intensity Focused Electromagnetic field):\nЭлектромагнитное поле сверхвысокой интенсивности заставляет мышцы сокращаться с такой частотой и силой, которая невозможна при произвольных тренировках. Тип сокращения — супрамаксимальный: мышца активируется на 100% (при обычной тренировке — 30–40%). За 30-минутную сессию — около 20 000 таких сокращений. Результат: гипертрофия и гиперплазия мышечных волокон — мышца не просто «тонизируется», а физически увеличивается в объёме.\n\nRF (RadioFrequency — монополярный режим):\nОдновременно нагревает подкожную жировую клетчатку до 43–45°C. При этой температуре жировые клетки (адипоциты) подвергаются апоптозу — запрограммированной клеточной гибели. Мёртвые адипоциты выводятся лимфатической системой в течение нескольких недель после процедуры.\n\nСинергия двух технологий в одном аппликаторе — ключевое преимущество NEO над классическим EMSCULPT: RF нагревает жир и одновременно повышает эффективность мышечных сокращений (подогретая мышца сокращается эффективнее).\n\nКлинические данные (BTL Aesthetics, peer-reviewed):\n— увеличение мышечной массы: +25% в зоне обработки;\n— уменьшение жировых отложений: –30%;\n— уменьшение объёма живота: –6 см в среднем;\n— укрепление мышц кора и восстановление диастаза прямых мышц живота.\n\nFDA-одобренная технология. 30+ клинических исследований.",
          en: "EMSCULPT NEO is BTL Aesthetics' second-generation device (NEO follows the original EMSCULPT). It combines two independent technologies in one applicator:\n\nHIFEM (High-Intensity Focused Electromagnetic field):\nAn ultra-high-intensity electromagnetic field forces muscles to contract at a frequency and intensity impossible with voluntary exercise. The contraction type is supramaximal: the muscle activates at 100% (a normal workout achieves 30-40%). In a 30-minute session: approximately 20,000 such contractions. Result: muscle fibre hypertrophy and hyperplasia — the muscle doesn't just 'tone up', it physically increases in volume.\n\nRF (monopolar radiofrequency):\nSimultaneously heats subcutaneous fat to 43–45°C. At this temperature fat cells (adipocytes) undergo apoptosis — programmed cell death. Dead adipocytes are cleared by the lymphatic system over several weeks after the procedure.\n\nThe synergy of both technologies in one applicator is NEO's key advantage over the original EMSCULPT: RF heats the fat and simultaneously improves the efficiency of muscle contractions (a warmed muscle contracts more effectively).\n\nClinical data (BTL Aesthetics, peer-reviewed):\n— muscle mass increase: +25% in the treated zone;\n— fat reduction: –30%;\n— waist circumference reduction: –6 cm on average;\n— core muscle strengthening and diastasis recti improvement.\n\nFDA-approved technology. 30+ clinical studies.",
        },
        calloutBody: {
          uk: "EMSCULPT NEO — не схуднення. Він перебудовує склад тіла: менше жиру, більше м'язів. На вазі ви можете навіть не схуднути (м'язи важчі за жир), але розмір одягу зменшиться, а фігура стане чіткішою.",
          ru: "EMSCULPT NEO — не похудение. Он перестраивает состав тела: меньше жира, больше мышц. На весах вы можете даже не похудеть (мышцы тяжелее жира), но размер одежды уменьшится, а фигура станет чётче.",
          en: "EMSCULPT NEO is not weight loss. It remodels body composition: less fat, more muscle. The scale may not move (muscle weighs more than fat), but your clothing size will decrease and your shape will become more defined.",
        },
      },
      {
        heading: { uk: "Зони роботи та показання", ru: "Зоны работы и показания", en: "Treatment zones and indications" },
        body: {
          uk: "EMSCULPT NEO — процедура для корекції фігури, а не лікування ожиріння. Найкращий кандидат — людина, що веде активний спосіб життя, але хоче підкреслити рельєф або позбутися локальних відкладень.\n\nЗони з підтвердженою ефективністю:\n— Живіт. Одночасне скорочення прямого і поперечного м'язів живота + RF на жирову клітковину. Ефективний при діастазі прямих м'язів (розходженні після вагітності) — клінічно підтверджено скорочення діастазу у середньому на 19%.\n— Сідниці. HIFEM стимулює великий і середній сідничний м'яз — ефект «бразильського ліфтингу» без імплантів. Об'єм сідниць збільшується, форма підтягується.\n— Руки. Трицепс і біцепс — зона «прощавай, рукоятка». EMSCULPT NEO зміцнює і тонізує.\n— Стегна. Квадрицепс, хамстрінг — корекція внутрішньої поверхні стегна (зона «щілина між ніг\"), зовнішньої частини (зона «галіфе»).\n— Литкові м'язи. Зміцнення, покращення форми, корекція набряклості.\n\nПоказання:\n— локальні жирові відкладення у поєднанні з недостатнім м'язовим тонусом;\n— діастаз прямих м'язів живота;\n— реабілітація після вагітності та пологів;\n— підготовка до або після баріатричних операцій (корекція тонусу);\n— спортивна доповнення (покращення результатів без надмірних тренувань).\n\nНЕ підходить: вагітність і грудне вигодовування, металеві або електронні імпланти у зоні лікування (кардіостимулятор, стрижні в хребті, ендопротези тазостегнового суглоба), злоякісні новоутворення у зоні обробки, активні запальні захворювання шкіри, гемофілія. ІМТ до 35 — оптимальний діапазон; при ІМТ >35 ефективність помітно нижча.",
          ru: "EMSCULPT NEO — процедура для коррекции фигуры, а не лечения ожирения. Лучший кандидат — человек, ведущий активный образ жизни, но желающий подчеркнуть рельеф или избавиться от локальных отложений.\n\nЗоны с подтверждённой эффективностью:\n— Живот. Одновременное сокращение прямой и поперечной мышц живота + RF на жировую клетчатку. Эффективен при диастазе прямых мышц (расхождении после беременности) — клинически подтверждено сокращение диастаза в среднем на 19%.\n— Ягодицы. HIFEM стимулирует большую и среднюю ягодичную мышцу — эффект «бразильского лифтинга» без имплантов. Объём ягодиц увеличивается, форма подтягивается.\n— Руки. Трицепс и бицепс — зона «прощай, рукоятка». EMSCULPT NEO укрепляет и тонизирует.\n— Бёдра. Квадрицепс, хамстринг — коррекция внутренней поверхности бедра, внешней части (зона «галифе»).\n— Икроножные мышцы. Укрепление, улучшение формы, коррекция отёчности.\n\nПоказания:\n— локальные жировые отложения в сочетании с недостаточным мышечным тонусом;\n— диастаз прямых мышц живота;\n— реабилитация после беременности и родов;\n— подготовка к или после бариатрических операций (коррекция тонуса);\n— спортивное дополнение (улучшение результатов без избыточных тренировок).\n\nНЕ подходит: беременность и грудное вскармливание, металлические или электронные импланты в зоне лечения, злокачественные новообразования в зоне обработки, активные воспалительные заболевания кожи, гемофилия. ИМТ до 35 — оптимальный диапазон; при ИМТ >35 эффективность заметно ниже.",
          en: "EMSCULPT NEO is a body-shaping procedure, not an obesity treatment. The ideal candidate is someone who leads an active life but wants to define their shape or address localised fat.\n\nZones with confirmed efficacy:\n— Abdomen. Simultaneous contraction of rectus and transverse abdominals + RF on fat tissue. Effective for diastasis recti (post-pregnancy separation) — clinically confirmed average reduction of 19%.\n— Glutes. HIFEM stimulates the gluteus maximus and medius — a 'Brazilian lift' effect without implants. Glute volume increases, shape lifts.\n— Arms. Triceps and biceps — the 'batwing' zone. EMSCULPT NEO tones and strengthens.\n— Thighs. Quadriceps, hamstrings — inner thigh correction ('thigh gap' zone), outer thigh ('saddlebag' zone).\n— Calves. Strengthening, shaping, oedema correction.\n\nIndications:\n— localised fat deposits combined with insufficient muscle tone;\n— diastasis recti;\n— post-pregnancy and post-partum rehabilitation;\n— preparation for or recovery from bariatric surgery;\n— athletic enhancement (better results without overtraining).\n\nNOT suitable for: pregnancy, metal or electronic implants in the treatment zone (pacemaker, spinal rods, hip prostheses), malignant tumours in the treatment zone, active skin inflammation, haemophilia. BMI under 35 is the optimal range; above 35, efficacy drops noticeably.",
        },
        calloutBody: {
          uk: "EMSCULPT NEO не спалює загальний жир — він впливає лише на жир під аплікатором. Якщо мета — загальне схуднення, потрібна системна робота (харчування, дефіцит калорій). EMSCULPT NEO — фінальний «штрих» для рельєфу, не стартова точка.",
          ru: "EMSCULPT NEO не сжигает общий жир — он воздействует только на жир под аппликатором. Если цель — общее похудение, нужна системная работа (питание, дефицит калорий). EMSCULPT NEO — финальный «штрих» для рельефа, не стартовая точка.",
          en: "EMSCULPT NEO doesn't burn total body fat — it targets only the fat under the applicator. If the goal is overall weight loss, systemic work (nutrition, calorie deficit) is needed. EMSCULPT NEO is the final 'polish' for definition, not the starting point.",
        },
      },
      {
        heading: { uk: "Курс, відчуття і результат", ru: "Курс, ощущения и результат", en: "Course, sensations and results" },
        body: {
          uk: "Стандартний курс EMSCULPT NEO — 4 сесії з інтервалом 5–7 днів. Одна зона (наприклад, живіт) — 30 хвилин. При одночасній обробці кількох зон (живіт + сідниці) — 2 аплікатори паралельно або послідовно.\n\nЩо відчувається під час сесії:\n— Перші 5–7 хвилин — аплікатор прогрівається RF. Відчуття рівного, приємного тепла. Температура поступово підвищується.\n— Потім — HIFEM скорочення. Ритмічні, сильні, ненавмисні скорочення м'язів. На 1-ій сесії — відчуття дивовижне і незвичне. До 3-ї — звично і навіть приємно (ефект «розминки»).\n— Відчуття болю — рідкісне (зазвичай перша сесія при максимальній інтенсивності). Інтенсивність завжди регулюється.\n\nПісля сесії:\n— М'язова крепатура через 12–48 годин (як після інтенсивного тренування) — це нормально і означає, що процедура спрацювала;\n— Жодних зовнішніх ознак: без почервоніння, без синців;\n— Повна соціальна активність одразу;\n— Фізичне тренування того ж дня — не рекомендується (м'яз вже «потренувався» до максимуму).\n\nРезультат:\n— Перший помітний результат — після 2–3 сесій (м'язи відчуваються щільнішими);\n— Видимий рельєф — через 4–6 тижнів після курсу (жирові клітини виводяться поступово);\n— Пік результату — через 3 місяці після курсу;\n— Тривалість — 6–12 місяців при підтримці фізичної активності. Без активності м'яз повертається до початкового стану за 3–6 місяців.",
          ru: "Стандартный курс EMSCULPT NEO — 4 сессии с интервалом 5–7 дней. Одна зона (например, живот) — 30 минут. При одновременной обработке нескольких зон (живот + ягодицы) — 2 аппликатора параллельно или последовательно.\n\nЧто ощущается во время сессии:\n— Первые 5–7 минут — аппликатор прогревается RF. Ощущение ровного, приятного тепла. Температура постепенно повышается.\n— Затем — HIFEM сокращения. Ритмичные, сильные, непроизвольные сокращения мышц. На 1-й сессии — ощущение удивительное и непривычное. К 3-й — привычно и даже приятно (эффект «разминки»).\n— Болевые ощущения — редкость (обычно первая сессия при максимальной интенсивности). Интенсивность всегда регулируется.\n\nПосле сессии:\n— Мышечная крепатура через 12–48 часов (как после интенсивной тренировки) — это нормально и означает, что процедура сработала;\n— Никаких внешних признаков: без покраснения, без синяков;\n— Полная социальная активность сразу;\n— Физическая тренировка в тот же день — не рекомендуется (мышца уже «потренировалась» до максимума).\n\nРезультат:\n— Первый заметный результат — после 2–3 сессий (мышцы ощущаются плотнее);\n— Видимый рельеф — через 4–6 недель после курса (жировые клетки выводятся постепенно);\n— Пик результата — через 3 месяца после курса;\n— Продолжительность — 6–12 месяцев при поддержании физической активности.",
          en: "The standard EMSCULPT NEO course is 4 sessions at 5-7 day intervals. One zone (e.g., abdomen) takes 30 minutes. Multiple zones treated simultaneously (abdomen + glutes) — 2 applicators in parallel or sequentially.\n\nWhat you feel during a session:\n— First 5-7 minutes — the applicator warms up with RF. A steady, comfortable warmth building gradually.\n— Then — HIFEM contractions. Rhythmic, powerful, involuntary muscle contractions. In session 1 the sensation is surprising and unfamiliar; by session 3, familiar and almost pleasant (a 'warm-up' feeling).\n— Pain is rare (usually only first session at maximum intensity). Intensity is always adjustable.\n\nAfterward:\n— Muscle soreness after 12-48 hours (like after an intense workout) — normal, and a sign the procedure worked;\n— No visible signs: no redness, no bruising;\n— Full social activity immediately;\n— Gym workout the same day — not recommended (the muscle has already trained to maximum).\n\nResults:\n— First noticeable change after 2-3 sessions (muscles feel firmer);\n— Visible definition 4-6 weeks after the course (fat cells clear gradually);\n— Peak result 3 months post-course;\n— Duration: 6-12 months with maintained physical activity.",
        },
        calloutBody: {
          uk: "Крепатура після EMSCULPT NEO — це добрий знак, а не привід для паніки. Якщо наступного дня м'язи болять — процедура викликала справжню гіпертрофічну реакцію. Якщо не болять після першої сесії — ми збільшимо інтенсивність.",
          ru: "Крепатура после EMSCULPT NEO — это добрый знак, а не повод для паники. Если на следующий день мышцы болят — процедура вызвала настоящую гипертрофическую реакцию. Если не болят после первой сессии — мы увеличим интенсивность.",
          en: "Muscle soreness after EMSCULPT NEO is a good sign, not cause for concern. If your muscles ache the next day, the procedure triggered a genuine hypertrophic response. If they don't ache after the first session, we'll increase the intensity.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "EMSCULPT NEO замінить тренажерний зал?", ru: "EMSCULPT NEO заменит тренажерный зал?", en: "Can EMSCULPT NEO replace the gym?" },
        answer: { uk: "Ні. EMSCULPT NEO будує м'язи і видаляє локальний жир — але не замінює кардіо, гнучкість, функціональні тренування та загальний метаболічний ефект від регулярної активності. Найкраще як доповнення до тренувань.", ru: "Нет. EMSCULPT NEO строит мышцы и удаляет локальный жир — но не заменяет кардио, гибкость, функциональные тренировки и общий метаболический эффект от регулярной активности. Лучшего всего — как дополнение к тренировкам.", en: "No. EMSCULPT NEO builds muscle and removes local fat — but doesn't replace cardio, flexibility, functional training and the systemic metabolic effect of regular activity. Best used as a supplement to exercise." },
      },
      {
        question: { uk: "Скільки процедур EMSCULPT NEO потрібно?", ru: "Сколько процедур EMSCULPT NEO нужно?", en: "How many EMSCULPT NEO sessions are needed?" },
        answer: { uk: "Стандартний курс — 4 сесії. Для деяких зон (сідниці) — 4–6. Підтримуюча сесія 1 раз на 3–6 місяців зберігає результат і продовжує м'язовий прогрес.", ru: "Стандартный курс — 4 сессии. Для некоторых зон (ягодицы) — 4–6. Поддерживающая сессия 1 раз в 3–6 месяцев сохраняет результат и продолжает мышечный прогресс.", en: "Standard course: 4 sessions. For some zones (glutes): 4-6. A maintenance session every 3-6 months preserves results and continues muscle progress." },
      },
      {
        question: { uk: "Чи допомагає EMSCULPT NEO при діастазі?", ru: "Помогает ли EMSCULPT NEO при диастазе?", en: "Does EMSCULPT NEO help with diastasis recti?" },
        answer: { uk: "Так. Клінічно підтверджено скорочення ширини діастазу в середньому на 19% після курсу. Але перед процедурою — обов'язкова консультація і УЗД-оцінка ширини діастазу. При ширині >3 см ефективність нижча; при ускладненому діастазі — потрібна консультація хірурга.", ru: "Да. Клинически подтверждено сокращение ширины диастаза в среднем на 19% после курса. Но перед процедурой — обязательна консультация и УЗИ-оценка ширины диастаза. При ширине >3 см эффективность ниже; при осложнённом диастазе — нужна консультация хирурга.", en: "Yes. Clinically confirmed average diastasis width reduction of 19% after a course. But a pre-procedure consultation and ultrasound assessment of diastasis width are mandatory. For width >3 cm, efficacy is lower; for complicated diastasis, a surgical consultation is needed." },
      },
      {
        question: { uk: "Чи є протипоказання до EMSCULPT NEO?", ru: "Есть ли противопоказания к EMSCULPT NEO?", en: "Are there contraindications to EMSCULPT NEO?" },
        answer: { uk: "Так: вагітність (абсолютне); металеві або електронні імпланти у зоні лікування (кардіостимулятор — абсолютне); ендопротези в зоні (наприклад, тазостегновий суглоб при обробці сідниць); онкологія у зоні; ІМТ >35 (різко знижує ефективність). Повний перелік — на консультації.", ru: "Да: беременность (абсолютное); металлические или электронные импланты в зоне лечения (кардиостимулятор — абсолютное); эндопротезы в зоне (например, тазобедренный сустав при обработке ягодиц); онкология в зоне; ИМТ >35 (резко снижает эффективность). Полный перечень — на консультации.", en: "Yes: pregnancy (absolute); metal or electronic implants in the treatment zone (pacemaker — absolute); joint prosthetics in the zone (e.g., hip replacement when treating glutes); cancer in the treatment zone; BMI >35 (sharply reduces efficacy). Full list at the consultation." },
      },
      {
        question: { uk: "Результат EMSCULPT NEO помітний?", ru: "Результат EMSCULPT NEO заметен?", en: "Is the EMSCULPT NEO result visible?" },
        answer: { uk: "Так — при реалістичних очікуваннях. На фото «до/після» через 3 місяці: чіткіші контури живота, менший об'єм талії, щільніші сідниці. Зміна вагового показника — часто мінімальна або відсутня (зменшення жиру + збільшення м'язів компенсуються). Орієнтуватись краще на об'єми і відчуття у одязі.", ru: "Да — при реалистичных ожиданиях. На фото «до/после» через 3 месяца: более чёткие контуры живота, меньший объём талии, более плотные ягодицы. Изменение весового показателя — часто минимальное или отсутствует (уменьшение жира + увеличение мышц компенсируются). Лучше ориентироваться на объёмы и ощущения в одежде.", en: "Yes — with realistic expectations. In 3-month before/after photos: clearer abdominal definition, smaller waist circumference, firmer glutes. Scale weight change is often minimal or absent (fat loss + muscle gain cancel out). Better to track by measurements and how clothes fit." },
      },
    ],
  },

  // ─── ULTRAFORMER MPT BODY ──────────────────────────────────────────────────
  {
    slug: "ultraformer-mpt-body",
    summary: {
      uk: "Ultraformer MPT Body у GENEVITY — HIFU для підтягування шкіри тіла без хірургії. Фокусований ультразвук стимулює неоколагенез у глибоких шарах шкіри живота, стегон, рук і зони декольте — ефективний при птозі шкіри після схуднення, вагітності або природного старіння.",
      ru: "Ultraformer MPT Body в GENEVITY — HIFU для подтяжки кожи тела без хирургии. Фокусированный ультразвук стимулирует неоколлагенез в глубоких слоях кожи живота, бёдер, рук и зоны декольте — эффективен при птозе кожи после похудения, беременности или естественного старения.",
      en: "Ultraformer MPT Body at GENEVITY — HIFU for non-surgical body skin tightening. Focused ultrasound stimulates neocollagenesis in the deep skin layers of abdomen, thighs, arms and décolletage — effective for skin laxity after weight loss, pregnancy or natural ageing.",
    },
    sections: [
      {
        heading: { uk: "HIFU для тіла: що і як підтягує", ru: "HIFU для тела: что и как подтягивает", en: "Body HIFU: what it tightens and how" },
        body: {
          uk: "Ultraformer MPT Body — та сама HIFU-платформа від CLASSYS, що використовується для ліфтингу обличчя, але з трансдюсерами більшого діаметру і глибини дії, адаптованими для товщої шкіри тіла.\n\nПринцип роботи ідентичний: фокусований ультразвук формує масив теплових коагуляційних точок (TCP) у глибоких шарах дерми і підшкірної клітковини. Температура 65–70°C у точці фокусу:\n— скорочує наявні колагенові волокна (негайний підтягуючий ефект);\n— запускає каскад неоколагенезу — нові волокна дозрівають 3–6 місяців після процедури.\n\nЧому шкіра тіла важча для ліфтингу, ніж обличчя:\n— Шкіра тіла товстіша і менш «живлена» кровоносними судинами;\n— Після вагітності або великого схуднення (>15–20 кг) шкіра може мати справжній «надлишок» — розтягнутий структурний компонент, який ніяка апаратна процедура не видалить без хірургії.\n\nUltraformer MPT Body ефективний при помірній в'ялості шкіри — коли є втрата тонусу без суттєвого надлишку тканини. При значному птозі після великого схуднення — рекомендуємо консультацію пластичного хірурга.",
          ru: "Ultraformer MPT Body — та же HIFU-платформа от CLASSYS, что используется для лифтинга лица, но с трансдюсерами большего диаметра и глубины действия, адаптированными для более толстой кожи тела.\n\nПринцип работы идентичен: фокусированный ультразвук формирует массив тепловых коагуляционных точек (TCP) в глубоких слоях дермы и подкожной клетчатки. Температура 65–70°C в точке фокуса:\n— сжимает имеющиеся коллагеновые волокна (немедленный подтягивающий эффект);\n— запускает каскад неоколлагенеза — новые волокна созревают 3–6 месяцев после процедуры.\n\nПочему кожа тела сложнее для лифтинга, чем лицо:\n— Кожа тела толще и менее «питаема» кровеносными сосудами;\n— После беременности или большого похудения (>15–20 кг) кожа может иметь настоящий «излишек» — растянутый структурный компонент, который никакая аппаратная процедура не уберёт без хирургии.\n\nUltraformer MPT Body эффективен при умеренной дряблости кожи — когда есть потеря тонуса без существенного избытка ткани. При значительном птозе после большого похудения — рекомендуем консультацию пластического хирурга.",
          en: "Ultraformer MPT Body is the same HIFU platform by CLASSYS used for face lifting, but with larger-diameter, deeper-range transducers adapted for the thicker skin of the body.\n\nThe working principle is identical: focused ultrasound creates a thermal coagulation point (TCP) array in deep dermal and subcutaneous layers. Temperature of 65–70°C at the focal point:\n— contracts existing collagen fibres (immediate tightening);\n— triggers neocollagenesis — new fibres mature over 3-6 months post-procedure.\n\nWhy body skin is harder to lift than facial skin:\n— Body skin is thicker and less vascularised;\n— After pregnancy or significant weight loss (>15-20 kg), the skin may have a true 'excess' — stretched structural tissue that no device procedure can remove without surgery.\n\nUltraformer MPT Body is effective for moderate skin laxity — where there is a loss of tone without significant excess tissue. For pronounced ptosis after major weight loss — we recommend a plastic surgery consultation.",
        },
        calloutBody: {
          uk: "Ultraformer MPT Body підтягує шкіру — але не видаляє її надлишок. Якщо «живіт звисає» після великого схуднення — це хірургічне питання. Ми не продаємо апаратний ліфтинг там, де потрібен скальпель.",
          ru: "Ultraformer MPT Body подтягивает кожу — но не убирает её излишек. Если «живот свисает» после большого похудения — это хирургический вопрос. Мы не продаём аппаратный лифтинг там, где нужен скальпель.",
          en: "Ultraformer MPT Body tightens skin — it doesn't remove excess skin. If the abdomen 'hangs' after significant weight loss — that's a surgical matter. We don't sell device-based lifting where a scalpel is needed.",
        },
      },
      {
        heading: { uk: "Зони та показання", ru: "Зоны и показания", en: "Zones and indications" },
        body: {
          uk: "Ефективні зони для Ultraformer MPT Body:\n\n— Живіт. Особливо ефективний при помірній в'ялості після вагітності або незначного схуднення. Обробляється дерма (3 мм трансдюсер) і підшкірна клітковина (4,5–6 мм трансдюсер).\n— Внутрішня і зовнішня поверхня стегон. Корекція «галіфе», підтягування внутрішньої поверхні («вушка»).\n— Руки. Зона «прощавай, рукоятка» — внутрішня поверхня плеча. HIFU ефективний при легкому і помірному птозі шкіри.\n— Декольте і верхня частина грудей. Горизонтальні складки декольте, в'ялість шкіри у верхній частині грудної клітки.\n— Коліна. Шкіра навколо і вище колінної чашечки, яка «звисає» з роком.\n— Сідниці (верхня зовнішня частина). Підйом і підтягування.\n\nПоказання:\n— помірна в'ялість і птоз шкіри тіла без значного надлишку;\n— природні вікові зміни тонусу шкіри;\n— помірна в'ялість після вагітності (через 6–12 місяців після пологів);\n— профілактика в'ялості при зниженні ваги.\n\nНЕ підходить:\n— вагітність;\n— метал, імпланти, кардіостимулятор у зоні;\n— онкологія у зоні;\n— виражений птоз шкіри після великого схуднення (>20 кг).\n\nОптимальний курс: 1–2 сесії з інтервалом 4–8 тижнів. Підтримка 1 раз на рік.",
          ru: "Эффективные зоны для Ultraformer MPT Body:\n\n— Живот. Особенно эффективен при умеренной дряблости после беременности или небольшого похудения. Обрабатывается дерма (трансдюсер 3 мм) и подкожная клетчатка (трансдюсер 4,5–6 мм).\n— Внутренняя и внешняя поверхность бёдер. Коррекция «галифе», подтяжка внутренней поверхности.\n— Руки. Зона «прощай, рукоятка» — внутренняя поверхность плеча. HIFU эффективен при лёгком и умеренном птозе кожи.\n— Декольте и верхняя часть груди. Горизонтальные складки декольте, дряблость кожи в верхней части грудной клетки.\n— Колени. Кожа вокруг и выше коленной чашечки.\n— Ягодицы (верхняя внешняя часть). Подъём и подтяжка.\n\nПоказания:\n— умеренная дряблость и птоз кожи тела без значительного избытка;\n— естественные возрастные изменения тонуса кожи;\n— умеренная дряблость после беременности (через 6–12 месяцев после родов);\n— профилактика дряблости при снижении веса.\n\nНЕ подходит:\n— беременность;\n— металл, импланты, кардиостимулятор в зоне;\n— онкология в зоне;\n— выраженный птоз кожи после большого похудения (>20 кг).\n\nОптимальный курс: 1–2 сессии с интервалом 4–8 недель. Поддержка 1 раз в год.",
          en: "Effective zones for Ultraformer MPT Body:\n\n— Abdomen. Especially effective for moderate laxity after pregnancy or mild weight loss. Dermis (3 mm transducer) and subcutaneous fat (4.5–6 mm transducer) are treated.\n— Inner and outer thighs. Saddlebag correction, inner thigh tightening.\n— Arms. The 'batwing' zone — inner surface of the upper arm. HIFU effective for mild to moderate skin ptosis.\n— Décolletage and upper chest. Horizontal décolletage creases, laxity of the upper chest skin.\n— Knees. Skin around and above the kneecap that droops with age.\n— Glutes (upper outer portion). Lifting and tightening.\n\nIndications:\n— moderate body skin laxity and ptosis without significant excess;\n— natural age-related loss of skin tone;\n— moderate laxity after pregnancy (6-12 months post-partum);\n— prevention of laxity during weight loss.\n\nNOT suitable for: pregnancy; metal, implants, pacemaker in the treatment zone; cancer in the zone; pronounced skin ptosis after major weight loss (>20 kg).\n\nOptimal course: 1-2 sessions at 4-8 week intervals. Maintenance once a year.",
        },
        calloutBody: {
          uk: "Після вагітності HIFU на живіт — не раніше ніж через 6 місяців після пологів, а при грудному вигодовуванні — тільки після його завершення. Ці терміни не умовні — вони захищають вас.",
          ru: "После беременности HIFU на живот — не ранее чем через 6 месяцев после родов, а при грудном вскармливании — только после его завершения. Эти сроки не условные — они защищают вас.",
          en: "After pregnancy, HIFU on the abdomen is not recommended before 6 months post-partum, and only after breastfeeding has finished. These timings are not arbitrary — they protect you.",
        },
      },
      {
        heading: { uk: "Сесія і відновлення", ru: "Сессия и восстановление", en: "Session and recovery" },
        body: {
          uk: "Сесія Ultraformer MPT Body для однієї зони (наприклад, живіт або внутрішня поверхня стегон) — 30–60 хвилин. Повна обробка кількох зон — до 90–120 хвилин.\n\nПроцедура:\n— нанесення ультразвукового гелю на зону;\n— аплікатор рухається по шкірі, «постріли» — миттєві коагуляційні точки;\n— відчуття: від легкого поколювання до короткого різкого відчуття в залежності від зони і глибини (живіт — менш чутливий, ніж обличчя);\n— аплікаційна анестезія (крем) за бажанням для підвищеної чутливості.\n\nПісля процедури:\n— легка набряклість 24–48 годин у зоні обробки (нормальна реакція);\n— можливі одиничні синці при обробці зон з тонкою шкірою (коліна, руки);\n— ніяких обмежень у роботі і соціальній активності;\n— уникати сауни і активного спорту 24–48 годин;\n— SPF 30+ на зони, відкриті сонцю, 2 тижні після.\n\nЕфект:\n— перший помітний підйом — протягом 2–4 тижнів (скорочення наявного колагену);\n— основний результат від нового колагену — через 3–6 місяців;\n— тривалість: 12–18 місяців.",
          ru: "Сессия Ultraformer MPT Body для одной зоны (например, живот или внутренняя поверхность бёдер) — 30–60 минут. Полная обработка нескольких зон — до 90–120 минут.\n\nПроцедура:\n— нанесение ультразвукового геля на зону;\n— аппликатор движется по коже, «выстрелы» — мгновенные коагуляционные точки;\n— ощущения: от лёгкого покалывания до короткого резкого ощущения в зависимости от зоны и глубины (живот — менее чувствителен, чем лицо);\n— аппликационная анестезия (крем) по желанию для повышенной чувствительности.\n\nПосле процедуры:\n— лёгкая отёчность 24–48 часов в зоне обработки (нормальная реакция);\n— возможны единичные синяки при обработке зон с тонкой кожей (колени, руки);\n— никаких ограничений в работе и социальной активности;\n— избегать сауны и активного спорта 24–48 часов;\n— SPF 30+ на открытые солнцу зоны 2 недели после.\n\nЭффект:\n— первый заметный подъём — в течение 2–4 недель (сокращение имеющегося коллагена);\n— основной результат от нового коллагена — через 3–6 месяцев;\n— продолжительность: 12–18 месяцев.",
          en: "A session for one zone (e.g., abdomen or inner thighs) takes 30-60 minutes. Full multi-zone treatment: up to 90-120 minutes.\n\nProcedure:\n— ultrasound gel applied to the zone;\n— applicator moves across the skin, 'shots' form instant coagulation points;\n— sensations: from mild tingling to a brief sharp sensation depending on zone and depth (abdomen less sensitive than face);\n— topical anaesthetic cream optional for higher sensitivity.\n\nAfterward:\n— mild swelling for 24-48 hours in the treated zone (normal);\n— occasional bruising on thin-skin zones (knees, arms);\n— no work or social restrictions;\n— avoid sauna and intense exercise for 24-48 hours;\n— SPF 30+ on sun-exposed zones for 2 weeks post-treatment.\n\nEffect:\n— first noticeable tightening within 2-4 weeks (existing collagen contraction);\n— main new-collagen result at 3-6 months;\n— duration: 12-18 months.",
        },
        calloutBody: {
          uk: "Для зони живота після пологів ми завжди оцінюємо наявність діастазу перед Ultraformer MPT Body. HIFU підтягує шкіру, але не закриває розходження м'язів — це завдання для EMSCULPT NEO або хірурга.",
          ru: "Для зоны живота после родов мы всегда оцениваем наличие диастаза перед Ultraformer MPT Body. HIFU подтягивает кожу, но не закрывает расхождение мышц — это задача для EMSCULPT NEO или хирурга.",
          en: "For post-partum abdomen, we always assess for diastasis recti before Ultraformer MPT Body. HIFU tightens the skin but doesn't close muscle separation — that's a job for EMSCULPT NEO or a surgeon.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "Ultraformer MPT Body або EMSCULPT NEO — що вибрати для живота?", ru: "Ultraformer MPT Body или EMSCULPT NEO — что выбрать для живота?", en: "Ultraformer MPT Body or EMSCULPT NEO for the abdomen?" },
        answer: { uk: "Різні задачі: HIFU підтягує в'ялу шкіру, EMSCULPT NEO будує м'язи і видаляє жир. При в'ялій шкірі без жиру — Ultraformer. При жирі і слабких м'язах — EMSCULPT NEO. При обох проблемах — комбінація.", ru: "Разные задачи: HIFU подтягивает дряблую кожу, EMSCULPT NEO строит мышцы и убирает жир. При дряблой коже без жира — Ultraformer. При жире и слабых мышцах — EMSCULPT NEO. При обеих проблемах — комбинация.", en: "Different goals: HIFU tightens lax skin; EMSCULPT NEO builds muscle and removes fat. For lax skin without fat — Ultraformer. For fat with weak muscles — EMSCULPT NEO. For both problems — a combination." },
      },
      {
        question: { uk: "Чи допомагає HIFU від розтяжок?", ru: "Помогает ли HIFU от растяжек?", en: "Does HIFU help with stretch marks?" },
        answer: { uk: "Дуже обмежено. Ultraformer MPT Body не є спеціалізованим засобом від розтяжок. Для корекції стрій — ефективніші лазерна шліфовка (AcuPulse CO₂) або мікрогольна RF (EXION PRIME).", ru: "Очень ограниченно. Ultraformer MPT Body не является специализированным средством от растяжек. Для коррекции стрий — более эффективны лазерная шлифовка (AcuPulse CO₂) или микроигольный RF (EXION PRIME).", en: "Very limited effect. Ultraformer MPT Body is not a specialised treatment for stretch marks. For striae correction — laser resurfacing (AcuPulse CO₂) or microneedling RF (EXION PRIME) are more effective." },
      },
      {
        question: { uk: "Через скільки місяців після пологів можна робити HIFU на живіт?", ru: "Через сколько месяцев после родов можно делать HIFU на живот?", en: "How many months after delivery can HIFU on the abdomen be done?" },
        answer: { uk: "Мінімум 6 місяців після пологів і лише після завершення грудного вигодовування. Також — попередня оцінка на предмет діастазу прямих м'язів.", ru: "Минимум 6 месяцев после родов и только после завершения грудного вскармливания. Также — предварительная оценка на наличие диастаза прямых мышц.", en: "Minimum 6 months after delivery and only after breastfeeding ends. Pre-procedure diastasis assessment is also required." },
      },
    ],
  },

  // ─── EXION BODY ────────────────────────────────────────────────────────────
  {
    slug: "exion-body",
    summary: {
      uk: "EXION Body у GENEVITY — монополярна RF-процедура з AI-контролем для підвищення тонусу шкіри тіла, зменшення об'ємів і корекції целюліту. Поєднує глибокий рівномірний нагрів тканин з ультразвуковою стимуляцією синтезу гіалуронової кислоти — без болю, без відновлення.",
      ru: "EXION Body в GENEVITY — монополярная RF-процедура с AI-контролем для повышения тонуса кожи тела, уменьшения объёмов и коррекции целлюлита. Сочетает глубокий равномерный нагрев тканей с ультразвуковой стимуляцией синтеза гиалуроновой кислоты — без боли, без восстановления.",
      en: "EXION Body at GENEVITY — AI-controlled monopolar RF for improving body skin tone, reducing volume and correcting cellulite. Combines deep even tissue heating with ultrasound-driven hyaluronic acid synthesis stimulation — no pain, no downtime.",
    },
    sections: [
      {
        heading: { uk: "EXION Body: технологія і відмінність від звичайного RF", ru: "EXION Body: технология и отличие от обычного RF", en: "EXION Body: technology and what sets it apart from regular RF" },
        body: {
          uk: "EXION Body — аплікатор великого формату платформи EXION від BTL Aesthetics, адаптований для зон тіла: живіт, стегна, сідниці, руки, спина.\n\nЯк EXION відрізняється від звичайного монополярного RF (VOLNEWMER):\n— AI-модуль EXION в реальному часі монопольне стежить за температурою тканин за допомогою алгоритму зворотного зв'язку. Звичайний RF визначає інтенсивність «вручну» — оператор налаштовує потужність, і температура тканин може варіюватися. EXION автоматично підтримує терапевтичну температуру (40–43°C) у кожен момент — без перегріву і без «холодних зон».\n— Ультразвуковий компонент EXION стимулює синтез гіалуронової кислоти у дермі — не тільки колаген, але й власне зволоження шкіри на клітинному рівні. Для зони тіла це особливо важливо: шкіра тіла від природи менш зволожена, ніж шкіра обличчя.\n\nЩо відбувається у тканинах:\n— Глибокий рівномірний нагрів дерми → неоколагенез і нееластиногенез;\n— Нагрів підшкірної жирової клітковини → ліполіз, зменшення об'єму жирових клітин;\n— Покращення мікроциркуляції → зменшення набряклості, корекція «апельсинової кірки»;\n— Ультразвукова стимуляція → синтез гіалуронової кислоти → підвищення тургору і зволоженості шкіри.\n\nFDA-схвалена платформа. Клінічно підтверджено: покращення тургору шкіри, зменшення целюліту, зниження об'єму талії і стегон після курсу.",
          ru: "EXION Body — аппликатор большого формата платформы EXION от BTL Aesthetics, адаптированный для зон тела: живот, бёдра, ягодицы, руки, спина.\n\nКак EXION отличается от обычного монополярного RF (VOLNEWMER):\n— AI-модуль EXION в реальном времени отслеживает температуру тканей с помощью алгоритма обратной связи. Обычный RF определяет интенсивность «вручную» — оператор настраивает мощность, и температура тканей может варьироваться. EXION автоматически поддерживает терапевтическую температуру (40–43°C) в каждый момент — без перегрева и без «холодных зон».\n— Ультразвуковой компонент EXION стимулирует синтез гиалуроновой кислоты в дерме — не только коллаген, но и собственное увлажнение кожи на клеточном уровне. Для зоны тела это особенно важно: кожа тела от природы менее увлажнена, чем кожа лица.\n\nЧто происходит в тканях:\n— Глубокий равномерный нагрев дермы → неоколлагенез и неоэластиногенез;\n— Нагрев подкожной жировой клетчатки → липолиз, уменьшение объёма жировых клеток;\n— Улучшение микроциркуляции → уменьшение отёчности, коррекция «апельсиновой корки»;\n— Ультразвуковая стимуляция → синтез гиалуроновой кислоты → повышение тургора и увлажнённости кожи.\n\nFDA-одобренная платформа. Клинически подтверждено: улучшение тургора кожи, уменьшение целлюлита, снижение объёма талии и бёдер после курса.",
          en: "EXION Body is the large-format applicator of the EXION platform from BTL Aesthetics, adapted for body zones: abdomen, thighs, glutes, arms, back.\n\nHow EXION differs from regular monopolar RF (VOLNEWMER):\n— EXION's AI module monitors tissue temperature in real time using a feedback algorithm. Regular RF sets intensity manually — the operator adjusts power and tissue temperature can vary. EXION automatically maintains therapeutic temperature (40–43°C) at every moment — no overheating, no cold zones.\n— EXION's ultrasound component stimulates hyaluronic acid synthesis in the dermis — not just collagen, but native cellular skin hydration. For body zones this matters particularly: body skin is naturally less hydrated than facial skin.\n\nWhat happens in the tissue:\n— Deep even dermal heating → neocollagenesis and neoelastinogenesis;\n— Subcutaneous fat heating → lipolysis, reduction in fat cell volume;\n— Improved microcirculation → less puffiness, cellulite improvement;\n— Ultrasound stimulation → hyaluronic acid synthesis → increased turgor and hydration.\n\nFDA-approved platform. Clinically confirmed: improved skin turgor, reduced cellulite, decreased waist and thigh circumference after a course.",
        },
        calloutBody: {
          uk: "EXION Body — єдина апаратна RF-процедура, яка одночасно стимулює і колаген, і гіалуронову кислоту в шкірі тіла. Це не маркетингова заява — це FDA-підтверджений механізм дії.",
          ru: "EXION Body — единственная аппаратная RF-процедура, которая одновременно стимулирует и коллаген, и гиалуроновую кислоту в коже тела. Это не маркетинговое заявление — это FDA-подтверждённый механизм действия.",
          en: "EXION Body is the only device-based RF procedure that simultaneously stimulates both collagen and hyaluronic acid in body skin. This is not a marketing claim — it's an FDA-confirmed mechanism of action.",
        },
      },
      {
        heading: { uk: "Показання: целюліт, в'ялість, корекція контуру", ru: "Показания: целлюлит, дряблость, коррекция контура", en: "Indications: cellulite, laxity, contour correction" },
        body: {
          uk: "EXION Body ефективний при:\n\n— Целюліті (ліподистрофія шкіри, «апельсинова кірка»). RF + ультразвук покращують мікроциркуляцію, розм'якшують фіброзні септи між жировими клітинами, стимулюють синтез колагену. Помітне покращення — з 2–3-ї сесії. Целюліт 1–3 ступеня (м'який і помірний) — найкращий відгук; 4 ступінь (склерозований) — потрібна комбінація процедур.\n— В'ялій шкірі тіла. Живіт, стегна, руки, коліна, декольте, шия. Курс EXION Body значно підвищує тонус шкіри там, де HIFU не потрібен або не підходить.\n— Набряклості і «важких» ногах. Покращення лімфо- і мікрокровообігу — ефективний при набряковій формі целюліту.\n— Корекції об'ємів. Ліполітичний ефект RF — до 2–3 см з обхвату талії або стегон після курсу.\n— Підготовці шкіри до схуднення або після нього. RF «підтягує» шкіру паралельно до зниження ваги, запобігаючи її обвисанню.\n\nОптимальний курс: 6–8 сесій з інтервалом 1 тиждень для активної корекції целюліту; 4–6 для загального тонусу. Підтримка — 1 раз на місяць або 1 раз на 3 місяці.\n\nНЕ підходить: вагітність, кардіостимулятор, метал у зоні, онкологія, активні шкірні запалення, тромбофлебіт у зоні.",
          ru: "EXION Body эффективен при:\n\n— Целлюлите (липодистрофия кожи, «апельсиновая корка»). RF + ультразвук улучшают микроциркуляцию, размягчают фиброзные септы между жировыми клетками, стимулируют синтез коллагена. Заметное улучшение — с 2–3-й сессии. Целлюлит 1–3 степени (мягкий и умеренный) — лучший отклик; 4 степень (склерозированный) — нужна комбинация процедур.\n— Дряблой коже тела. Живот, бёдра, руки, колени, декольте, шея. Курс EXION Body значительно повышает тонус кожи там, где HIFU не нужен или не подходит.\n— Отёчности и «тяжёлых» ногах. Улучшение лимфо- и микрокровообращения — эффективен при отёчной форме целлюлита.\n— Коррекции объёмов. Липолитический эффект RF — до 2–3 см с обхвата талии или бёдер после курса.\n— Подготовке кожи к похудению или после него. RF «подтягивает» кожу параллельно снижению веса, предотвращая её обвисание.\n\nОптимальный курс: 6–8 сессий с интервалом 1 неделя для активной коррекции целлюлита; 4–6 для общего тонуса. Поддержка — 1 раз в месяц или 1 раз в 3 месяца.\n\nНЕ подходит: беременность, кардиостимулятор, металл в зоне, онкология, активные кожные воспаления, тромбофлебит в зоне.",
          en: "EXION Body is effective for:\n\n— Cellulite (skin lipodystrophy, 'orange peel'). RF + ultrasound improve microcirculation, soften fibrous septa between fat cells, stimulate collagen synthesis. Noticeable improvement from sessions 2-3. Grade 1-3 (soft to moderate) cellulite responds best; grade 4 (sclerosed) needs a combined approach.\n— Lax body skin. Abdomen, thighs, arms, knees, décolletage, neck. An EXION Body course significantly improves skin tone where HIFU isn't needed or appropriate.\n— Puffiness and 'heavy' legs. Improved lymphatic and microcirculation — effective for oedematous cellulite.\n— Volume reduction. The RF lipolytic effect delivers up to 2-3 cm reduction in waist or thigh circumference after a course.\n— Skin preparation during or after weight loss. RF tightens skin in parallel with weight reduction, preventing sagging.\n\nOptimal course: 6-8 sessions at weekly intervals for active cellulite correction; 4-6 for general tone improvement. Maintenance: monthly or every 3 months.\n\nNOT suitable for: pregnancy, pacemaker, metal in the zone, cancer, active skin inflammation, thrombophlebitis in the zone.",
        },
        calloutBody: {
          uk: "Для зон із целюлітом 4-го ступеня (щільний, склерозований — «кірка не рухається») жодна RF-процедура не дасть вираженого результату без додаткових методів. Ми скажемо про це відкрито на консультації, а не після курсу.",
          ru: "Для зон с целлюлитом 4-й степени (плотный, склерозированный — «корка не движется») никакая RF-процедура не даст выраженного результата без дополнительных методов. Мы скажем об этом открыто на консультации, а не после курса.",
          en: "For grade-4 cellulite zones (dense, sclerosed — 'the skin doesn't move') no RF procedure will deliver a pronounced result without additional methods. We will say so openly at the consultation, not after you've paid for a course.",
        },
      },
      {
        heading: { uk: "Процедура та відчуття", ru: "Процедура и ощущения", en: "The procedure and what you feel" },
        body: {
          uk: "Сесія EXION Body для однієї зони (живіт або стегна) — 30–45 хвилин. Дві зони — 50–70 хвилин.\n\nХід процедури:\n1. Нанесення гелю. Аплікатор EXION Body великого розміру рухається по шкірі з гелем.\n2. AI-нагрів. Система автоматично виходить на терапевтичну температуру і підтримує її. Спеціаліст бачить температуру на дисплеї в реальному часі.\n3. Ультразвукові імпульси. Одночасно з RF — спрямований ультразвук, що стимулює гіалуронову кислоту.\n\nВідчуття:\n— рівне, глибоке тепло. Приємно;\n— «мурашки» або легке поколювання в деяких зонах — ультразвуковий компонент;\n— анестезія не потрібна.\n\nПісля процедури:\n— шкіра рожева і тепла 30–60 хвилин;\n— легкий набряк у перші кілька годин (норма);\n— соціальна активність без обмежень;\n— спорт — краще наступного дня;\n— при курсі для целюліту — рекомендуємо лімфодренажний масаж через 24 години після кожної сесії (підсилює виведення зруйнованих адипоцитів).",
          ru: "Сессия EXION Body для одной зоны (живот или бёдра) — 30–45 минут. Две зоны — 50–70 минут.\n\nХод процедуры:\n1. Нанесение геля. Аппликатор EXION Body большого размера движется по коже с гелем.\n2. AI-нагрев. Система автоматически выходит на терапевтическую температуру и поддерживает её. Специалист видит температуру на дисплее в реальном времени.\n3. Ультразвуковые импульсы. Одновременно с RF — направленный ультразвук, стимулирующий гиалуроновую кислоту.\n\nОщущения:\n— ровное, глубокое тепло. Приятно;\n— «мурашки» или лёгкое покалывание в некоторых зонах — ультразвуковой компонент;\n— анестезия не нужна.\n\nПосле процедуры:\n— кожа розовая и тёплая 30–60 минут;\n— лёгкий отёк в первые несколько часов (норма);\n— социальная активность без ограничений;\n— спорт — лучше на следующий день;\n— при курсе для целлюлита — рекомендуем лимфодренажный массаж через 24 часа после каждой сессии (усиливает выведение разрушенных адипоцитов).",
          en: "An EXION Body session for one zone (abdomen or thighs) takes 30-45 minutes. Two zones: 50-70 minutes.\n\nHow the procedure runs:\n1. Gel application. The large EXION Body applicator moves across the gel-coated skin.\n2. AI heating. The system automatically reaches therapeutic temperature and holds it. The specialist monitors temperature on the display in real time.\n3. Ultrasound pulses. Directed ultrasound runs simultaneously with RF, stimulating hyaluronic acid.\n\nSensations:\n— steady, deep warmth — pleasant;\n— 'pins and needles' or mild tingling in some zones — the ultrasound component;\n— no anaesthesia needed.\n\nAfterward:\n— skin pink and warm for 30-60 minutes;\n— mild swelling for a few hours (normal);\n— no social restrictions;\n— exercise better the next day;\n— for cellulite courses — we recommend lymphatic drainage massage 24 hours after each session (enhances clearance of destroyed adipocytes).",
        },
        calloutBody: {
          uk: "Лімфодренажний масаж після курсу EXION Body — не «доплата» і не обов'язок. Але якщо вам важливий максимальний результат від корекції целюліту — він реально прискорює виведення жирових клітин після ліполізу.",
          ru: "Лимфодренажный массаж после курса EXION Body — не «доплата» и не обязанность. Но если вам важен максимальный результат от коррекции целлюлита — он реально ускоряет выведение жировых клеток после липолиза.",
          en: "Lymphatic drainage massage after an EXION Body course is not an upsell and not obligatory. But if you want maximum cellulite correction results, it genuinely accelerates the clearance of fat cells after lipolysis.",
        },
      },
    ],
    faq: [
      {
        question: { uk: "Скільки сесій EXION Body потрібно при целюліті?", ru: "Сколько сессий EXION Body нужно при целлюлите?", en: "How many EXION Body sessions are needed for cellulite?" },
        answer: { uk: "6–8 сесій з інтервалом 1 тиждень для активної корекції. Перші результати — після 3-ї сесії. Підтримуючі сесії 1 раз на 4–6 тижнів подовжують ефект.", ru: "6–8 сессий с интервалом 1 неделя для активной коррекции. Первые результаты — после 3-й сессии. Поддерживающие сессии 1 раз в 4–6 недель продлевают эффект.", en: "6-8 sessions at weekly intervals for active correction. First results after session 3. Maintenance sessions every 4-6 weeks extend the effect." },
      },
      {
        question: { uk: "EXION Body чи EMSCULPT NEO для стегон?", ru: "EXION Body или EMSCULPT NEO для бёдер?", en: "EXION Body or EMSCULPT NEO for thighs?" },
        answer: { uk: "EXION Body — для в'ялої шкіри та целюліту. EMSCULPT NEO — для зміцнення м'язів і видалення локального жиру. При поєднанні целюліту, в'ялості і жирових відкладень — ефективна комбінація обох.", ru: "EXION Body — для дряблой кожи и целлюлита. EMSCULPT NEO — для укрепления мышц и удаления локального жира. При сочетании целлюлита, дряблости и жировых отложений — эффективна комбинация обоих.", en: "EXION Body — for lax skin and cellulite. EMSCULPT NEO — for muscle strengthening and local fat removal. When cellulite, laxity and fat deposits coexist — a combination of both is most effective." },
      },
      {
        question: { uk: "Чи є реабілітація після EXION Body?", ru: "Есть ли реабилитация после EXION Body?", en: "Is there any downtime after EXION Body?" },
        answer: { uk: "Ні. Легка рожевість і тепло 30–60 хвилин — і можна одразу йти на роботу. Жодних обмежень по соціальній активності.", ru: "Нет. Лёгкая розовость и тепло 30–60 минут — и можно сразу идти на работу. Никаких ограничений по социальной активности.", en: "None. Mild pinkness and warmth for 30-60 minutes — then straight back to work. No social restrictions." },
      },
      {
        question: { uk: "Чи допоможе EXION Body схуднути?", ru: "Поможет ли EXION Body похудеть?", en: "Will EXION Body help me lose weight?" },
        answer: { uk: "Ні — у тому сенсі, що загальна вага може не змінитися. Зменшуються об'єми у зоні обробки (до 2–3 см з обхвату), покращується рельєф і тургор. Для схуднення потрібен дефіцит калорій.", ru: "Нет — в том смысле, что общий вес может не измениться. Уменьшаются объёмы в зоне обработки (до 2–3 см с обхвата), улучшается рельеф и тургор. Для похудения нужен дефицит калорий.", en: "Not in the sense that overall weight may not change. Volume in the treated zone decreases (up to 2-3 cm circumference), and shape and turgor improve. Weight loss requires a calorie deficit." },
      },
    ],
  },
];

async function seedService(copy: ServiceCopy) {
  const svc = await sql`SELECT id FROM services WHERE slug = ${copy.slug} LIMIT 1`;
  if (!svc[0]) { console.error(`Service "${copy.slug}" not found — skip`); return; }
  const serviceId = svc[0].id as string;

  await sql`UPDATE services SET summary_uk=${copy.summary.uk}, summary_ru=${copy.summary.ru}, summary_en=${copy.summary.en} WHERE id=${serviceId}`;
  await sql`DELETE FROM content_sections WHERE owner_type='service' AND owner_id=${serviceId}`;
  await sql`DELETE FROM faq_items WHERE owner_type='service' AND owner_id=${serviceId}`;

  const sectionIds: string[] = [];
  for (let i = 0; i < copy.sections.length; i++) {
    const s = copy.sections[i];
    const id = randomUUID();
    sectionIds.push(id);
    const data = { heading: s.heading, body: s.body, calloutBody: s.calloutBody, heroImage: null };
    await sql`INSERT INTO content_sections(id,owner_type,owner_id,sort_order,section_type,data) VALUES(${id},'service',${serviceId},${i},'richText'::section_type,${JSON.stringify(data)}::jsonb)`;
  }
  for (let i = 0; i < copy.faq.length; i++) {
    const f = copy.faq[i];
    await sql`INSERT INTO faq_items(owner_type,owner_id,sort_order,question_uk,question_ru,question_en,answer_uk,answer_ru,answer_en) VALUES('service',${serviceId},${i},${f.question.uk},${f.question.ru},${f.question.en},${f.answer.uk},${f.answer.ru},${f.answer.en})`;
  }

  const newOrder = [...sectionIds.map(id => `section:${id}`), "faq", "doctors", "equipment", "relatedServices", "finalCTA"];
  await sql`UPDATE services SET block_order=${newOrder} WHERE id=${serviceId}`;
  console.log(`✓ ${copy.slug} — ${copy.sections.length} sections, ${copy.faq.length} FAQs`);
}

async function main() {
  for (const svc of SERVICES) await seedService(svc);
  await sql.end();
  console.log("\nV3b DONE — EMSCULPT NEO, Ultraformer MPT Body, EXION Body. Continue with v3c for M22, Splendor X, HydraFacial, AcuPulse CO₂.");
}
main().catch(e => { console.error(e); process.exit(1); });
