/**
 * V2 part C — Juvederm + PolyPhil. Last two injectable-cosmetology
 * pages, completing the category.
 */
import postgres from "postgres";
import * as fs from "fs";
import * as path from "path";
import { randomUUID } from "crypto";

const envContent = fs.readFileSync(path.resolve(__dirname, "../.env.local"), "utf-8");
const env: Record<string, string> = {};
envContent.split("\n").forEach((l) => {
  const [k, ...v] = l.split("=");
  if (k && v.length) env[k.trim()] = v.join("=").trim();
});
const sql = postgres(env.DATABASE_URL!);

type L = { uk: string; ru: string; en: string };
interface SectionCopy { heading: L; body: L; calloutBody: L; }
interface FaqCopy { question: L; answer: L; }
interface ServiceCopy { slug: string; summary: L; sections: SectionCopy[]; faq: FaqCopy[]; }

const juvederm: ServiceCopy = {
  slug: "juvederm",
  summary: {
    uk: "Juvederm у GENEVITY — преміум-лінійка філерів на основі гіалуронової кислоти від Allergan Aesthetics: Volift, Volbella, Voluma, Volux, Ultra. Кожен препарат — під свою зону і текстуру шкіри, кожна ін'єкція — точний інструмент архітектора обличчя.",
    ru: "Juvederm в GENEVITY — премиум-линейка филлеров на основе гиалуроновой кислоты от Allergan Aesthetics: Volift, Volbella, Voluma, Volux, Ultra. Каждый препарат — под свою зону и текстуру кожи, каждая инъекция — точный инструмент архитектора лица.",
    en: "Juvederm at GENEVITY — the premium hyaluronic-acid filler line from Allergan Aesthetics: Volift, Volbella, Voluma, Volux, Ultra. Each preparation targets a specific zone and texture, each injection a precision tool of facial architecture.",
  },
  sections: [
    {
      heading: { uk: "Що таке Juvederm", ru: "Что такое Juvederm", en: "What Juvederm is" },
      body: {
        uk: "Juvederm — преміум-лінійка ін'єкційних філерів на основі стабілізованої гіалуронової кислоти виробництва Allergan Aesthetics (США / Ірландія). Один з двох світових лідерів серед філерів (разом з Restylane), Juvederm відомий інноваційною технологією VYCROSS і HYLACROSS, яка забезпечує:\n\n— високу стабільність препарату (менша розсмоктуваність, довший ефект);\n— «м'яку» інтеграцію з тканинами — філер не «подушкується», а розподіляється природно;\n— передбачуваний результат — препарат веде себе однаково у різних пацієнтів;\n— можливість повної корекції гіалуронідазою при потребі.\n\nЛінійка Juvederm включає препарати з різною щільністю під різні зони обробки:\n— Juvederm Volbella — найм'якіший, для тонких ліній, губ, вусиків («ліній кролика»);\n— Juvederm Volift — середньої щільності, для носогубних складок, маріонеткових ліній;\n— Juvederm Volift Retouch — для тонкої корекції і доповнення;\n— Juvederm Voluma — для скульптурної корекції скул, відновлення середньої третини обличчя;\n— Juvederm Volux — найщільніший, для підборіддя, кута щелепи, для архітектурної перебудови нижньої третини;\n— Juvederm Ultra — класична лінійка для губ і середніх зон.\n\nУ GENEVITY, Дніпро, ми працюємо лише з оригінальним Juvederm, отриманим через офіційного дистриб'ютора Allergan. Кожен шприц має голографічну мітку, серійний номер і підлягає перевірці на сайті виробника.",
        ru: "Juvederm — премиум-линейка инъекционных филлеров на основе стабилизированной гиалуроновой кислоты производства Allergan Aesthetics (США / Ирландия). Один из двух мировых лидеров среди филлеров (вместе с Restylane), Juvederm известен инновационной технологией VYCROSS и HYLACROSS, которая обеспечивает:\n\n— высокую стабильность препарата (меньшая рассасываемость, более длительный эффект);\n— «мягкую» интеграцию с тканями — филлер не «подушкуется», а распределяется естественно;\n— предсказуемый результат — препарат ведёт себя одинаково у разных пациентов;\n— возможность полной коррекции гиалуронидазой при необходимости.\n\nЛинейка Juvederm включает препараты с разной плотностью под разные зоны обработки:\n— Juvederm Volbella — самый мягкий, для тонких линий, губ, усиков («линий кролика»);\n— Juvederm Volift — средней плотности, для носогубных складок, марионеточных линий;\n— Juvederm Volift Retouch — для тонкой коррекции и дополнения;\n— Juvederm Voluma — для скульптурной коррекции скул, восстановления средней трети лица;\n— Juvederm Volux — самый плотный, для подбородка, угла челюсти, для архитектурной перестройки нижней трети;\n— Juvederm Ultra — классическая линейка для губ и средних зон.\n\nВ GENEVITY, Днепр, мы работаем только с оригинальным Juvederm, полученным через официального дистрибьютора Allergan. Каждый шприц имеет голографическую метку, серийный номер и подлежит проверке на сайте производителя.",
        en: "Juvederm is a premium injectable filler line based on stabilised hyaluronic acid, manufactured by Allergan Aesthetics (USA / Ireland). One of two world leaders in fillers (alongside Restylane), Juvederm is known for its VYCROSS and HYLACROSS technology, which delivers:\n\n— high preparation stability (slower absorption, longer-lasting effect);\n— soft tissue integration — the filler doesn't cushion, it distributes naturally;\n— predictable results — the product behaves the same way in different patients;\n— full reversibility with hyaluronidase when needed.\n\nThe Juvederm line includes preparations at different densities for different zones:\n— Juvederm Volbella — softest, for fine lines, lips, upper lip \"bunny lines\";\n— Juvederm Volift — medium density, for nasolabial folds, marionette lines;\n— Juvederm Volift Retouch — for fine correction and touch-ups;\n— Juvederm Voluma — for sculpting cheekbones, restoring the midface;\n— Juvederm Volux — densest, for chin, jawline, architectural restructuring of the lower third;\n— Juvederm Ultra — the classic line for lips and midzones.\n\nAt GENEVITY Dnipro we work only with original Juvederm sourced through Allergan's official distributor. Every syringe has a holographic mark, a serial number, and can be verified on the manufacturer's website.",
      },
      calloutBody: {
        uk: "Оригінальність філеру — не деталь, а базовий стандарт. Контрафакт Juvederm — одна з найбільш частих причин естетичних проблем у Україні: «філери», зроблені у невідомих умовах, викликають набряки, асиметрії, гранулеми, які потім доводиться розчиняти.",
        ru: "Оригинальность филлера — не деталь, а базовый стандарт. Контрафакт Juvederm — одна из самых частых причин эстетических проблем в Украине: «филлеры», сделанные в неизвестных условиях, вызывают отёки, асимметрии, гранулёмы, которые потом приходится растворять.",
        en: "Filler authenticity isn't a detail — it's the baseline. Counterfeit Juvederm is one of the most common causes of aesthetic problems in Ukraine: \"fillers\" made in unknown conditions cause swelling, asymmetry, granulomas that later need to be dissolved.",
      },
    },
    {
      heading: { uk: "Коли обирають Juvederm", ru: "Когда выбирают Juvederm", en: "When to choose Juvederm" },
      body: {
        uk: "Juvederm обирають, коли потрібен передбачуваний, довготривалий і безпечний результат у контурній пластиці. Головні показання:\n\n— Корекція форми губ. Juvederm Volbella — один з найбільш популярних філерів для губ у світі: м'яка текстура, природна «водяниста» реакція у тканинах, стабільна форма 9–12 місяців. Volbella підходить для першого досвіду з філерами — результат природний, малопомітний, без «качиного» ефекту.\n— Відновлення об'єму середньої третини обличчя (щоки, скули). Juvederm Voluma — золотий стандарт для скульптурної корекції скул. Препарат щільний, тримається у тканинах 18 місяців і довше, дає чітко виражений лліфтинговий ефект при правильному розподілі.\n— Архітектурна корекція нижньої третини обличчя (підборіддя, кут щелепи). Juvederm Volux — найщільніший препарат у лінійці, створений саме для цих зон. Дозволяє створити чіткий контур щелепи, подовжити підборіддя, покращити овал обличчя без хірургії.\n— Носогубні складки і маріонеткові лінії. Juvederm Volift — препарат середньої щільності, оптимальний для цих зон: не дає «ефекту подушки», природно розгладжує складки.\n— Тонкі зморшки і слізна борозенка. Juvederm Volbella, рідко — Volift Retouch, у делікатних зонах навколо очей.\n\nЧас життя філеру Juvederm залежить від щільності препарату: Volbella у губах — 6–9 місяців; Volift у носогубці — 9–12; Voluma у щоках — 12–18; Volux у підборідді — 15–24 місяці.",
        ru: "Juvederm выбирают, когда нужен предсказуемый, длительный и безопасный результат в контурной пластике. Главные показания:\n\n— Коррекция формы губ. Juvederm Volbella — один из самых популярных филлеров для губ в мире: мягкая текстура, естественная «водянистая» реакция в тканях, стабильная форма 9–12 месяцев. Volbella подходит для первого опыта с филлерами — результат естественный, малозаметный, без «утиного» эффекта.\n— Восстановление объёма средней трети лица (щёки, скулы). Juvederm Voluma — золотой стандарт для скульптурной коррекции скул. Препарат плотный, держится в тканях 18 месяцев и дольше, даёт чётко выраженный лифтинговый эффект при правильном распределении.\n— Архитектурная коррекция нижней трети лица (подбородок, угол челюсти). Juvederm Volux — самый плотный препарат в линейке, созданный именно для этих зон. Позволяет создать чёткий контур челюсти, удлинить подбородок, улучшить овал лица без хирургии.\n— Носогубные складки и марионеточные линии. Juvederm Volift — препарат средней плотности, оптимальный для этих зон: не даёт «эффекта подушки», естественно разглаживает складки.\n— Тонкие морщины и слёзная борозда. Juvederm Volbella, реже — Volift Retouch, в деликатных зонах вокруг глаз.\n\nВремя жизни филлера Juvederm зависит от плотности препарата: Volbella в губах — 6–9 месяцев; Volift в носогубке — 9–12; Voluma в щеках — 12–18; Volux в подбородке — 15–24 месяца.",
        en: "Juvederm is chosen when you need a predictable, long-lasting and safe result in contour plasty.\n\n— Lip shape correction. Juvederm Volbella is one of the world's most popular lip fillers: soft texture, natural \"watery\" behaviour in tissue, stable shape 9-12 months. Volbella is ideal for first-time filler patients — natural, understated results without a \"duck\" effect.\n— Midface volume restoration (cheeks, cheekbones). Juvederm Voluma is the gold standard for sculpting cheekbones: dense, lasting 18+ months in tissue, delivering a clear lifting effect when correctly distributed.\n— Lower face architecture (chin, jawline). Juvederm Volux is the densest in the line, designed specifically for these zones. It creates a defined jawline, lengthens the chin, improves facial oval without surgery.\n— Nasolabial folds and marionette lines. Juvederm Volift at medium density is optimal — no cushion effect, natural smoothing.\n— Fine lines and tear troughs. Juvederm Volbella and, more rarely, Volift Retouch for delicate zones around the eyes.\n\nDuration depends on product density: Volbella in lips — 6-9 months; Volift in nasolabial — 9-12; Voluma in cheeks — 12-18; Volux in chin — 15-24 months.",
      },
      calloutBody: {
        uk: "Juvederm не перемагає за «кращістю» інші преміум-філери (Restylane, Teosyal). Це просто інший інструмент з іншою «інтеграцією» у шкіру. Вибір між ними — справа лікаря під ваш тип тканин, не справа прайсу.",
        ru: "Juvederm не побеждает по «лучшести» другие премиум-филлеры (Restylane, Teosyal). Это просто другой инструмент с другой «интеграцией» в кожу. Выбор между ними — дело врача под ваш тип тканей, не дело прайса.",
        en: "Juvederm isn't objectively \"better\" than other premium fillers (Restylane, Teosyal). It's a different tool with a different tissue integration. The choice between them is the doctor's call based on your tissue type — not a question of price.",
      },
    },
    {
      heading: { uk: "Процедура і реабілітація", ru: "Процедура и реабилитация", en: "Procedure and recovery" },
      body: {
        uk: "Процедура ін'єкцій Juvederm триває 30–60 хвилин залежно від кількості зон. Етапи:\n\n1. Консультація і картографування обличчя. Лікар робить фотопротокол, оцінює симетрію і пропорції, складає план корекції. На консультації обов'язково обговорюємо реалістичні очікування: що можна зробити одним шприцем, що потребує двох, а що вимагає курсової корекції.\n\n2. Вибір препарату Juvederm під зону. Для кожної обробки обирається препарат з потрібною щільністю — від Volbella до Volux. Часто в одну процедуру використовуємо 2–3 різних препарати Juvederm.\n\n3. Анестезія. Аплікаційний лідокаїновий крем на 15 хвилин для більшості зон. Для губ — провідникова анестезія стоматологічного типу (швидше й комфортніше). Важливо: Juvederm містить лідокаїн у самому препараті — це знижує дискомфорт під час ін'єкції.\n\n4. Техніка введення. Juvederm вводиться через голку або канюлю — залежно від зони:\n— голка: тонка корекція губ, слізної борозенки, дрібних ліній;\n— канюля: об'ємні зони (щоки, скули, підборіддя) — менше травми, нижчий ризик судинних пошкоджень, менше синяків.\n\n5. Реабілітація:\n— перші 24 години: без сауни, басейну, спорту, масажу обличчя, активної міміки у зоні обробки;\n— 48 годин: уникати горизонтального положення на оброблених зонах, не торкатись обличчя;\n— 2 тижні: SPF 30+, відмова від агресивних процедур (пілінги, лазер, масажі);\n— повний ефект — на 10–14 день, коли препарат «сідає».\n\nСиняки можливі у 15–20% випадків, частіше при обробці губ і носогубки голкою, проходять за 4–7 днів. Набряк у губах максимальний на 2–3 день, повністю йде до 10–14.",
        ru: "Процедура инъекций Juvederm длится 30–60 минут в зависимости от количества зон. Этапы:\n\n1. Консультация и картографирование лица. Врач делает фотопротокол, оценивает симметрию и пропорции, составляет план коррекции. На консультации обязательно обсуждаем реалистичные ожидания: что можно сделать одним шприцом, что требует двух, а что требует курсовой коррекции.\n\n2. Выбор препарата Juvederm под зону. Для каждой обработки выбирается препарат с нужной плотностью — от Volbella до Volux. Часто в одну процедуру используем 2–3 разных препарата Juvederm.\n\n3. Анестезия. Аппликационный лидокаиновый крем на 15 минут для большинства зон. Для губ — проводниковая анестезия стоматологического типа (быстрее и комфортнее). Важно: Juvederm содержит лидокаин в самом препарате — это снижает дискомфорт во время инъекции.\n\n4. Техника введения. Juvederm вводится через иглу или канюлю — в зависимости от зоны:\n— игла: тонкая коррекция губ, слёзной борозды, мелких линий;\n— канюля: объёмные зоны (щёки, скулы, подбородок) — меньше травмы, ниже риск сосудистых повреждений, меньше синяков.\n\n5. Реабилитация:\n— первые 24 часа: без сауны, бассейна, спорта, массажа лица, активной мимики в зоне обработки;\n— 48 часов: избегать горизонтального положения на обработанных зонах, не трогать лицо;\n— 2 недели: SPF 30+, отказ от агрессивных процедур (пилинги, лазер, массажи);\n— полный эффект — на 10–14 день, когда препарат «садится».\n\nСиняки возможны в 15–20% случаев, чаще при обработке губ и носогубки иглой, проходят за 4–7 дней. Отёк в губах максимален на 2–3 день, полностью уходит к 10–14.",
        en: "A Juvederm session takes 30-60 minutes depending on the number of zones.\n\n1. Consultation and facial mapping. The doctor takes photos, evaluates symmetry and proportions, builds the correction plan. We always discuss realistic expectations: what can be done in one syringe, what takes two, and what needs course correction.\n\n2. Product selection per zone. Each treatment area gets the right density — from Volbella to Volux. We often use 2-3 different Juvederm preparations in a single session.\n\n3. Anaesthesia. Topical lidocaine cream for 15 minutes in most zones. For lips — dental-style nerve-block anaesthesia (faster and more comfortable). Importantly: Juvederm contains lidocaine in the preparation itself, which reduces injection discomfort.\n\n4. Technique. Juvederm is delivered via needle or cannula depending on zone:\n— needle: precise lip correction, tear troughs, fine lines;\n— cannula: volume zones (cheeks, cheekbones, chin) — less trauma, lower vascular risk, fewer bruises.\n\n5. Recovery:\n— first 24 hours: no sauna, pool, sport, facial massage, strong expression in the treated area;\n— 48 hours: avoid lying on treated zones, don't touch the face;\n— 2 weeks: SPF 30+, no aggressive procedures (peels, laser, massage);\n— full settling at day 10-14 as the product integrates.\n\nBruising in 15-20% of cases, more often with lip and nasolabial needle technique, resolving in 4-7 days. Lip swelling peaks at day 2-3 and fully clears by 10-14.",
      },
      calloutBody: {
        uk: "Найпоширеніша помилка першої зустрічі з філерами — «зробіть мені побільше». GENEVITY вчить клієнтів принципу «меншого за раз»: краще робити корекцію в 2 етапи з інтервалом 2 тижні, ніж одразу ввести зайвий об'єм, який потім доведеться розчиняти.",
        ru: "Самая частая ошибка первой встречи с филлерами — «сделайте мне побольше». GENEVITY учит клиентов принципу «меньшего за раз»: лучше делать коррекцию в 2 этапа с интервалом 2 недели, чем сразу ввести лишний объём, который потом придётся растворять.",
        en: "The most common first-filler mistake is asking for \"a bit more\". GENEVITY teaches patients the principle of \"less at a time\": better to correct in two stages with a two-week gap than to add excess volume that later has to be dissolved.",
      },
    },
    {
      heading: { uk: "Протипоказання та безпека", ru: "Противопоказания и безопасность", en: "Contraindications and safety" },
      body: {
        uk: "Juvederm — один з найбільш клінічно досліджених філерів у світі: понад 16 млн процедур за 20 років, сотні опублікованих клінічних випробувань, підтверджена безпека профілю. Проте протипоказання існують для будь-якого ін'єкційного препарату.\n\nАбсолютні протипоказання:\n— вагітність і грудне вигодовування;\n— гіперчутливість до гіалуронової кислоти або лідокаїну;\n— активні запальні процеси у зоні ін'єкції;\n— активні інфекційні захворювання (включно з герпесом у стадії активного прояву, особливо для зони губ);\n— аутоімунні захворювання у фазі загострення;\n— порушення згортання крові;\n— онкологічні захворювання в активній фазі.\n\nВідносні протипоказання (процедуру можна робити, але з обережністю):\n— прийом антикоагулянтів — потребує обговорення з лікуючим лікарем;\n— схильність до утворення келоїдних рубців;\n— нещодавня імплантація зубних імплантів (інтервал 1 місяць);\n— нещодавнє лазерне шліфування чи пілінг (інтервал 2–4 тижні).\n\nМожливі побічні ефекти: набряклість (особливо у губах) — 2–10 днів; синяки — у 15–20% випадків; болючість у зоні обробки — 1–2 дні; невелика асиметрія у перші дні через набряк (нормалізується до 10–14 дня). Рідкісні ускладнення: гранулеми, інфекції, судинні пошкодження — практично виключені за умови оригінального препарату, сертифікованої техніки і досвідченого лікаря. Ось чому ми завжди показуємо оригінальну упаковку і серійний номер перед процедурою.",
        ru: "Juvederm — один из самых клинически исследованных филлеров в мире: более 16 млн процедур за 20 лет, сотни опубликованных клинических испытаний, подтверждённая безопасность профиля. Однако противопоказания существуют для любого инъекционного препарата.\n\nАбсолютные противопоказания:\n— беременность и грудное вскармливание;\n— гиперчувствительность к гиалуроновой кислоте или лидокаину;\n— активные воспалительные процессы в зоне инъекции;\n— активные инфекционные заболевания (включая герпес в стадии активного проявления, особенно для зоны губ);\n— аутоиммунные заболевания в фазе обострения;\n— нарушения свёртываемости крови;\n— онкологические заболевания в активной фазе.\n\nОтносительные противопоказания (процедуру можно делать, но с осторожностью):\n— приём антикоагулянтов — требует обсуждения с лечащим врачом;\n— склонность к образованию келоидных рубцов;\n— недавняя имплантация зубных имплантов (интервал 1 месяц);\n— недавняя лазерная шлифовка или пилинг (интервал 2–4 недели).\n\nВозможные побочные эффекты: отёчность (особенно в губах) — 2–10 дней; синяки — в 15–20% случаев; болезненность в зоне обработки — 1–2 дня; небольшая асимметрия в первые дни из-за отёка (нормализуется к 10–14 дню). Редкие осложнения: гранулёмы, инфекции, сосудистые повреждения — практически исключены при условии оригинального препарата, сертифицированной техники и опытного врача. Вот почему мы всегда показываем оригинальную упаковку и серийный номер перед процедурой.",
        en: "Juvederm is one of the world's most clinically studied fillers: over 16 million procedures in 20 years, hundreds of published clinical studies, a confirmed safety profile. But contraindications exist for any injectable.\n\nAbsolute contraindications:\n— pregnancy and breastfeeding;\n— hypersensitivity to hyaluronic acid or lidocaine;\n— active inflammation in the injection zone;\n— active infections (including active herpes, especially for lip zones);\n— autoimmune flare-ups;\n— clotting disorders;\n— active-phase oncology.\n\nRelative contraindications (procedure possible with caution):\n— anticoagulant therapy — requires discussion with your treating doctor;\n— tendency to keloid scarring;\n— recent dental implants (1-month interval);\n— recent laser resurfacing or peel (2-4 week interval).\n\nPossible side effects: swelling (especially lips) — 2-10 days; bruising — 15-20% of cases; injection-site tenderness — 1-2 days; mild asymmetry in the first days due to uneven swelling (normalises by day 10-14). Rare complications: granulomas, infections, vascular events — effectively excluded with original product, certified technique and an experienced doctor. That's why we always show the original packaging and serial number before the procedure.",
      },
      calloutBody: {
        uk: "Гіалуронідаза — страхова система Juvederm. Якщо результат вас не влаштував, якщо препарат мігрував, якщо хтось колись ввів зайве — ми можемо розчинити філер за 24–48 годин. Це перевага, якої не мають постійні біополімери (силікон, акрил), які практично не видаляються.",
        ru: "Гиалуронидаза — страховая система Juvederm. Если результат вас не устроил, если препарат мигрировал, если кто-то когда-то ввёл лишнее — мы можем растворить филлер за 24–48 часов. Это преимущество, которого нет у постоянных биополимеров (силикон, акрил), которые практически не удаляются.",
        en: "Hyaluronidase is Juvederm's insurance system. If you're not happy with the result, if the product has migrated, if someone once injected too much — we can dissolve the filler in 24-48 hours. That's an advantage permanent biopolymers (silicone, acrylic) don't have — they're effectively impossible to remove.",
      },
    },
  ],
  faq: [
    { question: { uk: "Які препарати Juvederm використовуються у GENEVITY?", ru: "Какие препараты Juvederm используются в GENEVITY?", en: "Which Juvederm preparations does GENEVITY use?" },
      answer: { uk: "Ми працюємо з оригінальною лінійкою Juvederm від Allergan Aesthetics: Volbella (для губ, тонких ліній, слізної борозенки), Volift (середня щільність для носогубних складок), Volift Retouch (тонка корекція), Voluma (скульптура скул), Volux (щільний, для підборіддя та кута щелепи), Ultra (класика для середніх зон). Кожен шприц має голографічну мітку і серійний номер, який перевіряємо на сайті Allergan при відкритті упаковки.",
        ru: "Мы работаем с оригинальной линейкой Juvederm от Allergan Aesthetics: Volbella (для губ, тонких линий, слёзной борозды), Volift (средняя плотность для носогубных складок), Volift Retouch (тонкая коррекция), Voluma (скульптура скул), Volux (плотный, для подбородка и угла челюсти), Ultra (классика для средних зон). Каждый шприц имеет голографическую метку и серийный номер, который проверяем на сайте Allergan при открытии упаковки.",
        en: "We work with the original Juvederm line from Allergan Aesthetics: Volbella (for lips, fine lines, tear troughs), Volift (medium density for nasolabial folds), Volift Retouch (fine correction), Voluma (cheekbone sculpting), Volux (dense, for chin and jawline), Ultra (classic for midzones). Every syringe has a holographic mark and serial number, verified on Allergan's site when the packaging is opened." }},
    { question: { uk: "Скільки коштують ін'єкції Juvederm у Дніпрі?", ru: "Сколько стоят инъекции Juvederm в Днепре?", en: "How much do Juvederm injections cost in Dnipro?" },
      answer: { uk: "Ціна — за шприц препарату. Базові лінійки (Volift, Ultra) у середньому доступніші, преміум (Voluma, Volux) — дорожче через щільність і тривалість ефекту. Кількість шприців на процедуру — від 0,5 до 3+ залежно від зон. На консультації лікар складає точний план: який препарат, у якому об'ємі, у яку зону. Жодних «сюрпризів» у рахунку після процедури — фінальна ціна фіксується до першої ін'єкції.",
        ru: "Цена — за шприц препарата. Базовые линейки (Volift, Ultra) в среднем доступнее, премиум (Voluma, Volux) — дороже из-за плотности и длительности эффекта. Количество шприцов на процедуру — от 0,5 до 3+ в зависимости от зон. На консультации врач составляет точный план: какой препарат, в каком объёме, в какую зону. Никаких «сюрпризов» в счёте после процедуры — финальная цена фиксируется до первой инъекции.",
        en: "Price is per syringe. Base lines (Volift, Ultra) are more accessible, premium (Voluma, Volux) more expensive due to density and duration. Session count: 0.5 to 3+ syringes by zones. The doctor builds an exact plan at consultation — product, volume, zone. No billing surprises — the final price is locked before the first injection." }},
    { question: { uk: "Чим Juvederm відрізняється від Restylane чи інших філерів?", ru: "Чем Juvederm отличается от Restylane или других филлеров?", en: "How does Juvederm differ from Restylane or other fillers?" },
      answer: { uk: "Обидва — преміум-філери на основі гіалуронової кислоти від провідних світових виробників. Основні відмінності: Juvederm використовує технології VYCROSS / HYLACROSS з модифікованими поперечними зв'язками, що дає «м'якіше» злиття з тканинами; Restylane використовує технологію NASHA — трохи щільніша структура, більш «скульптурний» результат. На практиці: Juvederm частіше обирають для губ і зон з тонкою шкірою; Restylane — для скульптурної корекції. Обидва препарати однаково безпечні і ефективні — вибір роблять під тканини конкретного пацієнта, а не за «кращістю» бренду.",
        ru: "Оба — премиум-филлеры на основе гиалуроновой кислоты от ведущих мировых производителей. Основные отличия: Juvederm использует технологии VYCROSS / HYLACROSS с модифицированными поперечными связями, что даёт «мягче» слияние с тканями; Restylane использует технологию NASHA — немного более плотная структура, более «скульптурный» результат. На практике: Juvederm чаще выбирают для губ и зон с тонкой кожей; Restylane — для скульптурной коррекции. Оба препарата одинаково безопасны и эффективны — выбор делают под ткани конкретного пациента, а не по «лучшести» бренда.",
        en: "Both are premium hyaluronic-acid fillers from leading global manufacturers. The main differences: Juvederm uses VYCROSS / HYLACROSS technology with modified cross-links, giving a softer tissue fusion; Restylane uses NASHA technology — slightly denser structure, more sculptural result. In practice: Juvederm is more often chosen for lips and thin-skin zones; Restylane for sculptural correction. Both are equally safe and effective — the choice is based on the patient's tissue, not on brand \"superiority\"." }},
    { question: { uk: "Скільки тримається ефект від Juvederm?", ru: "Сколько держится эффект от Juvederm?", en: "How long does Juvederm last?" },
      answer: { uk: "Залежить від конкретного препарату в лінійці і зони введення. Volbella у губах — 6–9 місяців. Volift у носогубних складках — 9–12 місяців. Voluma у щоках і скулах — 12–18 місяців. Volux у підборідді і кута щелепи — 15–24 місяці. У людей з високим метаболізмом (активний спорт, часті перельоти, інтенсивне сонце) ефект розсмоктується на 20–30% швидше.",
        ru: "Зависит от конкретного препарата в линейке и зоны введения. Volbella в губах — 6–9 месяцев. Volift в носогубных складках — 9–12 месяцев. Voluma в щеках и скулах — 12–18 месяцев. Volux в подбородке и угле челюсти — 15–24 месяца. У людей с высоким метаболизмом (активный спорт, частые перелёты, интенсивное солнце) эффект рассасывается на 20–30% быстрее.",
        en: "Depends on the specific preparation and zone. Volbella in lips — 6-9 months. Volift in nasolabial — 9-12 months. Voluma in cheeks and cheekbones — 12-18 months. Volux in chin and jawline — 15-24 months. Active athletes, frequent travellers and those with intense sun exposure absorb fillers 20-30% faster." }},
    { question: { uk: "Чи можна розчинити Juvederm, якщо результат не сподобався?", ru: "Можно ли растворить Juvederm, если результат не понравился?", en: "Can Juvederm be dissolved if I don't like the result?" },
      answer: { uk: "Так, це одна з головних переваг Juvederm і всіх гіалуронових філерів. При потребі ми вводимо гіалуронідазу — фермент, який швидко розщеплює гіалуронову кислоту. Препарат розчиняється за 24–48 годин. Це дозволяє скоригувати результат, якщо ви передумали; прибрати мігрований філер; або повністю видалити філер, якщо ви більше не хочете його зберігати. Рідкісна ситуація, але важлива страховка.",
        ru: "Да, это одно из главных преимуществ Juvederm и всех гиалуроновых филлеров. При необходимости мы вводим гиалуронидазу — фермент, быстро расщепляющий гиалуроновую кислоту. Препарат растворяется за 24–48 часов. Это позволяет скорректировать результат, если вы передумали; убрать мигрированный филлер; или полностью удалить филлер, если вы больше не хотите его сохранять. Редкая ситуация, но важная страховка.",
        en: "Yes — it's one of the key advantages of Juvederm and all hyaluronic fillers. When needed we inject hyaluronidase, an enzyme that rapidly breaks down hyaluronic acid. The product dissolves in 24-48 hours. This lets us correct a result you've changed your mind about, remove migrated filler, or fully remove it if you no longer want to keep it. A rare situation but an important safeguard." }},
    { question: { uk: "Як підготуватись до процедури Juvederm?", ru: "Как подготовиться к процедуре Juvederm?", en: "How do I prepare for a Juvederm session?" },
      answer: { uk: "За 3–5 днів до процедури: відмова від алкоголю, аспірину і добавок, що розріджують кров (омега-3 у високих дозах, вітамін E, гінкго) — якщо немає медичних протипоказань. Не планувати процедуру на день перед важливою подією: набряки у губах можуть триматись до тижня, синяки — 4–7 днів. Якщо у вас активний герпес — повідомте лікаря, процедуру для губ перенесемо до повної ремісії. Прийти з очищеною шкірою, без макіяжу.",
        ru: "За 3–5 дней до процедуры: отказ от алкоголя, аспирина и добавок, разжижающих кровь (омега-3 в высоких дозах, витамин E, гинкго) — если нет медицинских противопоказаний. Не планируйте процедуру на день перед важным событием: отёки в губах могут держаться до недели, синяки — 4–7 дней. Если у вас активный герпес — сообщите врачу, процедуру для губ перенесём до полной ремиссии. Прийти с очищенной кожей, без макияжа.",
        en: "3-5 days before: stop alcohol, aspirin and blood thinners (high-dose omega-3, vitamin E, ginkgo) unless medically required. Don't book the procedure right before an important event — lip swelling can last up to a week, bruises 4-7 days. If you have active herpes, tell the doctor; lip treatment is postponed until full remission. Arrive with cleansed skin, no makeup." }},
  ],
};

const polyphil: ServiceCopy = {
  slug: "polyphil",
  summary: {
    uk: "PolyPhil у GENEVITY — ін'єкційний препарат нового покоління на основі полінуклеотидів і гіалуронової кислоти. Гібрид між Rejuran і біоревіталізацією: водночас регенерує шкіру на клітинному рівні й забезпечує глибоке зволоження. Унікальний інструмент для пацієнтів, які шукають комплексного ефекту за один курс.",
    ru: "PolyPhil в GENEVITY — инъекционный препарат нового поколения на основе полинуклеотидов и гиалуроновой кислоты. Гибрид между Rejuran и биоревитализацией: одновременно регенерирует кожу на клеточном уровне и обеспечивает глубокое увлажнение. Уникальный инструмент для пациентов, которые ищут комплексного эффекта за один курс.",
    en: "PolyPhil at GENEVITY — a new-generation injectable combining polynucleotides and hyaluronic acid. A hybrid between Rejuran and biorevitalisation: it simultaneously regenerates the skin at the cellular level and delivers deep hydration. A unique tool for patients seeking a complete effect from a single course.",
  },
  sections: [
    {
      heading: { uk: "Що таке PolyPhil", ru: "Что такое PolyPhil", en: "What PolyPhil is" },
      body: {
        uk: "PolyPhil — ін'єкційний препарат, який поєднує два активні компоненти: полінуклеотиди (PN) — короткі фрагменти ДНК, отримані з лосося, потужні стимулятори регенерації; і стабілізовану гіалуронову кислоту — базовий компонент біоревіталізаторів, що забезпечує зволоження і об'єм. Поєднання дає результат двох процедур за один сеанс: клітинна регенерація + зволоження.\n\nПрепарат розроблений у Південній Кореї як відповідь на запит пацієнтів «хочу і Rejuran, і біоревіталізацію». На ринку України PolyPhil позиціонується як преміум-рішення для комплексного омолодження без потреби складати окремі курси. У GENEVITY ми обираємо PolyPhil, коли пацієнт приходить з багаторівневими запитами: суха шкіра + постакне + тонкі лінії; зневоднення + фотостаріння; чи коли потрібно скоротити час реабілітації, поєднавши процедури.\n\nPolyPhil випускається у двох варіантах: базовий (для обличчя, шиї, декольте) і PolyPhil Eyes (для чутливої зони навколо очей, з меншою щільністю і лідокаїном). Обираємо препарат під зону обробки і цілі пацієнта.",
        ru: "PolyPhil — инъекционный препарат, который объединяет два активных компонента: полинуклеотиды (ПН) — короткие фрагменты ДНК, полученные из лосося, мощные стимуляторы регенерации; и стабилизированную гиалуроновую кислоту — базовый компонент биоревитализаторов, обеспечивающий увлажнение и объём. Объединение даёт результат двух процедур за один сеанс: клеточная регенерация + увлажнение.\n\nПрепарат разработан в Южной Корее как ответ на запрос пациентов «хочу и Rejuran, и биоревитализацию». На рынке Украины PolyPhil позиционируется как премиум-решение для комплексного омоложения без необходимости составлять отдельные курсы. В GENEVITY мы выбираем PolyPhil, когда пациент приходит с многоуровневыми запросами: сухая кожа + постакне + тонкие линии; обезвоживание + фотостарение; или когда нужно сократить время реабилитации, объединив процедуры.\n\nPolyPhil выпускается в двух вариантах: базовый (для лица, шеи, декольте) и PolyPhil Eyes (для чувствительной зоны вокруг глаз, с меньшей плотностью и лидокаином). Выбираем препарат под зону обработки и цели пациента.",
        en: "PolyPhil is an injectable combining two active components: polynucleotides (PN) — short DNA fragments derived from salmon, powerful regenerative stimulators; and stabilised hyaluronic acid — the base component of biorevitalisers, providing hydration and volume. The combination delivers the result of two procedures in a single session: cellular regeneration + hydration.\n\nThe preparation was developed in South Korea in response to patients asking for \"both Rejuran and biorevitalisation\". In the Ukrainian market, PolyPhil is positioned as a premium solution for comprehensive rejuvenation without needing separate courses. At GENEVITY we choose PolyPhil when a patient presents multi-level concerns: dry skin + post-acne + fine lines; dehydration + photo-ageing; or when we want to compress downtime by combining procedures.\n\nPolyPhil comes in two variants: base (for face, neck, décolleté) and PolyPhil Eyes (for the sensitive eye area, with lower density and lidocaine). We select the preparation based on treatment area and patient goals.",
      },
      calloutBody: {
        uk: "PolyPhil — це не «Rejuran + біоревіталізація за меншу ціну». Це самостійний препарат з власним профілем дії. Переваг не завжди більше, ніж у двох окремих курсів, але зручність — значно вища. Вибір під ваш випадок — на консультації.",
        ru: "PolyPhil — это не «Rejuran + биоревитализация за меньшую цену». Это самостоятельный препарат со своим профилем действия. Преимуществ не всегда больше, чем у двух отдельных курсов, но удобство — значительно выше. Выбор под ваш случай — на консультации.",
        en: "PolyPhil isn't \"Rejuran + biorevitalisation at a lower price\". It's an independent preparation with its own action profile. Benefits aren't always greater than two separate courses, but convenience is significantly higher. The right choice for your case — at consultation.",
      },
    },
    {
      heading: { uk: "Показання і переваги", ru: "Показания и преимущества", en: "Indications and advantages" },
      body: {
        uk: "PolyPhil обирають пацієнти з комплексними запитами. Основні показання:\n\n— зневоднена шкіра з втратою пружності + дрібні зморшки одночасно;\n— фотостаріння у середньому віці (35–50 років), коли потрібна і регенерація, і зволоження;\n— підготовка шкіри до сезону активного сонця — курс PolyPhil навесні укріплює шкіру перед літом;\n— період відновлення після хвороб, стресу, тривалих перельотів;\n— постакне у поєднанні зі зневодненою шкірою;\n— зона навколо очей (PolyPhil Eyes) — сухість, «курячі лапки», потоншена шкіра повік;\n— пацієнти, які хочуть отримати результат за меншу кількість візитів: замість 8 процедур (4 Rejuran + 4 біоревіталізація) можна зробити 3–4 PolyPhil.\n\nПереваги PolyPhil:\n— Подвійна дія. Одна ін'єкція дає стимуляцію клітинної регенерації + глибоке зволоження.\n— Скорочення кількості процедур. Ефект 2-в-1 економить час і відвідування.\n— Швидший видимий результат, ніж у чистого Rejuran. Завдяки гіалуроновій кислоті свіжість шкіри помітна вже у перші дні — без чекання 2 тижнів.\n— Триваліший ефект, ніж у чистої біоревіталізації. Полінуклеотиди стимулюють тривалу регенерацію — результат тримається 9–12 місяців.\n— Хороша переносимість. Препарат рідко викликає побічні ефекти, не вимагає складної реабілітації.\n\nОбмеження методу: PolyPhil дорожчий за чисту біоревіталізацію або окремий Rejuran через комплексний склад; для пацієнтів з вузькою задачею (тільки зволоження чи тільки регенерація) раціональніше використовувати «чистий» препарат.",
        ru: "PolyPhil выбирают пациенты с комплексными запросами. Основные показания:\n\n— обезвоженная кожа с потерей упругости + мелкие морщины одновременно;\n— фотостарение в среднем возрасте (35–50 лет), когда нужна и регенерация, и увлажнение;\n— подготовка кожи к сезону активного солнца — курс PolyPhil весной укрепляет кожу перед летом;\n— период восстановления после болезней, стресса, длительных перелётов;\n— постакне в сочетании с обезвоженной кожей;\n— зона вокруг глаз (PolyPhil Eyes) — сухость, «гусиные лапки», утончённая кожа век;\n— пациенты, которые хотят получить результат за меньшее количество визитов: вместо 8 процедур (4 Rejuran + 4 биоревитализация) можно сделать 3–4 PolyPhil.\n\nПреимущества PolyPhil:\n— Двойное действие. Одна инъекция даёт стимуляцию клеточной регенерации + глубокое увлажнение.\n— Сокращение количества процедур. Эффект 2-в-1 экономит время и посещения.\n— Более быстрый видимый результат, чем у чистого Rejuran. Благодаря гиалуроновой кислоте свежесть кожи заметна уже в первые дни — без ожидания 2 недель.\n— Более длительный эффект, чем у чистой биоревитализации. Полинуклеотиды стимулируют длительную регенерацию — результат держится 9–12 месяцев.\n— Хорошая переносимость. Препарат редко вызывает побочные эффекты, не требует сложной реабилитации.\n\nОграничения метода: PolyPhil дороже чистой биоревитализации или отдельного Rejuran из-за комплексного состава; для пациентов с узкой задачей (только увлажнение или только регенерация) рациональнее использовать «чистый» препарат.",
        en: "PolyPhil is chosen by patients with complex requests.\n\nIndications:\n— dehydrated skin with loss of firmness + fine lines simultaneously;\n— photo-ageing in middle age (35-50) when both regeneration and hydration are needed;\n— skin preparation for the sun season — a PolyPhil course in spring strengthens the skin before summer;\n— recovery after illness, stress or long travel;\n— post-acne combined with dehydrated skin;\n— eye area (PolyPhil Eyes) — dryness, crow's feet, thinned eyelid skin;\n— patients who want results in fewer visits: instead of 8 sessions (4 Rejuran + 4 biorevitalisation) they can do 3-4 PolyPhil.\n\nAdvantages:\n— Dual action. A single injection delivers cellular regeneration + deep hydration.\n— Fewer sessions. The 2-in-1 effect saves time and visits.\n— Faster visible result than pure Rejuran. Thanks to the hyaluronic acid, freshness is noticeable within days — no 2-week wait.\n— Longer effect than pure biorevitalisation. The polynucleotides drive long-term regeneration — the result holds for 9-12 months.\n— Good tolerance. The preparation rarely causes side effects and doesn't demand complex recovery.\n\nLimitations: PolyPhil costs more than pure biorevitalisation or standalone Rejuran because of the combined formulation. For patients with a narrow concern (hydration only, or regeneration only), a \"pure\" product is more rational.",
      },
      calloutBody: {
        uk: "Ми не намагаємось «продати» PolyPhil кожному пацієнту. Часто для 28-річного клієнта краще класична біоревіталізація; для 45-річного з постакне — чистий Rejuran. PolyPhil потужний там, де є одразу кілька «фронтів роботи». Вибір інструменту — частина лікарської роботи, не маркетинг.",
        ru: "Мы не пытаемся «продать» PolyPhil каждому пациенту. Часто для 28-летнего клиента лучше классическая биоревитализация; для 45-летнего с постакне — чистый Rejuran. PolyPhil мощен там, где есть сразу несколько «фронтов работы». Выбор инструмента — часть врачебной работы, не маркетинг.",
        en: "We don't try to \"sell\" PolyPhil to every patient. For a 28-year-old, classical biorevitalisation is often the better choice; for a 45-year-old with post-acne, pure Rejuran. PolyPhil is powerful where multiple \"fronts\" need work simultaneously. Tool selection is clinical, not marketing.",
      },
    },
    {
      heading: { uk: "Процедура і результати", ru: "Процедура и результаты", en: "Procedure and results" },
      body: {
        uk: "Процедура PolyPhil триває 30–45 хвилин. Етапи:\n\n1. Консультація. Лікар оцінює стан шкіри, обговорює ваші очікування, пояснює різницю між PolyPhil, Rejuran і класичною біоревіталізацією. Разом обираємо, який препарат і в якому об'ємі оптимальний для вашої задачі.\n\n2. Підготовка. Демакіяж, обробка антисептиком, аплікаційна анестезія лідокаїновим кремом на 15–20 хвилин. PolyPhil Eyes містить лідокаїн у препараті — додаткова анестезія при обробці зони навколо очей часто не потрібна.\n\n3. Техніка введення. Аналогічно Rejuran — мануальні ін'єкції тонкою голкою за мезотерапевтичною технікою. На 1 мл препарату припадає 40–60 точок. Для зони навколо очей (PolyPhil Eyes) використовуємо канюлю — знижує ризик синяків і пошкодження судин.\n\n4. Завершення. Нанесення заспокійливої маски. Догляд: 24 години без сауни, басейну, спорту, масажу; 2 тижні активного SPF; м'яке очищення шкіри перші 3 дні.\n\n5. Курс. Оптимальний курс — 3–4 процедури з інтервалом 3–4 тижні. Підтримка — 1 процедура на 6 місяців.\n\nРезультати за часовою шкалою:\n— Перший тиждень: шкіра свіжіша, пружніша — ефект зволоження помітний швидко завдяки гіалуроновій кислоті;\n— 3–4 тиждень: видиме ущільнення шкіри, зменшення тонких зморшок;\n— 2–3 місяць: повний ефект після курсу — стабільна пружність, покращена текстура, довгостроковий «світіння»;\n— 9–12 місяців: ефект тримається, поступово поступово зменшується. Підтримка однією процедурою повертає результат у повному об'ємі.",
        ru: "Процедура PolyPhil длится 30–45 минут. Этапы:\n\n1. Консультация. Врач оценивает состояние кожи, обсуждает ваши ожидания, объясняет разницу между PolyPhil, Rejuran и классической биоревитализацией. Вместе выбираем, какой препарат и в каком объёме оптимален для вашей задачи.\n\n2. Подготовка. Демакияж, обработка антисептиком, аппликационная анестезия лидокаиновым кремом на 15–20 минут. PolyPhil Eyes содержит лидокаин в препарате — дополнительная анестезия при обработке зоны вокруг глаз часто не требуется.\n\n3. Техника введения. Аналогично Rejuran — мануальные инъекции тонкой иглой по мезотерапевтической технике. На 1 мл препарата приходится 40–60 точек. Для зоны вокруг глаз (PolyPhil Eyes) используем канюлю — снижает риск синяков и повреждения сосудов.\n\n4. Завершение. Нанесение успокаивающей маски. Уход: 24 часа без сауны, бассейна, спорта, массажа; 2 недели активного SPF; мягкое очищение кожи первые 3 дня.\n\n5. Курс. Оптимальный курс — 3–4 процедуры с интервалом 3–4 недели. Поддержка — 1 процедура в 6 месяцев.\n\nРезультаты по временной шкале:\n— Первая неделя: кожа свежее, упруже — эффект увлажнения заметен быстро благодаря гиалуроновой кислоте;\n— 3–4 неделя: видимое уплотнение кожи, уменьшение тонких морщин;\n— 2–3 месяц: полный эффект после курса — стабильная упругость, улучшенная текстура, долгосрочное «свечение»;\n— 9–12 месяцев: эффект держится, постепенно уменьшается. Поддержка одной процедурой возвращает результат в полном объёме.",
        en: "A PolyPhil session takes 30-45 minutes.\n\n1. Consultation. The doctor evaluates the skin, discusses your expectations and explains the difference between PolyPhil, Rejuran and classical biorevitalisation. Together we choose the optimal preparation and volume for your concern.\n\n2. Preparation. Makeup removal, antiseptic, topical lidocaine cream for 15-20 minutes. PolyPhil Eyes contains lidocaine in the preparation itself — extra anaesthesia around the eyes often isn't needed.\n\n3. Technique. Similar to Rejuran — manual injections with a fine needle in a mesotherapy technique. 1 ml of product covers 40-60 points. For the eye area (PolyPhil Eyes) we use a cannula, reducing bruising and vascular risk.\n\n4. Finish. Calming mask. Aftercare: 24 hours without sauna, pool, sport, massage; 2 weeks of active SPF; gentle cleansing for the first 3 days.\n\n5. Course. Optimal: 3-4 sessions with 3-4 week intervals. Maintenance: one session every 6 months.\n\nResults timeline:\n— Week 1: fresher, firmer skin — the hydration effect is visible quickly thanks to the hyaluronic acid;\n— Weeks 3-4: visible skin firming, fine-line softening;\n— Months 2-3: full post-course effect — stable firmness, improved texture, long-term glow;\n— 9-12 months: effect holds, gradually diminishing. A single maintenance session restores the full result.",
      },
      calloutBody: {
        uk: "Якщо порівнювати з чистим Rejuran: PolyPhil менш болісний і з швидшою реакцією шкіри. Якщо з чистою біоревіталізацією: PolyPhil глибше і довше. Це «золота середина» для пацієнтів, які хочуть результат, а не експеримент з процедурами.",
        ru: "Если сравнивать с чистым Rejuran: PolyPhil менее болезнен и с более быстрой реакцией кожи. Если с чистой биоревитализацией: PolyPhil глубже и длительнее. Это «золотая середина» для пациентов, которые хотят результат, а не эксперимент с процедурами.",
        en: "Compared with pure Rejuran: PolyPhil is less uncomfortable and the skin responds faster. Compared with pure biorevitalisation: PolyPhil is deeper and longer-lasting. It's the middle path for patients who want results rather than an experiment with procedures.",
      },
    },
    {
      heading: { uk: "Протипоказання, безпека, вартість", ru: "Противопоказания, безопасность, стоимость", en: "Contraindications, safety, cost" },
      body: {
        uk: "Протипоказання до PolyPhil — стандартні для ін'єкційних процедур із полінуклеотидами:\n— вагітність і грудне вигодовування;\n— гіперчутливість до гіалуронової кислоти, полінуклеотидів або лідокаїну;\n— алергія на рибні продукти (полінуклеотиди виділяються з ДНК лосося);\n— активні запальні процеси або інфекції у зоні ін'єкції;\n— аутоімунні захворювання у фазі загострення;\n— онкологічні захворювання в активній фазі;\n— порушення згортання крові;\n— прийом антикоагулянтів.\n\nПобічні ефекти — мінімальні:\n— почервоніння у місцях ін'єкцій (до 6 годин);\n— набряклість (1–2 доби);\n— невеликі синяки (у 10–15% випадків, 4–7 днів);\n— шкірне лущення на 3–5 день як нормальна ознака регенерації;\n— дуже рідко — алергічні реакції (при неперевіреному алергічному анамнезі).\n\nВартість PolyPhil у Дніпрі. PolyPhil — преміум-препарат з вищою ціною, ніж чиста біоревіталізація, але нижчою, ніж сукупна вартість двох окремих курсів (Rejuran + біоревіталізація). На консультації лікар розраховує точну вартість вашого курсу. Базова ціна однієї процедури вказана у прайсі; курс із 3–4 процедур пропонуємо за зниженою ціною за сеанс.",
        ru: "Противопоказания к PolyPhil — стандартные для инъекционных процедур с полинуклеотидами:\n— беременность и грудное вскармливание;\n— гиперчувствительность к гиалуроновой кислоте, полинуклеотидам или лидокаину;\n— аллергия на рыбные продукты (полинуклеотиды выделяются из ДНК лосося);\n— активные воспалительные процессы или инфекции в зоне инъекции;\n— аутоиммунные заболевания в фазе обострения;\n— онкологические заболевания в активной фазе;\n— нарушения свёртываемости крови;\n— приём антикоагулянтов.\n\nПобочные эффекты — минимальные:\n— покраснение в местах инъекций (до 6 часов);\n— отёчность (1–2 суток);\n— небольшие синяки (в 10–15% случаев, 4–7 дней);\n— кожное шелушение на 3–5 день как нормальный признак регенерации;\n— очень редко — аллергические реакции (при непроверенном аллергическом анамнезе).\n\nСтоимость PolyPhil в Днепре. PolyPhil — премиум-препарат с более высокой ценой, чем чистая биоревитализация, но ниже суммарной стоимости двух отдельных курсов (Rejuran + биоревитализация). На консультации врач рассчитывает точную стоимость вашего курса. Базовая цена одной процедуры указана в прайсе; курс из 3–4 процедур предлагаем по сниженной цене за сеанс.",
        en: "Contraindications are standard for polynucleotide-based injectables:\n— pregnancy and breastfeeding;\n— hypersensitivity to hyaluronic acid, polynucleotides or lidocaine;\n— allergy to fish products (polynucleotides are derived from salmon DNA);\n— active inflammation or infection in the injection zone;\n— autoimmune flare-ups;\n— active-phase oncology;\n— clotting disorders;\n— anticoagulant therapy.\n\nSide effects are minimal: redness at injection sites (up to 6 hours); swelling (1-2 days); small bruises (10-15% of cases, 4-7 days); light skin peeling at day 3-5 as a normal sign of regeneration; very rarely — allergic reactions (in cases of unchecked allergy history).\n\nPolyPhil cost in Dnipro. PolyPhil is a premium preparation priced higher than pure biorevitalisation but lower than the combined cost of two separate courses (Rejuran + biorevitalisation). At consultation the doctor calculates the exact course cost. Base per-session pricing is on the list; a 3-4 session course is offered at a reduced per-session rate.",
      },
      calloutBody: {
        uk: "PolyPhil — нова процедура в Україні (ринок з 2021). Клінічних даних поки менше, ніж по Rejuran, але препарат сертифікований, безпечний і вже довів свою ефективність у Південній Кореї. Ми впроваджуємо його як комплексне рішення для пацієнтів, яким потрібен результат «два в одному».",
        ru: "PolyPhil — новая процедура в Украине (рынок с 2021). Клинических данных пока меньше, чем по Rejuran, но препарат сертифицирован, безопасен и уже доказал свою эффективность в Южной Корее. Мы внедряем его как комплексное решение для пациентов, которым нужен результат «два в одном».",
        en: "PolyPhil is a newer procedure in Ukraine (on the market since 2021). Clinical data is less extensive than for Rejuran, but the preparation is certified, safe, and has already proven effective in South Korea. We adopt it as a complex solution for patients who want a \"two-in-one\" result.",
      },
    },
  ],
  faq: [
    { question: { uk: "Скільки коштує процедура PolyPhil у Дніпрі?", ru: "Сколько стоит процедура PolyPhil в Днепре?", en: "How much does PolyPhil cost in Dnipro?" },
      answer: { uk: "Вартість PolyPhil вища, ніж чистої біоревіталізації чи окремого Rejuran, оскільки препарат поєднує дві активні складові. Ціна залежить від препарату (базовий PolyPhil чи PolyPhil Eyes), об'єму (1 мл, 2 мл) і площі обробки. У GENEVITY базова вартість однієї процедури зазначена у прайсі; курс із 3–4 процедур пропонуємо за зниженою ціною. Важливо: PolyPhil коштує менше, ніж сума двох окремих курсів (Rejuran + біоревіталізація) — це раціональний вибір для комплексних задач.",
        ru: "Стоимость PolyPhil выше, чем чистой биоревитализации или отдельного Rejuran, поскольку препарат сочетает две активные составляющие. Цена зависит от препарата (базовый PolyPhil или PolyPhil Eyes), объёма (1 мл, 2 мл) и площади обработки. В GENEVITY базовая стоимость одной процедуры указана в прайсе; курс из 3–4 процедур предлагаем по сниженной цене. Важно: PolyPhil стоит меньше, чем сумма двух отдельных курсов (Rejuran + биоревитализация) — это рациональный выбор для комплексных задач.",
        en: "PolyPhil costs more than pure biorevitalisation or standalone Rejuran because the preparation combines two active components. Price depends on the preparation (base PolyPhil or PolyPhil Eyes), volume (1 ml, 2 ml) and area. GENEVITY's base per-session pricing is on the list; a 3-4 session course is offered at a reduced rate. Importantly: PolyPhil costs less than the combined total of two separate courses (Rejuran + biorevitalisation) — it's a rational choice for complex concerns." }},
    { question: { uk: "У чому різниця між PolyPhil і Rejuran?", ru: "В чём разница между PolyPhil и Rejuran?", en: "What's the difference between PolyPhil and Rejuran?" },
      answer: { uk: "Rejuran — чисто полінуклеотидний препарат: глибока регенерація, але помірне зволоження, повільний видимий результат (2–3 місяці). PolyPhil — поєднання полінуклеотидів і гіалуронової кислоти: та ж регенерація + додатково глибоке зволоження, швидший видимий ефект (2 тижні). Обидва працюють однаково з тривалістю ефекту, обидва вимагають курсу з 3–4 процедур. Вибір — за задачею: чиста регенерація (постакне) — Rejuran; комплексне омолодження зі зволоженням — PolyPhil.",
        ru: "Rejuran — чисто полинуклеотидный препарат: глубокая регенерация, но умеренное увлажнение, медленный видимый результат (2–3 месяца). PolyPhil — сочетание полинуклеотидов и гиалуроновой кислоты: та же регенерация + дополнительно глубокое увлажнение, более быстрый видимый эффект (2 недели). Оба работают одинаково с длительностью эффекта, оба требуют курса из 3–4 процедур. Выбор — по задаче: чистая регенерация (постакне) — Rejuran; комплексное омоложение с увлажнением — PolyPhil.",
        en: "Rejuran is a pure polynucleotide preparation: deep regeneration but moderate hydration, slow visible result (2-3 months). PolyPhil combines polynucleotides and hyaluronic acid: the same regeneration plus deep hydration, faster visible effect (2 weeks). Both deliver similar result duration, both need a 3-4 session course. The choice depends on the goal: pure regeneration (post-acne) — Rejuran; complex rejuvenation with hydration — PolyPhil." }},
    { question: { uk: "Чи підходить PolyPhil для зони навколо очей?", ru: "Подходит ли PolyPhil для зоны вокруг глаз?", en: "Is PolyPhil suitable for the eye area?" },
      answer: { uk: "Так, для цього є спеціальний препарат PolyPhil Eyes — з меншою щільністю і лідокаїном у складі, що робить його оптимальним для чутливої шкіри повік. Результат — зменшення сухості, «курячих лапок», покращення якості шкіри навколо очей. Вводиться канюлею, що мінімізує ризик синяків і пошкодження судин у цій делікатній зоні.",
        ru: "Да, для этого есть специальный препарат PolyPhil Eyes — с меньшей плотностью и лидокаином в составе, что делает его оптимальным для чувствительной кожи век. Результат — уменьшение сухости, «гусиных лапок», улучшение качества кожи вокруг глаз. Вводится канюлей, что минимизирует риск синяков и повреждения сосудов в этой деликатной зоне.",
        en: "Yes — there's a dedicated PolyPhil Eyes preparation, with lower density and lidocaine in the formulation, making it optimal for sensitive eyelid skin. The result: reduced dryness, softened crow's feet, improved eye-area skin quality. Delivered via cannula, minimising the risk of bruising and vascular injury in this delicate zone." }},
    { question: { uk: "Через скільки видно результат від PolyPhil?", ru: "Через сколько виден результат от PolyPhil?", en: "When are PolyPhil results visible?" },
      answer: { uk: "Перший ефект свіжості і зволоження — через тиждень після першої процедури (завдяки гіалуроновій кислоті у складі). Помітне ущільнення шкіри — через 3–4 тижні. Повний ефект після курсу (3–4 процедури) — через 2–3 місяці. Це один з швидших серед регенеративних препаратів — саме завдяки комбінації з гіалуронкою.",
        ru: "Первый эффект свежести и увлажнения — через неделю после первой процедуры (благодаря гиалуроновой кислоте в составе). Заметное уплотнение кожи — через 3–4 недели. Полный эффект после курса (3–4 процедуры) — через 2–3 месяца. Это один из более быстрых среди регенеративных препаратов — именно благодаря комбинации с гиалуронкой.",
        en: "First freshness and hydration effect — within a week of the first session (thanks to the hyaluronic acid). Noticeable firming — at 3-4 weeks. Full effect after a 3-4 session course — at 2-3 months. This is one of the faster regenerative preparations, precisely because of the hyaluronic-acid combination." }},
    { question: { uk: "Чи можна поєднувати PolyPhil з іншими процедурами?", ru: "Можно ли сочетать PolyPhil с другими процедурами?", en: "Can PolyPhil be combined with other procedures?" },
      answer: { uk: "Так, PolyPhil чудово поєднується з більшістю процедур. Класичні пари: PolyPhil + ботулінотерапія (перший для якості шкіри, другий для зморшок — інтервал 1–2 тижні); PolyPhil + філери (об'єм від філерів, якість шкіри від PolyPhil); PolyPhil + апаратні процедури (HydraFacial, EXION, Ultraformer) з інтервалом 2 тижні. Не поєднуємо з Rejuran чи чистою біоревіталізацією в один курс — це надлишкове дублювання.",
        ru: "Да, PolyPhil прекрасно сочетается с большинством процедур. Классические пары: PolyPhil + ботулинотерапия (первый для качества кожи, второй для морщин — интервал 1–2 недели); PolyPhil + филлеры (объём от филлеров, качество кожи от PolyPhil); PolyPhil + аппаратные процедуры (HydraFacial, EXION, Ultraformer) с интервалом 2 недели. Не сочетаем с Rejuran или чистой биоревитализацией в один курс — это избыточное дублирование.",
        en: "Yes — PolyPhil combines well with most procedures. Classic pairings: PolyPhil + botulinum (PolyPhil for skin quality, botulinum for lines — 1-2 week interval); PolyPhil + fillers (volume from fillers, skin quality from PolyPhil); PolyPhil + apparatus (HydraFacial, EXION, Ultraformer) with 2-week intervals. We don't combine it with Rejuran or pure biorevitalisation in the same course — that would be redundant duplication." }},
    { question: { uk: "Чи болісна процедура PolyPhil?", ru: "Болезненна ли процедура PolyPhil?", en: "Is PolyPhil painful?" },
      answer: { uk: "Менш болісна, ніж Rejuran, завдяки гіалуроновій кислоті у складі — вона полегшує розподіл препарату у тканинах. Базова PolyPhil вимагає аплікаційну анестезію (лідокаїновий крем на 15–20 хвилин). PolyPhil Eyes вже містить лідокаїн — додаткова анестезія зазвичай не потрібна. Більшість пацієнтів оцінюють дискомфорт на 3–4 з 10, що помітно комфортніше за Rejuran.",
        ru: "Менее болезненна, чем Rejuran, благодаря гиалуроновой кислоте в составе — она облегчает распределение препарата в тканях. Базовая PolyPhil требует аппликационную анестезию (лидокаиновый крем на 15–20 минут). PolyPhil Eyes уже содержит лидокаин — дополнительная анестезия обычно не требуется. Большинство пациентов оценивают дискомфорт на 3–4 из 10, что заметно комфортнее Rejuran.",
        en: "Less uncomfortable than Rejuran, thanks to the hyaluronic acid in the formulation — it helps the product distribute in tissue. Base PolyPhil requires topical anaesthesia (lidocaine cream for 15-20 minutes). PolyPhil Eyes already contains lidocaine — additional anaesthesia is usually not needed. Most patients rate discomfort at 3-4 out of 10 — noticeably more comfortable than Rejuran." }},
  ],
};

async function applyService(copy: ServiceCopy) {
  const svc = await sql`SELECT id FROM services WHERE slug = ${copy.slug} LIMIT 1`;
  if (!svc[0]) { console.error(`✗ ${copy.slug} not found`); return; }
  const id = svc[0].id as string;
  await sql`UPDATE services SET summary_uk=${copy.summary.uk}, summary_ru=${copy.summary.ru}, summary_en=${copy.summary.en} WHERE id=${id}`;
  await sql`DELETE FROM content_sections WHERE owner_type='service' AND owner_id=${id}`;
  await sql`DELETE FROM faq_items WHERE owner_type='service' AND owner_id=${id}`;
  const sectionIds: string[] = [];
  for (let i = 0; i < copy.sections.length; i++) {
    const s = copy.sections[i]; const sid = randomUUID(); sectionIds.push(sid);
    const data = { heading: s.heading, body: s.body, calloutBody: s.calloutBody, heroImage: null };
    await sql`INSERT INTO content_sections (id, owner_type, owner_id, sort_order, section_type, data) VALUES (${sid}, 'service', ${id}, ${i}, 'richText'::section_type, ${JSON.stringify(data)}::jsonb)`;
  }
  for (let i = 0; i < copy.faq.length; i++) {
    const f = copy.faq[i];
    await sql`INSERT INTO faq_items (owner_type, owner_id, sort_order, question_uk, question_ru, question_en, answer_uk, answer_ru, answer_en) VALUES ('service', ${id}, ${i}, ${f.question.uk}, ${f.question.ru}, ${f.question.en}, ${f.answer.uk}, ${f.answer.ru}, ${f.answer.en})`;
  }
  const order = [...sectionIds.map((s) => `section:${s}`), "faq", "doctors", "equipment", "relatedServices", "finalCTA"];
  await sql`UPDATE services SET block_order=${order} WHERE id=${id}`;
  console.log(`✓ ${copy.slug} — ${copy.sections.length} sections, ${copy.faq.length} FAQs`);
}

async function main() {
  for (const c of [juvederm, polyphil]) await applyService(c);
  await sql.end();
  console.log("\nV2 DONE — all 10 injectable-cosmetology services have TZ-aligned copy. Reply \"continue to V3\" for apparatus cosmetology (EMFACE, EMSCULPT NEO, Ultraformer, HydraFacial, and others).");
}
main().catch((e) => { console.error(e); process.exit(1); });
