/** TZ #12 — the six apparatus-cosmetology pages. */
import { EQ, COSMETOLOGISTS, type ServiceSeed } from "./lib";

export const apparatus: ServiceSeed[] = [
  // ─── 1. SMAS-ЛІФТИНГ ──────────────────────────────────────────────────────
  {
    slug: "smas-lifting",
    meta: {
      category: "apparatus-cosmetology",
      h1: { uk: "SMAS-ліфтинг в Дніпрі", ru: "SMAS-лифтинг в Днепре", en: "SMAS lifting in Dnipro" },
      seoTitle: {
        uk: "SMAS-ліфтинг в Дніпрі - Cмас ліфтинг",
        ru: "SMAS-лифтинг в Днепре - Смас лифтинг",
        en: "SMAS Lifting in Dnipro - SMAS lifting price",
      },
      seoDesc: {
        uk: "Апаратний SMAS ліфтинг в Дніпрі 🤍 GENEVITY. Доступні ціни на ультразвуковий СМАС ліфтінг 💫 Ефект без операцій.",
        ru: "Аппаратный SMAS лифтинг в Днепре 🤍 GENEVITY. Доступные цены на ультразвуковой SMAS лифтинг 💫 Эффект без операций.",
        en: "Hardware SMAS lifting in Dnipro 🤍 GENEVITY. Available prices on ultrasonic SMAS lifting 💫 Effect without surgery.",
      },
    },
    title: { uk: "SMAS-ліфтинг", ru: "SMAS-лифтинг", en: "SMAS Lifting" },
    summary: {
      uk: "Апаратний SMAS-ліфтинг у GENEVITY на Ultraformer MPT: сфокусований ультразвук ущільнює м'язово-апоневротичний шар на глибині 4,5 мм і повертає чіткість овалу без розрізів і реабілітації.",
      ru: "Аппаратный SMAS-лифтинг в GENEVITY на Ultraformer MPT: сфокусированный ультразвук уплотняет мышечно-апоневротический слой на глубине 4,5 мм и возвращает чёткость овала без разрезов и реабилитации.",
      en: "Hardware SMAS lifting at GENEVITY on the Ultraformer MPT: focused ultrasound tightens the musculo-aponeurotic layer at a depth of 4.5 mm and restores a defined jawline without incisions or downtime.",
    },
    procedureLength: { uk: "60-90 хвилин", ru: "60-90 минут", en: "60-90 minutes" },
    effectDuration: { uk: "12-18 місяців", ru: "12-18 месяцев", en: "12-18 months" },
    sessionsRecommended: { uk: "1 процедура, повтор через рік", ru: "1 процедура, повтор через год", en: "1 session, repeated after a year" },
    related: ["ultraformer-mpt", "rf-lifting", "emface", "volnewmer"],
    doctors: COSMETOLOGISTS,
    equipment: [EQ.ULTRAFORMER_MPT],
    sections: [
      {
        type: "richText",
        heading: { uk: "Що таке SMAS-ліфтинг", ru: "Что такое SMAS-лифтинг", en: "What SMAS lifting is" },
        body: {
          uk: "SMAS-ліфтинг - це апаратна підтяжка обличчя сфокусованим ультразвуком, яка працює з тим самим шаром, що й хірург під час фейсліфтингу. SMAS (superficial musculo-aponeurotic system) - щільна м'язово-апоневротична пластина під підшкірним жиром: саме вона тримає овал, і саме її розтягнення дає брилі та опущені кути рота.\n\nВ GENEVITY процедуру виконують на Ultraformer MPT. Апарат доставляє ультразвукову енергію точково, у мікрозони на заданій глибині - 4,5 мм для SMAS, 3,0 мм для дерми, 1,5 мм для поверхневих шарів. У точці фокуса тканина нагрівається до 65-70 °C і скорочується одразу, а протягом наступних місяців у ній вибудовується новий колаген.\n\nШкіра при цьому залишається неушкодженою: енергія проходить крізь неї, не пошкоджуючи епідерміс. Тому після SMAS-ліфтингу немає ні швів, ні періоду відновлення - того ж дня можна повернутися до звичайних справ.",
          ru: "SMAS-лифтинг - это аппаратная подтяжка лица сфокусированным ультразвуком, которая работает с тем же слоем, что и хирург во время фейслифтинга. SMAS (superficial musculo-aponeurotic system) - плотная мышечно-апоневротическая пластина под подкожным жиром: именно она держит овал, и именно её растяжение даёт брыли и опущенные уголки рта.\n\nВ GENEVITY процедуру выполняют на Ultraformer MPT. Аппарат доставляет ультразвуковую энергию точечно, в микрозоны на заданной глубине - 4,5 мм для SMAS, 3,0 мм для дермы, 1,5 мм для поверхностных слоёв. В точке фокуса ткань нагревается до 65-70 °C и сокращается сразу, а в течение следующих месяцев в ней выстраивается новый коллаген.\n\nКожа при этом остаётся неповреждённой: энергия проходит сквозь неё, не затрагивая эпидермис. Поэтому после SMAS-лифтинга нет ни швов, ни периода восстановления - в тот же день можно вернуться к обычным делам.",
          en: "SMAS lifting is a device-based facelift with focused ultrasound that targets the very layer a surgeon addresses during a facelift. The SMAS - superficial musculo-aponeurotic system - is a dense sheet of muscle and fascia beneath the subcutaneous fat: it holds the contour of the face, and its laxity is what produces jowls and drooping corners of the mouth.\n\nAt GENEVITY the treatment is performed on the Ultraformer MPT. The device delivers ultrasound energy in precise micro-zones at a set depth - 4.5 mm for the SMAS, 3.0 mm for the dermis, 1.5 mm for the superficial layers. At the focal point the tissue reaches 65-70 °C and contracts immediately, and over the following months new collagen is laid down in it.\n\nThe skin itself is left intact: the energy passes through the epidermis without damaging it. That is why SMAS lifting leaves no sutures and needs no recovery time - you can return to your usual routine the same day.",
        },
      },
      {
        type: "indicationsContraindications",
        indicationsHeading: { uk: "Кому підходить ультразвуковий SMAS-ліфтинг", ru: "Кому подходит ультразвуковой SMAS-лифтинг", en: "Who ultrasonic SMAS lifting suits" },
        indications: [
          { uk: "Втрата чіткості овалу обличчя, перші брилі", ru: "Потеря чёткости овала лица, первые брыли", en: "A softening jawline and the first signs of jowls" },
          { uk: "Опущення брів і нависання верхньої повіки", ru: "Опущение бровей и нависание верхнего века", en: "Descending brows and heaviness of the upper eyelid" },
          { uk: "Носогубні складки та опущені кути рота", ru: "Носогубные складки и опущенные уголки рта", en: "Nasolabial folds and downturned corners of the mouth" },
          { uk: "Дряблість шкіри шиї та зони підборіддя", ru: "Дряблость кожи шеи и зоны подбородка", en: "Laxity of the neck and submental area" },
          { uk: "Бажання відкласти або доповнити хірургічну підтяжку", ru: "Желание отложить или дополнить хирургическую подтяжку", en: "A wish to postpone or complement surgical lifting" },
          { uk: "Вік 35+ зі збереженою якістю шкіри", ru: "Возраст 35+ с сохранённым качеством кожи", en: "Age 35+ with reasonably preserved skin quality" },
        ],
        contraindicationsHeading: { uk: "Коли процедуру не проводять", ru: "Когда процедуру не проводят", en: "When the treatment is not performed" },
        contraindications: [
          { uk: "Вагітність і період лактації", ru: "Беременность и период лактации", en: "Pregnancy and breastfeeding" },
          { uk: "Гострі запальні процеси та пошкодження шкіри в зоні впливу", ru: "Острые воспалительные процессы и повреждения кожи в зоне воздействия", en: "Acute inflammation or broken skin in the treatment area" },
          { uk: "Кардіостимулятор або інші імплантовані електронні пристрої", ru: "Кардиостимулятор или другие имплантированные электронные устройства", en: "A pacemaker or other implanted electronic devices" },
          { uk: "Онкологічні захворювання в активній фазі", ru: "Онкологические заболевания в активной фазе", en: "Active oncological disease" },
          { uk: "Виражений надлишок шкіри, коли показана хірургія", ru: "Выраженный избыток кожи, когда показана хирургия", en: "Marked skin excess, where surgery is the appropriate option" },
          { uk: "Декомпенсовані хронічні захворювання, некомпенсований цукровий діабет", ru: "Декомпенсированные хронические заболевания, некомпенсированный сахарный диабет", en: "Decompensated chronic disease or uncontrolled diabetes" },
        ],
      },
      {
        type: "steps",
        heading: { uk: "Як проходить процедура SMAS-ліфтингу", ru: "Как проходит процедура SMAS-лифтинга", en: "How the SMAS lifting session works" },
        steps: [
          { title: { uk: "Консультація та розмітка", ru: "Консультация и разметка", en: "Consultation and mapping" }, description: { uk: "Лікар оцінює товщину тканин, ступінь птозу і наносить розмітку - вона задає кількість ліній та глибину для кожної ділянки.", ru: "Врач оценивает толщину тканей, степень птоза и наносит разметку - она задаёт количество линий и глубину для каждого участка.", en: "The physician assesses tissue thickness and the degree of ptosis, then draws a map that sets the number of lines and the depth for each zone." } },
          { title: { uk: "Підготовка шкіри", ru: "Подготовка кожи", en: "Skin preparation" }, description: { uk: "Демакіяж, антисептична обробка та нанесення провідного гелю. За потреби - аплікаційна анестезія для чутливих зон.", ru: "Демакияж, антисептическая обработка и нанесение проводящего геля. При необходимости - аппликационная анестезия для чувствительных зон.", en: "Make-up removal, antiseptic prep and conductive gel. Topical anaesthetic is applied to sensitive zones if needed." } },
          { title: { uk: "Робота картриджами", ru: "Работа картриджами", en: "Working through the cartridges" }, description: { uk: "Лікар послідовно проходить зони картриджами різної глибини: 4,5 мм по SMAS, 3,0 і 1,5 мм по дермі та поверхневих шарах.", ru: "Врач последовательно проходит зоны картриджами разной глубины: 4,5 мм по SMAS, 3,0 и 1,5 мм по дерме и поверхностным слоям.", en: "The physician works through the zones with cartridges of different depths: 4.5 mm on the SMAS, 3.0 and 1.5 mm on the dermis and superficial layers." } },
          { title: { uk: "Завершення та рекомендації", ru: "Завершение и рекомендации", en: "Finishing and aftercare" }, description: { uk: "Гель знімають, наносять заспокійливий засіб із SPF. Лікар пояснює, чого очікувати в найближчі тижні, і призначає контрольний огляд.", ru: "Гель снимают, наносят успокаивающее средство с SPF. Врач объясняет, чего ожидать в ближайшие недели, и назначает контрольный осмотр.", en: "The gel is removed and a soothing product with SPF applied. The physician explains what to expect over the coming weeks and schedules a follow-up." } },
        ],
      },
      {
        type: "bullets",
        heading: { uk: "Що дає СМАС-ліфтинг обличчя", ru: "Что даёт СМАС-лифтинг лица", en: "What SMAS lifting of the face delivers" },
        items: [
          { uk: "Чіткіший овал і піднятий кут нижньої щелепи", ru: "Более чёткий овал и приподнятый угол нижней челюсти", en: "A sharper oval and a lifted jaw angle" },
          { uk: "Ущільнення тканин шиї та підборіддя", ru: "Уплотнение тканей шеи и подбородка", en: "Firmer tissue across the neck and chin" },
          { uk: "Відкритий погляд за рахунок підтяжки брів", ru: "Открытый взгляд за счёт подтяжки бровей", en: "A more open eye area thanks to brow elevation" },
          { uk: "Поступове наростання ефекту - результат виглядає природно", ru: "Постепенное нарастание эффекта - результат выглядит естественно", en: "A gradual build-up of the effect, so the result reads as natural" },
          { uk: "Без розрізів, швів і періоду відновлення", ru: "Без разрезов, швов и периода восстановления", en: "No incisions, no sutures, no downtime" },
          { uk: "Одна процедура на рік замість курсу з багатьох сеансів", ru: "Одна процедура в год вместо курса из многих сеансов", en: "One session a year instead of a long course" },
        ],
      },
      {
        type: "richText",
        heading: { uk: "Результат СМАС-ліфтингу та відновлення", ru: "Результат СМАС-лифтинга и восстановление", en: "Results of SMAS lifting and recovery" },
        body: {
          uk: "Перше підтягування помітне одразу після сеансу - це реакція тканин на термічне скорочення. Далі ефект тимчасово згладжується, а з 6-8 тижня починає наростати знову: у зонах впливу формується новий колаген. Максимум результату оцінюють через 3-4 місяці, і він тримається в середньому 12-18 місяців.\n\nПеріоду відновлення немає. У перші дні можливе легке почервоніння, набряк або чутливість при натисканні - це нормальна реакція, яка минає самостійно. Декоративну косметику можна наносити того ж дня.\n\n**Щоб результат тримався довше:**\n- використовуйте SPF 50 щодня, особливо в перші тижні;\n- відкладіть сауну, баню й інтенсивні тренування на 3-5 днів;\n- пийте достатньо води - колагеногенез потребує ресурсу;\n- поверніться на контрольний огляд через 3 місяці, щоб лікар оцінив динаміку.\n\nSMAS-ліфтинг добре поєднується з ін'єкційними методиками: ботулінотерапію та біоревіталізацію зазвичай планують через 2 тижні після сеансу.",
          ru: "Первое подтягивание заметно сразу после сеанса - это реакция тканей на термическое сокращение. Затем эффект временно сглаживается, а с 6-8 недели начинает нарастать снова: в зонах воздействия формируется новый коллаген. Максимум результата оценивают через 3-4 месяца, и он держится в среднем 12-18 месяцев.\n\nПериода восстановления нет. В первые дни возможны лёгкое покраснение, отёк или чувствительность при надавливании - это нормальная реакция, которая проходит самостоятельно. Декоративную косметику можно наносить в тот же день.\n\n**Чтобы результат держался дольше:**\n- используйте SPF 50 ежедневно, особенно в первые недели;\n- отложите сауну, баню и интенсивные тренировки на 3-5 дней;\n- пейте достаточно воды - коллагеногенез требует ресурса;\n- вернитесь на контрольный осмотр через 3 месяца, чтобы врач оценил динамику.\n\nSMAS-лифтинг хорошо сочетается с инъекционными методиками: ботулинотерапию и биоревитализацию обычно планируют через 2 недели после сеанса.",
          en: "The first tightening is visible immediately after the session - the tissue's response to thermal contraction. The effect then softens for a while and starts to build again from week 6-8, as new collagen forms in the treated zones. Peak result is assessed at 3-4 months and holds for 12-18 months on average.\n\nThere is no recovery period. Mild redness, swelling or tenderness on pressure may occur in the first few days; this is a normal response that settles on its own. Make-up can be applied the same day.\n\n**To make the result last:**\n- use SPF 50 daily, especially in the first weeks;\n- postpone sauna, steam rooms and intensive training for 3-5 days;\n- drink enough water - collagen synthesis needs the resource;\n- come back for a review at 3 months so the physician can assess progress.\n\nSMAS lifting combines well with injectables: botulinum toxin and biorevitalisation are usually planned two weeks after the session.",
        },
      },
    ],
    faqs: [
      { question: { uk: "Чи боляче робити SMAS-ліфтинг?", ru: "Больно ли делать SMAS-лифтинг?", en: "Is SMAS lifting painful?" },
        answer: { uk: "Відчуття описують як короткі теплі імпульси в глибині тканин - вони тривають частку секунди на кожній точці. Найчутливіші зони - вздовж нижньої щелепи та над кістками, там лікар зменшує потужність або застосовує аплікаційну анестезію. Більшість пацієнтів проходить процедуру без знеболення.", ru: "Ощущения описывают как короткие тёплые импульсы в глубине тканей - они длятся долю секунды в каждой точке. Самые чувствительные зоны - вдоль нижней челюсти и над костями, там врач снижает мощность или применяет аппликационную анестезию. Большинство пациентов проходит процедуру без обезболивания.", en: "Patients describe short pulses of warmth deep in the tissue, lasting a fraction of a second at each point. The most sensitive areas are along the jawline and over bone, where the physician lowers the energy or uses a topical anaesthetic. Most people go through the session without any anaesthesia." } },
      { question: { uk: "Чим SMAS-ліфтинг відрізняється від RF-ліфтингу?", ru: "Чем SMAS-лифтинг отличается от RF-лифтинга?", en: "How does SMAS lifting differ from RF lifting?" },
        answer: { uk: "Глибиною роботи. Ультразвук фокусується точно на 4,5 мм і скорочує SMAS - каркас, який тримає овал. Радіочастота нагріває дерму та підшкірний шар ширше й м'якше, покращуючи щільність і текстуру шкіри. SMAS-ліфтинг обирають, коли потрібна підтяжка контуру, RF - коли головний запит це якість шкіри. Часто методики комбінують.", ru: "Глубиной работы. Ультразвук фокусируется точно на 4,5 мм и сокращает SMAS - каркас, который держит овал. Радиочастота нагревает дерму и подкожный слой шире и мягче, улучшая плотность и текстуру кожи. SMAS-лифтинг выбирают, когда нужна подтяжка контура, RF - когда главный запрос это качество кожи. Часто методики комбинируют.", en: "In the depth they work at. Ultrasound focuses precisely at 4.5 mm and contracts the SMAS - the framework that holds the facial contour. Radiofrequency heats the dermis and subcutaneous layer more broadly and gently, improving density and texture. SMAS lifting is chosen when the contour needs lifting, RF when skin quality is the main concern. The two are often combined." } },
      { question: { uk: "Скільки процедур потрібно для результату?", ru: "Сколько процедур нужно для результата?", en: "How many sessions are needed?" },
        answer: { uk: "Зазвичай одна повноцінна процедура на рік. На відміну від більшості апаратних методик, SMAS-ліфтинг не потребує курсу: одного сеансу з достатньою кількістю ліній вистачає, щоб запустити ремоделювання. Повтор планують через 12-18 місяців, коли лікар побачить, що ефект почав згасати.", ru: "Обычно одна полноценная процедура в год. В отличие от большинства аппаратных методик, SMAS-лифтинг не требует курса: одного сеанса с достаточным количеством линий хватает, чтобы запустить ремоделирование. Повтор планируют через 12-18 месяцев, когда врач увидит, что эффект начал угасать.", en: "Usually one full session per year. Unlike most device treatments, SMAS lifting does not require a course: a single session with enough lines is sufficient to trigger remodelling. A repeat is planned at 12-18 months, when the physician sees the effect beginning to fade." } },
      { question: { uk: "З якого віку можна робити СМАС-ліфтинг?", ru: "С какого возраста можно делать СМАС-лифтинг?", en: "From what age can SMAS lifting be done?" },
        answer: { uk: "Найчастіше - з 35 років, коли з'являються перші ознаки гравітаційного птозу, але шкіра ще здатна активно синтезувати колаген. До 30 років процедура рідко доцільна: підтягувати ще нічого. Після 55-60 років лікар оцінює, чи достатньо апаратної методики, чи ефективнішою буде хірургічна підтяжка.", ru: "Чаще всего - с 35 лет, когда появляются первые признаки гравитационного птоза, но кожа ещё способна активно синтезировать коллаген. До 30 лет процедура редко целесообразна: подтягивать ещё нечего. После 55-60 лет врач оценивает, достаточно ли аппаратной методики или эффективнее будет хирургическая подтяжка.", en: "Most often from 35, when the first signs of gravitational ptosis appear but the skin can still synthesise collagen actively. Before 30 the treatment is rarely justified - there is nothing to lift yet. After 55-60 the physician assesses whether a device treatment is enough or whether surgery would give a better result." } },
      { question: { uk: "Чи можна поєднувати SMAS-ліфтинг із філерами та ботоксом?", ru: "Можно ли сочетать SMAS-лифтинг с филлерами и ботоксом?", en: "Can SMAS lifting be combined with fillers and botulinum toxin?" },
        answer: { uk: "Так, і це часта тактика. Ультразвук працює з каркасом, ін'єкції - з об'ємом і мімікою, тому вони доповнюють одне одного. Послідовність визначає лікар: зазвичай спершу SMAS-ліфтинг, а ін'єкції через 2 тижні. Якщо філери вже введені, лікар обходить зону їх розташування або витримує паузу.", ru: "Да, и это частая тактика. Ультразвук работает с каркасом, инъекции - с объёмом и мимикой, поэтому они дополняют друг друга. Последовательность определяет врач: обычно сначала SMAS-лифтинг, а инъекции через 2 недели. Если филлеры уже введены, врач обходит зону их расположения или выдерживает паузу.", en: "Yes, and it is a common strategy. Ultrasound works on the framework, injections on volume and muscle activity, so they complement each other. The physician decides the sequence: usually SMAS lifting first, injections two weeks later. If fillers are already in place, the physician avoids that area or allows an interval." } },
      { question: { uk: "Чи можна повернутися до роботи одразу після сеансу?", ru: "Можно ли вернуться к работе сразу после сеанса?", en: "Can I go back to work straight after the session?" },
        answer: { uk: "Так. SMAS-ліфтинг не пошкоджує поверхню шкіри, тому кірочок і лущення не буває. Може залишитися легке почервоніння на 1-2 години та невеликий набряк, який маскується тональним засобом. Планувати вихідний не потрібно.", ru: "Да. SMAS-лифтинг не повреждает поверхность кожи, поэтому корочек и шелушения не бывает. Может остаться лёгкое покраснение на 1-2 часа и небольшой отёк, который маскируется тональным средством. Планировать выходной не нужно.", en: "Yes. SMAS lifting does not damage the skin surface, so there is no crusting or peeling. Mild redness may last an hour or two and slight swelling can be covered with foundation. There is no need to book a day off." } },
      { question: { uk: "Скільки коштує SMAS-ліфтинг у Дніпрі?", ru: "Сколько стоит SMAS-лифтинг в Днепре?", en: "How much does SMAS lifting cost in Dnipro?" },
        answer: { uk: "Вартість залежить від зон і кількості ліній, які потрібні саме вам: обличчя, шия, підборіддя та зона брів рахуються окремо. Точну суму лікар називає на консультації після огляду - до цього будь-яка цифра була б умовною. Актуальні ціни на процедуру є в розділі «Ціни», і адміністратор озвучить їх під час запису.", ru: "Стоимость зависит от зон и количества линий, которые нужны именно вам: лицо, шея, подбородок и зона бровей считаются отдельно. Точную сумму врач называет на консультации после осмотра - до этого любая цифра была бы условной. Актуальные цены на процедуру есть в разделе «Цены», и администратор озвучит их при записи.", en: "The price depends on the zones and the number of lines you need: face, neck, chin and brow area are counted separately. The physician gives the exact figure at the consultation after examining you - before that any number would be notional. Current prices are listed in the Prices section, and the administrator will quote them when you book." } },
    ],
  },

  // ─── 2. RF-ЛІФТИНГ ────────────────────────────────────────────────────────
  {
    slug: "rf-lifting",
    meta: {
      category: "apparatus-cosmetology",
      h1: { uk: "RF-ліфтинг в Дніпрі", ru: "RF-лифтинг в Днепре", en: "RF lifting in Dnipro" },
      seoTitle: {
        uk: "RF-lifting в Дніпрі - RF-ліфтінг",
        ru: "RF-лифтинг в Днепре - процедура RF-лифтинг",
        en: "RF Lifting in Dnipro - RF lifting price",
      },
      seoDesc: {
        uk: "Радіохвильовий ліфтинг в Дніпрі 🤍 GENEVITY. Доступні ціни на радіочастотний ліфтинг 💫 Гладка та пружна шкіра.",
        ru: "Радиоволновой лифтинг в Днепре 🤍 GENEVITY. Доступные цены на радиочастотный лифтинг 💫 Гладкая и упругая кожа.",
        en: "Radiowave lifting in Dnipro 🤍 GENEVITY. Available prices on radiofrequency lifting 💫 Smooth and firm skin.",
      },
    },
    title: { uk: "RF-ліфтинг", ru: "RF-лифтинг", en: "RF Lifting" },
    summary: {
      uk: "Радіочастотний ліфтинг у GENEVITY на EXION і VOLNEWMER: контрольоване нагрівання дерми ущільнює колагенові волокна, повертає шкірі пружність і згладжує дрібні зморшки без голок і реабілітації.",
      ru: "Радиочастотный лифтинг в GENEVITY на EXION и VOLNEWMER: контролируемый нагрев дермы уплотняет коллагеновые волокна, возвращает коже упругость и разглаживает мелкие морщины без игл и реабилитации.",
      en: "Radiofrequency lifting at GENEVITY on EXION and VOLNEWMER: controlled dermal heating tightens collagen fibres, restores firmness and smooths fine lines without needles or downtime.",
    },
    procedureLength: { uk: "30-45 хвилин", ru: "30-45 минут", en: "30-45 minutes" },
    effectDuration: { uk: "до 12 місяців після курсу", ru: "до 12 месяцев после курса", en: "up to 12 months after a course" },
    sessionsRecommended: { uk: "4-6 процедур курсом", ru: "4-6 процедур курсом", en: "4-6 sessions per course" },
    related: ["exion-face", "volnewmer", "microneedling-rf-lifting", "smas-lifting"],
    doctors: COSMETOLOGISTS,
    equipment: [EQ.EXION_FACE, EQ.VOLNEWMER],
    sections: [
      {
        type: "richText",
        heading: { uk: "Що таке RF-ліфтинг шкіри", ru: "Что такое RF-лифтинг кожи", en: "What RF lifting of the skin is" },
        body: {
          uk: "RF-ліфтинг - це радіохвильова підтяжка, під час якої струм високої частоти проходить крізь тканини й нагріває дерму зсередини. Колагенові волокна при нагріванні до 40-42 °C скорочуються, а фібробласти отримують сигнал виробляти новий колаген і еластин. Шкіра поступово стає щільнішою, а контур - чіткішим.\n\nНа відміну від ультразвуку, радіочастота працює не точково, а рівномірно прогріває обраний обсяг тканини. Тому RF-ліфтинг обирають, коли головний запит - якість шкіри: втрата тонусу, дрібна сітка зморщок, розширені пори, млявість щік або зони навколо очей.\n\nВ GENEVITY процедуру виконують на двох платформах. EXION - монополярний RF із AI-контролем температури, який ще й стимулює вироблення власної гіалуронової кислоти. VOLNEWMER працює трансдермально, доставляючи активні речовини вглиб без голок. Лікар обирає апарат за станом шкіри та вашим запитом.",
          ru: "RF-лифтинг - это радиоволновая подтяжка, во время которой ток высокой частоты проходит сквозь ткани и нагревает дерму изнутри. Коллагеновые волокна при нагреве до 40-42 °C сокращаются, а фибробласты получают сигнал вырабатывать новый коллаген и эластин. Кожа постепенно становится плотнее, а контур - чётче.\n\nВ отличие от ультразвука, радиочастота работает не точечно, а равномерно прогревает выбранный объём ткани. Поэтому RF-лифтинг выбирают, когда главный запрос - качество кожи: потеря тонуса, мелкая сетка морщин, расширенные поры, вялость щёк или зоны вокруг глаз.\n\nВ GENEVITY процедуру выполняют на двух платформах. EXION - монополярный RF с AI-контролем температуры, который вдобавок стимулирует выработку собственной гиалуроновой кислоты. VOLNEWMER работает трансдермально, доставляя активные вещества вглубь без игл. Врач выбирает аппарат по состоянию кожи и вашему запросу.",
          en: "RF lifting is a radiowave tightening treatment in which a high-frequency current passes through the tissue and heats the dermis from within. Heated to 40-42 °C, collagen fibres contract while fibroblasts receive the signal to produce new collagen and elastin. The skin gradually becomes denser and the contour more defined.\n\nUnlike ultrasound, radiofrequency does not work in points - it heats the selected volume of tissue evenly. That is why RF lifting is chosen when skin quality is the main concern: loss of tone, a fine network of lines, enlarged pores, slack cheeks or a tired eye area.\n\nAt GENEVITY the treatment runs on two platforms. EXION is monopolar RF with AI temperature control that also stimulates the skin's own hyaluronic acid production. VOLNEWMER works transdermally, delivering active substances into the deeper layers without needles. The physician selects the device according to your skin and your goal.",
        },
      },
      {
        type: "indicationsContraindications",
        indicationsHeading: { uk: "Показання до радіочастотного ліфтингу", ru: "Показания к радиочастотному лифтингу", en: "Indications for radiofrequency lifting" },
        indications: [
          { uk: "Втрата пружності та тонусу шкіри обличчя", ru: "Потеря упругости и тонуса кожи лица", en: "Loss of firmness and tone in the facial skin" },
          { uk: "Дрібні мімічні зморшки та зневоднення", ru: "Мелкие мимические морщины и обезвоженность", en: "Fine expression lines and dehydration" },
          { uk: "Розширені пори й нерівна текстура", ru: "Расширенные поры и неровная текстура", en: "Enlarged pores and uneven texture" },
          { uk: "М'якість контуру щік і підборіддя", ru: "Мягкость контура щёк и подбородка", en: "Softening of the cheek and chin contour" },
          { uk: "Дряблість шкіри шиї, декольте, рук", ru: "Дряблость кожи шеи, декольте, рук", en: "Laxity of the neck, decolletage and arms" },
          { uk: "Підготовка шкіри до інших методик або підтримка результату", ru: "Подготовка кожи к другим методикам или поддержание результата", en: "Preparing the skin for other treatments or maintaining a result" },
        ],
        contraindicationsHeading: { uk: "Протипоказання", ru: "Противопоказания", en: "Contraindications" },
        contraindications: [
          { uk: "Кардіостимулятор, металеві та електронні імпланти в зоні впливу", ru: "Кардиостимулятор, металлические и электронные импланты в зоне воздействия", en: "A pacemaker or metal and electronic implants in the treatment area" },
          { uk: "Вагітність і лактація", ru: "Беременность и лактация", en: "Pregnancy and breastfeeding" },
          { uk: "Гострі запалення, герпес у стадії загострення", ru: "Острые воспаления, герпес в стадии обострения", en: "Acute inflammation or an active herpes outbreak" },
          { uk: "Онкологічні та автоімунні захворювання в активній фазі", ru: "Онкологические и аутоиммунные заболевания в активной фазе", en: "Active oncological or autoimmune disease" },
          { uk: "Некомпенсований цукровий діабет, захворювання щитоподібної залози в декомпенсації", ru: "Некомпенсированный сахарный диабет, заболевания щитовидной железы в декомпенсации", en: "Uncontrolled diabetes or decompensated thyroid disease" },
          { uk: "Нещодавно введені нитки або філери в зоні процедури", ru: "Недавно введённые нити или филлеры в зоне процедуры", en: "Recently placed threads or fillers in the treatment area" },
        ],
      },
      {
        type: "steps",
        heading: { uk: "Як проходить процедура RF-ліфтингу", ru: "Как проходит процедура RF-лифтинга", en: "How the RF lifting session works" },
        steps: [
          { title: { uk: "Огляд і вибір протоколу", ru: "Осмотр и выбор протокола", en: "Assessment and protocol" }, description: { uk: "Лікар оцінює щільність і зволоженість шкіри, визначає зони та підбирає апарат - EXION чи VOLNEWMER.", ru: "Врач оценивает плотность и увлажнённость кожи, определяет зоны и подбирает аппарат - EXION или VOLNEWMER.", en: "The physician assesses skin density and hydration, defines the zones and selects the device - EXION or VOLNEWMER." } },
          { title: { uk: "Очищення та нанесення гелю", ru: "Очищение и нанесение геля", en: "Cleansing and gel application" }, description: { uk: "Шкіру очищують від макіяжу й себуму, наносять провідний гель, який забезпечує рівномірний контакт манипули.", ru: "Кожу очищают от макияжа и себума, наносят проводящий гель, который обеспечивает равномерный контакт манипулы.", en: "The skin is cleansed of make-up and sebum, then a conductive gel is applied for even contact with the handpiece." } },
          { title: { uk: "Прогрівання зон", ru: "Прогрев зон", en: "Heating the zones" }, description: { uk: "Манипула рухається по масажних лініях, утримуючи температуру в робочому діапазоні. Відчуття - рівне приємне тепло.", ru: "Манипула движется по массажным линиям, удерживая температуру в рабочем диапазоне. Ощущение - ровное приятное тепло.", en: "The handpiece moves along the massage lines, holding the temperature within the working range. It feels like even, comfortable warmth." } },
          { title: { uk: "Догляд після сеансу", ru: "Уход после сеанса", en: "Post-session care" }, description: { uk: "Наносять зволожувальну сироватку та SPF. Наступний сеанс планують через 7-14 днів залежно від протоколу.", ru: "Наносят увлажняющую сыворотку и SPF. Следующий сеанс планируют через 7-14 дней в зависимости от протокола.", en: "A hydrating serum and SPF are applied. The next session is scheduled in 7-14 days depending on the protocol." } },
        ],
      },
      {
        type: "bullets",
        heading: { uk: "Переваги радіохвильового ліфтингу", ru: "Преимущества радиоволнового лифтинга", en: "Advantages of radiowave lifting" },
        items: [
          { uk: "Помітне ущільнення шкіри вже після 2-3 сеансів", ru: "Заметное уплотнение кожи уже после 2-3 сеансов", en: "Visible skin tightening after just 2-3 sessions" },
          { uk: "Працює на обличчі, шиї, декольте та тілі", ru: "Работает на лице, шее, декольте и теле", en: "Works on the face, neck, decolletage and body" },
          { uk: "Безболісно й без анестезії", ru: "Безболезненно и без анестезии", en: "Painless and without anaesthesia" },
          { uk: "Немає пошкодження шкіри - можна робити цілий рік", ru: "Нет повреждения кожи - можно делать круглый год", en: "No damage to the skin surface, so it can be done all year round" },
          { uk: "Поєднується з ін'єкційними та доглядовими протоколами", ru: "Сочетается с инъекционными и уходовыми протоколами", en: "Combines with injectable and skincare protocols" },
          { uk: "Підходить для профілактики вікових змін після 30 років", ru: "Подходит для профилактики возрастных изменений после 30 лет", en: "Suitable as prevention of age-related changes after 30" },
        ],
      },
      {
        type: "richText",
        heading: { uk: "Скільки тримається ефект RF-ліфтингу", ru: "Сколько держится эффект RF-лифтинга", en: "How long the RF lifting effect lasts" },
        body: {
          uk: "Одразу після сеансу шкіра виглядає свіжішою і трохи підтягнутою - це наслідок термічного скорочення колагену та посиленого кровообігу. Накопичувальний ефект розкривається до кінця курсу з 4-6 процедур: щільність і рівність тону наростають поступово.\n\nПісля завершення курсу результат тримається близько року за умови підтримки. Підтримувальні сеанси зазвичай проводять раз на 2-3 місяці - цього достатньо, щоб не втрачати набуте.\n\n**Що впливає на тривалість ефекту:**\n- вихідний стан шкіри та вік - чим раніше почати, тим довше тримається результат;\n- сонце: без щоденного SPF новий колаген руйнується швидше;\n- куріння й дефіцит сну сповільнюють синтез колагену;\n- домашній догляд із ретиноїдами, вітаміном С та зволоженням підсилює й продовжує ефект.\n\nЯкщо разом із якістю шкіри потрібна підтяжка контуру, лікар може запропонувати поєднати RF з ультразвуковим SMAS-ліфтингом - методики працюють на різній глибині й доповнюють одна одну.",
          ru: "Сразу после сеанса кожа выглядит свежее и слегка подтянутой - это следствие термического сокращения коллагена и усиленного кровообращения. Накопительный эффект раскрывается к концу курса из 4-6 процедур: плотность и ровность тона нарастают постепенно.\n\nПосле завершения курса результат держится около года при условии поддержки. Поддерживающие сеансы обычно проводят раз в 2-3 месяца - этого достаточно, чтобы не терять достигнутое.\n\n**Что влияет на длительность эффекта:**\n- исходное состояние кожи и возраст - чем раньше начать, тем дольше держится результат;\n- солнце: без ежедневного SPF новый коллаген разрушается быстрее;\n- курение и дефицит сна замедляют синтез коллагена;\n- домашний уход с ретиноидами, витамином С и увлажнением усиливает и продлевает эффект.\n\nЕсли вместе с качеством кожи нужна подтяжка контура, врач может предложить сочетать RF с ультразвуковым SMAS-лифтингом - методики работают на разной глубине и дополняют друг друга.",
          en: "Straight after a session the skin looks fresher and slightly tighter - the result of thermal collagen contraction and improved circulation. The cumulative effect emerges by the end of a course of 4-6 sessions, as density and evenness of tone build gradually.\n\nOnce the course is complete the result holds for around a year with maintenance. Top-up sessions are usually done every 2-3 months, which is enough to preserve what has been gained.\n\n**What affects how long the effect lasts:**\n- the starting condition of your skin and your age - the earlier you begin, the longer it holds;\n- sun exposure: without daily SPF, new collagen breaks down faster;\n- smoking and lack of sleep slow collagen synthesis;\n- home care with retinoids, vitamin C and good hydration strengthens and extends the effect.\n\nIf you need contour lifting as well as better skin quality, the physician may suggest combining RF with ultrasonic SMAS lifting - the two work at different depths and complement each other.",
        },
      },
    ],
    faqs: [
      { question: { uk: "Чи безпечний RF-ліфтинг для обличчя?", ru: "Безопасен ли RF-лифтинг для лица?", en: "Is RF lifting safe for the face?" },
        answer: { uk: "Так, за умови коректного протоколу та справного обладнання. Апарати, на яких ми працюємо, контролюють температуру в реальному часі й не дають перегріву. Ризик виникає тоді, коли процедуру виконують без урахування протипоказань - наприклад, за наявності металевих імплантів у зоні впливу. Тому огляд лікаря перед першим сеансом обов'язковий.", ru: "Да, при условии корректного протокола и исправного оборудования. Аппараты, на которых мы работаем, контролируют температуру в реальном времени и не допускают перегрева. Риск возникает тогда, когда процедуру выполняют без учёта противопоказаний - например, при наличии металлических имплантов в зоне воздействия. Поэтому осмотр врача перед первым сеансом обязателен.", en: "Yes, provided the protocol is correct and the equipment is properly maintained. The devices we use monitor temperature in real time and prevent overheating. Risk arises when contraindications are ignored - for example metal implants in the treatment area. That is why an examination before the first session is mandatory." } },
      { question: { uk: "Скільки сеансів RF-ліфтингу потрібно?", ru: "Сколько сеансов RF-лифтинга нужно?", en: "How many RF lifting sessions are needed?" },
        answer: { uk: "Стандартний курс - 4-6 процедур з інтервалом 7-14 днів. Точну кількість лікар визначає після огляду: молодій шкірі з профілактичним запитом вистачає 4 сеансів, при вираженій втраті тонусу протокол розширюють. Далі переходять на підтримку раз на 2-3 місяці.", ru: "Стандартный курс - 4-6 процедур с интервалом 7-14 дней. Точное количество врач определяет после осмотра: молодой коже с профилактическим запросом хватает 4 сеансов, при выраженной потере тонуса протокол расширяют. Далее переходят на поддержку раз в 2-3 месяца.", en: "A standard course is 4-6 sessions at 7-14 day intervals. The physician sets the exact number after examination: younger skin treated preventively may need only four, while marked loss of tone calls for a longer protocol. Maintenance then follows every 2-3 months." } },
      { question: { uk: "Чи можна робити RF-ліфтинг влітку?", ru: "Можно ли делать RF-лифтинг летом?", en: "Can RF lifting be done in summer?" },
        answer: { uk: "Так. Радіочастота не пошкоджує епідерміс і не підвищує фоточутливість, тому сезонних обмежень немає. Єдина умова - щоденний SPF 50, як і в будь-яку іншу пору року. Якщо шкіра щойно засмагла й почервоніла, сеанс краще відкласти на кілька днів.", ru: "Да. Радиочастота не повреждает эпидермис и не повышает фоточувствительность, поэтому сезонных ограничений нет. Единственное условие - ежедневный SPF 50, как и в любое другое время года. Если кожа только что загорела и покраснела, сеанс лучше отложить на несколько дней.", en: "Yes. Radiofrequency does not damage the epidermis or increase photosensitivity, so there are no seasonal restrictions. The one condition is daily SPF 50, as at any other time of year. If your skin is freshly tanned and red, postpone the session for a few days." } },
      { question: { uk: "Чим RF-ліфтинг відрізняється від мікроголкового RF?", ru: "Чем RF-лифтинг отличается от микроигольчатого RF?", en: "How does RF lifting differ from microneedling RF?" },
        answer: { uk: "Класичний RF-ліфтинг проводить енергію через поверхню шкіри, не порушуючи її цілісності, - це м'яка методика без відновлення. Мікроголковий RF доставляє енергію через тонкі голки одразу в дерму, тому працює глибше й ефективніше з рубцями, постакне та вираженими зморшками, але потребує 2-3 днів на відновлення.", ru: "Классический RF-лифтинг проводит энергию через поверхность кожи, не нарушая её целостности, - это мягкая методика без восстановления. Микроигольчатый RF доставляет энергию через тонкие иглы сразу в дерму, поэтому работает глубже и эффективнее с рубцами, постакне и выраженными морщинами, но требует 2-3 дней на восстановление.", en: "Classic RF lifting conducts energy through the skin surface without breaking it - a gentle option with no downtime. Microneedling RF delivers energy through fine needles directly into the dermis, so it works deeper and is more effective on scars, post-acne and pronounced wrinkles, but it needs 2-3 days of recovery." } },
      { question: { uk: "Чи буде помітний результат після першої процедури?", ru: "Будет ли заметен результат после первой процедуры?", en: "Will I see a result after the first session?" },
        answer: { uk: "Легкий ефект видно одразу: шкіра виглядає свіжішою, рельєф - рівнішим. Але це переважно наслідок прогрівання й припливу крові, він тримається кілька днів. Стійкі зміни з'являються з 3-4 сеансу, коли починає працювати новий колаген.", ru: "Лёгкий эффект виден сразу: кожа выглядит свежее, рельеф - ровнее. Но это преимущественно следствие прогрева и притока крови, он держится несколько дней. Устойчивые изменения появляются с 3-4 сеанса, когда начинает работать новый коллаген.", en: "A light effect is visible immediately: the skin looks fresher and smoother. That is mostly the result of warming and increased blood flow, though, and it lasts a few days. Lasting change appears from the third or fourth session, once new collagen starts to build." } },
      { question: { uk: "Чи можна робити RF-ліфтинг після філерів?", ru: "Можно ли делать RF-лифтинг после филлеров?", en: "Can RF lifting be done after fillers?" },
        answer: { uk: "Можна, але не одразу. Лікар витримує паузу 2-4 тижні після ін'єкцій, щоб філер повністю інтегрувався. Нагрівання не «розчиняє» гіалуронову кислоту, проте передчасна процедура може змістити препарат або посилити набряк. Обов'язково скажіть лікарю, що і коли вам вводили.", ru: "Можно, но не сразу. Врач выдерживает паузу 2-4 недели после инъекций, чтобы филлер полностью интегрировался. Нагрев не «растворяет» гиалуроновую кислоту, однако преждевременная процедура может сместить препарат или усилить отёк. Обязательно скажите врачу, что и когда вам вводили.", en: "Yes, but not immediately. The physician allows 2-4 weeks after injections so the filler can fully integrate. Heating does not dissolve hyaluronic acid, but treating too early can displace the product or increase swelling. Always tell your physician what was injected and when." } },
      { question: { uk: "Скільки коштує RF-ліфтинг у Дніпрі?", ru: "Сколько стоит RF-лифтинг в Днепре?", en: "How much does RF lifting cost in Dnipro?" },
        answer: { uk: "Ціна залежить від апарата, кількості зон і того, чи береться процедура курсом. Актуальні ціни на радіочастотний ліфтинг є в розділі «Ціни» на сайті, і адміністратор назве їх під час запису. Остаточний розрахунок лікар зробить після огляду, коли складе протокол саме для вашої шкіри.", ru: "Цена зависит от аппарата, количества зон и того, берётся ли процедура курсом. Актуальные цены на радиочастотный лифтинг есть в разделе «Цены» на сайте, и администратор назовёт их при записи. Окончательный расчёт врач сделает после осмотра, когда составит протокол именно для вашей кожи.", en: "The price depends on the device, the number of zones and whether you take a course. Current prices for radiofrequency lifting are listed in the Prices section, and the administrator will quote them when you book. The final figure comes from the physician once the protocol for your skin is set." } },
    ],
  },

  // ─── 3. МІКРОГОЛКОВИЙ RF-ЛІФТИНГ ─────────────────────────────────────────
  {
    slug: "microneedling-rf-lifting",
    meta: {
      category: "apparatus-cosmetology",
      h1: { uk: "Мікроголковий RF-ліфтинг в Дніпрі", ru: "Микроигольчатый RF-лифтинг в Днепре", en: "Microneedling RF lifting in Dnipro" },
      seoTitle: {
        uk: "Мікроголковий RF-ліфтинг в Дніпрі - RF-ліфтинг мікроголковий",
        ru: "Микроигольчатый RF-лифтинг в Днепре - RF-лифтинг микроигольчатый",
        en: "Microneedling RF Lifting in Dnipro - Microneedling RF lifting price",
      },
      seoDesc: {
        uk: "Мікроголковий ліфтинг в Дніпрі 🤍 GENEVITY. Доступні ціни на мікроігольчастий RF-ліфтинг 💫 Шкіра без зморшок.",
        ru: "RF-лифтинг игольчатый в Днепре 🤍 GENEVITY. Доступные цены на фракционный микроигольчатый RF-лифтинг 💫 Кожа без морщин.",
        en: "Microneedling lifting in Dnipro 🤍 GENEVITY. Available prices on fractional microneedling RF lifting 💫 Skin without wrinkles.",
      },
    },
    title: { uk: "Мікроголковий RF-ліфтинг", ru: "Микроигольчатый RF-лифтинг", en: "Microneedling RF Lifting" },
    summary: {
      uk: "Фракційний мікроголковий RF-ліфтинг у GENEVITY на EXION: тонкі голки доставляють радіочастотну енергію одразу в дерму, ремоделюючи рубці, постакне та глибокі зморшки за 3-4 дні відновлення.",
      ru: "Фракционный микроигольчатый RF-лифтинг в GENEVITY на EXION: тонкие иглы доставляют радиочастотную энергию сразу в дерму, ремоделируя рубцы, постакне и глубокие морщины за 3-4 дня восстановления.",
      en: "Fractional microneedling RF lifting at GENEVITY on EXION: fine needles deliver radiofrequency energy straight into the dermis, remodelling scars, post-acne and deeper wrinkles with 3-4 days of recovery.",
    },
    procedureLength: { uk: "45-60 хвилин", ru: "45-60 минут", en: "45-60 minutes" },
    effectDuration: { uk: "18-24 місяці після курсу", ru: "18-24 месяца после курса", en: "18-24 months after a course" },
    sessionsRecommended: { uk: "3-4 процедури з інтервалом 4 тижні", ru: "3-4 процедуры с интервалом 4 недели", en: "3-4 sessions four weeks apart" },
    related: ["exion-face", "rf-lifting", "laser-resurfacing-post-acne", "biorevitalisation"],
    doctors: COSMETOLOGISTS,
    equipment: [EQ.EXION_FACE],
    sections: [
      {
        type: "richText",
        heading: { uk: "Що таке мікроголковий RF-ліфтинг", ru: "Что такое микроигольчатый RF-лифтинг", en: "What microneedling RF lifting is" },
        body: {
          uk: "Мікроголковий RF-ліфтинг об'єднує два механізми в одній процедурі. Насадка з тонкими ізольованими голками проколює шкіру на заданій глибині - від 0,5 до 3,5 мм, - і в момент проколу з кінчиків голок подається радіочастотна енергія. Верхні шари шкіри залишаються цілими, а прогрів відбувається точно там, де потрібно.\n\nМікроушкодження запускають природну регенерацію, а термічний імпульс одночасно ущільнює колагенові волокна. Такий подвійний вплив дає результат, недосяжний ані для класичного RF, ані для звичайного мікронідлінгу окремо.\n\nВ GENEVITY фракційний мікроголковий RF-ліфтинг виконують на EXION - платформі з монополярним RF і AI-контролем енергії. Лікар змінює глибину проколу від зони до зони: глибше на щоках і в зоні рубців, поверхневіше навколо очей і на лобі. Саме тому методику вибирають для складних запитів - постакне, розтяжок, атрофічних рубців і вираженого зниження тонусу.",
          ru: "Микроигольчатый RF-лифтинг объединяет два механизма в одной процедуре. Насадка с тонкими изолированными иглами прокалывает кожу на заданной глубине - от 0,5 до 3,5 мм, - и в момент прокола с кончиков игл подаётся радиочастотная энергия. Верхние слои кожи остаются целыми, а прогрев происходит точно там, где нужно.\n\nМикроповреждения запускают естественную регенерацию, а термический импульс одновременно уплотняет коллагеновые волокна. Такое двойное воздействие даёт результат, недостижимый ни для классического RF, ни для обычного микронидлинга по отдельности.\n\nВ GENEVITY фракционный микроигольчатый RF-лифтинг выполняют на EXION - платформе с монополярным RF и AI-контролем энергии. Врач меняет глубину прокола от зоны к зоне: глубже на щеках и в зоне рубцов, поверхностнее вокруг глаз и на лбу. Именно поэтому методику выбирают для сложных запросов - постакне, растяжек, атрофических рубцов и выраженного снижения тонуса.",
          en: "Microneedling RF lifting brings two mechanisms together in one treatment. A tip with fine insulated needles punctures the skin to a set depth - from 0.5 to 3.5 mm - and radiofrequency energy is released from the needle tips at the moment of insertion. The upper layers stay intact while the heating happens exactly where it is needed.\n\nThe micro-injuries trigger natural regeneration, while the thermal pulse simultaneously tightens collagen fibres. This dual action produces results that neither classic RF nor plain microneedling can achieve alone.\n\nAt GENEVITY fractional microneedling RF lifting is performed on EXION, a platform with monopolar RF and AI-controlled energy. The physician varies the needle depth from zone to zone: deeper on the cheeks and over scars, shallower around the eyes and on the forehead. This is why the method is chosen for demanding cases - post-acne, stretch marks, atrophic scars and marked loss of tone.",
        },
      },
      {
        type: "indicationsContraindications",
        indicationsHeading: { uk: "Показання до мікроігольчастого RF-ліфтингу", ru: "Показания к микроигольчатому RF-лифтингу", en: "Indications for microneedling RF lifting" },
        indications: [
          { uk: "Атрофічні рубці та сліди постакне", ru: "Атрофические рубцы и следы постакне", en: "Atrophic scars and post-acne marks" },
          { uk: "Глибокі зморшки, які не піддаються поверхневим методикам", ru: "Глубокие морщины, не поддающиеся поверхностным методикам", en: "Deep wrinkles that surface treatments cannot reach" },
          { uk: "Розширені пори й нерівний рельєф шкіри", ru: "Расширенные поры и неровный рельеф кожи", en: "Enlarged pores and uneven skin texture" },
          { uk: "Знижений тонус шкіри обличчя, шиї, живота", ru: "Сниженный тонус кожи лица, шеи, живота", en: "Reduced tone of the face, neck or abdomen" },
          { uk: "Розтяжки після схуднення або вагітності", ru: "Растяжки после похудения или беременности", en: "Stretch marks after weight loss or pregnancy" },
          { uk: "Підвищена жирність шкіри та активна себорея", ru: "Повышенная жирность кожи и активная себорея", en: "Oily skin and active seborrhoea" },
        ],
        contraindicationsHeading: { uk: "Коли методика не підходить", ru: "Когда методика не подходит", en: "When the method is not suitable" },
        contraindications: [
          { uk: "Кардіостимулятор і металеві імпланти в зоні впливу", ru: "Кардиостимулятор и металлические импланты в зоне воздействия", en: "A pacemaker or metal implants in the treatment area" },
          { uk: "Схильність до келоїдних рубців", ru: "Склонность к келоидным рубцам", en: "A tendency to form keloid scars" },
          { uk: "Активний запальний процес, гнійничкові висипання, герпес", ru: "Активный воспалительный процесс, гнойничковые высыпания, герпес", en: "Active inflammation, pustular lesions or herpes" },
          { uk: "Порушення згортання крові, прийом антикоагулянтів", ru: "Нарушения свёртывания крови, приём антикоагулянтов", en: "Coagulation disorders or anticoagulant therapy" },
          { uk: "Вагітність і лактація", ru: "Беременность и лактация", en: "Pregnancy and breastfeeding" },
          { uk: "Свіжа засмага та прийом ізотретиноїну протягом останніх 6 місяців", ru: "Свежий загар и приём изотретиноина в последние 6 месяцев", en: "A fresh tan or isotretinoin use within the past six months" },
        ],
      },
      {
        type: "steps",
        heading: { uk: "Як проходить процедура RF-ліфтингу голковим методом", ru: "Как проходит процедура RF-лифтинга игольчатым методом", en: "How the needle-based RF lifting session works" },
        steps: [
          { title: { uk: "Консультація та підбір глибини", ru: "Консультация и подбор глубины", en: "Consultation and depth planning" }, description: { uk: "Лікар аналізує рельєф шкіри, тип рубців і товщину дерми, після чого визначає глибину голок для кожної зони.", ru: "Врач анализирует рельеф кожи, тип рубцов и толщину дермы, после чего определяет глубину игл для каждой зоны.", en: "The physician analyses skin texture, scar type and dermal thickness, then sets the needle depth for each zone." } },
          { title: { uk: "Аплікаційна анестезія", ru: "Аппликационная анестезия", en: "Topical anaesthesia" }, description: { uk: "На очищену шкіру наносять анестетик і витримують 30-40 хвилин - процедура проходить комфортно.", ru: "На очищенную кожу наносят анестетик и выдерживают 30-40 минут - процедура проходит комфортно.", en: "An anaesthetic cream is applied to cleansed skin and left for 30-40 minutes, so the session is comfortable." } },
          { title: { uk: "Фракційний прохід", ru: "Фракционный проход", en: "The fractional pass" }, description: { uk: "Лікар послідовно опрацьовує зони, роблячи 1-3 проходи. Відчуття - тиск і коротке тепло в момент імпульсу.", ru: "Врач последовательно обрабатывает зоны, делая 1-3 прохода. Ощущение - давление и короткое тепло в момент импульса.", en: "The physician works zone by zone with 1-3 passes. It feels like pressure and a brief warmth at the moment of the pulse." } },
          { title: { uk: "Відновлювальний догляд", ru: "Восстанавливающий уход", en: "Recovery care" }, description: { uk: "Наносять заспокійливу маску та регенерувальний засіб, видають інструкції на 5 днів догляду вдома.", ru: "Наносят успокаивающую маску и регенерирующее средство, выдают инструкции на 5 дней ухода дома.", en: "A calming mask and a regenerating product are applied, along with instructions for five days of home care." } },
        ],
      },
      {
        type: "bullets",
        heading: { uk: "Що вирішує фракційний RF-ліфтинг", ru: "Что решает фракционный RF-лифтинг", en: "What fractional RF lifting solves" },
        items: [
          { uk: "Згладжує атрофічні рубці й сліди постакне", ru: "Сглаживает атрофические рубцы и следы постакне", en: "Smooths atrophic scars and post-acne marks" },
          { uk: "Ущільнює шкіру там, де поверхневі методики не працюють", ru: "Уплотняет кожу там, где поверхностные методики не работают", en: "Densifies skin where surface treatments fall short" },
          { uk: "Звужує пори й вирівнює рельєф", ru: "Сужает поры и выравнивает рельеф", en: "Tightens pores and evens out texture" },
          { uk: "Зменшує вираженість розтяжок на тілі", ru: "Уменьшает выраженность растяжек на теле", en: "Reduces the visibility of stretch marks on the body" },
          { uk: "Безпечний для темної шкіри - енергія не залежить від пігменту", ru: "Безопасен для тёмной кожи - энергия не зависит от пигмента", en: "Safe for darker skin, since the energy is not pigment-dependent" },
          { uk: "Результат наростає до 6 місяців після курсу", ru: "Результат нарастает до 6 месяцев после курса", en: "The result keeps improving for up to six months after the course" },
        ],
      },
      {
        type: "richText",
        heading: { uk: "Відновлення після мікроголкового RF-ліфтингу", ru: "Восстановление после микроигольчатого RF-лифтинга", en: "Recovery after microneedling RF lifting" },
        body: {
          uk: "Перші години після процедури шкіра виражено червона й гаряча, як після сонця, - це очікувана реакція. До кінця першої доби почервоніння спадає, залишається набряк і відчуття стягнутості. На 2-3 день з'являється дрібна сіточка з мікроскоринок, яка сходить самостійно за 3-5 днів.\n\nПовернутися до роботи більшість пацієнтів може на 3-4 добу, тому процедуру зручно планувати на початок вихідних.\n\n**Правила відновлення:**\n- перші 12 годин не вмиватися й не наносити косметику;\n- 5 днів використовувати лише м'яке очищення та регенерувальний крем, який призначив лікар;\n- не здирати кірочки - це головна причина пігментних плям після процедури;\n- SPF 50 щодня протягом місяця, навіть у похмуру погоду;\n- відкласти сауну, басейн і тренування на 7 днів.\n\nПерші зміни рельєфу видно вже через 3-4 тижні, а повна картина формується до 6 місяців після завершення курсу - саме стільки триває ремоделювання колагену.",
          ru: "Первые часы после процедуры кожа выраженно красная и горячая, как после солнца, - это ожидаемая реакция. К концу первых суток покраснение спадает, остаётся отёк и ощущение стянутости. На 2-3 день появляется мелкая сеточка из микрокорочек, которая сходит самостоятельно за 3-5 дней.\n\nВернуться к работе большинство пациентов может на 3-4 сутки, поэтому процедуру удобно планировать на начало выходных.\n\n**Правила восстановления:**\n- первые 12 часов не умываться и не наносить косметику;\n- 5 дней использовать только мягкое очищение и регенерирующий крем, назначенный врачом;\n- не сдирать корочки - это главная причина пигментных пятен после процедуры;\n- SPF 50 ежедневно в течение месяца, даже в пасмурную погоду;\n- отложить сауну, бассейн и тренировки на 7 дней.\n\nПервые изменения рельефа видны уже через 3-4 недели, а полная картина формируется к 6 месяцам после завершения курса - именно столько длится ремоделирование коллагена.",
          en: "For the first few hours the skin is markedly red and hot, much like after sun exposure - an expected reaction. By the end of day one the redness subsides, leaving swelling and a feeling of tightness. On days two to three a fine grid of micro-crusts appears and flakes away on its own within 3-5 days.\n\nMost patients return to work on day three or four, so the treatment is easy to schedule at the start of a weekend.\n\n**Recovery rules:**\n- do not wash your face or apply make-up for the first 12 hours;\n- for five days use only gentle cleansing and the regenerating cream your physician prescribes;\n- never pick the crusts - this is the main cause of post-treatment pigmentation;\n- wear SPF 50 daily for a month, even on cloudy days;\n- postpone sauna, swimming pool and training for seven days.\n\nThe first textural changes are visible after 3-4 weeks, and the full picture develops by six months after the course - that is how long collagen remodelling takes.",
        },
      },
    ],
    faqs: [
      { question: { uk: "Чи боляче робити мікроголковий RF-ліфтинг?", ru: "Больно ли делать микроигольчатый RF-лифтинг?", en: "Is microneedling RF lifting painful?" },
        answer: { uk: "Процедуру завжди виконують під аплікаційною анестезією, яку витримують 30-40 хвилин. Після цього відчуття зводяться до тиску та короткого тепла в момент імпульсу. Найчутливіші зони - лоб, скроні та ділянка над верхньою губою; там лікар працює обережніше й на меншій глибині.", ru: "Процедуру всегда выполняют под аппликационной анестезией, которую выдерживают 30-40 минут. После этого ощущения сводятся к давлению и короткому теплу в момент импульса. Самые чувствительные зоны - лоб, виски и участок над верхней губой; там врач работает осторожнее и на меньшей глубине.", en: "The treatment is always done under topical anaesthesia left on for 30-40 minutes. After that the sensation is limited to pressure and a brief warmth with each pulse. The most sensitive areas are the forehead, temples and the region above the upper lip, where the physician works more gently and at a shallower depth." } },
      { question: { uk: "Скільки процедур потрібно, щоб прибрати постакне?", ru: "Сколько процедур нужно, чтобы убрать постакне?", en: "How many sessions are needed to treat post-acne?" },
        answer: { uk: "Зазвичай 3-4 сеанси з інтервалом 4 тижні. Атрофічні рубці не зникають повністю, але стають істотно менш помітними: рельєф вирівнюється, тінь у заглибленнях зменшується. При глибоких рубцях лікар може розширити курс до 5-6 процедур або поєднати методику з лазерною шліфовкою.", ru: "Обычно 3-4 сеанса с интервалом 4 недели. Атрофические рубцы не исчезают полностью, но становятся существенно менее заметными: рельеф выравнивается, тень в углублениях уменьшается. При глубоких рубцах врач может расширить курс до 5-6 процедур или сочетать методику с лазерной шлифовкой.", en: "Usually 3-4 sessions four weeks apart. Atrophic scars do not disappear entirely but become considerably less noticeable: the surface evens out and the shadow in the depressions softens. For deeper scarring the physician may extend the course to 5-6 sessions or combine the method with laser resurfacing." } },
      { question: { uk: "Чи залишаються сліди від голок?", ru: "Остаются ли следы от игл?", en: "Do the needles leave marks?" },
        answer: { uk: "Слідів у вигляді рубців не залишається: голки дуже тонкі, а проколи загоюються за кілька днів. Тимчасово видно дрібну сіточку мікроскоринок і почервоніння - вони сходять за 3-5 днів. Ризик пігментації є лише тоді, коли кірочки здирають або виходять на сонце без SPF.", ru: "Следов в виде рубцов не остаётся: иглы очень тонкие, а проколы заживают за несколько дней. Временно видна мелкая сеточка микрокорочек и покраснение - они сходят за 3-5 дней. Риск пигментации есть только тогда, когда корочки сдирают или выходят на солнце без SPF.", en: "No scarring is left: the needles are very fine and the punctures heal within days. A fine grid of micro-crusts and redness is visible temporarily and clears in 3-5 days. Pigmentation is a risk only if the crusts are picked or the skin is exposed to sun without SPF." } },
      { question: { uk: "Чи можна робити процедуру на тілі?", ru: "Можно ли делать процедуру на теле?", en: "Can the treatment be done on the body?" },
        answer: { uk: "Так. Мікроголковий RF ефективно працює з розтяжками на животі й стегнах, дряблістю шкіри внутрішньої поверхні рук і зоною після схуднення. Протокол для тіла відрізняється глибиною та щільністю проходів, а відновлення триває приблизно так само - 3-5 днів.", ru: "Да. Микроигольчатый RF эффективно работает с растяжками на животе и бёдрах, дряблостью кожи внутренней поверхности рук и зоной после похудения. Протокол для тела отличается глубиной и плотностью проходов, а восстановление длится примерно так же - 3-5 дней.", en: "Yes. Microneedling RF works well on stretch marks across the abdomen and thighs, laxity on the inner arms and areas left after weight loss. The body protocol differs in depth and pass density, and recovery takes about the same time - 3-5 days." } },
      { question: { uk: "У яку пору року краще проходити курс?", ru: "В какое время года лучше проходить курс?", en: "What time of year is best for a course?" },
        answer: { uk: "Оптимально - з жовтня по березень, коли сонячна активність нижча. Влітку процедуру теж проводять, але вимоги до захисту суворіші: SPF 50 щодня, жодного засмагання протягом місяця до й після сеансу. Якщо ви плануєте відпустку на морі, курс краще перенести.", ru: "Оптимально - с октября по март, когда солнечная активность ниже. Летом процедуру тоже проводят, но требования к защите строже: SPF 50 ежедневно, никакого загара в течение месяца до и после сеанса. Если вы планируете отпуск на море, курс лучше перенести.", en: "October to March is ideal, when the sun is weaker. The treatment can be done in summer too, but protection rules are stricter: SPF 50 daily and no tanning for a month before or after each session. If you have a beach holiday planned, postpone the course." } },
      { question: { uk: "Чим мікроголковий RF кращий за звичайний мікронідлінг?", ru: "Чем микроигольчатый RF лучше обычного микронидлинга?", en: "How is microneedling RF better than plain microneedling?" },
        answer: { uk: "Звичайний мікронідлінг створює лише механічні мікроушкодження, тому працює переважно на рівні текстури. Додавання радіочастоти дає термічне ущільнення колагену на глибині, і саме воно забезпечує ліфтинг. За однакової кількості сеансів результат помітно виразніший, особливо на рубцях і зниженому тонусі.", ru: "Обычный микронидлинг создаёт лишь механические микроповреждения, поэтому работает преимущественно на уровне текстуры. Добавление радиочастоты даёт термическое уплотнение коллагена на глубине, и именно оно обеспечивает лифтинг. При одинаковом количестве сеансов результат заметно выразительнее, особенно на рубцах и сниженном тонусе.", en: "Plain microneedling creates only mechanical micro-injuries, so it works mainly at the level of texture. Adding radiofrequency produces thermal collagen tightening at depth, and that is what delivers the lift. For the same number of sessions the result is noticeably stronger, especially on scars and lax skin." } },
      { question: { uk: "Скільки коштує мікроголковий RF-ліфтинг у Дніпрі?", ru: "Сколько стоит микроигольчатый RF-лифтинг в Днепре?", en: "How much does microneedling RF lifting cost in Dnipro?" },
        answer: { uk: "Вартість залежить від площі зони, кількості проходів і того, чи береться курс цілком. Актуальні ціни є в розділі «Ціни», а адміністратор озвучить їх під час запису. Точний розрахунок лікар зробить після огляду - коли стане зрозуміло, скільки сеансів потрібно саме вам.", ru: "Стоимость зависит от площади зоны, количества проходов и того, берётся ли курс целиком. Актуальные цены есть в разделе «Цены», а администратор озвучит их при записи. Точный расчёт врач сделает после осмотра - когда станет понятно, сколько сеансов нужно именно вам.", en: "The price depends on the size of the area, the number of passes and whether you book the whole course. Current prices are in the Prices section and the administrator will quote them when you book. The exact figure comes from the physician after examination, once it is clear how many sessions you need." } },
    ],
  },
];
