/** TZ #12 — the five laser-hair-removal zone pages (Splendor X). */
import { EQ, COSMETOLOGISTS, type ServiceSeed } from "./lib";

export const laser: ServiceSeed[] = [
  // ─── 7. ЛАЗЕРНА ЕПІЛЯЦІЯ ЖИВОТА ──────────────────────────────────────────
  {
    slug: "laser-abdomen",
    meta: {
      category: "laser-hair-removal",
      h1: { uk: "Лазерна епіляція живота в Дніпрі", ru: "Лазерная эпиляция живота в Днепре", en: "Laser hair removal for the abdomen in Dnipro" },
      seoTitle: {
        uk: "Лазерна епіляція живота в Дніпрі - Видалення волосся на животі",
        ru: "Лазерная эпиляция живота в Днепре - Лазерная эпиляция живот",
        en: "Laser Hair Removal for Abdomen in Dnipro - Abdomen laser hair removal price",
      },
      seoDesc: {
        uk: "Лазерна епіляція на животі в Дніпрі 🤍 GENEVITY. Доступні ціни на видалення волосся на животі 💫 Гладкість та комфорт.",
        ru: "Лазерная эпиляция на животе в Днепре 🤍 GENEVITY. Доступные цены на лазерное удаление волос на животе 💫 Гладкая кожа.",
        en: "Laser hair removal on abdomen in Dnipro 🤍 GENEVITY. Available prices on laser hair removal for stomach 💫 Smooth skin.",
      },
    },
    title: { uk: "Лазерна епіляція живота", ru: "Лазерная эпиляция живота", en: "Laser Hair Removal for Abdomen" },
    summary: {
      uk: "Лазерна епіляція живота у GENEVITY на Splendor X: прибираємо волосся по білій лінії та на всій площі живота. Якщо ріст волосся посилився раптово, лікар порадить перевірити гормональний фон.",
      ru: "Лазерная эпиляция живота в GENEVITY на Splendor X: убираем волосы по белой линии и на всей площади живота. Если рост волос усилился внезапно, врач посоветует проверить гормональный фон.",
      en: "Abdominal laser hair removal at GENEVITY on the Splendor X: we treat the linea alba and the whole abdominal area. If growth has increased suddenly, the physician will advise checking your hormone levels.",
    },
    procedureLength: { uk: "15-25 хвилин", ru: "15-25 минут", en: "15-25 minutes" },
    effectDuration: { uk: "до 90% менше волосся після курсу", ru: "до 90% меньше волос после курса", en: "up to 90% less hair after a course" },
    sessionsRecommended: { uk: "6-8 процедур курсом", ru: "6-8 процедур курсом", en: "6-8 sessions per course" },
    related: ["laser-back", "laser-legs", "laser-women", "splendor-x"],
    doctors: COSMETOLOGISTS,
    equipment: [EQ.SPLENDOR_X],
    sections: [
      {
        type: "richText",
        heading: { uk: "Особливості лазерної епіляції на животі", ru: "Особенности лазерной эпиляции на животе", en: "What makes abdominal laser hair removal specific" },
        body: {
          uk: "Лазерна епіляція живота відрізняється від інших зон одним: волосся тут майже завжди гормонозалежне. У жінок ріст темного жорсткого волосся по білій лінії - від пупка донизу - часто вказує на підвищений рівень андрогенів. У чоловіків це варіант норми, тому запит зазвичай суто естетичний.\n\nШкіра живота тонка й чутлива, а волосся - різнорідне: щільніше по центральній лінії й м'якше по боках. Через це лікар змінює параметри в межах однієї зони, а не проходить її на однакових налаштуваннях.\n\nВ GENEVITY процедуру виконують на Splendor X - лазері з двома довжинами хвиль. Александритовий промінь (755 нм) працює з тонким світлішим волоссям, Nd:YAG (1064 нм) - із жорстким волоссям і на засмаглій шкірі. Великий розмір плями дозволяє пройти живіт за 15-20 хвилин.\n\nЯкщо волосся на животі з'явилося раптово або росте разом із висипаннями та порушенням циклу, лікар порекомендує консультацію ендокринолога. Лазер прибере видимий прояв, але без корекції причини волосся відновлюватиметься швидше.",
          ru: "Лазерная эпиляция живота отличается от других зон одним: волосы здесь почти всегда гормонозависимые. У женщин рост тёмных жёстких волос по белой линии - от пупка вниз - часто указывает на повышенный уровень андрогенов. У мужчин это вариант нормы, поэтому запрос обычно чисто эстетический.\n\nКожа живота тонкая и чувствительная, а волосы - разнородные: плотнее по центральной линии и мягче по бокам. Из-за этого врач меняет параметры в пределах одной зоны, а не проходит её на одинаковых настройках.\n\nВ GENEVITY процедуру выполняют на Splendor X - лазере с двумя длинами волн. Александритовый луч (755 нм) работает с тонкими более светлыми волосами, Nd:YAG (1064 нм) - с жёсткими волосами и на загорелой коже. Большой размер пятна позволяет пройти живот за 15-20 минут.\n\nЕсли волосы на животе появились внезапно или растут вместе с высыпаниями и нарушением цикла, врач порекомендует консультацию эндокринолога. Лазер уберёт видимое проявление, но без коррекции причины волосы будут восстанавливаться быстрее.",
          en: "Laser hair removal on the abdomen differs from other zones in one respect: the hair here is almost always hormone-dependent. In women, dark coarse hair along the linea alba - running down from the navel - often points to raised androgen levels. In men it is a normal variant, so the request is usually purely aesthetic.\n\nThe skin of the abdomen is thin and sensitive, and the hair is uneven: denser along the midline and softer at the sides. For that reason the physician varies the settings within a single zone rather than treating it all identically.\n\nAt GENEVITY the treatment uses the Splendor X, a dual-wavelength laser. The alexandrite beam (755 nm) handles finer, lighter hair, while the Nd:YAG (1064 nm) suits coarse hair and tanned skin. Its large spot size means the abdomen takes only 15-20 minutes.\n\nIf abdominal hair has appeared suddenly, or alongside breakouts and cycle irregularity, the physician will suggest seeing an endocrinologist. The laser removes the visible sign, but without addressing the cause the hair returns faster.",
        },
      },
      {
        type: "indicationsContraindications",
        indicationsHeading: { uk: "Кому підходить лазерна епіляція живота", ru: "Кому подходит лазерная эпиляция живота", en: "Who abdominal laser hair removal suits" },
        indications: [
          { uk: "Темне волосся по білій лінії живота", ru: "Тёмные волосы по белой линии живота", en: "Dark hair along the linea alba" },
          { uk: "Волосся навколо пупка та в нижній частині живота", ru: "Волосы вокруг пупка и в нижней части живота", en: "Hair around the navel and on the lower abdomen" },
          { uk: "Подразнення та вростання після гоління чи воску", ru: "Раздражение и врастание после бритья или воска", en: "Irritation and ingrown hairs after shaving or waxing" },
          { uk: "Чоловічий запит на суцільне видалення волосся на животі", ru: "Мужской запрос на сплошное удаление волос на животе", en: "Men seeking full removal of abdominal hair" },
          { uk: "Підготовка до пляжного сезону або спортивних змагань", ru: "Подготовка к пляжному сезону или спортивным соревнованиям", en: "Preparing for the beach season or sports competitions" },
          { uk: "Продовження зони бікіні вгору - для рівного переходу", ru: "Продолжение зоны бикини вверх - для ровного перехода", en: "Extending the bikini area upwards for a seamless transition" },
        ],
        contraindicationsHeading: { uk: "Протипоказання", ru: "Противопоказания", en: "Contraindications" },
        contraindications: [
          { uk: "Вагітність і період лактації", ru: "Беременность и период лактации", en: "Pregnancy and breastfeeding" },
          { uk: "Свіжа засмага - потрібна пауза 2 тижні", ru: "Свежий загар - нужна пауза 2 недели", en: "A fresh tan - a two-week interval is required" },
          { uk: "Пошкодження шкіри, запалення, свіжі рубці в зоні", ru: "Повреждения кожи, воспаления, свежие рубцы в зоне", en: "Broken skin, inflammation or fresh scars in the area" },
          { uk: "Прийом фотосенсибілізувальних препаратів та ізотретиноїну", ru: "Приём фотосенсибилизирующих препаратов и изотретиноина", en: "Photosensitising medication or isotretinoin" },
          { uk: "Онкологічні захворювання в активній фазі", ru: "Онкологические заболевания в активной фазе", en: "Active oncological disease" },
          { uk: "Татуювання в зоні впливу - лікар обходить його", ru: "Татуировки в зоне воздействия - врач обходит их", en: "Tattoos in the treatment area, which the physician works around" },
        ],
      },
      {
        type: "steps",
        heading: { uk: "Як проходить сеанс епіляції живота", ru: "Как проходит сеанс эпиляции живота", en: "How an abdominal session works" },
        steps: [
          { title: { uk: "Огляд і тест-імпульс", ru: "Осмотр и тест-импульс", en: "Assessment and test pulse" }, description: { uk: "Лікар визначає фототип і тип волосся, робить пробний імпульс і підбирає довжину хвилі - 755 або 1064 нм.", ru: "Врач определяет фототип и тип волос, делает пробный импульс и подбирает длину волны - 755 или 1064 нм.", en: "The physician assesses your phototype and hair type, delivers a test pulse and selects the wavelength - 755 or 1064 nm." } },
          { title: { uk: "Підготовка зони", ru: "Подготовка зоны", en: "Preparing the area" }, description: { uk: "Зону очищують, за потреби добривають волосся до довжини 1-2 мм. Пацієнт вдягає окуляри.", ru: "Зону очищают, при необходимости добривают волосы до длины 1-2 мм. Пациент надевает очки.", en: "The area is cleansed and the hair trimmed to 1-2 mm if needed. Protective goggles are put on." } },
          { title: { uk: "Обробка живота", ru: "Обработка живота", en: "Treating the abdomen" }, description: { uk: "Лікар проходить зону послідовно, змінюючи параметри для щільної центральної лінії й м'якших бічних ділянок.", ru: "Врач проходит зону последовательно, меняя параметры для плотной центральной линии и более мягких боковых участков.", en: "The physician works through the zone in sequence, adjusting settings for the dense midline and the softer areas at the sides." } },
          { title: { uk: "Охолодження та догляд", ru: "Охлаждение и уход", en: "Cooling and aftercare" }, description: { uk: "Наносять заспокійливий гель. Наступний сеанс планують через 4-6 тижнів, за фазою росту волосся.", ru: "Наносят успокаивающий гель. Следующий сеанс планируют через 4-6 недель, по фазе роста волос.", en: "A soothing gel is applied. The next session is scheduled in 4-6 weeks, in line with the hair growth cycle." } },
        ],
      },
      {
        type: "bullets",
        heading: { uk: "Що дає лазерне видалення волосся на животі", ru: "Что даёт лазерное удаление волос на животе", en: "What laser hair removal on the abdomen delivers" },
        items: [
          { uk: "Волосся стає тоншим і світлішим уже після 2-3 сеансів", ru: "Волосы становятся тоньше и светлее уже после 2-3 сеансов", en: "Hair becomes finer and lighter after just 2-3 sessions" },
          { uk: "Зникає подразнення та вростання після гоління", ru: "Исчезает раздражение и врастание после бритья", en: "No more irritation and ingrown hairs from shaving" },
          { uk: "Рівний перехід із зоною бікіні", ru: "Ровный переход с зоной бикини", en: "A seamless transition into the bikini area" },
          { uk: "Швидкий сеанс - велика зона проходиться за 15-20 хвилин", ru: "Быстрый сеанс - большая зона проходится за 15-20 минут", en: "A quick session - the whole area takes 15-20 minutes" },
          { uk: "Безпечно для чутливої шкіри завдяки контактному охолодженню", ru: "Безопасно для чувствительной кожи благодаря контактному охлаждению", en: "Safe for sensitive skin thanks to contact cooling" },
          { uk: "Лікар одразу побачить, чи потрібне обстеження гормонального фону", ru: "Врач сразу увидит, нужно ли обследование гормонального фона", en: "The physician will spot straight away whether hormone testing is warranted" },
        ],
      },
      {
        type: "richText",
        heading: { uk: "Скільки процедур потрібно та як доглядати шкіру", ru: "Сколько процедур нужно и как ухаживать за кожей", en: "How many sessions you need and how to care for the skin" },
        body: {
          uk: "Лазер руйнує лише ті фолікули, що перебувають у фазі активного росту - це приблизно 20-30% волосся одночасно. Тому потрібен курс: у середньому 6-8 сеансів з інтервалом 4-6 тижнів. При гормонозалежному рості кількість може бути більшою, а після курсу знадобляться підтримувальні сеанси раз на 6-12 місяців.\n\nПерші випадання видно на 10-14 день після сеансу - волосся просто виходить із фолікула під час душу.\n\n**Догляд між процедурами:**\n- голити зону можна й потрібно, а от виривати - ні: віск, епілятор і цукрова паста видаляють фолікул, на який має подіяти лазер;\n- 2 дні після сеансу без сауни, басейну й гарячої ванни;\n- SPF 50 на зону, якщо вона відкрита сонцю;\n- не використовувати скраби й кислоти протягом 3 днів.\n\nЯкщо ви приймаєте гормональні препарати або плануєте вагітність, скажіть про це лікарю: це впливає і на графік курсу, і на очікуваний результат.",
          ru: "Лазер разрушает только те фолликулы, что находятся в фазе активного роста - это примерно 20-30% волос одновременно. Поэтому нужен курс: в среднем 6-8 сеансов с интервалом 4-6 недель. При гормонозависимом росте количество может быть больше, а после курса понадобятся поддерживающие сеансы раз в 6-12 месяцев.\n\nПервые выпадения видны на 10-14 день после сеанса - волосы просто выходят из фолликула во время душа.\n\n**Уход между процедурами:**\n- брить зону можно и нужно, а вот выдёргивать - нет: воск, эпилятор и сахарная паста удаляют фолликул, на который должен подействовать лазер;\n- 2 дня после сеанса без сауны, бассейна и горячей ванны;\n- SPF 50 на зону, если она открыта солнцу;\n- не использовать скрабы и кислоты в течение 3 дней.\n\nЕсли вы принимаете гормональные препараты или планируете беременность, скажите об этом врачу: это влияет и на график курса, и на ожидаемый результат.",
          en: "The laser destroys only follicles in the active growth phase - roughly 20-30% of the hair at any one time. That is why a course is needed: on average 6-8 sessions at 4-6 week intervals. Hormone-driven growth may require more, and maintenance sessions every 6-12 months after the course.\n\nThe first shedding is visible 10-14 days after a session, when the hairs simply slip out of the follicle in the shower.\n\n**Care between sessions:**\n- shaving the area is fine and encouraged, but plucking is not: wax, epilators and sugaring remove the very follicle the laser needs to reach;\n- no sauna, swimming pool or hot bath for two days after a session;\n- SPF 50 on the area if it is exposed to the sun;\n- no scrubs or acids for three days.\n\nIf you are taking hormonal medication or planning a pregnancy, tell your physician: it affects both the course schedule and the expected result.",
        },
      },
    ],
    faqs: [
      { question: { uk: "Чи боляче робити лазерну епіляцію живота?", ru: "Больно ли делать лазерную эпиляцию живота?", en: "Is abdominal laser hair removal painful?" },
        answer: { uk: "Живіт вважається однією з комфортніших зон. Відчуття описують як короткі теплі поколювання; манипула Splendor X має контактне охолодження, яке знімає більшу частину дискомфорту. Чутливішою буде центральна лінія, де волосся щільніше - там лікар працює повільніше.", ru: "Живот считается одной из более комфортных зон. Ощущения описывают как короткие тёплые покалывания; манипула Splendor X имеет контактное охлаждение, которое снимает большую часть дискомфорта. Чувствительнее будет центральная линия, где волосы плотнее - там врач работает медленнее.", en: "The abdomen is one of the more comfortable areas. Patients describe brief warm prickles; the Splendor X handpiece has contact cooling that removes most of the discomfort. The midline, where the hair is denser, is more sensitive, and the physician works more slowly there." } },
      { question: { uk: "Чому волосся на животі росте у жінок?", ru: "Почему волосы на животе растут у женщин?", en: "Why do women grow hair on the abdomen?" },
        answer: { uk: "Найчастіше через підвищену чутливість фолікулів до андрогенів або справжній надлишок цих гормонів. Причиною бувають синдром полікістозних яєчників, порушення роботи надниркових залоз, деякі препарати. Якщо ріст посилився швидко, ми радимо консультацію ендокринолога - у GENEVITY її можна пройти в той самий день.", ru: "Чаще всего из-за повышенной чувствительности фолликулов к андрогенам или истинного избытка этих гормонов. Причиной бывают синдром поликистозных яичников, нарушения работы надпочечников, некоторые препараты. Если рост усилился быстро, мы советуем консультацию эндокринолога - в GENEVITY её можно пройти в тот же день.", en: "Most often because the follicles are unusually sensitive to androgens, or because those hormones are genuinely elevated. Polycystic ovary syndrome, adrenal disorders and certain medications can all be behind it. If growth has increased quickly we recommend seeing an endocrinologist - at GENEVITY that can be arranged the same day." } },
      { question: { uk: "Скільки сеансів потрібно для зони живота?", ru: "Сколько сеансов нужно для зоны живота?", en: "How many sessions does the abdomen need?" },
        answer: { uk: "У середньому 6-8 процедур з інтервалом 4-6 тижнів. Якщо ріст волосся гормонозалежний, курс може бути довшим - до 10 сеансів. Точну кількість лікар прогнозує після 2-3 процедури, коли стане видно, як ваше волосся відповідає на лазер.", ru: "В среднем 6-8 процедур с интервалом 4-6 недель. Если рост волос гормонозависимый, курс может быть длиннее - до 10 сеансов. Точное количество врач прогнозирует после 2-3 процедуры, когда станет видно, как ваши волосы отвечают на лазер.", en: "On average 6-8 sessions at 4-6 week intervals. If growth is hormone-driven the course may be longer, up to ten sessions. The physician can predict the number after two or three sessions, once it is clear how your hair responds to the laser." } },
      { question: { uk: "Чи можна робити епіляцію живота під час вагітності?", ru: "Можно ли делать эпиляцию живота во время беременности?", en: "Can the abdomen be treated during pregnancy?" },
        answer: { uk: "Ні. Вагітність - протипоказання для лазерної епіляції, і зона живота тут особливо чутлива. Крім того, гормональні зміни під час вагітності самі по собі змінюють ріст волосся, тому результат курсу був би непрогнозованим. Повернутися до процедур можна після завершення лактації.", ru: "Нет. Беременность - противопоказание для лазерной эпиляции, и зона живота здесь особенно чувствительна. Кроме того, гормональные изменения во время беременности сами по себе меняют рост волос, поэтому результат курса был бы непрогнозируемым. Вернуться к процедурам можно после завершения лактации.", en: "No. Pregnancy is a contraindication for laser hair removal, and the abdomen is a particularly sensitive area. Hormonal changes in pregnancy also alter hair growth in their own right, so the outcome of a course would be unpredictable. Treatment can resume once breastfeeding has finished." } },
      { question: { uk: "Що робити з волоссям між сеансами?", ru: "Что делать с волосами между сеансами?", en: "What should I do about the hair between sessions?" },
        answer: { uk: "Тільки голити. Віск, епілятор, цукрова паста й пінцет видаляють волосся разом із коренем, а лазеру потрібен саме фолікул із пігментом - без нього імпульс не спрацює. Голитися можна будь-коли, за винятком доби перед сеансом: волосся має бути 1-2 мм.", ru: "Только брить. Воск, эпилятор, сахарная паста и пинцет удаляют волосы вместе с корнем, а лазеру нужен именно фолликул с пигментом - без него импульс не сработает. Бриться можно в любое время, за исключением суток перед сеансом: волосы должны быть 1-2 мм.", en: "Shave only. Wax, epilators, sugaring and tweezers remove the hair together with its root, and the laser needs precisely that pigmented follicle - without it the pulse has nothing to act on. You can shave at any time, except in the 24 hours before a session, when the hair should be 1-2 mm long." } },
      { question: { uk: "Чи залишаться сліди або пігментація після процедури?", ru: "Останутся ли следы или пигментация после процедуры?", en: "Will the treatment leave marks or pigmentation?" },
        answer: { uk: "За правильно підібраних параметрів - ні. Одразу після сеансу можливе почервоніння та перифолікулярний набряк, схожий на «гусячу шкіру», - він минає за кілька годин. Ризик пігментації з'являється, якщо працювати на засмаглій шкірі або виходити на сонце без SPF у перші дні.", ru: "При правильно подобранных параметрах - нет. Сразу после сеанса возможны покраснение и перифолликулярный отёк, похожий на «гусиную кожу», - он проходит за несколько часов. Риск пигментации появляется, если работать на загорелой коже или выходить на солнце без SPF в первые дни.", en: "Not when the settings are chosen correctly. Redness and perifollicular swelling resembling goose bumps may appear straight after a session and settle within a few hours. Pigmentation becomes a risk only if the skin is treated while tanned or exposed to sun without SPF in the first days." } },
      { question: { uk: "Скільки коштує лазерна епіляція живота в Дніпрі?", ru: "Сколько стоит лазерная эпиляция живота в Днепре?", en: "How much does abdominal laser hair removal cost in Dnipro?" },
        answer: { uk: "Ціна залежить від того, береться весь живіт чи лише біла лінія, і від того, чи оформлюєте ви курс. Актуальні ціни є в розділі «Ціни» на сайті, адміністратор назве їх під час запису. Разом із животом часто беруть зону бікіні - лікар підкаже, чи є сенс поєднати.", ru: "Цена зависит от того, берётся весь живот или только белая линия, и от того, оформляете ли вы курс. Актуальные цены есть в разделе «Цены» на сайте, администратор назовёт их при записи. Вместе с животом часто берут зону бикини - врач подскажет, есть ли смысл совместить.", en: "The price depends on whether you treat the whole abdomen or just the linea alba, and on whether you book a course. Current prices are in the Prices section and the administrator will quote them when you book. The bikini area is often treated alongside the abdomen, and the physician will advise whether combining them makes sense." } },
    ],
  },

  // ─── 8. ЛАЗЕРНА ЕПІЛЯЦІЯ ОБЛИЧЧЯ ─────────────────────────────────────────
  {
    slug: "laser-face",
    meta: {
      category: "laser-hair-removal",
      h1: { uk: "Лазерна епіляція обличчя в Дніпрі", ru: "Лазерная эпиляция лица в Днепре", en: "Facial laser hair removal in Dnipro" },
      seoTitle: {
        uk: "Лазерна епіляція обличчя в Дніпрі - Лазерне видалення волосся на обличчі",
        ru: "Лазерная эпиляция лица в Днепре - Лазерное удаление волос на лице",
        en: "Facial Laser Hair Removal in Dnipro - Facial laser hair removal price",
      },
      seoDesc: {
        uk: "Лазерна епіляція на обличчі в Дніпрі 🤍 GENEVITY. Доступні ціни на видалення волосся на обличчі лазером 💫 Чиста та гладка шкіра.",
        ru: "Лазерная эпиляция на лице в Днепре 🤍 GENEVITY. Доступные цены на удаление волос с лица лазером 💫 Чистая и гладкая кожа.",
        en: "Laser hair removal on face in Dnipro 🤍 GENEVITY. Available prices on laser hair removal for face 💫 Clean and smooth skin.",
      },
    },
    title: { uk: "Лазерна епіляція обличчя", ru: "Лазерная эпиляция лица", en: "Facial Laser Hair Removal" },
    summary: {
      uk: "Лазерна епіляція обличчя у GENEVITY на Splendor X: над верхньою губою, на підборідді, щоках і скронях. Делікатні параметри для тонкої шкіри, без опіків і подразнення.",
      ru: "Лазерная эпиляция лица в GENEVITY на Splendor X: над верхней губой, на подбородке, щеках и висках. Деликатные параметры для тонкой кожи, без ожогов и раздражения.",
      en: "Facial laser hair removal at GENEVITY on the Splendor X: upper lip, chin, cheeks and temples. Gentle settings for thin skin, with no burns or irritation.",
    },
    procedureLength: { uk: "10-20 хвилин", ru: "10-20 минут", en: "10-20 minutes" },
    effectDuration: { uk: "стійке зменшення росту після курсу", ru: "стойкое уменьшение роста после курса", en: "a lasting reduction in growth after a course" },
    sessionsRecommended: { uk: "8-10 процедур з інтервалом 4 тижні", ru: "8-10 процедур с интервалом 4 недели", en: "8-10 sessions four weeks apart" },
    related: ["laser-underarms", "laser-women", "splendor-x", "laser-arms"],
    doctors: COSMETOLOGISTS,
    equipment: [EQ.SPLENDOR_X],
    sections: [
      {
        type: "richText",
        heading: { uk: "Чому лазерна епіляція обличчя потребує окремого підходу", ru: "Почему лазерная эпиляция лица требует отдельного подхода", en: "Why facial laser hair removal needs a separate approach" },
        body: {
          uk: "Лазерна епіляція на обличчі - найделікатніша зона в усій методиці. Шкіра тут тонка, судини близько до поверхні, а сальні залози активніші, ніж на тілі. Додайте до цього близькість очей і різнорідність волосся: над верхньою губою воно зазвичай тонке й світле, на підборідді - жорсткіше й темніше.\n\nТому параметри для обличчя завжди нижчі за тілесні, а кількість сеансів - більша. Тонке волосся містить менше пігменту, тож поглинає менше енергії й реагує повільніше. Це нормально: результат приходить, просто не за 4 сеанси.\n\nSplendor X дозволяє працювати двома довжинами хвиль і змінювати розмір плями, тому лікар прицільно обробляє невеликі ділянки - зону над губою, підборіддя, лінію бакенбардів, міжбрів'я, - не зачіпаючи сусідні.\n\nОкремо про гормони: інтенсивний ріст темного волосся на підборідді та щоках у жінок - привід перевірити рівень андрогенів. Лазер прибирає прояв, але при некоригованому гормональному фоні волосся відновлюється швидше, і курс доводиться продовжувати.",
          ru: "Лазерная эпиляция на лице - самая деликатная зона во всей методике. Кожа здесь тонкая, сосуды близко к поверхности, а сальные железы активнее, чем на теле. Добавьте к этому близость глаз и разнородность волос: над верхней губой они обычно тонкие и светлые, на подбородке - жёстче и темнее.\n\nПоэтому параметры для лица всегда ниже телесных, а количество сеансов - больше. Тонкие волосы содержат меньше пигмента, значит поглощают меньше энергии и реагируют медленнее. Это нормально: результат приходит, просто не за 4 сеанса.\n\nSplendor X позволяет работать двумя длинами волн и менять размер пятна, поэтому врач прицельно обрабатывает небольшие участки - зону над губой, подбородок, линию бакенбардов, межбровье, - не задевая соседние.\n\nОтдельно о гормонах: интенсивный рост тёмных волос на подбородке и щеках у женщин - повод проверить уровень андрогенов. Лазер убирает проявление, но при некорригированном гормональном фоне волосы восстанавливаются быстрее, и курс приходится продлевать.",
          en: "The face is the most delicate area in the whole method. The skin is thin, the vessels sit close to the surface and the sebaceous glands are more active than on the body. Add to that the proximity of the eyes and the variety of hair types: above the upper lip it is usually fine and light, on the chin coarser and darker.\n\nSettings for the face are therefore always lower than for the body, and the number of sessions higher. Fine hair contains less pigment, absorbs less energy and responds more slowly. That is normal - the result comes, just not in four sessions.\n\nThe Splendor X allows two wavelengths and a variable spot size, so the physician can treat small areas precisely - the upper lip, chin, sideburn line, glabella - without touching the neighbouring skin.\n\nA word on hormones: heavy growth of dark hair on a woman's chin and cheeks is a reason to check androgen levels. The laser removes the visible sign, but with an uncorrected hormonal picture the hair returns faster and the course has to be extended.",
        },
      },
      {
        type: "indicationsContraindications",
        indicationsHeading: { uk: "Показання до лазерного видалення волосся на обличчі", ru: "Показания к лазерному удалению волос на лице", en: "Indications for facial laser hair removal" },
        indications: [
          { uk: "Волосся над верхньою губою", ru: "Волосы над верхней губой", en: "Hair on the upper lip" },
          { uk: "Одиничні жорсткі волоски на підборідді та щоках", ru: "Одиночные жёсткие волоски на подбородке и щеках", en: "Isolated coarse hairs on the chin and cheeks" },
          { uk: "Корекція лінії бакенбардів і скронь", ru: "Коррекция линии бакенбардов и висков", en: "Reshaping the sideburn and temple line" },
          { uk: "Волосся в міжбрів'ї та на переніссі", ru: "Волосы в межбровье и на переносице", en: "Hair between the brows and on the bridge of the nose" },
          { uk: "Псевдофолікуліт і вростання після гоління у чоловіків", ru: "Псевдофолликулит и врастание после бритья у мужчин", en: "Pseudofolliculitis and ingrown hairs after shaving in men" },
          { uk: "Корекція лінії росту бороди", ru: "Коррекция линии роста бороды", en: "Shaping the beard line" },
        ],
        contraindicationsHeading: { uk: "Коли процедуру відкладають", ru: "Когда процедуру откладывают", en: "When the treatment is postponed" },
        contraindications: [
          { uk: "Свіжа засмага обличчя", ru: "Свежий загар лица", en: "A fresh facial tan" },
          { uk: "Активне запалення, герпес, гнійничкові висипання", ru: "Активное воспаление, герпес, гнойничковые высыпания", en: "Active inflammation, herpes or pustular lesions" },
          { uk: "Прийом ізотретиноїну протягом останніх 6 місяців", ru: "Приём изотретиноина в последние 6 месяцев", en: "Isotretinoin use within the past six months" },
          { uk: "Вагітність і лактація", ru: "Беременность и лактация", en: "Pregnancy and breastfeeding" },
          { uk: "Світле, руде та сиве волосся - у ньому немає меланіну", ru: "Светлые, рыжие и седые волосы - в них нет меланина", en: "Blond, red or grey hair, which contains no melanin" },
          { uk: "Нещодавній хімічний пілінг або лазерна шліфовка обличчя", ru: "Недавний химический пилинг или лазерная шлифовка лица", en: "A recent chemical peel or facial laser resurfacing" },
        ],
      },
      {
        type: "steps",
        heading: { uk: "Як проходить лазерна епіляція на обличчі", ru: "Как проходит лазерная эпиляция на лице", en: "How a facial session works" },
        steps: [
          { title: { uk: "Консультація та тест", ru: "Консультация и тест", en: "Consultation and test" }, description: { uk: "Лікар оцінює фототип, тип волосся і виключає гормональні причини надлишкового росту. Робить тест-імпульс на невеликій ділянці.", ru: "Врач оценивает фототип, тип волос и исключает гормональные причины избыточного роста. Делает тест-импульс на небольшом участке.", en: "The physician assesses your phototype and hair type and rules out hormonal causes of excess growth, then delivers a test pulse to a small area." } },
          { title: { uk: "Демакіяж і розмітка зон", ru: "Демакияж и разметка зон", en: "Make-up removal and zone mapping" }, description: { uk: "Обличчя очищують від косметики, окреслюють межі обробки - особливо важливо для лінії бакенбардів і брів.", ru: "Лицо очищают от косметики, очерчивают границы обработки - особенно важно для линии бакенбардов и бровей.", en: "The face is cleansed of make-up and the treatment borders are outlined - especially important along the sideburn and brow lines." } },
          { title: { uk: "Прицільна обробка", ru: "Прицельная обработка", en: "Targeted treatment" }, description: { uk: "Лікар працює малою плямою по кожній зоні. Очі захищені окулярами, повіки й брови залишаються поза зоною впливу.", ru: "Врач работает малым пятном по каждой зоне. Глаза защищены очками, веки и брови остаются вне зоны воздействия.", en: "The physician works zone by zone with a small spot size. The eyes are shielded with goggles, and the eyelids and brows stay outside the treatment field." } },
          { title: { uk: "Заспокоєння шкіри", ru: "Успокоение кожи", en: "Calming the skin" }, description: { uk: "Наносять протизапальний засіб і SPF 50. Макіяж можна нанести наступного дня.", ru: "Наносят противовоспалительное средство и SPF 50. Макияж можно нанести на следующий день.", en: "An anti-inflammatory product and SPF 50 are applied. Make-up can be worn again the next day." } },
        ],
      },
      {
        type: "bullets",
        heading: { uk: "Переваги епіляції обличчя лазером", ru: "Преимущества эпиляции лица лазером", en: "Advantages of facial laser hair removal" },
        items: [
          { uk: "Немає подразнення й вростання, типових для гоління та воску", ru: "Нет раздражения и врастания, типичных для бритья и воска", en: "None of the irritation and ingrown hairs that come with shaving or wax" },
          { uk: "Волосся не грубішає, як після пінцета", ru: "Волосы не грубеют, как после пинцета", en: "The hair does not coarsen the way it does after tweezing" },
          { uk: "Короткий сеанс - 10-20 хвилин", ru: "Короткий сеанс - 10-20 минут", en: "A short session of 10-20 minutes" },
          { uk: "Прицільна робота малою плямою без зачіпання сусідніх зон", ru: "Прицельная работа малым пятном без задевания соседних зон", en: "Precise work with a small spot that spares the surrounding skin" },
          { uk: "Одночасно зменшується почервоніння та псевдофолікуліт", ru: "Одновременно уменьшается покраснение и псевдофолликулит", en: "Redness and pseudofolliculitis subside at the same time" },
          { uk: "Можна повертатися до звичних справ одразу після процедури", ru: "Можно возвращаться к привычным делам сразу после процедуры", en: "You can go straight back to your day afterwards" },
        ],
      },
      {
        type: "richText",
        heading: { uk: "Чого очікувати після процедури", ru: "Чего ожидать после процедуры", en: "What to expect afterwards" },
        body: {
          uk: "Одразу після сеансу на обличчі з'являється легке почервоніння й невеликий набряк навколо фолікулів. На тонкій шкірі це помітніше, ніж на тілі, але минає за 2-6 годин. Косметику краще не наносити до наступного ранку.\n\nВолосся починає випадати з 10-14 дня. У проміжку між сеансами воно росте, і це нормально: лазер не діє на фолікули у фазі спокою, тому наступний сеанс «збирає» вже іншу їх частину.\n\n**Що важливо для обличчя:**\n- SPF 50 щодня протягом усього курсу - обличчя завжди відкрите сонцю;\n- відкласти кислоти, ретиноїди й скраби на 5-7 днів після сеансу;\n- не використовувати пінцет і віск між процедурами - тільки гоління або тример;\n- при схильності до герпесу лікар може призначити профілактичний противірусний препарат.\n\nКурс для обличчя довший, ніж для тіла: у середньому 8-10 сеансів. Причина не в апараті, а в біології - тонке світле волосся поглинає менше енергії. Після завершення курсу зазвичай потрібні підтримувальні процедури раз на 6-12 місяців, особливо якщо ріст волосся гормонозалежний.",
          ru: "Сразу после сеанса на лице появляется лёгкое покраснение и небольшой отёк вокруг фолликулов. На тонкой коже это заметнее, чем на теле, но проходит за 2-6 часов. Косметику лучше не наносить до следующего утра.\n\nВолосы начинают выпадать с 10-14 дня. В промежутке между сеансами они растут, и это нормально: лазер не действует на фолликулы в фазе покоя, поэтому следующий сеанс «собирает» уже другую их часть.\n\n**Что важно для лица:**\n- SPF 50 ежедневно в течение всего курса - лицо всегда открыто солнцу;\n- отложить кислоты, ретиноиды и скрабы на 5-7 дней после сеанса;\n- не использовать пинцет и воск между процедурами - только бритьё или триммер;\n- при склонности к герпесу врач может назначить профилактический противовирусный препарат.\n\nКурс для лица длиннее, чем для тела: в среднем 8-10 сеансов. Причина не в аппарате, а в биологии - тонкие светлые волосы поглощают меньше энергии. После завершения курса обычно нужны поддерживающие процедуры раз в 6-12 месяцев, особенно если рост волос гормонозависимый.",
          en: "Straight after a session the face shows mild redness and slight swelling around the follicles. On thin skin this is more noticeable than on the body, but it settles within two to six hours. It is best not to apply make-up until the next morning.\n\nThe hair starts to shed from day 10-14. Between sessions it grows back, and that is expected: the laser cannot act on follicles in the resting phase, so the next session catches a different share of them.\n\n**What matters on the face:**\n- SPF 50 every day throughout the course - the face is always exposed;\n- postpone acids, retinoids and scrubs for 5-7 days after each session;\n- no tweezers or wax between sessions, only shaving or a trimmer;\n- if you are prone to herpes, the physician may prescribe preventive antiviral medication.\n\nA facial course is longer than a body one: 8-10 sessions on average. The reason is biology, not the device - fine, light hair absorbs less energy. After the course, maintenance every 6-12 months is usually needed, particularly when growth is hormone-driven.",
        },
      },
    ],
    faqs: [
      { question: { uk: "Чи можна робити лазерну епіляцію над верхньою губою?", ru: "Можно ли делать лазерную эпиляцию над верхней губой?", en: "Can laser hair removal be done on the upper lip?" },
        answer: { uk: "Так, це одна з найпопулярніших зон. Шкіра там тонка й чутлива, тому лікар працює на знижених параметрах і малим розміром плями. Сеанс триває близько 5 хвилин. Волосся тут часто тонке, тому знадобиться більше процедур, ніж, наприклад, для пахв.", ru: "Да, это одна из самых популярных зон. Кожа там тонкая и чувствительная, поэтому врач работает на сниженных параметрах и малым размером пятна. Сеанс длится около 5 минут. Волосы здесь часто тонкие, поэтому понадобится больше процедур, чем, например, для подмышек.", en: "Yes, it is one of the most requested areas. The skin there is thin and sensitive, so the physician uses reduced settings and a small spot size. The session takes about five minutes. The hair is often fine, so more sessions are needed than for the underarms, for example." } },
      { question: { uk: "Чи не почне волосся рости сильніше після лазера?", ru: "Не начнут ли волосы расти сильнее после лазера?", en: "Will the hair grow back stronger after the laser?" },
        answer: { uk: "Ні, лазер не стимулює ріст. Рідкісне явище парадоксального гіпертрихозу описане для окремих зон обличчя при роботі на занижених параметрах у пацієнтів із певними фототипами. Саме тому лікар підбирає енергію індивідуально й контролює відповідь після кожного сеансу.", ru: "Нет, лазер не стимулирует рост. Редкое явление парадоксального гипертрихоза описано для отдельных зон лица при работе на заниженных параметрах у пациентов с определёнными фототипами. Именно поэтому врач подбирает энергию индивидуально и контролирует ответ после каждого сеанса.", en: "No, the laser does not stimulate growth. The rare phenomenon of paradoxical hypertrichosis has been described in certain facial areas when under-powered settings are used in patients of particular phototypes. This is precisely why the physician selects the energy individually and reviews the response after every session." } },
      { question: { uk: "Скільки сеансів потрібно для обличчя?", ru: "Сколько сеансов нужно для лица?", en: "How many sessions does the face need?" },
        answer: { uk: "У середньому 8-10 з інтервалом 4 тижні - більше, ніж для тіла. Волосся на обличчі тонше й містить менше пігменту, тому реагує повільніше. Після основного курсу зазвичай потрібні підтримувальні сеанси раз на 6-12 місяців.", ru: "В среднем 8-10 с интервалом 4 недели - больше, чем для тела. Волосы на лице тоньше и содержат меньше пигмента, поэтому реагируют медленнее. После основного курса обычно нужны поддерживающие сеансы раз в 6-12 месяцев.", en: "Eight to ten on average, four weeks apart - more than for the body. Facial hair is finer and holds less pigment, so it responds more slowly. After the main course, maintenance sessions every 6-12 months are usually needed." } },
      { question: { uk: "Чи можна робити епіляцію обличчя при куперозі?", ru: "Можно ли делать эпиляцию лица при куперозе?", en: "Can the face be treated if I have thread veins?" },
        answer: { uk: "Так, за акуратно підібраних параметрів. Більше того, Nd:YAG частково працює й із судинним компонентом. Але якщо купероз виражений, лікар спершу пропонує курс фототерапії на M22, а вже потім - епіляцію: так шкіра переносить процедури комфортніше.", ru: "Да, при аккуратно подобранных параметрах. Более того, Nd:YAG частично работает и с сосудистым компонентом. Но если купероз выражен, врач сначала предлагает курс фототерапии на M22, а уже потом - эпиляцию: так кожа переносит процедуры комфортнее.", en: "Yes, with carefully chosen settings - and the Nd:YAG wavelength even works partly on the vascular component. If the thread veins are pronounced, though, the physician will suggest a course of M22 phototherapy first and hair removal afterwards, which the skin tolerates more comfortably." } },
      { question: { uk: "Чи допоможе лазер від сивого або світлого волосся на обличчі?", ru: "Поможет ли лазер от седых или светлых волос на лице?", en: "Does the laser work on grey or blond facial hair?" },
        answer: { uk: "Ні. Лазер знаходить фолікул за пігментом, а в сивому, білявому й рудому волоссі меланіну немає або надто мало. Такі волоски залишаться. Лікар чесно попередить про це на консультації й запропонує альтернативу - наприклад, електроепіляцію в профільній клініці.", ru: "Нет. Лазер находит фолликул по пигменту, а в седых, светлых и рыжих волосах меланина нет или слишком мало. Такие волоски останутся. Врач честно предупредит об этом на консультации и предложит альтернативу - например, электроэпиляцию в профильной клинике.", en: "No. The laser locates the follicle by its pigment, and grey, blond and red hair contains little or no melanin. Those hairs will remain. The physician will say so plainly at the consultation and suggest an alternative, such as electrolysis at a specialist clinic." } },
      { question: { uk: "Чи можна поєднувати епіляцію обличчя з іншими процедурами?", ru: "Можно ли совмещать эпиляцию лица с другими процедурами?", en: "Can facial hair removal be combined with other treatments?" },
        answer: { uk: "Так, але з паузами. Ін'єкційні процедури й пілінги планують не раніше ніж через тиждень після сеансу епіляції. Лазерну шліфовку і глибокі пілінги - з інтервалом 3-4 тижні в обидва боки. Послідовність зручно узгодити одразу на консультації, щоб не збивати графік курсу.", ru: "Да, но с паузами. Инъекционные процедуры и пилинги планируют не раньше чем через неделю после сеанса эпиляции. Лазерную шлифовку и глубокие пилинги - с интервалом 3-4 недели в обе стороны. Последовательность удобно согласовать сразу на консультации, чтобы не сбивать график курса.", en: "Yes, but with intervals. Injectables and peels are scheduled no sooner than a week after a hair-removal session. Laser resurfacing and deep peels need three to four weeks either side. It is easiest to agree the sequence at the consultation so the course schedule is not disrupted." } },
      { question: { uk: "Скільки коштує лазерна епіляція обличчя в Дніпрі?", ru: "Сколько стоит лазерная эпиляция лица в Днепре?", en: "How much does facial laser hair removal cost in Dnipro?" },
        answer: { uk: "Вартість рахується по зонах: верхня губа, підборіддя, щоки, скроні та обличчя цілком мають різну ціну. Актуальні ціни є в розділі «Ціни», адміністратор назве їх під час запису. При оформленні курсу умови вигідніші - уточніть це на консультації.", ru: "Стоимость считается по зонам: верхняя губа, подбородок, щёки, виски и лицо целиком имеют разную цену. Актуальные цены есть в разделе «Цены», администратор назовёт их при записи. При оформлении курса условия выгоднее - уточните это на консультации.", en: "Pricing is by zone: upper lip, chin, cheeks, temples and the full face are priced separately. Current prices are in the Prices section and the administrator will quote them when you book. Booking a course comes with better terms - ask about it at your consultation." } },
    ],
  },

  // ─── 9. ЛАЗЕРНА ЕПІЛЯЦІЯ ПАХВ ────────────────────────────────────────────
  {
    slug: "laser-underarms",
    meta: {
      category: "laser-hair-removal",
      h1: { uk: "Лазерна епіляція пахв в Дніпрі", ru: "Лазерная эпиляция подмышек в Днепре", en: "Underarm laser hair removal in Dnipro" },
      seoTitle: {
        uk: "Лазерна епіляція пахв в Дніпрі - Лазерна епіляція пахви",
        ru: "Лазерная эпиляция подмышек в Днепре - Подмышки лазерная эпиляция",
        en: "Underarm Laser Hair Removal in Dnipro - Underarm laser hair removal price",
      },
      seoDesc: {
        uk: "Лазерна епіляція під пахвами в Дніпрі 🤍 GENEVITY. Доступні ціни на лазерну епіляцію підмишок 💫 Абсолютна гладкість.",
        ru: "Лазерная эпиляция на подмышки в Днепре 🤍 GENEVITY. Доступные цены на лазерное удаление волос подмышками 💫 Абсолютная гладкость.",
        en: "Laser hair removal for underarms in Dnipro 🤍 GENEVITY. Available prices on laser hair removal underarms 💫 Absolute smoothness.",
      },
    },
    title: { uk: "Лазерна епіляція пахв", ru: "Лазерная эпиляция подмышек", en: "Underarm Laser Hair Removal" },
    summary: {
      uk: "Лазерна епіляція пахв у GENEVITY на Splendor X: зона з найщільнішим темним волоссям реагує на лазер найкраще. Сеанс триває 5-10 хвилин, курс - коротший, ніж для більшості зон.",
      ru: "Лазерная эпиляция подмышек в GENEVITY на Splendor X: зона с самыми плотными тёмными волосами реагирует на лазер лучше всего. Сеанс длится 5-10 минут, курс - короче, чем для большинства зон.",
      en: "Underarm laser hair removal at GENEVITY on the Splendor X: the area with the densest dark hair responds best of all to the laser. A session takes 5-10 minutes and the course is shorter than for most zones.",
    },
    procedureLength: { uk: "5-10 хвилин", ru: "5-10 минут", en: "5-10 minutes" },
    effectDuration: { uk: "до 90% менше волосся після курсу", ru: "до 90% меньше волос после курса", en: "up to 90% less hair after a course" },
    sessionsRecommended: { uk: "5-7 процедур курсом", ru: "5-7 процедур курсом", en: "5-7 sessions per course" },
    related: ["laser-bikini", "laser-arms", "laser-legs", "splendor-x"],
    doctors: COSMETOLOGISTS,
    equipment: [EQ.SPLENDOR_X],
    sections: [
      {
        type: "richText",
        heading: { uk: "Чому пахви - найвдячніша зона для лазера", ru: "Почему подмышки - самая благодарная зона для лазера", en: "Why the underarms respond best to the laser" },
        body: {
          uk: "Лазерна епіляція пахв дає найшвидший видимий результат серед усіх зон, і причина суто фізична. Волосся тут густе, темне й товсте, тобто містить багато меланіну - саме того пігменту, який поглинає лазерний промінь. Чим більше пігменту, тим ефективніше нагрівається фолікул.\n\nДодатковий фактор - площа. Дві пахви проходяться за 5-10 хвилин, тому процедуру легко вбудувати в будь-який графік.\n\nВ GENEVITY зону обробляють на Splendor X. Для світлої шкіри з темним волоссям використовують александритову довжину хвилі 755 нм, для смаглявої або засмаглої - Nd:YAG 1064 нм, який не «бачить» пігмент шкіри й тому безпечний навіть для темних фототипів.\n\nОкремий бонус - зникає щоденне гоління, а з ним подразнення, вростання й потемніння шкіри під пахвами. Багато пацієнтів відзначають, що шкіра стає світлішою й рівнішою вже до середини курсу: постійне механічне подразнення припиняється.",
          ru: "Лазерная эпиляция подмышек даёт самый быстрый видимый результат среди всех зон, и причина сугубо физическая. Волосы здесь густые, тёмные и толстые, то есть содержат много меланина - именно того пигмента, который поглощает лазерный луч. Чем больше пигмента, тем эффективнее нагревается фолликул.\n\nДополнительный фактор - площадь. Две подмышки проходятся за 5-10 минут, поэтому процедуру легко встроить в любой график.\n\nВ GENEVITY зону обрабатывают на Splendor X. Для светлой кожи с тёмными волосами используют александритовую длину волны 755 нм, для смуглой или загорелой - Nd:YAG 1064 нм, который не «видит» пигмент кожи и потому безопасен даже для тёмных фототипов.\n\nОтдельный бонус - исчезает ежедневное бритьё, а с ним раздражение, врастание и потемнение кожи под мышками. Многие пациенты отмечают, что кожа становится светлее и ровнее уже к середине курса: постоянное механическое раздражение прекращается.",
          en: "Underarm laser hair removal shows results faster than any other zone, and the reason is purely physical. The hair here is dense, dark and thick, meaning it holds a great deal of melanin - the very pigment that absorbs the laser beam. The more pigment, the more efficiently the follicle heats.\n\nSize helps too. Both underarms take 5-10 minutes, so the treatment fits into any schedule.\n\nAt GENEVITY the area is treated on the Splendor X. Fair skin with dark hair is treated at the alexandrite wavelength of 755 nm; for olive or tanned skin the Nd:YAG at 1064 nm is used, which does not 'see' skin pigment and is therefore safe even for darker phototypes.\n\nThere is a further benefit: daily shaving stops, and with it the irritation, ingrown hairs and darkening of the underarm skin. Many patients notice their skin looking lighter and smoother by the middle of the course, simply because the constant mechanical irritation has ended.",
        },
      },
      {
        type: "indicationsContraindications",
        indicationsHeading: { uk: "Показання до епіляції зони пахв", ru: "Показания к эпиляции зоны подмышек", en: "Indications for underarm hair removal" },
        indications: [
          { uk: "Густе темне волосся, яке доводиться голити щодня", ru: "Густые тёмные волосы, которые приходится брить ежедневно", en: "Dense dark hair that has to be shaved daily" },
          { uk: "Подразнення й почервоніння після бритви", ru: "Раздражение и покраснение после бритвы", en: "Irritation and redness from razors" },
          { uk: "Вростання волосся й запальні елементи", ru: "Врастание волос и воспалительные элементы", en: "Ingrown hairs and inflamed bumps" },
          { uk: "Потемніння шкіри від постійного гоління", ru: "Потемнение кожи от постоянного бритья", en: "Skin darkening caused by constant shaving" },
          { uk: "Бажання перестати залежати від воску та епілятора", ru: "Желание перестать зависеть от воска и эпилятора", en: "Wanting to stop relying on wax and epilators" },
          { uk: "Чоловічий запит на скорочення густоти без повного видалення", ru: "Мужской запрос на сокращение густоты без полного удаления", en: "Men wanting to thin the hair rather than remove it entirely" },
        ],
        contraindicationsHeading: { uk: "Протипоказання", ru: "Противопоказания", en: "Contraindications" },
        contraindications: [
          { uk: "Вагітність і лактація", ru: "Беременность и лактация", en: "Pregnancy and breastfeeding" },
          { uk: "Свіжа засмага в зоні впливу", ru: "Свежий загар в зоне воздействия", en: "A fresh tan in the treatment area" },
          { uk: "Гнійничкові запалення та гідраденіт", ru: "Гнойничковые воспаления и гидраденит", en: "Pustular inflammation or hidradenitis" },
          { uk: "Прийом фотосенсибілізувальних препаратів", ru: "Приём фотосенсибилизирующих препаратов", en: "Photosensitising medication" },
          { uk: "Онкологічні захворювання в активній фазі", ru: "Онкологические заболевания в активной фазе", en: "Active oncological disease" },
          { uk: "Свіжі татуювання в зоні пахв", ru: "Свежие татуировки в зоне подмышек", en: "Fresh tattoos in the underarm area" },
        ],
      },
      {
        type: "steps",
        heading: { uk: "Як проходить процедура", ru: "Как проходит процедура", en: "How the session runs" },
        steps: [
          { title: { uk: "Підбір довжини хвилі", ru: "Подбор длины волны", en: "Selecting the wavelength" }, description: { uk: "Лікар оцінює фототип і густоту волосся, обирає 755 або 1064 нм і робить тест-імпульс.", ru: "Врач оценивает фототип и густоту волос, выбирает 755 или 1064 нм и делает тест-импульс.", en: "The physician assesses your phototype and hair density, selects 755 or 1064 nm and delivers a test pulse." } },
          { title: { uk: "Очищення зони", ru: "Очищение зоны", en: "Cleansing the area" }, description: { uk: "Пахви очищують від залишків дезодоранту - його не можна наносити в день процедури.", ru: "Подмышки очищают от остатков дезодоранта - его нельзя наносить в день процедуры.", en: "The underarms are cleansed of deodorant residue - deodorant must not be applied on the day of treatment." } },
          { title: { uk: "Обробка лазером", ru: "Обработка лазером", en: "Laser pass" }, description: { uk: "Кожну пахву проходять за 2-4 хвилини. Відчуття - короткі гарячі поколювання з холодом від охолодження манипули.", ru: "Каждую подмышку проходят за 2-4 минуты. Ощущение - короткие горячие покалывания с холодом от охлаждения манипулы.", en: "Each underarm takes two to four minutes. It feels like short hot prickles alternating with the cold of the handpiece cooling." } },
          { title: { uk: "Догляд після сеансу", ru: "Уход после сеанса", en: "Aftercare" }, description: { uk: "Наносять пантенол або заспокійливий гель. Дезодорант можна повернути через 24 години.", ru: "Наносят пантенол или успокаивающий гель. Дезодорант можно вернуть через 24 часа.", en: "Panthenol or a soothing gel is applied. Deodorant can be used again after 24 hours." } },
        ],
      },
      {
        type: "bullets",
        heading: { uk: "Чому обирають лазерну епіляцію підмишок", ru: "Почему выбирают лазерную эпиляцию подмышек", en: "Why people choose underarm laser hair removal" },
        items: [
          { uk: "Найкоротший курс серед усіх зон - зазвичай 5-7 сеансів", ru: "Самый короткий курс среди всех зон - обычно 5-7 сеансов", en: "The shortest course of any zone - usually 5-7 sessions" },
          { uk: "Сеанс триває 5-10 хвилин", ru: "Сеанс длится 5-10 минут", en: "A session takes 5-10 minutes" },
          { uk: "Зникає щоденне гоління й пов'язане з ним подразнення", ru: "Исчезает ежедневное бритьё и связанное с ним раздражение", en: "No more daily shaving and the irritation that comes with it" },
          { uk: "Шкіра світлішає та вирівнюється", ru: "Кожа светлеет и выравнивается", en: "The skin lightens and evens out" },
          { uk: "Немає вростання волосся й запальних елементів", ru: "Нет врастания волос и воспалительных элементов", en: "No ingrown hairs and no inflamed bumps" },
          { uk: "Безпечно для смаглявої шкіри завдяки Nd:YAG", ru: "Безопасно для смуглой кожи благодаря Nd:YAG", en: "Safe for olive skin thanks to the Nd:YAG wavelength" },
        ],
      },
      {
        type: "richText",
        heading: { uk: "Результат і що варто знати про дезодорант", ru: "Результат и что стоит знать о дезодоранте", en: "Results, and what to know about deodorant" },
        body: {
          uk: "Помітне порідіння видно вже після другого сеансу - у зоні пахв відповідь на лазер найвиразніша. Повний курс складає 5-7 процедур з інтервалом 4-6 тижнів. Після нього залишаються поодинокі тонкі волоски, які прибирають підтримувальними сеансами раз на 8-12 місяців.\n\nДезодорант - окреме питання. У день процедури його наносити не можна: залишки солей алюмінію на шкірі можуть локально перегрітися під імпульсом. Після сеансу дезодорант повертають через добу, і краще без спирту та віддушок протягом перших 2-3 днів.\n\n**Правила після процедури:**\n- 48 годин без сауни, басейну, гарячої ванни та інтенсивних тренувань - піт подразнює оброблену шкіру;\n- носити вільний одяг із натуральних тканин перші дні;\n- не використовувати скраби в зоні протягом тижня;\n- голити зону між сеансами можна вільно, виривати - ні.\n\nЯкщо ви помічаєте не лише надлишковий ріст волосся, а й підвищену пітливість, скажіть про це лікарю: гіпергідроз коригують окремо, і ботулінотерапія в зоні пахв добре поєднується з курсом епіляції.",
          ru: "Заметное поредение видно уже после второго сеанса - в зоне подмышек ответ на лазер самый выразительный. Полный курс составляет 5-7 процедур с интервалом 4-6 недель. После него остаются единичные тонкие волоски, которые убирают поддерживающими сеансами раз в 8-12 месяцев.\n\nДезодорант - отдельный вопрос. В день процедуры его наносить нельзя: остатки солей алюминия на коже могут локально перегреться под импульсом. После сеанса дезодорант возвращают через сутки, и лучше без спирта и отдушек в течение первых 2-3 дней.\n\n**Правила после процедуры:**\n- 48 часов без сауны, бассейна, горячей ванны и интенсивных тренировок - пот раздражает обработанную кожу;\n- носить свободную одежду из натуральных тканей первые дни;\n- не использовать скрабы в зоне в течение недели;\n- брить зону между сеансами можно свободно, выдёргивать - нет.\n\nЕсли вы замечаете не только избыточный рост волос, но и повышенную потливость, скажите об этом врачу: гипергидроз корректируют отдельно, и ботулинотерапия в зоне подмышек хорошо сочетается с курсом эпиляции.",
          en: "Noticeable thinning appears after the second session - the underarms give the clearest response to the laser of any zone. A full course is 5-7 sessions at 4-6 week intervals, after which a few fine hairs remain and are cleared with maintenance sessions every 8-12 months.\n\nDeodorant deserves a separate note. It must not be applied on the day of treatment: aluminium salt residue on the skin can overheat locally under the pulse. Deodorant can be used again 24 hours after the session, ideally alcohol- and fragrance-free for the first two or three days.\n\n**Rules after the treatment:**\n- 48 hours without sauna, swimming pool, hot baths or intensive training - sweat irritates treated skin;\n- wear loose clothing in natural fabrics for the first days;\n- no scrubs in the area for a week;\n- shaving between sessions is fine; plucking is not.\n\nIf you notice excessive sweating as well as hair growth, mention it to your physician: hyperhidrosis is treated separately, and underarm botulinum therapy combines well with a hair-removal course.",
        },
      },
    ],
    faqs: [
      { question: { uk: "Скільки сеансів потрібно для зони пахв?", ru: "Сколько сеансов нужно для зоны подмышек?", en: "How many sessions do the underarms need?" },
        answer: { uk: "Зазвичай 5-7 процедур з інтервалом 4-6 тижнів - це менше, ніж для більшості зон. Волосся тут густе й темне, тому лазер знаходить фолікул легше. Далі достатньо підтримувального сеансу раз на 8-12 місяців.", ru: "Обычно 5-7 процедур с интервалом 4-6 недель - это меньше, чем для большинства зон. Волосы здесь густые и тёмные, поэтому лазер находит фолликул легче. Далее достаточно поддерживающего сеанса раз в 8-12 месяцев.", en: "Usually 5-7 sessions at 4-6 week intervals, fewer than for most areas. The hair here is dense and dark, so the laser finds the follicle more easily. After that, one maintenance session every 8-12 months is enough." } },
      { question: { uk: "Чи можна користуватися дезодорантом після процедури?", ru: "Можно ли пользоваться дезодорантом после процедуры?", en: "Can I use deodorant after the treatment?" },
        answer: { uk: "Через 24 години - так. У день процедури дезодорант наносити не можна ні до, ні після: залишки антиперспіранту на шкірі підвищують ризик локального перегріву та подразнення. Перші 2-3 дні краще обрати засіб без спирту й віддушок.", ru: "Через 24 часа - да. В день процедуры дезодорант наносить нельзя ни до, ни после: остатки антиперспиранта на коже повышают риск локального перегрева и раздражения. Первые 2-3 дня лучше выбрать средство без спирта и отдушек.", en: "After 24 hours, yes. On the day of the treatment deodorant must not be used before or after: antiperspirant residue on the skin raises the risk of local overheating and irritation. For the first two or three days choose an alcohol- and fragrance-free product." } },
      { question: { uk: "Чи боляче робити епіляцію пахв?", ru: "Больно ли делать эпиляцию подмышек?", en: "Is underarm hair removal painful?" },
        answer: { uk: "Зона чутлива через тонку шкіру й густе волосся, тому відчуття виразніші, ніж на ногах. Але сеанс дуже короткий - 2-4 хвилини на кожну пахву, - а вбудоване охолодження манипули знімає більшу частину дискомфорту. З кожним сеансом волосся рідшає, і відчуття слабшають.", ru: "Зона чувствительная из-за тонкой кожи и густых волос, поэтому ощущения выразительнее, чем на ногах. Но сеанс очень короткий - 2-4 минуты на каждую подмышку, - а встроенное охлаждение манипулы снимает большую часть дискомфорта. С каждым сеансом волосы редеют, и ощущения слабеют.", en: "The area is sensitive because the skin is thin and the hair dense, so the sensation is stronger than on the legs. The session is very short, though - two to four minutes per side - and the handpiece's built-in cooling removes most of the discomfort. As the hair thins with each session, the sensation eases." } },
      { question: { uk: "Чи стане шкіра під пахвами світлішою?", ru: "Станет ли кожа под мышками светлее?", en: "Will the underarm skin become lighter?" },
        answer: { uk: "Найчастіше так, і це побічний, але приємний ефект. Потемніння шкіри під пахвами зазвичай спричинене постійним механічним подразненням від бритви та воску. Коли гоління припиняється, шкіра поступово вирівнюється й світлішає. При вираженій гіперпігментації лікар може додати окремий протокол освітлення.", ru: "Чаще всего да, и это побочный, но приятный эффект. Потемнение кожи под мышками обычно вызвано постоянным механическим раздражением от бритвы и воска. Когда бритьё прекращается, кожа постепенно выравнивается и светлеет. При выраженной гиперпигментации врач может добавить отдельный протокол осветления.", en: "Usually yes, as a welcome side effect. Darkening under the arms is generally caused by constant mechanical irritation from razors and wax. Once shaving stops, the skin gradually evens out and lightens. Where hyperpigmentation is marked, the physician can add a separate brightening protocol." } },
      { question: { uk: "Чи можна робити епіляцію пахв улітку?", ru: "Можно ли делать эпиляцию подмышек летом?", en: "Can underarms be treated in summer?" },
        answer: { uk: "Так, і це одна з небагатьох зон, для якої літо не проблема: пахви майже не засмагають. Обмеження стандартні - не приходити на сеанс одразу після пляжу й не відвідувати басейн та сауну 48 годин після процедури.", ru: "Да, и это одна из немногих зон, для которой лето не проблема: подмышки почти не загорают. Ограничения стандартные - не приходить на сеанс сразу после пляжа и не посещать бассейн и сауну 48 часов после процедуры.", en: "Yes - and this is one of the few areas where summer is not an issue, since the underarms barely tan. The usual limits apply: do not come straight from the beach, and avoid the pool and sauna for 48 hours afterwards." } },
      { question: { uk: "Що робити, якщо після сеансу з'явилися дрібні прищики?", ru: "Что делать, если после сеанса появились мелкие прыщики?", en: "What if small spots appear after a session?" },
        answer: { uk: "Поодинокі елементи фолікуліту в перші дні трапляються - зона пітлива, а фолікули після імпульсу тимчасово чутливіші. Зазвичай усе минає за 2-3 дні за умови сухості та вільного одягу. Якщо елементи болючі або їх багато, зателефонуйте нам: лікар огляне зону й призначить місцевий засіб.", ru: "Единичные элементы фолликулита в первые дни встречаются - зона потливая, а фолликулы после импульса временно чувствительнее. Обычно всё проходит за 2-3 дня при условии сухости и свободной одежды. Если элементы болезненные или их много, позвоните нам: врач осмотрит зону и назначит местное средство.", en: "The odd folliculitis spot does happen in the first days - the area sweats and the follicles are temporarily more reactive after the pulse. It usually clears within two or three days if the skin is kept dry and clothing loose. If the spots are painful or numerous, call us: the physician will examine the area and prescribe a topical treatment." } },
      { question: { uk: "Скільки коштує лазерна епіляція пахв у Дніпрі?", ru: "Сколько стоит лазерная эпиляция подмышек в Днепре?", en: "How much does underarm laser hair removal cost in Dnipro?" },
        answer: { uk: "Пахви - одна з найдоступніших зон завдяки невеликій площі. Актуальні ціни є в розділі «Ціни» на сайті, і адміністратор назве їх під час запису. Зону часто беруть у комплексі з бікіні або руками - у такому разі умови вигідніші.", ru: "Подмышки - одна из самых доступных зон благодаря небольшой площади. Актуальные цены есть в разделе «Цены» на сайте, и администратор назовёт их при записи. Зону часто берут в комплексе с бикини или руками - в таком случае условия выгоднее.", en: "The underarms are one of the most affordable zones thanks to their small size. Current prices are in the Prices section and the administrator will quote them when you book. The area is often combined with the bikini line or arms, which comes with better terms." } },
    ],
  },
];
